### ISSUE TITLE
suboptimal type inference

### ISSUE THREAD

**Issue by Trass3r** [microsoft/pyright#1080]
**Describe the bug**
```py
def hexify(value):
    # type: (int | str) -> str
    val = value # deduced int | str
    if not isinstance(value, str):
        val = hex(value) # deduced str

    if val.find("0x") != -1: # deduced str | int
        # ...
    return val
```

**To Reproduce**
Tested with latest pylance.
It leads to error message `Cannot access member "find" for type "int"`.

**Expected behavior**
Pyright infers that `val` will always be `str` in the end.
The expected behavior can be observed if you get rid of the intermediate `val` variable.

**Comment by erictraut** [comment]
Pyright is doing the right thing here.

I think you're assuming that the type checker will be able to deduce that your conditional type check for `value` will somehow also narrow the type of `val` because you previously assigned `value` to `val`. That's not an assumption that a static type checker can make.

The following will work:
```python
def hexify(value):
    # type: (int | str) -> str
    val = value
    if not isinstance(val, str):
        val = hex(val)

    return val
```

Here the conditional type check narrows the type of `val` from `int | str` to `int` within the `if` block and narrows it to `str` in the (implied) `else` block.

This example might help clarify:
```python
def hexify(value):
    # type: (int | str) -> str
    val = value
    if not isinstance(val, str):
        reveal_type(value)
        reveal_type(val)
    else:
        reveal_type(value)
        reveal_type(val)
```

**Comment by Trass3r** [comment]
> I think you're assuming that the type checker will be able to deduce that your conditional type check for `value` will somehow also narrow the type of `val` because you previously assigned `value` to `val`. That's not an assumption that a static type checker can make.

I see, do you have an example of when that assumption would break?
