### ISSUE TITLE
check dict.get key names on TypedDict

### ISSUE THREAD

**Issue by tekumara** [microsoft/pyright#1122]
**Is your feature request related to a problem? Please describe.**
[PEP 589](https://www.python.org/dev/peps/pep-0589/) doesn't require `dict.get` be checked:

> d.get(e) and e in d should be allowed for TypedDict objects, for an arbitrary expression e with type str.

However, mypy does check `dict.get` calls:

```python
from typing import Optional
from typing_extensions import TypedDict


class Config(TypedDict, total=False):
    name: str


def extract_name(c: Config) -> Optional[str]:
    a = c.get("name1")
    b = c.get("name1", None)
    return b
```

```
$ mypy test.py
test.py:10: error: TypedDict "Config" has no key 'name1'
test.py:10: note: Did you mean "name"?
test.py:11: error: TypedDict "Config" has no key 'name1'
test.py:11: note: Did you mean "name"?
Found 2 errors in 1 file (checked 1 source file)
```

This is handy for catching typos.

**Describe the solution you'd like**

A strict option in pyright to check key names in TypedDict when used in `dict.get`

**Additional context**

pyright 1.1.81

**Comment by erictraut** [comment]
I looked into this. I don't see a straightforward way to implement this without adding special-case logic specifically for this case. I don't think it's worth it. The `get` method is implemented as a series of overloads that are synthesized based on the names of the entries in the TypedDict. The final overload accepts any `str` value. This overload is required because the key value can't always be statically determined. Plus, it's legitimate to pass a non-present key name to the two-parameter form of `get`, which takes a default value.
