### ISSUE TITLE
Pyright v1.81 and v1.80 root execution environment sometimes ignored

### ISSUE THREAD

**Issue by nathanrpage97** [microsoft/pyright#1124]
**Describe the bug**

After updating to pylance 2020.10.2 (pyright 1.81), it no longer imports the correct library location when setting `executionEnvironments.root` if there is a folder with the same name.

**To Reproduce**

Here is a mock of a project I'm working on. I have to put the python foo library in a subfolder to not collide with c library folder name.

File Structure:
```bash
.
├── foo/    # c source library
├── examples/
├── pyproject.toml
└── python/
    └── foo/  # python wrapper library
``` 

pyrightconfig.json
```json
{
  "executionEnvironments": [
    {
      "root": "python"
    }
  ],
}
```

Add a file into examples or other top level folder that is not python/ (e.g., examples/)
examples/example.py
```python
import foo
from foo import bar # this line fails to find bar 
foo.bar # this line fails to find bar
```

**Expected behavior**

By setting the execution environments root, it should ignore the top level foo always. This is how it worked in <=v1.79.

**VS Code extension or command-line**
Running from pylance but also fails when using purely pyright v1.81/v1.80.

**Comment by erictraut** [comment]
Execution environments are selected based on the path of the file being analyzed. If you place a ".py" file in the "examples" folder, it is not considered part of the execution environment rooted at "python". This is the way execution environments have worked since I implemented them, so I can't explain why you thought it was working in your project previously. Have you changed any other parts of your pyrightconfig.json file?

**Comment by nathanrpage97** [comment]
Ahh I see. I got it working by setting the ``extraPaths`` for each directory as you mentioned. Thanks!
