### ISSUE TITLE
Expose ParamSpec in earlier versions of Python

### ISSUE THREAD

**Issue by layday** [microsoft/pyright#1153]
Similar to `TypeGuard`, would it be possible to allow importing `ParamSpec` in Python < 3.10 from `typing_extensions` even though it is not available at runtime?  It's a shame not being able to use `ParamSpec` as it makes complex decorators a lot more viable.

**Comment by erictraut** [comment]
In general, we ship only unmodified typeshed stubs. I made an exception for `TypeGuard` because it is an unratified PEP, and we're experimenting with it. `ParamSpec` and `Concatenate` are part of a ratified PEP (612), so they should be added to the official typeshed `typing_extensions.pyi` stub file. If you'd like to submit that PR to typeshed, we can pick up the change in the next release of pyright. In the meantime, you can modify your own local copy of `typing_extensions` to include `ParamSpec` and `Concatenate`.

**Comment by layday** [comment]
I can't imagine it will be accepted in the typeshed before it's added to the `typing_extensions` package itself and that would probably be for the author of the PEP to do.  I suppose we just have to wait - thank you for answering.
