### ISSUE TITLE
Unrecognized imports when using Sublime Text 4 with a conda environment

### ISSUE THREAD

**Issue by desilinguist** [microsoft/pyright#1204]
**Describe the bug**
Imports are not recognized when using conda environments with Sublime Text  + LSP. 

**To Reproduce**
Added a file called "pyrightconfig.json" to the root of my working directory with the following contents:

```json
{
  "include": [
    "/Users/nmadnani/work/skll"
  ],
  
  "exclude": [
    "**/node_modules",
    "**/__pycache__",
    "build",
    ".git"
  ],

  "reportMissingImports": true,

  "venv_path": "/Users/nmadnani/anaconda/envs",
  "venv": "skll",

  "pythonVersion": "3.7",
  "pythonPlatform": "Darwin",

}
```

**Expected behavior**
I would expect the imports in my conda environment to be recognized but they are not – looks like pyright does not recognize the environment at all. 

**VS Code extension or command-line**
Using Sublime Text 4 (build 4093) + Sublime LSP (v1.1.0) + LSP-pyright (v1.1.5). 

**Additional context**
Using the old Microsoft Python Language Server via the LSP settings works just fine and recognizes the imports just fine.

**Comment by erictraut** [comment]
I don't know anything about sublime or how it interacts with LSPs, so I don't know if this is a configuration problem or a bug in sublime. It's unlikely a problem with Pyright because it works fine with conda with other clients. 

Please try to repro the problem using either the CLI version of Pyright or the VS Code extension. That will help determine whether it's a configuration issue or a problem with sublime's LSP support.

**Comment by erictraut** [comment]
One thing I noticed about your posted config file is that your "include" section is using an absolute path. Paths within the "include" section should generally be relative to the root directory of your workspace (where the pyrightconfig.json file is located).

**Comment by erictraut** [comment]
Ah, I think I just noticed the problem. Your config file is using "venv_path" rather than "venvPath".

Incidentally, if you edit this config file using VS Code (and with the Pyright extension installed), VS Code will verify that the config file follows the proper JSON schema. It will highlight issues like this one.

**Comment by desilinguist** [comment]
Thank you for the prompt response! I changed `venv_path` to `venvPath` and removed the `include` and `exclude` flags from the JSON file. I also had a stray comma at the end which I also removed. If I try the CLI version, things seem to work fine with this file but Sublime itself still doesn't work. I guess the bug is in a Sublime plugin then.
