### ISSUE TITLE
Operator "*" not supported for types "object" and "object" when using print() and reduce

### ISSUE THREAD

**Issue by fredlb** [microsoft/pyright#1231]
**Describe the bug**
This line
`print(reduce((lambda x, y: x * y), [1, 2, 3, 4]))`
produces this error
`Operator "*" not supported for types "object" and "object"`

skipping the print() or assigning to a variable does not produce any error:
`product = reduce((lambda x, y: x * y), [1, 2, 3, 4])`

Using pyright 1.1.91

**Comment by erictraut** [comment]
`reduce` isn't a builtin symbol. Which library are you importing it from?

**Comment by fredlb** [comment]
Ah sorry, `functools` https://docs.python.org/3/library/functools.html

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release.

The first parameter to `print` is typed as an `object`, which incorrectly influenced the TypeVar solver's choice when solving for `_T` in the `reduce` function. This propagated all the way to the lambda expression and its arguments.

**Comment by erictraut** [comment]
This is now fixed in Pyright 1.1.92, which I just published. It will also be addressed in next week's Pylance release.
