### ISSUE TITLE
Support importing ParamSpec and Concatenate from typing_extensions (PEP 612)

### ISSUE THREAD

**Issue by gvanrossum** [microsoft/pyright#1276]
I've just introduced `ParamSpec` and `Concatenate` in typing_extensions.pyi in typeshed.

I'd like code that uses
```
from typing_extensions import ParamSpec, Concatenate
```
to work in all Python versions (not just in 3.10).

The real typing_extensions distro will be updated soon.

**Comment by erictraut** [comment]
I pulled the latest typeshed stubs into the pyright repo, and they will be included in the next release.

This change doesn't require any code changes to the type checker logic, so if you want to try it out in the meantime, you can manually update the copy of `typing_extensions.pyi` that ships with pyright or pylance. Just select `typing_extensions` in the import statement and press F12 to display it in VS Code, then copy in the additional lines that define ParamSpec and Concatenate.

**Comment by gvanrossum** [comment]
Thanks that works. Does it work without pyright changes because you anticipated this, or because of some other magic? I.e. if I put ParamSpec in foo.pyi and type `from foo import ParamSpec` would that also have the same semantics?

Either way you can close this issue.

**Comment by erictraut** [comment]
It's because of the way that pyright recognizes special built-in types — those that require special handling within the type checker (like "Tuple", "TypeVar" and "ParamSpec"). Pyright designates a small subset of modules (`builtins.pyi`, `typing.pyi` and `typing_extensions.pyi`) as "modules that define special built-in types". It accommodates the possibility that these special types could be declared in any of these special modules. It doesn't care whether it finds "ParamSpec" declared in `typing.pyi` or `typing_extensions.pyi`. It treats them the same. This simplifies the code and accommodates more flexibility in cases like this one.

I'll close the issue once we release the next version of pyright with the updated typeshed stubs.

**Comment by erictraut** [comment]
Fixed bug in "is None" and "is not None" type narrowing logic when dealing with recursive type aliases. It will also be in the next published release of Pylance.
