### ISSUE TITLE
Show documentation when entering arguments of a function

### ISSUE THREAD

**Issue by quantum-booty** [microsoft/pyright#1280]
I am using pyright language server inside nvim, and this is what it looks like right now:
![image](https://user-images.githubusercontent.com/28958399/102233090-c6e20200-3ee7-11eb-964d-6727c20b50cc.png)
It would be nice to show documentation like the palantir/pyls:
![image](https://user-images.githubusercontent.com/28958399/102233209-ed07a200-3ee7-11eb-80fe-78510517d064.png)

Furthermore, it looks like the function signature is not as accurate as the pyls, for example in pyls the second argument is index: Optional[Axes]=None, but in pyright its something not really readable.

**Comment by erictraut** [comment]
If Pyright is using type information from a type stub, it will use any doc string information from that type stub. Since many type stubs contain no doc strings, there will be nothing for it to display.

Pylance (which is built on top of Pyright) adds a feature where it will search out the original source code associated with a type stub and try to find the doc string in the source. This isn't a feature we plan to include in Pyright though. So if you want this feature, you'd need to switch to Pylance, which works only with VS Code.
