### ISSUE TITLE
Dict with kwargs

### ISSUE THREAD

**Issue by timrid** [microsoft/pyright#1300]
**Describe the bug**
If I create a dict with kwargs, `_KT` is undefined (`Unknown`). It should be `str`.

**To Reproduce**
```python
a = dict(helloworld=1)
reveal_type(a)
```

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/6593626/102722528-e9b65100-4301-11eb-86b4-5fe9155f91fb.png)

**VS Code extension or command-line**
Python extension: v2020.12.424452561
Pylance extension: v2020.12.2

**Comment by erictraut** [comment]
This is an unfortunate result of the way the `dict` constructor is defined in the type stub. The constructor overload that handles this case does not include `_KT_` in its signature, so there's no way for the type checker to determine the value of `_KT` in this case.

```python
    @overload
    def __init__(self, **kwargs: _VT) -> None: ...
```

I recommend against using this form of dict construction in favor of the standard dict syntax:
```python
{ "helloworld": 1 }
```

If you must use this form of the constructor, the workaround is to provide an explicit type annotation:
```python
a: Dict[str, int] = dict(helloworld=1)
```

**Comment by timrid** [comment]
Alright, thanks for the quick reply.

But then how can mypy do it right? It generates the following output:
`note: Revealed type is 'builtins.dict[builtins.str*, builtins.int*]'`

**Comment by timrid** [comment]
I wonder why not something like this is used in the stubs? That works for me. I only changed the `__init__` to `__new__` and gave it an return value.

```python
from typing import MutableMapping, Generic, TypeVar, Iterable, Dict, Iterator

_KT = TypeVar("_KT")
_VT = TypeVar("_VT")


class dict2(MutableMapping[_KT, _VT], Generic[_KT, _VT]):
    def __new__(cls, **kwargs: _VT) -> "dict2[str, _VT]":
        ...
    def __len__(self) -> int: ...
    def __getitem__(self, k: _KT) -> _VT: ...
    def __setitem__(self, k: _KT, v: _VT) -> None: ...
    def __delitem__(self, v: _KT) -> None: ...
    def __iter__(self) -> Iterator[_KT]: ...

a = dict2(helloworld=1)
reveal_type(a)
```

**Comment by erictraut** [comment]
Mypy must have added some special-case logic to cover this particular method of this particular class. We try not to do this in pyright because it's a slippery slope. 

Your proposed solution might work, but it's incomplete. You'd need to define additional overloads for the `__new__` method. Otherwise the use of alternate constructor arguments would generate false positive errors. If you want to propose such a solution, please submit an issue or a PR to the typeshed repo. We regularly pull updates from typeshed when we publish updated versions of pylance and pyright.
