### ISSUE TITLE
'Never' as a type in pyright message

### ISSUE THREAD

**Issue by lucidbee** [microsoft/pyright#136]
A confusing error message.

"560:37 - error: Argument of type 'Never' cannot be assigned to parameter 'lesson' of type 'Lesson'"

The parameter had been assigned a value of None and the function was expecting a parameter of type Lesson. 

What is the meaning of 'Never' here? It is not defined in our code base.

**Comment by lucidbee** [comment]
Possibly this is a typescript type leaking into the error message.

**Comment by erictraut** [comment]
"Never" what results when the type constraint system comes to the conclusion that no possible types can meet the constraint. For example:
```
foo = Foo()
if isinstance(foo, Foo):
   foo.do_something()
else:
   foo.do_something()
```

In this case, the second "foo" in the else clause is type "Never" because the first if statement should have always been taken. 

The error message is telling you that you should never get to this location in the code.

You're right that this concept and the "Never" type comes from TypeScript. It seemed like a reasonable term, and I didn't have a better alternative. :)

I can and should document this better. Thanks for the suggestion.

**Comment by erictraut** [comment]
I've added documentation for the "Never" type [here](https://github.com/microsoft/pyright/blob/master/docs/internals.md).

**Comment by scanzy** [comment]
What about this:

```python
class Base:
    def myFunc(self) -> None:
        if isinstance(self, Named):
            print(self.GetName())

class Named:
    def GetName(self) -> str:
        return "John"

class Person(Base, Named):
    ...
```

I get the error:
`# Cannot access member 'GetName' for type 'Never'. Unsupported type 'Never'`

**Comment by erictraut** [comment]
In the example above, the `isinstance` check is narrowing the type of `self` within the `if` statement block. Outside of the `isinstance` check, the type of `self` is assumed to be `Base`.

I see what you're trying to do here, and one could make the argument that Pyright's type narrowing shouldn't apply to `self` in this case because its type might be a subclass of `Base`.

What you're doing in this code snippet is an antipattern in object-oriented programming — something that is to be avoided. A base class should not know about classes that derive from it. Derived classes should override functionality in the base class using method overrides.

**Comment by tino** [comment]
I experience it in this situation:
```python
if not os.environ.get("TESTING", False):
  # Setup database
  # ...
  db_pool = PGPool(**pool_setup)
else:
  db_pool = None
```

In a file using the `db_pool.conn()` I get 
```
Cannot access member "conn" for type "Never"
  Type "Never" is unsupported (PylancereportGeneralTypeIssues)
```

**Comment by nathan-chappell** [comment]
In my case, it's coming to the conclusion because the value is modified in a closure, and it won't let me convince it otherwise.

![image](https://github.com/microsoft/pyright/assets/36384302/d91d2a47-168d-42af-81a7-e683a3ca084e)
