### ISSUE TITLE
Add output of all aliases in --verifytypes report

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#1379]
**Is your feature request related to a problem? Please describe.**
As discussed here:  
https://github.com/pandas-dev/pandas/issues/28142#issuecomment-761856002

It would be useful to see the aliases in the report, since the public API can be discerned at the top level of pandas.

**Describe the solution you'd like**
Either an option to include the aliases (or always include them) in the JSON output of `--verifytypes`

**Comment by erictraut** [comment]
I've added this capability, but there are a few caveats:

1. Alternate names are output only in the case that they are publicly re-exported using one of the idioms documented [here](https://github.com/microsoft/pyright/blob/master/docs/typed-libraries.md#library-interface). An internal import that is not re-exported will not be reported as an alternate name. This means, for example, that `pandas.core.series.Series` does not report an alternate name `pandas.Series` with the released version of pandas because `pandas/__init__.py` does not use the redundant import form (`from pandas.core.api import Series as Series`) when importing `Series`, so it's treated as a private import without a re-export.
2. Alternate names for symbols declared within a module or class are not listed by virtue of their containing module or class being publicly exported. That means, for example, that `pandas.core.series.Series.axes` would not list an alternate name of `pandas.Series.axes` even if `pandas.core.series.Series` does list `pandas.Series` as an alternate name. It's not practical to list all alternate names of every sub-scoped symbol because it would result in an explosion of alternate names in many cases.

Hopefully this will still be useful with these two limitations.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.102, which I just published.
