### ISSUE TITLE
Load types defined in external packages.

### ISSUE THREAD

**Issue by mhzed** [microsoft/pyright#139]
**Is your feature request related to a problem? Please describe.**

Here is a screen shot:

![Screen Shot 2019-05-29 at 11 29 40](https://user-images.githubusercontent.com/1879769/58527794-b20b2400-8206-11e9-8719-52a8b48f25b7.jpg)

1. pyright deduces that Y is of type 'unknown' instead of "nd.NDArray".  "nd.NDArray" is a class defined in a python file in the external package "mxnet" (go to definition works in vscode).
2. all type checks by pyright are bypassed subsequently, as illustrated by the code below.

**Describe the solution you'd like**
It appears pyright maps all symbols imported from external packages into 'unknown'.  
Ideally pyright should try its best to parse/load the types in the external packages when available.

**Additional context**

**Comment by erictraut** [comment]
This is a very intentional design decision for pyright. Interfaces for external modules should be described by type stub files. If no such type stub file is available, you should create your own. For more background about this design decision, see this [documentation](https://github.com/microsoft/pyright/blob/master/docs/import-resolution.md#importance-of-type-stub-files).
