### ISSUE TITLE
Performance regression in version 1.1.100+ for large libraries

### ISSUE THREAD

**Issue by YodaEmbedding** [microsoft/pyright#1404]
**Describe the bug**
Pyright responds very slowly for the sample document below, particularly for `textDocument/hover` and `textDocument/completion`.

**To Reproduce**
Open an editor or LSP client (e.g. Neovim 0.5) running Pyright 1.1.100+. Then insert:

```python
import tensorflow as tf
tf.keras.Model.predict
 
```

Now type anything on line 3 (e.g. "`tf.`") to bring up a completion menu. This takes a large amount of time.

Further details are in https://github.com/neovim/nvim-lspconfig/issues/681.

**Expected behavior**
Much faster.

**Screenshots or Code**

https://user-images.githubusercontent.com/721196/105492147-53f94300-5c6c-11eb-8d1c-17067b75f05d.mp4

**Additional context**
The performance is much faster in Pyright 1.1.98 or 1.1.99. Although, even in these versions performance could still be improved; things run near-instantaneously in VSCode with Pylance. (My guess is that Pylance includes tensorflow type stubs.) It seems that merely referencing `tf.keras.Model.predict` somehow causes an overall slowdown in Pyright. However, I could not replicate this slowdown with most other `tf.keras.*` functions, nor with other libraries.

**Comment by jakebailey** [comment]
My first guess is the decorator change that @bschnurr noticed caused a regression. Pylance does not include stubs for tensorflow, no.

Do you have "useLibraryCodeForTypes" enabled?

**Comment by erictraut** [comment]
Am I correct in assuming that you have "python.analysis.useLibraryCodeForTypes" enabled? That will cause pyright to infer types from the tensorflow Python code, which will be performance-intensive and error-prone. I highly recommend using type stubs.

I've tried to repro the problems you're seeing. I've followed the steps above, and I'm not seeing a noticeable performance problem. I wonder if I'm using a different version of tensorflow than you because "tf.keras" is evaluated as the type of `Any`, so all types "hanging off of" that type are also `Any`.

I've reviewed the change list for Pyright 1.1.100, and I don't see any changes that would have an obvious performance impact. Have you confirmed that when you downgrade to Pyright 1.1.99 the performance increases? I'm wondering if some other change in your environment (e.g. upgrading to a new version of tensorflow) could explain the problem?

**Comment by erictraut** [comment]
Ah yes, I forgot about the change in decorator processing. That could explain this perf difference. This change greatly improves type evaluations in some cases, so I don't recommend reversing it.

**Comment by erictraut** [comment]
I had an older version of tensorflow installed. With the latest released version, I'm now seeing more complete types and somewhat longer response times.

When I type "tf.", there is a 1090ms pause. That's not terrible given at it needs to parse, bind, and partially analyze 65 (largish) source files. When I type "tf.keras.", there is another 137ms pause. That's almost imperceptible. Adding "Model." is also almost imperceptible.

A very long pause occurs when "predict" is added. This requires pyright to read, parse and bind about 370 more source files and adds about 7900ms! The issue is that there is no return type annotation for the `predict` method, so pyright attempts to infer it. That requires analyzing all of the code paths that return values within this function.

I tried adding a return type annotation of `-> Any` to the `predict` method, and the performance lag was almost completely eliminated.

I don't see anything wrong here. The changes in 1.1.100 improved type inference in cases where decorates were completely unannotated, so that's likely causing the type analyzer to do more work (but also get a better answer) when it's asked to infer the return type of `predict`.

The right answer here is for tensorflow to include inlined types. In the meantime, I recommend either installing type stubs for tensorflow or disabling `useLibraryCodeForTypes`.
