### ISSUE TITLE
Ability to run language server in browser

### ISSUE THREAD

**Issue by VincentBel** [microsoft/pyright#1452]
**Is your feature request related to a problem? Please describe.**

It seems current language server implementation only works in Node.js environment. Any plan to add browser support?

**Describe the solution you'd like**

**Additional context**

As far as I can see, most VSCode extensions/libraries now support running in browser. Like the builtin [`typescript-language-features`](https://github.com/microsoft/vscode/blob/1.52.1/extensions/typescript-language-features/src/extension.browser.ts) extension.

The benefits includes: 
- VSCode is adding support for running extensions in nodeless environment (the [`VSCodeVim`](https://github.com/VSCodeVim/Vim/pull/5130) extension has just finished the migration)
- Directly used in monaco editor (like the [`vscode-json-languageservice`](https://github.com/microsoft/vscode-json-languageservice))

**Comment by erictraut** [comment]
No, we don't have any plans to support this. There are a number of dependencies that are not supported in a browser.

**Comment by erictraut** [comment]
Thanks for the inquiry. It's possible this could become a priority at some point, but not for the foreseeable future.

I'm going to close this feature request for now, but others should feel free to upvote it or add more justifications and use cases. At some point, we could revive it.

**Comment by dlech** [comment]
In light of [this announcement](https://devblogs.microsoft.com/python/python-in-visual-studio-code-september-2021-release/#a-rich-python-editing-experience-in-the-browser-via-github-dev), has something changed in this regard?

**Comment by jakebailey** [comment]
Yes, in that we added web extension support in the Python and Pylance extensions for github.dev's general release. There are still a lot of limitations, but largely, since Pylance is pyright (with extra stuff), you can use it instead on github.dev. I doubt we'll make the same changes to the pyright extension, given github.dev is the only host of the web build and we're actively supporting it.

We had been thinking about creating something like mypy-play or TypeScript's playground for pyright (since internally, we've mostly de-nodified the codebase), but this will take a bit more effort that wasn't required for VS Code's web extensions. I'd still like to do so, it's just about time and hosting it in a way that's not difficult to publish.

**Comment by dlech** [comment]
> add more justifications and use cases

Our use case is for https://code.pybricks.com. This is a Progressive Web App for programming LEGO creations with MicroPython. We don't need a full language server. As a first step, we would just like to add code completion. So, e.g. if the `pyright-internal` package was published and was able to run in a web browser, we might be able to do this.

**Comment by wch** [comment]
Running pyright in the browser would also be helpful for a project I'm working on.

With regard to the practical hurdles of making it work, it appears that they're surmountable. There is a fork of pyright that has been modified to run in the browser here:
https://github.com/microbit-foundation/pyright

**Comment by rushilpatel0** [comment]
+1 to the comments above. Another browser compatible fork although behind by about a year was created by the folks at TypeFox.
https://github.com/TypeFox/pyright/tree/browser/packages/browser-pyright

I'm currently using the fork from Typefox to autocompletion and documentation annotations. Would love to see an official version that is browser compatible

**Comment by wch** [comment]
@rushilpatel0 I made a version of pyright that runs in the browser and is up-to-date. And more importantly, it is easy to update because the shimming is mostly outside of the core pyright code. https://github.com/posit-dev/pyright 

For more information, see https://github.com/posit-dev/pyright/blob/pyright-browser/THIS_FORK.md

**Comment by grace-yiyi** [comment]
> [@rushilpatel0](https://github.com/rushilpatel0) I made a version of pyright that runs in the browser and is up-to-date. And more importantly, it is easy to update because the shimming is mostly outside of the core pyright code. https://github.com/posit-dev/pyright
> 
> For more information, see https://github.com/posit-dev/pyright/blob/pyright-browser/THIS_FORK.md

Can it be used for vscode web extension?I don't want to use pylance, because it is not open source.
