### ISSUE TITLE
Can intellisense work in this case

### ISSUE THREAD

**Issue by vpeopleonatank** [microsoft/pyright#1509]
I have, for example
```python
class TrainConf:
    logs_root_dir: str
   ...

def generate_log_dir_path(config: TrainConf) -> Path:
    ...
    logs_root_dir = path_check.get_path(config.logs_root_dir, force_relative_to_project=True)
   ...
```

My pyright setup can't resolve `logs_root_dir` , is this missing feature or bug?
![image](https://user-images.githubusercontent.com/30976876/108522274-3d8fe700-72ff-11eb-95a6-1219354e9f62.png)

**Comment by erictraut** [comment]
The sample you've provided is not complete, so I can't diagnose the problem. In particular, I can't tell how you have declared the `path_check` function. Could you please add post a minimal but complete example?

You may find it useful to use the type information provided in the hover text. Just hover over the symbol, and pyright will tell you what it thinks the type of that symbol is.

**Comment by vpeopleonatank** [comment]
For below sample code, if I comment line `@dataclass(frozen=True)`, intellisense work as normal, but uncomment it get pyright can't resolve and appear the error message like the first comment. `pydantic` is installed via pip.
```python
from pydantic.dataclasses import dataclass

@dataclass(frozen=True)
class TrainConf:
    logs_root_dir: str

def example_f(config: TrainConf):
    config.logs_root_dir
```

**Comment by erictraut** [comment]
This is because you're using the dataclass class from the pydantic package. This class uses a metaclass that implements non-standard semantics that cannot be described in the Python type system. Pyright has no insights about these semantics.

PEP 557 introduced dataclass as part of the Python stdlib. Pyright contains full support for this PEP. So if you change your code from `from pydantic.dataclasses import dataclass` to `from dataclasses import dataclass`, you will receive intellisense and type checking support. If you stick with pydantic, you won't.

**Comment by vpeopleonatank** [comment]
Thanks for clarification.
