### ISSUE TITLE
Some Imports within a venv are not resolving

### ISSUE THREAD

**Issue by MHDante** [microsoft/pyright#1523]
This might be related to one of the many tickets that @ipkiss42 submitted recently, so please let me know if it's a dupe.

**Describe the bug**
Certain packages have unknown members and submodules when imported as part of a venv.
However, entering the venv and running pyright from that environment addresses the issue. 
This indicates that there is probably lookup issues when using the `venv ` option in `pyrightconfig.json`
Mainly a pain point when using a project with multiple execution environments.

This issue happens to more than just the torch module. I have also seen it happen on numpy and our internal packages.
Perhaps this has to do with the inclusion of `py.typed` or `.pth` files.

**To Reproduce**

Assumes `git`, `pyright` and `python` (3.7.9) are installed.

### Bash
```bash
git clone --branch venv-import https://github.com/MHDante/pyright-test.git
cd pyright-test/
chmod +x setup.sh
./setup.sh 
pyright .
# see errors
source ./venvs/venv_common/bin/activate
pyright .
# no errors

```
### Windows:
```batch
git clone --branch venv-import https://github.com/MHDante/pyright-test.git
cd pyright-test/
./setup.bat
pyright .
rem see errors
./venvs/venv_common/scripts/activate
pyright .
rem no errors

```

**Expected behavior**
types imported into from the venv that is associated with that root should have the appropriate type information

Or at least, the behaviour should be the same when using "venv" config option versus when running pyright from within the venv

**Screenshots or Code**

You can navigate an example that illustrates the issue here:

https://github.com/MHDante/pyright-test/tree/venv-imports

Interpreter: python3.7 
![image](https://user-images.githubusercontent.com/4652122/108666411-06f3d100-74a5-11eb-8c78-e2e2437eca7e.png)
Interpreter: venv_common  (local venv)
![image](https://user-images.githubusercontent.com/4652122/108666467-2ab71700-74a5-11eb-91e9-0b79c6675f97.png)

**VS Code extension or command-line**

pyright 1.1.112
pylance 2021.2.3

**Additional context**
You guys are super cool.

**Comment by erictraut** [comment]
The problem is that any source file that is outside not contained within an execution environment root directory uses the default configuration settings, which means the default venv is effect (if it is specified). In this pyrightconfig.json file, there is no "venv" specified outside of the execution environments, so no venv is in effect. The "torch" package imports from itself using absolute import statements like `from torch import x` rather than using relative imports like `from .y import x`. These absolute import statements go through a normal import resolution process, but because it uses the default venv (which is not specified), the imports are unresolved.

The current logic determines the execution environment based on the path of the source file. It needs to be updated to understand that the execution environment can be inherited from the importer. For example, if the file `foo.py` is within execution environment `root1`, and it imports `torch/__init__.py`, then `torch/__init__.py` should also be analyzed as though it's in execution environment `root1` even though it's not located under that directory.

This is going to be a big change, and it could take a while to get it right. In the meantime, a partial workaround is to define a default "venv" setting in pyrightconfig.json outside of all execution environments. In other words, include the following line in your config file:
```
  "venv": "venv_common",
```

**Comment by MHDante** [comment]
Just a note that setting that top-level `venv` re-introduces this issue:
https://github.com/microsoft/pyright/issues/1508

Can be reproduced here:
https://github.com/MHDante/pyright-test/tree/1523_example

**Comment by erictraut** [comment]
After some investigation, I can confirm that this is a dup of #1508. As I mentioned in that issue, support for different venvs within different execution environments was an ill-conceived feature. We need to decide whether to remove it or somehow fix it.
