### ISSUE TITLE
How to limit diagnostic result from pyright

### ISSUE THREAD

**Issue by vpeopleonatank** [microsoft/pyright#1543]
I use neovim as editor with pyright as language server. When I open vscode with pylance enabled, It only returns errors such as undefined class or variable, unresolved import. My neovim with default pyright returns above listed errors and types of errors about type checking such as `Operator "+" not supported for types "None" and "int"    Operator "+" not supported for types "None" and "int"`. Can I limit diagnostic result from pyright like vscode?

**Comment by erictraut** [comment]
Pylance and pyright differ in two important settings:
* python.analysis.typeCheckingMode: Pylance defaults to "none" and Pyright defaults to "basic"
* python.analysis.useLibraryCodeForTypes: Pylance defaults to true and Pyright defaults to false

If you want pyright to behave the same as Pylance, you'll need to make those settings adjustments.

Also Pylance ships with some additional bundled type stubs, so if you're seeing further differences in behavior it may be due to the presence of these bundled stubs. You can download these bundled stubs from [this github site](https://github.com/microsoft/python-type-stubs) and install them manually in your environment.

**Comment by vpeopleonatank** [comment]
In CLI Options guide of pyright, I can't get any args for setting above options: [cli_pyright_doc](https://github.com/microsoft/pyright/blob/master/docs/command-line.md)
But in [Pyright Configuration guide](https://github.com/microsoft/pyright/blob/master/docs/configuration.md), It does.
Can I set these two settings in pyright cli?

**Comment by erictraut** [comment]
Yes, you can set these in the pyrightconfig.json file.
