### ISSUE TITLE
How to disable type errors from a single module?

### ISSUE THREAD

**Issue by happycoder97** [microsoft/pyright#1555]
I am using OpenCV, GLFW and pyimgui. These don't have type stub files.
I want to disable the type errors just for these modules.
But I want to keep other errors, for example if I mistype a function name, it should say function not found.
How to configure this?

I have been looking at the [configuration docs](https://github.com/microsoft/pyright/blob/master/docs/configuration.md), but couldn't figure how to do this.

**Comment by erictraut** [comment]
Are you referring to a module that is implemented within your project or a module that you're importing from a third-party package? I'm presuming it's the latter.

By default, pyright will treat all imported symbols from untyped libraries (those that do not have a "py.typed" file and have no stub files) as "Unknown" type. When you use these symbols, you won't get any type checking, completion suggestions, etc, but you shouldn't receive any errors either.

Is it possible that you've enabled the "useLibraryCodeForTypes" configuration setting? If you enable this, pyright will attempt to infer types from untyped library code. This is useful for completion suggestions, but it's rarely accurate or complete enough for type checking. That's why it's disabled by default in pyright. If you've enabled this setting, then disabling it should eliminate the errors you're seeing. You will still get type checking for all of the typed libraries.

**Comment by happycoder97** [comment]
Yes! Putting useLibraryCodeForTypes: false in pyrightconfig.json worked.
I wonder where it got set to true. I'm using coc-pyright btw.

Thanks. That fixed it. Closing the issue.

For future readers: pyrightconfig.json needs to be put in the root of your project directory. I am using neovim+coc+coc-pyright. I think this is the same for other editors too.
