### ISSUE TITLE
Support resolving virtual paths

### ISSUE THREAD

**Issue by mohmyo** [microsoft/pyright#1595]
**Is your feature request related to a problem? Please describe.**
Pylance can't resolve importing `requests.packages.urllib3.util.retry` because it is not an actual file.

![image](https://user-images.githubusercontent.com/14170159/110329693-9e206300-8025-11eb-9a4b-ef3499cd3731.png)

Can't blame Pylance for not resolving that because this is the content of `requests.packages`, [see](https://github.com/psf/requests/blob/master/requests/packages.py).

**Describe the solution you'd like**
Maybe it can look for the possible nearby files that can complete this path.

**Comment by erictraut** [comment]
Pyright won't be able to handle dynamic module cases like this. "Looking around for nearby files" would be highly non-deterministic and error prone, so that's not a viable solution.

You can disable the `reportMissingModuleSource` diagnostic check for that line using a `# type: ignore` or for the entire file using `# pyright: reportMissingModuleSource=true`.
