### ISSUE TITLE
First argument to NewType should match assigned variable name

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#1605]
`A = NewType("B", int)` should generate an error

**Comment by erictraut** [comment]
On second thought, I'm not sure this should be an error. It's legitimate to assign any type any name as a type alias.

**Comment by LeuschkeTressa** [comment]
I propose adding this as an error. (Possibly disabled by default.)

Although not strictly required by the docs/PEP, flagging this as an error could be argued to be the least surprising behaviour, since:

* mismatches are probably unintentional in most cases
* this is an error in mypy, which many users are used to
* all code examples in [the documentation](https://docs.python.org/3/library/typing.html?highlight=runtime_checkable#newtype) and [the PEP](https://peps.python.org/pep-0484/#newtype-helper-function) have matching argument value<->variable names
* for the similar `TypeVar`, this _is_ an error (according to the docs/PEP) (and pyright correctly flags it as such)

Practical use case:
* A user uses a code refactoring tool to rename the variable at some place in the code where the variable is _used_. At that location the user doesn't see the string argument and the mis-match is caused by the tool renaming the variable on all locations (but the string argument will be left untouched).

A possible source of confusion for users with unintentional mismatches would be tools (linters, code hints, type checkers) presenting the user with a type name. The tool would typically pull it from the `TypeName.__name__`, which is set from the string argument, and hence not equal to `TypeName`.

Possibly of some relevance:
* The CPython implementation is basically the identity function + setting `.__name__`, which means that the runtime behaviour doesn't really leave room for CPython to express an opinion on whether to enforce this. In that case, the mypy implementation could be regarded to be somewhat authorative.

Background:
* @JukkaL commenting on making this an error in the original mypy implementation: https://github.com/python/mypy/issues/1284#issuecomment-233907725. This is also the thread discussing the introduction of `NewType`.

**Comment by erictraut** [comment]
This is more of a linting concern, probably not something that a static type checker should concern itself with. You could check whether pylint provides a rule to enforce this.

**Comment by LeuschkeTressa** [comment]
> This is more of a linting concern, probably not something that a static type checker should concern itself with.

I can see that making sense.

> You could check whether pylint provides a rule to enforce this.

Just checked - it does.
