### ISSUE TITLE
[Feature Request] Support * syntax in pyrightConfig extraPaths

### ISSUE THREAD

**Issue by danielgordon10** [microsoft/pyright#1684]
This would be nice to have if we have a dir with a bunch of libraries installed. It seems like currently we need to provide paths to each directory separately.

**Comment by jakebailey** [comment]
See also: https://github.com/microsoft/pylance-release/issues/973

One consideration is that file watching logic for this becomes a little complicated because 1) we may need special handlers for parent directories of globbed items to know when the paths have to be regenerated, and 2) glob patterns may match files which we don't want in extraPaths (besides maybe zips if those ever get supported).

What is your specific use case for this, as opposed to something like using editable installs? Are you trying to have a folder that contains many projects, or some external libs that are collected in some other folder?

**Comment by danielgordon10** [comment]
"some external libs that are collected in some other folder" - This

**Comment by erictraut** [comment]
Since this feature request is already captured in the pylance repo, I'm going to close this one as a duplicate.
