### ISSUE TITLE
Literal class member type widening

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [microsoft/pyright#1687]
**Describe the bug**

```python
from typing_extensions import Literal


def pet_speak(pet_type: Literal["cat", "dog"]):
    if pet_type == "cat":
        print("meow")

    print("bark")


class Pet:
    def __init__(self, pet_type: Literal["cat", "dog"]):
        self._pet_type = pet_type

    def speak(self):
        return pet_speak(self._pet_type)
```

pyright on that script reports an error of self._pet_type has type str when passed to pet_speak. If I look at the type of it when defined in constructor by reveal_type it is properly literal so somehow it loses its literal type and becomes a string in speak.

**Expected behavior**
No error.

**VS Code extension or command-line**
pyright command line version 1.1.125. 

**Additional context**
python version is 3.7.8 which is why I use typing_extensions for Literal.

**Comment by erictraut** [comment]
The current behavior is intended. When the type of a class or instance variable is inferred, literals are "stripped" from the type (i.e. it is widened to its non-literal type) because that's almost always what the code intends in such cases. 

If your intent is to retain the literal type for the class or instance variable, you can provide an explicit type annotation for it, like this:

```python
from typing_extensions import Literal


Pets = Literal["cat", "dog"]

def pet_speak(pet_type: Pets):
    if pet_type == "cat":
        print("meow")

    print("bark")

class Pet:
    def __init__(self, pet_type: Pets):
        self._pet_type: Pets = pet_type

    def speak(self):
        return pet_speak(self._pet_type)
```

**Comment by hmc-cs-mdrissi** [comment]
Providing explicit annotations works fine for me, so I'll go ahead and close this.
