### ISSUE TITLE
psycopg2: "DatabaseError" is unknown import symbol

### ISSUE THREAD

**Issue by bersace** [microsoft/pyright#1759]
Hi,

I'm new to static type analisys in Python. I found that pyright found more errors than other tools. Bravo !

I'm adding pyright to a public project : [Dramatiq-pg](https://gitlab.com/dalibo/dramatiq-pg/-/merge_requests/59). I'm facing an issue. If I enable `--lib`, more typo are detected but it triggers other unrelated errors on pyscopg2 :

``` console
$ cat pyrightconfig.json 
{
    "include": [
        "dramatiq_pg"
    ],
    "useLibraryCodeForTypes": true
}
$ pyright
Loading configuration file at /home/bersace/src/dalibo/dramatiq-pg/pyrightconfig.json
Assuming Python version 3.9
Assuming Python platform Linux
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding .git
stubPath /home/bersace/src/dalibo/dramatiq-pg/typings is not a valid directory.
Searching for source files
Found 6 source files
/home/bersace/src/dalibo/dramatiq-pg/dramatiq_pg/broker.py
  /home/bersace/src/dalibo/dramatiq-pg/dramatiq_pg/broker.py:19:5 - error: "Notify" is unknown import symbol (reportGeneralTypeIssues)
  /home/bersace/src/dalibo/dramatiq-pg/dramatiq_pg/broker.py:20:5 - error: "quote_ident" is unknown import symbol (reportGeneralTypeIssues)
  /home/bersace/src/dalibo/dramatiq-pg/dramatiq_pg/broker.py:206:40 - error: Cannot access member "_consum_conn" for type "PostgresConsumer"
    Member "_consum_conn" is unknown (reportGeneralTypeIssues)
/home/bersace/src/dalibo/dramatiq-pg/dramatiq_pg/utils.py
  /home/bersace/src/dalibo/dramatiq-pg/dramatiq_pg/utils.py:10:22 - error: "DatabaseError" is unknown import symbol (reportGeneralTypeIssues)
  /home/bersace/src/dalibo/dramatiq-pg/dramatiq_pg/utils.py:10:37 - error: "OperationalError" is unknown import symbol (reportGeneralTypeIssues)
  /home/bersace/src/dalibo/dramatiq-pg/dramatiq_pg/utils.py:13:5 - error: "quote_ident" is unknown import symbol (reportGeneralTypeIssues)
6 errors, 0 warnings, 0 infos 
Completed in 1.281sec
$
```

I don't know how to satisfy pyright about theses `unknown import symbol`. Do you have a clue on how to fix this ?

**Comment by bersace** [comment]
Hi @erictraut, thanks for the answer !

psycopg3 is far from ready for production and wont be available on old and current systems. Database world is pretty conservative ;-) Actually, I'm bound to what's available on CentOS 7 or 8.

I wrote partial type stubs for pyscopg2 and pyright is happy. Me too. :+1: 

If I disable `useLibraryCodeForTypes`, I loose some typo detection in my own code. As if pyright totaly ignores internal API and only validates usage of external libraries. Typo detection is one killer feature to use pyright. What other way than enabling `useLibraryCodeForTypes` triggers this typo detection ?

**Comment by erictraut** [comment]
I'm not sure what you mean by "typo detection". There are many forms of coding errors. Pyright will report basic syntax errors regardless of whether it has type information available. Detection of many other classes of errors requires an understanding of the types of symbols used within a statement or expression.

For example:
```python
x = 3 + foo # Error reported because foo is undefined (no type information needed)

import datetime
datetime.dat(2021, 4, 13) # Typo in "date" caught because type information is available for "datetime"

import untyped_lib
untyped_lib.dat(2021, 4, 13) # No errors because type information is unavailable for "untyped_lib"
```

Perhaps you could give a specific example of a "typo" that you are trying to detect?

**Comment by bersace** [comment]
@erictraut Yes that's exactly that. So I need `useLibraryCodeForTypes` to enable type inference on my code. I was confused by the recommendation to disable `useLibraryCodeForTypes`. I'm closing, feel free to correct me if I'm wrong.

Thanks for the help !

**Comment by erictraut** [comment]
`useLibraryCodeForTypes` disables type inference only for external libraries, not within your code. Inference is always enabled for your own code.

**Comment by bersace** [comment]
Hmm, thus, how do you explain this behaviour :

``` console
$ git diff dramatiq_pg
diff --git a/dramatiq_pg/broker.py b/dramatiq_pg/broker.py
index ad65400..4f0f53b 100644
--- a/dramatiq_pg/broker.py
+++ b/dramatiq_pg/broker.py
@@ -203,7 +203,7 @@ class PostgresConsumer(Consumer):
                 check_conn(self._consume_conn)
             except ConnectionClosed:
                 logger.info("Connection closed. Reconnecting...")
-                self.pool.putconn(self._consume_conn)
+                self.pool.putconn(self._consum_conn) # typo !
                 self._consume_conn = None
 
         if self._consume_conn is None:
$ pyright --lib dramatiq_pg
No configuration file found.
Assuming Python platform Linux
Searching for source files
Found 6 source files
/home/bersace/src/dalibo/dramatiq-pg/dramatiq_pg/broker.py
  /home/bersace/src/dalibo/dramatiq-pg/dramatiq_pg/broker.py:206:40 - error: Cannot access member "_consum_conn" for type "PostgresConsumer"
    Member "_consum_conn" is unknown (reportGeneralTypeIssues)
1 error, 0 warnings, 0 infos 
Completed in 1.346sec
$ pyright --lib dramatiq_pg
No configuration file found.
Assuming Python platform Linux
Searching for source files
Found 6 source files
/home/bersace/src/dalibo/dramatiq-pg/dramatiq_pg/broker.py
  /home/bersace/src/dalibo/dramatiq-pg/dramatiq_pg/broker.py:206:40 - error: Cannot access member "_consum_conn" for type "PostgresConsumer"
    Member "_consum_conn" is unknown (reportGeneralTypeIssues)
1 error, 0 warnings, 0 infos 
Completed in 1.252sec
```

`PostgresConsumer` is defined in this file, not in an external library. Why would `--lib` enable this typo detection ?

**Comment by erictraut** [comment]
You are correct that `PostgresConsumer` is defined in this file, but it derives from the class `Consumer`, which is not defined in this file. When pyright evaluates the expression `self._consum_conn`, it cannot tell whether the member `_consum_conn` is valid because it doesn't have visibility into the class that `PostgresConsumer` derives from.

You can find situations like this by adding the following line to your `pyrightconfig.json` file:
```
    "reportUntypedBaseClass": "warning"
```

When you enable `useLibraryCodeForTypes`, pyright is able to infer enough information about `Consumer` to find this error. But as I explained previously, type inference can easily lead to false positive errors when type checking. My recommendation is to disable `useLibraryCodeForTypes` and create type stubs for `dramatiq`. I was able to to use the "--createstub" option in pyright to generate a reasonable "first draft" of these stubs.

One thing you might want to do is run pyright within VS Code rather than from the command line. By running it as a language server in an editor, it will be much easier for you to see what types are being propagated and where. You can simply hover over any symbol, and pyright will tell you want type it thinks that symbol contains at that point in the code flow. If it was unable to determine the type, it will indicate "Unknown".

Pyright also has a way to report the use of any symbol that has an unknown or partially-unknown type. These represent "blind spots" for the type checker. You can add the following to your `pyrightconfig.json` file to display these as warnings:
```
    "reportUnknownParameterType": "warning",
    "reportUnknownArgumentType": "warning",
    "reportUnknownLambdaType": "warning",
    "reportUnknownVariableType": "warning",
    "reportUnknownMemberType": "warning"
```

**Comment by bersace** [comment]
Understood. Thanks for the explanation. :+1:
