### ISSUE TITLE
List concatenation bug?

### ISSUE THREAD

**Issue by tamuhey** [microsoft/pyright#1777]
```python
def f_optional(x: List[Optional[int]]):
    # 1. ERROR: Operator "+" not supported for types "list[int]" and "List[int | None]"
    [0] + x
    x + [0]

    y: List[Optional[int]] = [0]
    y + x  #  2. OK

    ["a"] + x  # 3. ERROR (heterogeneous concatenation, bug?)
```

Pyright seems to judge `[0] + x` (case `1`) as heterogeneous concatenation, because it passes the case `2`.
I have 2 questions:

1. Is it a bug?
2. Error in the concatenation to create heterogeneous list (case 3) is a bug?

### pyright version

pyright 1.1.132

## Updated

Since `list.__add__` is annotated as follows, I think the error in "heterogeneous concatenation" is not a bug in Pyright

```python
def __add__(self, x: List[_T]) -> List[_T]: ...
```

**Comment by erictraut** [comment]
Pyright has no special knowledge of how the `__add__` or `__radd__` operators apply to any specific type, including lists. It bases its analysis on the type information provided to it. In this particular case, the relevant type information can be found in the builtins.pyi typeshed stub.

```python
class list(MutableSequence[_T], Generic[_T]):
    ...
    def __add__(self, x: List[_T]) -> List[_T]: ...
```

This definition provides no support for heterogeneous list types because `_T` is fixed by the type of the LHS of the `+` operator.

Perhaps this should be changed to the following?

```python
typedef _S = TypeVar("_S")

class list(MutableSequence[_T], Generic[_T]):
    ...
    def __add__(self, x: List[_S]) -> List[Union[_T, _S]]: ...
```

If you think that's the case, please feel free to file a bug in the typeshed repo. If you can get agreement for that change, we'll promptly merge the updated typeshed stubs into pyright.

**Comment by tamuhey** [comment]
Thanks for your reply. I understand it is not a bug in Pyright for LHS case.
What about RHS case?:

```python
def f_optional(x: List[Optional[int]]):
    x + [0] # ERROR
```

I think Pyright can infer `[0]: List[Optional[int]]`, don't it?

**Comment by erictraut** [comment]
The LHS and RHS types must both be evaluated prior to evaluating the type of the expression that includes the `+` operator. We don't know whether the `__add__` or `__radd__` will be used, and in some cases, a combination of the two can even be used because the LHS and RHS might be union types. That means the RHS type cannot be inferred from the LHS type. Both need to be evaluated independently of each other before the type of the expression is evaluated.

**Comment by tamuhey** [comment]
Thanks, it is easy to understand this is not a bug.
I reported to typeshed repo: https://github.com/python/typeshed/issues/5234

**Comment by tamuhey** [comment]
A related issue was opened in 2018:

https://github.com/python/typeshed/issues/2383

This issue had been fixed once but was reverted.

https://github.com/python/typeshed/pull/2404
