### ISSUE TITLE
unbound variable detection is too strict

### ISSUE THREAD

**Issue by dlax** [microsoft/pyright#1790]
It seems that detection for unbound variables is too strict as it (apparently) only considers boolean values in conditions, whereas the truth value applies at runtime.

For instance, it's common to use `while 1:` as a condition:

```python
def f() -> int:
    while 1:
        x = 1
        break
    return x
```

On that example, pyright raises:
```
/tmp/pyright/test.py
  /tmp/pyright/test.py:5:12 - error: "x" is possibly unbound (reportUnboundVariable)
```

**Comment by erictraut** [comment]
Is this really common? I've never seen this before. Why would someone use `while 1` instead of `while True`? The former is less readable.

`while True` happens to work because pyright's logic knows about a small number of special-cased expression forms whose values can be statically determined early in the analysis, prior to building the code flow graph. Numeric expressions like `1` are not part of this special casing. I'm not inclined to add more special cases to handle this use case.

My recommendation is to do one of the following:
1. Switch to `while True`.
2. Initialize your variables prior to the loop if you plan to use their values after the loop.
3. Disable the `reportUnboundVariable` diagnostic either throughout your project or in individual files as necessary.

**Comment by dlax** [comment]
It's quite common, although certainly old-fashioned and can be encountered in "ancient" code bases (see Python's stdlib for instance).

So it's apparently not an overlook, and your position is reasonable then.
