### ISSUE TITLE
Pyright could not resolve import

### ISSUE THREAD

**Issue by yannickperrenet** [microsoft/pyright#1809]
**Describe the bug**
Pyright is unable to resolve imports when using `executionEnvironments` in the `pyrightconfig.json`. This happens ever since upgrading to pyright `1.1.136`, and happens independent of the import as long as it is an additionally installed import (e.g. standard library works fine). I am unsure of the exact version I came from but I verified version `1.1.96` works fine for me.

For example: "Import 'docker' could not be resolved"

**To Reproduce**
Project structure:
```bash
.
├── project-1
│   ├── __init__.py
│   └── main.py
├── project-2
│   ├── __init__.py
│   └── main.py
├── pyrightconfig.json
└── venvs
    ├── project-1
    └── project-2
```
and install `docker` inside the `project-1` virtual environment (created using `virtualenv -p python3 project-1`).

Inside the `project-1/main.py` put:
```python3
import docker
```

For the `pyrightconfig.json`:
```json
{
  "venvPath": "venvs",

  "pythonVersion": "3.8",
  "pythonPlatform": "Linux",

  "executionEnvironments": [
    {
      "root": "project-1",
      "venv": "project-1"
    },
    {
      "root": "project-2",
      "venv": "project-2"
    }
  ]
}
```

Now when opening the file `project-1/main.py` I am unable to jump to the definition of `docker`. 

**Expected behavior**
I expect to be able to jump to the definition of the import and not seeing "Import 'docker' could not be resolved". (Again, this works fine on previous versions of pyright.)

**Additional context**
I run `pyright` using Nvim's built-in LSP support: https://github.com/neovim/nvim-lspconfig, without adding any additional settings.

**Comment by erictraut** [comment]
Execution environments do not support separate virtual environments. Earlier versions of pyright allowed you to specify a "venv" per execution environment, but it never really worked because of the way that import resolutions work in pyright.

See https://github.com/microsoft/pyright/issues/1508 for details.

If you have multiple subprojects that require different virtual environments, you can define a different pyrightconfig.json file in each subproject root and run pyright separately for each of the subprojects. If you are using pyright as a language server and your client supports multi-root workspaces, you can define a different workspace root for each subproject.

**Comment by yannickperrenet** [comment]
The aforementioned issue (#1508) gave some much needed context, thank you. Nevertheless, for me it really is a bummer as the "one configuration file multi-venv support" feature was exactly what made me switch to pyright in the first place given that it allowed me to point to the respective venv to use for every project inside my monorepo based on its file path. 

The `venvPath` configuration does confuse somewhat in this context, especially: "Path to a directory containing one or more subdirectories, each of which contains a virtual environment." Given that "multi-venv" is not supported, what is the use case of this? And can I use it to solve my problem instead of having to define a `pyrightconfig.json` in each subproject root?

**Comment by erictraut** [comment]
The `venvPath` is typically not set in the configuration file because that path likely differs from one developer's machine to another. So it's more typical to choose a common venv name that is specified in the configuration file and then allow each developer on the team to specify their own venvPath, specified in their VS Code settings or on the pyright command line.

Is it feasible for you to create a single venv that is common to all of your subprojects — i.e. contains all of the dependent libraries required by all of your subprojects?

Another option is to not rely on virtual environments at all for type checking. Instead, check in type stubs (full or partial) for all of the libraries you depend upon. That's what we do in my team's monorepo.

**Comment by yannickperrenet** [comment]
> The venvPath is typically not set in the configuration file because that path likely differs from one developer's machine to another.

Got it! Thank you.

> Is it feasible for you to create a single venv that is common to all of your subprojects — i.e. contains all of the dependent libraries required by all of your subprojects?

I could, but I generally dislike this approach because different subprojects can dependent on a different version of the same package (due to version requirements of other packages).

> Another option is to not rely on virtual environments at all for type checking.

When it comes to type checking this makes a lot of sense to me. On the other hand, I love the fact that pyright can also be used as a language server (besides the type checking) allowing me to do things like "jump to definition" and for this use case checking in type stubs does not make sense.

I am going to close this issue now as I consider it resolved. Thank you a bunch for your quick and elaborate responses!
