### ISSUE TITLE
[ Django ] Foreign key set method not recognized (reportGeneralTypeIssues)

### ISSUE THREAD

**Issue by Lestt** [microsoft/pyright#1879]
Hello,

I'm using code-server to develop in python using django. Here is my IDE configuration:
```
code-server: v3.10.0
 VS Code: v1.56.0
Commit: 6610bff3216c48fdd0884191338b1092765dbb5a
Date: 2021-05-10T20:34:05Z
Browser: Mozilla/5.0 (X11; CrOS x86_64 13816.64.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.100 Safari/537.36
```

I'm using `Pyright v1.1.37`  to have the auto import / completion features, and it looks working well so far in most of the cases.
I have an error when i'm using django relation "magic" methods, Pyright does not recognized them.

Here is the error:

![image](https://user-images.githubusercontent.com/1737422/118734572-0b504000-b882-11eb-9102-580814713d04.png)

Here is my extension settings in code-server:
![image](https://user-images.githubusercontent.com/1737422/118736782-b6fb8f00-b886-11eb-9d20-a95852a07b8e.png)

Here is a small description of the classes `Person`, `RegStepValue` and `TimestampedModel`:
```
class TimestampedModel(models.Model):
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(default=timezone.now)

    class Meta:
        abstract = True


class Person(TimestampedModel):
    id = models.TextField(primary_key=True, editable=False, default=None)

    class Meta:
        db_table = "Person"


class RegStepValue(TimestampedModel):
    id = models.TextField(primary_key=True, default=uuid.uuid4, editable=False)
    person = models.ForeignKey(
        Person, models.DO_NOTHING, db_column="PersonId", db_constraint=False
    )

    class Meta:
        db_table = "RegStepValue"

```

I have installed `django-stubs`. Here is the details of the python / python packages i'm using:
```
 $ python3 --version
Python 3.8.3

mypy==0.770
django-stubs==1.5.0
```

Here is the setup.cfg in my root folder:
```
[flake8]
max-line-length = 120
exclude = .tox,.git,*/migrations/*,*/static/CACHE/*,docs,node_modules

[pycodestyle]
max-line-length = 120
exclude = .tox,.git,*/migrations/*,*/static/CACHE/*,docs,node_modules

[mypy]
# See https://sobolevn.me/2019/08/typechecking-django-and-drf
python_version = 3.8
check_untyped_defs = True
ignore_missing_imports = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True
warn_unreachable = True
warn_no_return = True

plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = config.settings.test

[mypy-*.migrations.*]
# Django migrations should not produce any errors:
ignore_errors = True

[coverage:run]
include = fango/*
omit = *migrations*, *tests*
plugins =
    django_coverage_plugin
```

I may have misconfigured something, but I really don't know what.

Any ideas ?

**Comment by jakebailey** [comment]
The django stubs make use of a mypy plugin (see your config), but pyright isn't mypy and can't use it, so uses the stubs as they are written now. It's very likely that this behavior is a dynamic behavior that the mypy plugin patches over and doesn't actually exist in the type stubs for django.

**Comment by Lestt** [comment]
@jakebailey Thanks for your reply.
I think it is a runtime behavior as these methods are auto interpreted by django on the runtime. Is there any way to set `pyright` to have the same behavior as `mypy` here ?

**Comment by erictraut** [comment]
As @jakebailey mentioned, django is doing behind-the-scenes runtime "magic" that is not described in the type information for django. There is a mypy plugin, but this is specific to mypy and cannot be used with other type checkers like pyright. So unfortunately, there's no great answer here.

A few potential workarounds:
1. Use `# type: ignore` comments to suppress the error
2. Manually edit the class to include the symbols that are dynamically generated by django; this can be done conditionally using the TYPE_CHECKER flag so the code is not executed at runtime

**Comment by erictraut** [comment]
I'm going to close this because there's not much we can do about it at this time other than offer the above workarounds.

**Comment by bobbyrenwick** [comment]
> 2\. Manually edit the class to include the symbols that are dynamically generated by django; this can be done conditionally using the TYPE_CHECKER flag so the code is not executed at runtime

Sorry for not understanding this, but I searched the repo and couldn't find much in the way of details about this `TYPE_CHECKER` flag. What does it mean? Please could you give an example? I'd love for reverse django relations to be correctly typed across our codebase, instead of ignoring the issues.

**Comment by bellini666** [comment]
@bobbyrenwick , I'm typing django with those types (https://github.com/sbdchd/django-types) and something like this:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from django.db.models.manager import RelatedManager


class Foo(models.Model):
    if TYPE_CHECKING:
        bars = RelatedManager["Bar"]()  # here is the trick

    objects = models.Manager["Foo"]()


class Bar(models.Model):
    objects = models.Manager["Bar"]()

    foo_id: int  # would be foi_id = Optional[int] if the foreign key could be null
    foo = models.ForeignKey[Foo](
        Foo,
        related_name="bars",
    )
```

With that I have the right typings for `objects`'s methods (e.g. all(), first(), get(), etc), the foreignkey also points to the right object and automatically considers the object to be `Optional` if `null=True` (done by the django-types project I mentioned) and I also can access `Foo().bars` and it will have the right typings for me.

You have to manually declare the typing inside the related model and inside a `if TYPE_CHECKING` because `RelatedManager` is something created dynamically and can't really be imported.

**Comment by bobbyrenwick** [comment]
Thank you @bellini666! That's a very helpful response 🥇. I am basically doing the same, but casting to RelatedManager and ignoring the accessing being wrong on every access. This will save me from having to do that every time. Thanks 😄.

**Comment by devrrior** [comment]
Hi, I've read this issue and how to resolve the problem with pyright and Django, but I don't get how to should work the ForeignKey, for example, I have this:
```
class Order(models.Model):
    objects= models.Manager['Order']()

```

**Comment by devrrior** [comment]
Hi, I've read this issue and how to resolve the problem with pyright and Django, but I don't get how to should work the ForeignKey, I've read the documentation for 'django-types' but is so different compare with your code. 

For example, I have this:

```python
class Order(models.Model):
    objects= models.Manager['Order']()

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True,)
    objects = models.Manager['OrderItem']()

```
How I should type the code using `django-types`?  Thanks

**Comment by bellini666** [comment]
@devrrior I'm going to send a PR to django-types to improve their documentation. But your example is fine!

The foreignkey is something that we want to say that when accessing it we can expect to receive the other object there. Based on your exact example, you can do either of the following:

- `order = models.ForeignKey(Order)  # this will generate "order: Order"`
- `order = models.ForeignKey(Order, null=True)  # this will generate "order: Optional[Order]"`
- `order = models.ForeignKey("Order")  # this will not work because the typing can't extract the order from the argument dinamically. You can workaround as in the next example`
- `order = models.ForeignKey["Order"]("Order")  # this will generate "order: Order"`
- `order = models.ForeignKey["Order"]("Order", null=True)  # this will generate "order: Optional[Order]"`

So, if you are passing the object itself as the first argument, you don't need to put the `[]` right next to it (I force myself to do just to make it a habit). If the pointed object is a string (because it is in another file for example) need to add it there. In this case also, since pyright needs to know what "Order" means in the typing, you need to import it also. If it is not possible to import due to circular issues you can import it in a `if TYPE_CHECKING` statement.

Also, if you want to have the related objectset mapped, since in your example you did not modify it it will be called `orderitem_set` (or something like that, I usually name it all so I don't remember =P). You should do like this:

```python
class Order(models.Model):
    if TYPE_CHECKING:
        orderitem_set = RelatedManager['OrderItem']()
    objects= models.Manager['Order']()

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True,)
    objects = models.Manager['OrderItem']()
```

**Comment by devrrior** [comment]
@bellini666 Thanks for the help, now it's clear to me.
