### ISSUE TITLE
Dynamic subclass of abstract class in module makes pylance/pyright think the dynamic class is abstract

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#1920]
**Describe the bug**
A class declared in a module is not using the definition of the class protected by `TYPE_CHECKING`, with a bunch of other conditions present.    Getting error
```
Cannot instantiate abstract class "MyBase"
  "MyBase.myfun" is abstract
  "MyBase.something" is abstract
```

**To Reproduce**
The attached zip file has a top level file `startmylib.py`, and two packages `mylib` and `mylibuser` .  There is an abstract base class `mylib.MyBase` that has two implementations `myimpl1.MyImpl` and `myimpl2.MyImpl`.   The `__init__.py` in `mylib` has a class that a user can use to choose which implementation to use (i.e., either `myimpl1` or `myimpl2`).  This `__init__.py` has in it an `import` statement protected by `TYPE_CHECKING` that picks the implementation in `myimpl1` for type checking purposes.  The user code that leverages `mylib` is in the package `mylibuser`.  In there is `testmylib.py`, which imports `MyImpl` and in `makeit`, instantiates the `MyImpl` class.  In that instantiation, you get the error listed above.  The top level `startmylib.py` is an example of usage, where you first choose which implementation to use, and then call a function in `testmylib` to execute code based on the selected implementation of `MyImpl`.

It seems that the following conditions all have to be present to cause the error.  Removing any one of them makes the error go away:

- `testmylib.py` imports `logfun` from `mylib.util` .  If you remove this, the error goes away.
- The instantiation of `MyImpl` in `makeit()` in `testmylib` uses a named argument.  Changing it from `MI(name="meh")` to `MI("meh")` removes the error
- The base class has an abstract class method that is a property.  If you make it just an abstract class method (and other associated changes) to make it a method, not a property), the error goes away.

**Expected behavior**
Just like in `mypy`, no error is reported.

**Screenshots or Code**
[mylib.zip](https://github.com/microsoft/pyright/files/6563293/mylib.zip)
Code (required a bunch of files to get this simplified from our real code in order to replicate) is in ZIP file.  

**VS Code extension or command-line**
VS Code in pylance 2021.5.4.  Have reproduced using conda environments based on python 3.7 or 3.8.

**Additional context**
If you go to the error in `testmylib.py` that has `result = MI(name="meh")`, and tell VSC to "Go to declaration", it finds the declaration of `MyImpl` inside the `Chooser` class that is inside a method, rather than the definition of `MyImpl` that is inside the `if TYPE_CHECKING` block.  I would have thought it would have used the definition inside of `TYPE_CHECKING`

**Comment by erictraut** [comment]
Here's why you're seeing this behavior. The file `__init__.py` has a module-level (global) variable called `MyImpl`. This variable has no type annotation, so its type must be inferred by the type checker. Inference is performed by looking at all of the places in the code where a value is assigned to this variable. There are two such places. The first is the `import` statement within the `TYPE_CHECKING` conditional. The second is within the `choice` property setter. The type assigned to the variable by the import statement is of type `Type[MyImpl]`. The type assigned to the variable in the `choice` property setter is of type `Type[MyBase]`.

The `Chooser` class has a very odd implementation here. It appears to be a selector class, but it's also setting a global variable each time its `choice` setter is called. Is this what you intend? If so, why? Is it a singleton? If so, why is it even a class?

Here are a few suggestions.

1. You could change `Chooser` to be a factory class. Using this tried-and-true pattern, the `Chooser` class would instantiate the chosen class rather than returning the class and expecting the caller to instantiate it.

2. You could modify `__init__.py` to declare a global variable with a well-defined union type that includes non-abstract classes.

```python
from mylib.impl1 import MyImpl as m1
from mylib.impl2 import MyImpl as m2

MyImpl: Union[Type[m1], Type[m2]] = m1

...

    def choose(self):
        if self._choice == 1:
            return m1
        elif self._choice == 2:
            return m2
        else:
            raise Exception("Bad choice")

```

3. You can define a class method on the abstract class that allows you to instantiate the class without directly calling the constructor:
```python
# In the MyBase class
    @classmethod
    def create(cls, name: str = ""):
        return cls(name)

# In testmylib.py
def makeit():
    result = MI.create(name="meh")
    return result
```

**Comment by Dr-Irv** [comment]
Thanks @erictraut .  The Factory pattern was what I was looking for, so I made the modifications to do that and that resolved a number of other issues in our code.

> Here's why you're seeing this behavior. The file __init__.py has a module-level (global) variable called MyImpl. This variable has no type annotation, so its type must be inferred by the type checker. Inference is performed by looking at all of the places in the code where a value is assigned to this variable. There are two such places. The first is the import statement within the TYPE_CHECKING conditional. The second is within the choice property setter. The type assigned to the variable by the import statement is of type Type[MyImpl]. The type assigned to the variable in the choice property setter is of type Type[MyBase].

My question is why does `pyright` choose the _second_ interpretation, when the first one is bracketed by `if TYPE_CHECKING`  ? Shouldn't that first definition be the one that `pyright` chooses (which I presume is what `mypy` is doing) ?

**Comment by erictraut** [comment]
In general, the last assignment in a module is the one that ends up getting "exported" from that module. Consider the following:

```python
# file1.py
from datetime import datetime
datetime = 3

# file2.py
from .file1 import datetime

reveal_type(datetime) # int
```

The type of the imported `datetime` in this case is `int` rather than `Type[datetime]` because `file1` "overwrote" the imported value later in the module's execution flow. So it's correct to choose the last assignment when determining the exported type of the `datetime` symbol.

The presence of an `if TYPE_CHECKING` conditional is irrelevant from a type checking perspective. That's treated simply as an `if True` by the type checker.

In your particular example, you were manipulating the exported symbol in a function using a `global` name binding within a function. There's an argument to be made that pyright should ignore that assignment for purposes of determining the exported symbol, since it can't tell whether the function is called at runtime. But I'm concerned that making that change could break something else. And your code in this particular case was doing something _very_ unusual, so I don't think it's worth changing the behavior to accommodate that pattern.

**Comment by Dr-Irv** [comment]
> In general, the last assignment in a module is the one that ends up getting "exported" from that module.
> 
> In your particular example, you were manipulating the exported symbol in a function using a `global` name binding within a function. There's an argument to be made that pyright should ignore that assignment for purposes of determining the exported symbol, since it can't tell whether the function is called at runtime. But I'm concerned that making that change could break something else. And your code in this particular case was doing something _very_ unusual, so I don't think it's worth changing the behavior to accommodate that pattern.

Except if I do a `reveal_type(MyImpl)` at the bottom of `mylib/__init__.py`, I get `Type[MyImpl]` and not `Type[MyBase]`, so it doesn't seem that it used that the last usage determined the type.

**Comment by erictraut** [comment]
When pyright processes an import statement, it doesn't perform a full code flow analysis of the target module. That would be extremely expensive and would require a full code flow analysis of the full transitive closure of all imports in a collection of modules. Instead, it assumes that it can use the last type assigned to the imported symbol.

When you do a reveal_type within a module, it's performing a full code flow analysis within that file.

So yes, you will get different answers in these two cases. That's expected.

**Comment by Dr-Irv** [comment]
Thanks for the feedback.  As mentioned above, I changed our code to use the Factory pattern, removing all this funky stuff I did to get things working, and we're now good.
