### ISSUE TITLE
Incorrect output for reveal_type for type aliases for Literal

### ISSUE THREAD

**Issue by Zomatree** [microsoft/pyright#1943]
**Describe the bug**
The type shown from reveal_type when passed a type alias for a Literal only displays the name of the variable

**Expected behavior**
I expect the type shown to display what is inside the alias.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/39768508/120669635-8c652500-c487-11eb-9997-c9bc4b7cfbb6.png)

**VS Code extension or command-line**
`pyright 1.1.146`

**Comment by erictraut** [comment]
It was a conscious decision not to expand type aliases within `reveal_type` output because pyright supports recursive type aliases, and expanding those results in a hard-to-read mess. However, I think it's reasonable to expect that type aliases are expanded in most cases for `reveal_type` output. I've updated the logic to handle recursive type aliases a bit differently. It now expands the first level but doesn't expand recursively.

This change will be in the next release.

**Comment by erictraut** [comment]
This is included in pyright 1.1.147, which I just published. It will also be included in the next release of pylance.
