### ISSUE TITLE
How to turn off `Code is unreachable` for a line or block of code?

### ISSUE THREAD

**Issue by thep0y** [microsoft/pyright#1951]
I want to judge the current platform, so I need to use the `sys.platform` function, so I ran into this issue.

<img width="666" alt="截屏2021-06-06 20 44 08" src="https://user-images.githubusercontent.com/51874567/120924787-f25fdf80-c707-11eb-8879-f25d50d0b89b.png">

This hint makes me irritable, how can I turn it off temporarily?

**Comment by erictraut** [comment]
There is no way to disable an "unreachable " hint within pyright. There is perhaps a way to disable it in your editor. Which editor are you using?

Your editor is displaying this hint in a manner that would bother me as well. VS Code displays this hint as a subtle "graying out" of the text rather than a more explicit underlining effect. Perhaps you can suggest to the maintainers of your editor to do what VS Code does in this situation.

**Comment by thep0y** [comment]
Hi, I am using Sublime Text 4.

Is it possible to add the function to diable some hints with comments? Like `# ingore unreachable` or `# pyright: off`?

**Comment by erictraut** [comment]
I don't think that should be the responsibility of a language server. Please provide feedback to the maintainers of sublime.

**Comment by DetachHead** [comment]
you can disable it by creating this `pyrightconfig.json` to your project:
```json
{
    "pythonPlatform": "All",
}
```
