### ISSUE TITLE
Option to report type annotation source

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#1962]
**Is your feature request related to a problem? Please describe.**
When working with large 3rd-party libraries that have sometimes incorrect type annotations, e.g., pandas, it would be great if pyright can point to the file+line number where it got the type annotation from.

**Describe the solution you'd like**
An option for pyright to report where it got the type definition from.

**Comment by erictraut** [comment]
You can already right-click on a symbol and choose "Go to Declaration", and you will go to the source of that symbol's type. For example, if you want to know where a particular method is declared because it appears to have incorrect parameter or return type declarations, right-click on the method name and choose "Go To Declaration" or press F12. This assumes you're using VS Code. If you are using a different client, this functionality may be exposed in a different manner.
