### ISSUE TITLE
About the next step of pyright VSCode extension.

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#197]
First of all, this is not a feature request but simply a question.

I'm now working on a fully functional solution on VSCode for our big typed python projects. These are the features I'd like to have:
1. static type checking and error report (pyright, [vscode-python](https://github.com/microsoft/vscode-python))
2. type hint on hover (pyright, vscode-python)
3. reference finding and jump to defination (pyright, vscode-python)
4. provide in-file symbol navigation (vscode-python)
5. code formating and format on save (vscode-python based on autopep8 & isort)
6. auto import via intelliSense suggestion or "code actions"/"quick fix" ([importmagic](https://github.com/pilat/vscode-importmagic))
7. simple refactoring features like symbol renaming (vscode-python)
8. debuggin features (break point, variable watch, etc.)

At the begining, I use pyright + vscode-python + importmagic, but there's several problem:
1. It's very slow. Pyright and vscode-python(python-language-server) both do their own analysis work so code needs to be analysis twice.(plus importmagic has it's indexing process which makes it slower)
2. Duplicate suggestion items. We have #122 discussed about this.
3. Very few refactoring feature and quick fixes, and the most import "renaming" feature is buggy (internal error for no reason).
4. Importmagic is not doing a good work (slow, wrong suggest in some context, unfriendly to relative dir, etc.)

So, here's the problem. Vscode-python is just not as good as the TypeScript extension (who did great job on all the feature above), and both vscode-python and pyright are from microsoft, so what's the goal of pyright extension in a longer term?

**Is pyright going to be a optional language service or analyzer for the vscode-python extension, or a (somehow) replacement of it?**

**Or pyright will  focus on nothing more but checking and completion related features?** In that case, **is there a chance that other extension can implement other features base on the pyright's AST?**

I hope that python development under VSCode can be as good as PyCharm (or even better), pyright is the key reason that I believe that's possible.

I'm plainning to implement a extension that can do some of the features (formating, auto import, file symbol) as a replacement of vscode-python, but there's still some features that can only be done with a semantic analyzer (like renaming and quick fixes).

Please let me know what are the pyright team think.

Thanks.

**Comment by erictraut** [comment]
Good discussion to have. 

The VSCode Python extension contains a bunch of functionality that's factored into various subcomponents. For example, it includes debugging support, a way to specify the current python interpreter, support for third-party linters, and language service support. In that last category, it supports two different language servers - the first is based on [JEDI](python JEDI), the second is the [Microsoft Python Language Server](https://github.com/microsoft/python-language-server) developed by a team at Microsoft. The VSCode Python extension contains a setting that allows you to specify which of these two language servers you'd like to run. Pyright is another language server, so one potential solution is to allow users to disable both JEDI and the PLS. That way, you could get all the other functionality of the VSCode Python extension and use Pyright as your LS. I've reached out to the team that owns the PLS and the VSCode Python extension to see if they're amenable to that solution. This would address problems #1 and #2 on your list above.

As for #3 and #4, I'm open to adding these feature to pyright. Please open separate feature requests.

I'm reluctant to expose Pyright's AST through an extension interface. This would potentially limit future evolution of pyright because I'd need to maintain strict backward compatibility with all extensions.

**Comment by erictraut** [comment]
Incidentally, there is no "pyright team". Just me. :)

The VSCode Python extension and the PLS are staffed by teams of engineers who are dedicated to those projects. Pyright is something I'm doing in my spare time -- motivated primarily by the needs of my team. I'm glad that you and others are also finding it useful too. The more people who use it, the more motivated I'll be to continue to improve it!

**Comment by giyyapan** [comment]
Thank you for your serious reply!

> Pyright is another language server, so one potential solution is to allow users to disable both JEDI and the PLS. That way, you could get all the other functionality of the VSCode Python extension and use Pyright as your LS. I've reached out to the team that owns the PLS and the VSCode Python extension to see if they're amenable to that solution.

I'll be very happy to see pyright can work with vscode-python as a LS, and I think this is the best choice among all the others.

_FYI, I created an [issue](https://github.com/microsoft/vscode-python/issues/6899#issuecomment-520660175) before about adding an option to fully disable intelliSense from vscode-python, but your solution here is better_

> As for #3 and #4, I'm open to adding these feature to pyright. Please open separate feature requests.

Very glad to hear that! I'll open some feature request later, and I'm happy to help you implement them (If you need, and if I'm qualified enough).

> Incidentally, there is no "pyright team". Just me. :)

That's amazing! I'm so impressed about the great work you've done already and how motivated you are. Thanks again for your hard work!

_I'm very serious about using it on our product, hope this could give you some extra motivation :smile:_
