### ISSUE TITLE
Subclass inherits from generic class can' be assigned to it's parent type.

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#198]
**Describe the bug**

A class that inherits from generic class can't be assigned to it's parent type. please see the screenshot.

![image](https://user-images.githubusercontent.com/3479453/63008076-73574280-beb4-11e9-8055-e142e2a199c9.png)
_the 3rd error might not be the same with the 1st and 2nd, but the error message looks similar_

The full error message:
```
Argument of type 'Dict[str, B]' cannot be assigned to parameter 'data' of type 'Dict[str, A]'
  'B' is incompatible with 'A'
```

```
Argument of type 'List[B]' cannot be assigned to parameter 'data' of type 'List[A]'
  'B' is incompatible with 'A'
```

```
Argument of type 'G[B]' cannot be assigned to parameter 'data' of type 'G[A]'
  'B' is incompatible with 'A'
```

I read #130 and #110 , but I think this might be a different case, because the error says 'B' is incompatible with 'A',  and 'B' IS compatiple with 'A'.

**To Reproduce**
Full code:
```python
from typing import Dict, Generic, List

class A:...
class B(A):...

def fn_no_generic(data: A):...
fn_no_generic(B()) # <- this is ok

def fn(data: Dict[str, A]):...

d1: Dict[str, B]
fn(d1) # <- error

def fn2(data:List[A]):...
d2: List[B]
fn2(d2) # <- error

T = TypeVar('T')
class G(Generic[T]):...
def fn3(data: G[A]):...
d3: G[B]
fn3(d3) # <- error
```

**Expected behavior**
Like the `fn_no_generic` function, 'B' should be considered compatiple with 'A'.

**VS Code extension or command-line**
VSCode extension 1.0.55

**Comment by erictraut** [comment]
As counterintuitive as this might seem, the behavior you're seeing is correct. If you want to understand why, check out [PEP 483](https://www.python.org/dev/peps/pep-0483/). In particular, read the section that explains covariance, contravariance and invariance. For mutable sequences like List, the type parameter is invariant, which means that if a List[A] is expected, then List[B] is not allowed, nor is the converse allowed. Note that if you use an immutable sequence like Sequence[A], you can pass a Sequence[B]. That's because the type variable in that case is covariant.

**Comment by giyyapan** [comment]
Got it, I'll try somthing about immutable sequence.
Thanks for your explanation!
