### ISSUE TITLE
Potential type narrowing issue when  for class instance variables

### ISSUE THREAD

**Issue by plafosse** [microsoft/pyright#2019]
This could be a regression. If I recall correctly I don't think I was getting this issue prior to 1.1.149.

```python
from typing import Optional
class Foo():
    def __init__(self, f:Optional[str]):
        if f is None:
            self._f = None
            raise Exception()
        else:
            self._f = f

    def f(self) -> str:
        return self._f.capitalize()
```

Produces the following error
```
"capitalize" is not a known member of "None"
```

**VS Code extension or command-line**
VS Code extension version 1.1.149

**Comment by erictraut** [comment]
This isn't a regression. It's an intended change in behavior. We decided to enable the `reportOptionalMemberAccess` diagnostic rule by default in "basic" type checking mode. This was based on significant feedback we received from pyright users. See [here](https://github.com/microsoft/pyright/discussions/1969) for a discussion.

You can eliminate the error in the code above by deleting the `self._f = None` line. It's not needed anyway, since you're throwing an exception in this code path.

Alternatively, if you don't want to use the `reportOptionalMemberAccess` diagnostic check, you can override the default in the configuration settings.

**Comment by plafosse** [comment]
ok this is understandable. What about this example?

```python
import threading
class _Thread(threading.Thread):
    def __init__(self, task):
        threading.Thread.__init__(self)
        assert task is not None
        self.task = task

    def run(self):
        self.task.run()
        self.task.finish()
        self.task = None
```

Which gives me the following:

```
"run" is not a known member of "None"
"finish" is not a known member of "None"
```
