### ISSUE TITLE
Pyright doesn't check `__slots__`

### ISSUE THREAD

**Issue by Zomatree** [microsoft/pyright#2022]
**Is your feature request related to a problem? Please describe.**
Currently pyright doesn't check slots at all, this can be a issue when for example you forget to include an attribute name in the slots and try set or use that attribute, at runtime this fails but pyright doesn't check anything and allows it.

**Describe the solution you'd like**
Pyright should check if the attribute exists in the slots and raise an error when trying to use or set the attribute that don't exist in the slots.

**Additional context**
![image](https://user-images.githubusercontent.com/39768508/122871829-7aa8cc00-d327-11eb-944b-c05ad3784431.png)

**Comment by erictraut** [comment]
The evaluation of the expression assigned to `__slots__` cannot generally be determined at static analysis time. Pyright evaluates types of variables and expressions, not values. I suppose it would be possible to handle some specific cases like the ones in your example above where the expression is a tuple or list with string literals, but it wouldn't work in general.

The use of `__slots__` is an advanced Python feature that very few developers use.

I'll point out that mypy doesn't support checking of `__slots__` either.

For these reasons, I think we'd need a stronger signal from users to justify investing in a feature like this.

**Comment by Rapptz** [comment]
I think it makes sense to check for `__slots__` in a static manner, similar to the precedent set by `TypedDict`, `enum.Enum`, and `namedtuple` functional interfaces. I use `__slots__` and I don't think anyone make use of the dynamic nature using an iterable. I'll probably note that the Python standard library special cases dict `__slots__` by using their value as a docstring when using `inspect.getdoc`, unsure if that's of interest.

> For these reasons, I think we'd need a stronger signal from users to justify investing in a feature like this.

I think the feature is desirable,  though I don't know how complicated it'd be to implement. Functionally to me it's the same as a regular `dataclass` or `TypedDict` with potential inheritance and using inferred types. Having the type checker figure out whether an attribute is in slots or not would be handy for when you update code but forget to update slots, turning the runtime error into a compile time one.

**Comment by bijij** [comment]
I don't commonly use `__slots__` in my own code, but I will occasionally contribute to a library which does, and in adding new functionallity forget to add attributes to `__slots__` causing an error at runtime, like in the the scenario @Rapptz laid out.

For that reason I'd like to see `__slots__`, when used as a builtin iterable of strings (`tuple`, `list`, `dict`, etc).

**Comment by erictraut** [comment]
OK, it sounds like many pyright users want this feature.

I've implemented the following:
* If `__slots__` is defined, the symbols that are specified in the slots list are declared as instance variables for the class even if they are not otherwise assigned within the class. When selecting "go to declaration" for the instance variable, you will be taken to the slots entry that declares that instance variable.
* If `__slots__` is specified within a class and all of its subclasses and there is no explicit `__dict__` specified in any of the slots entries, any attempt to write to an instance variable through `self` will generate an error if that instance variable is not in the slots list. Properties are special-cased.
* If `__slots__` is defined within a class and a class variable is declared that conflicts with one of the slots declared locally within that class, an error is generated. (This condition generates a runtime exception by the Python interpreter, so it's good for the type checker to flag it.)

These diagnostics are reported as part of the reportGeneralTypeErrors diagnostic check. I considered creating a separate diagnostic check, but we generally split out specific checks only if there's a good reason to do so. I didn't see a good reason in this case. We can split it out in the future if there's cause to do so.

The expression assigned to `__slots__` must be a simple string literal (not an f-string and not a composite string), a tuple with zero or more simple string literals, or a list with zero or more simple string literals. Other more exotic expression forms are treated as though there is no `__slots__` assigned, which effectively disables these checks.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.153, which I just published. It will also be included in the next release of pylance.
