### ISSUE TITLE
Unpacking TypeVar constraints when type is Unknown.

### ISSUE THREAD

**Issue by bijij** [microsoft/pyright#2057]
**Is your feature request related to a problem? Please describe.**
In some library code, I have a a class which has a method which return type can be a few different types, It's currently a class generic using a typevar with these types as the constraint.

That being said however in some places it's not necessary to be aware of which type the instance generic is.
Rather than typing `Foo[Union[X, Y, Z]]` everywhere or defining an alias to the `Union` I was wondering if `Unknown` could be unpacked to be the `Union` of constraints automatically by pright.

Consider this code.

```py
from typing import Generic, TypeVar


T = TypeVar('T', int, str)


class Foo(Generic[T]):
    value: T

def foo(a: Foo) -> None:
    reveal_type(a.value)

```

Currently pyright will say `Type of "a.value" is "Unknown"`

**Describe the solution you'd like**
If the type is `Unknown` could pyright not expand the typevar to be the Union of the constraints? e.g.
`a.value` would become `int | str`, at least, when outside the class itself.

**Additional context**
Mypy, doesn't do this either, is there some logical reason why this wouldn't be desired?

**Comment by erictraut** [comment]
The current behavior is intended. You have defined a generic class that takes a single type argument, but when you use it the function `foo`, you have omitted the type argument. According to PEP 484, any omitted type argument is supposed to be interpreted as `Any`. Pyright uses the special form of `Any` called `Unknown` in this case because it is an "implicit" `Any`.

If your intent is for `foo` to accept a parameter of type `Foo[T]`, you should include `T` as the type argument:
```python
def foo(a: Foo[T]) -> None:
    reveal_type(a.value)
```

**Comment by erictraut** [comment]
You may want to enable the `reportMissingTypeArguments` diagnostic check. It will tell you when you have omitted type arguments in your type annotations.
