### ISSUE TITLE
Auto-insert of imports

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#207]
A type completion feature that automatically inserts imports at the top of the file.

**Comment by giyyapan** [comment]
Import candidate can be ambiguous in many contexts.

For example, variable `TEXT` can be imported from `sqlalchemy`, `sqlalchemy.orm` and whatever file that imported it using `from sqlalchemy import TEXT` or `from sqlalchemy import *` statement`.

If all possible auto-import candidate appears in the completion list, that will make everything else harder to find.

Some possible solution:
- Only suggest import source where the variable defined in and those uses `from X import *` syntax beacuse many `__init__.py` uses this way to organize exported members.
- Provide an option to disable the feature.

I also suggest some other approaches:
1. Add a refactoring/code action to import a specific unimported variable (this is what Pycharm do)
2. Or simply add a command to import cursor selected name (importmagic have this command)

![image](https://user-images.githubusercontent.com/3479453/63408782-6097bd00-c422-11e9-8e91-871ae161d059.png)
_code action in pychar_

![image](https://user-images.githubusercontent.com/3479453/63409054-fc292d80-c422-11e9-9b31-ea0ba4581b4b.png)
![image](https://user-images.githubusercontent.com/3479453/63409062-021f0e80-c423-11e9-9d7a-fa7f597882aa.png)
_importmagic's "Resolve Import" command_

**Comment by erictraut** [comment]
The TypeScript language service solves this by independently displaying the multiple sources of an import, allowing you to pick the one you want. I think that's less cumbersome than a separate command or a refactoring action. I'll play around with it when I have time to implement it. This feature will take a while to implement.

**Comment by giyyapan** [comment]
Python is not like TypeScript because the python's exports are more implicit (js only exports variables with "exports" keyword), so there's going to be much more possible import source for a name then in TypeScript.

But above all, it's all about optimization.

I preferer the "assisted manual import" approach above "auto-import completion" simply because I think auto-import in python can be harder to optimize and may not always behave as expected, but it's indeed easier to use.

I gave up importmagic for it messed up the IntelliSense feature. Mainly because it suggests auto-import event on cursor location like `user.` (cursor after name + dot), which is nonsense and should only contain member names of variable `user`.

If completion is the thing, I think these rules might be important:
- Never suggest auto-import when the user wants to type a member name of a variable (like `a.b`).

- Always put the existing variable name suggestions (like local variables or function parameters) before auto-import suggestions in the completion list 

  Say we have defined a local variable named `castable`. If a user typed "cast", suggestion `castable` should be above suggestion `import cast from typing` even the latter have a better match.

  Without this, I always have to worry whether I'm triggering auto-import on some strange name when I type the first few letters of a variable name and hit `tab`. It's unbearable.

I hope you can bring us a TypeScript level auto-import feature. That will be super amazing!

**Comment by erictraut** [comment]
This is now implemented in 1.0.58, which I just published. I'm really happy with how well it turned out. I opted for the fully automatic and integrated approach, the same as TypeScript offers. It's very fast, and it's smart about where to insert the new import statement. I also implemented your recommended ordering rules. Let me know what you think.

**Comment by giyyapan** [comment]
Just tried, It's simply THE BEST auto-import implementation I've ever used in VSCode! It's fast and smart enough in most cases. Thanks for your work! :+1: 

Still, I have some issues.

**First**
local variables are not always on the top. It's okay this way, I'm just reporting this because you said you implemented my recommended ordering rules in case it's a bug.
![image](https://user-images.githubusercontent.com/3479453/64522398-77984380-d32c-11e9-818b-0f83abdc4f05.png)


**Second**
I noticed that the auto-import will only be triggered if user types at least three characters, but there are shorter variables that need to be imported, like `from flask import g`. 

Probably you can provide a short variable candidate if there's an exact match.

For example. If a user types "g", "from flask import g" will be suggested, but "from X import good_variable" won't.

**Third**
`from some_dir import name_of_the_py_file` cases are not supported.
Say, I have a file called `utils.py` in dir `app/helpers`, and common use case would be:
```python
from app.helpers import utils

utils.some_func()
```
But when I type `utils`, pyright not suggesting `from app.helpers import utils`.

There's a lot of use cases like this in our project. please treat the name of pythons file as valid auto-import candidates.

**Comment by erictraut** [comment]
Thanks for the feedback.

1. I didn't follow your suggestion exactly. This is one case where I deviated slightly. All symbols are initially grouped above all auto-imports. Once you select one of them, the MRU cache will boost the priority of an auto-import selection above a local symbol. That's what happened in the screen shot you posted. If you're curious about the details of the implementation, search for [Sort Category](https://github.com/microsoft/pyright/blob/master/server/src/languageService/completionProvider.ts).

2. This was intentional. After a single character, there are necessarily going to be a lot of matches returned. I'm not sure about the idea of changing the matching behavior (exact vs. fuzzy) based on character count. That could be confusing. I'll try eliminating the two-character limit entirely and see how that feels.

3. That's a bug. I'll open a separate ticket for this one.

**Comment by giyyapan** [comment]
For short variables like "g" described in #2, maybe that's where the "semi-auto" solution shines.

Generally, adding a minimal character count limit is very reasonable, and I wouldn't recommend you to decrease the limit (3 is fine).

But there are commonly used short variables, and if we hope we don't have to write the import by hand, it seems that the only way would be adding a code action "import this variable" to all undefined variables, and let the user choose a source to import like what Pycharm does.
