### ISSUE TITLE
assignment error on d: Dict[Literal["key", "key2"], int] = dict(key=1)

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pyright#2083]
**Describe the bug**
I am getting this error

```
Expression of type "dict[str, int]" cannot be assigned to declared type "Dict[Literal['key', 'key2'], int]"
  TypeVar "_KT@dict" is invariant
    Type "str" cannot be assigned to type "Literal['key', 'key2']"
      "str" cannot be assigned to type "Literal['key']"
PylancereportGeneralTypeIssues
```

**To Reproduce**
put this code in editor in strict mode.

```python
from typing import Dict, Literal
d: Dict[Literal["key", "key2"], int] = dict(key=1)
```

**Expected behavior**
no error on assignment. if I change dict creation to dict creation literals such as
```python
d: Dict[Literal["key", "key2"], int] = { "key": 1 }
```

it works as expected.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/1333179/125677815-df23f75e-a41f-42e4-ad10-eb2be318c3c6.png)

**VS Code extension or command-line**
vs code

**Additional context**
it looks like type evaluator infer type for dict(key=1) as dict[str, int] but dict creation literal use bi-directional type inference and get its type as type annotated - Dict[Literal["key", "key2"], int]

**Comment by erictraut** [comment]
This is expected behavior. The `dict` constructor is overloaded, but the overload that applies in this case is:
```python
    def __init__(self: Dict[str, _VT], **kwargs: _VT) -> None: ...
```
Note that the specialized class in this case uses `str` as a key type.

You've identified the correct way to handle this in code — use a dictionary expression rather than a call to the `dict` constructor.

**Comment by heejaechang** [comment]
I see. so issue was not actually the assignment to d2 but because self is hard coded to Dict[/**str**/, _VT]. where _KT is actually the literals.

**Comment by heejaechang** [comment]
so, if I change the stub to _KT = TypeVar("_KT", bound=str) and make self: Dict[_KT, _VT], it will work?

I just tested this 

``` python
_T = TypeVar("_T", bound=str)

class MyClass(Generic[_T]):
    pass

t: MyClass[Literal["key"]] = MyClass()
```

and it behaves correctly.

**Comment by erictraut** [comment]
It might work, but the mechanism used in this particular overload (where the `self` parameter of `__init__` is annotated) is a non-standard annotation mechanism that has never been fully documented in any PEP. I was reluctant to support it in pyright because of this, but I was kind of forced to because typeshed adopted it. But the fact that it's undocumented (and I'd argue, not very well thought out), it's likely that each type checker will work differently in this case. I would recommend that we not try to get too fancy with the dict constructor. This is an extreme edge case, and there's a good, viable workaround.
