### ISSUE TITLE
Pyright forbids to call len on list narrowed from object

### ISSUE THREAD

**Issue by ethframe** [microsoft/pyright#2192]
**Describe the bug**
`len(x)` after `isinstance(x, list)` is reported as an error, even though `len` takes an argument of type `Sized`, and `list[Unknown]` is of type `Sized`, which is not partially unknown.

**To Reproduce**
```python
def foo(x: object) -> int:
    if isinstance(x, list):
        return len(x)
    return 0
```

produces the following error:

```
foo.py:3:20 - error: Argument type is partially unknown
  Argument corresponds to parameter "__obj" in function "len"
  Argument type is "list[Unknown]" (reportUnknownArgumentType)
```

**Expected behavior**
No errors.

**VS Code extension or command-line**
pyright 1.1.162.

**Comment by erictraut** [comment]
This behavior is expected. The error isn't saying that the call is forbidden. It's saying that the argument type is partially unknown.

You appear to have `reportUnknownArgumentType` enabled, which is one of the strictest checks supported by pyright. The `isinstance` check narrows the type of `x` to `list[Unknown]` because it has no way of knowing what type argument is appropriate in this case. The `reportUnknownArgumentType` check notifies you when the type of an argument is unknown or partially unknown.

Unfortunately, the `isinstance` operator doesn't allow you to specify a specialized class type as a second parameter. It would be convenient in this case to use `isinstance(x, List[Any])`.

You have several options here:
1. If you find that `reportUnknownArgumentType` is too noisy, you can disable it globally for your project or on a per-file basis using `# pyright: reportUnknownArgumentType=false`
2. Use `# type: ignore` to suppress the error on this line
3. Use a cast `cast(list[Any], x)`
4. Use a user-defined type guard function

```python
def is_list_any(x: object) -> TypeGuard[List[Any]]:
    return isinstance(x, list)

def foo(x: object) -> int:
    if is_list_any(x):
        return len(x)
    return 0
```

**Comment by ethframe** [comment]
I suppose this should've been a feature request. I think pyright can avoid reporting partially unknown argument if it can be upcasted to some fully known type that can also be passed as an argument.

To illustrate this I'll use a simplified example. Suppose we have the following two classes:

```python
class A:
    pass


T = TypeVar('T')


class B(A, Generic[T]):
    pass
```

And a function that takes a value of type `A`:

```python
def foo(a: A) -> None:
    pass
```

We want to write another function that takes an `object` and calls `foo` on it when the object is an instance of `B`:

```python
def bar(x: object) -> None:
    if isinstance(x, B):
        foo(x)  # error: Argument type is partially unknown
```

We can't have such a function without disabling `reportUnknownArgumentType`. However, we can add a `cast` to change the type of `x`:

```python
def bar(x: object) -> None:
    if isinstance(x, B):
        foo(cast(A, x))
```

This works fine. But what seems odd to me is that pyright already knows that `B[Unknown]` is a subtype of `A` and it can exploit that fact to automatically "upcast" partially unknown type and avoid reporting the error:

```python
def baz(x: object) -> None:
    if isinstance(x, A):
        foo(x)  # Ok
    if isinstance(x, B):
        # error: Unnecessary isinstance call; "B[Unknown]" is always an instance of "A"
        if isinstance(x, A):
            # isinstance(x, B) implies isinstance(x, A),
            # and isinstance(x, A) is sufficient for foo(x) to typecheck,
            # but pyright emits an error
            foo(x)  # error: Argument type is partially unknown
```

On a side note, I found another workaround for the original function. Pyright reports no errors for `x.__len__()`. This seems to be expected behavior, because the method is bound and does not have `Unknown` in its signature.

**Comment by ethframe** [comment]
@erictraut should I create an enhancement request?

**Comment by erictraut** [comment]
The feature is working as intended currently. The `reportUnknownArgumentType` is meant to inform you when the type of an argument is fully or partially unknown. I don't think it's appropriate to conditionally suppress it for special-case circumstances like this one.
