### ISSUE TITLE
Variable types potentially incorrect when dealing with __enter__ and __exit__

### ISSUE THREAD

**Issue by dob9601** [microsoft/pyright#2216]
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

**Describe the bug**
If a variable is initialised as None (or completely unbound) in a class' init, but then bound in `__enter__` and accessed in `__exit__`, Pyright treats it as if it is potentially unbound despite `__enter__` always being called before `__exit__`. Arguably the user could be calling `__exit__` directly, but that could also be considered to be (generally) being bad practice aside from where certain design choices necessitate it.

Whether this is an issue, or something that should be handled is subjective but thought it'd be worth raising either way

**Expected Behaviour**
Pyright treats code in `__exit__` as if it had been called immediately after `__enter__`

**Actual Behaviour**
Pyright raises an error, even if the specific variable has definitely been initialised in `__enter__`
**Screenshots or Code**
![image](https://user-images.githubusercontent.com/24723950/130355793-e74f0672-577c-4a20-97d2-0c73400204f6.png)

**VS Code extension or command-line**
`coc-pyright` (Command line)

**Additional context**
Pyright version 1.1.161

**Comment by erictraut** [comment]
Yes, this is intended behavior. Static type checkers like pyright perform local type analysis within individual execution scopes, but they don't have any notion of the order in which functions might be called at runtime. In this case, you are assuming that the `__enter__` method will always be called before `__exit__` because they are normally used in pairs, but a static type checker doesn't have that knowledge. (I say "normally" because these methods could be invoked explicitly in any order even though that's not typically how they are used.)

The recommended workaround is to add the statement `assert self.bar is not None` at the beginning of the `__exit__` method. This not only informs the static type checker of your assumption, but it also serves as human-readable documentation and runtime enforcement of your assumption.
