### ISSUE TITLE
#type comments don't register as usage

### ISSUE THREAD

**Issue by lucidbee** [microsoft/pyright#222]
for k,v in self.envs.items(): # type: ItemsView[int, Union[_SingleAgentEnv, _MultiAgentEnv, Optional]]
        if (v == actor):
               env_id = k
 
ItemsView gets  error: Import 'ItemsView' is not accessed

**Comment by erictraut** [comment]
Pyright supports type comments only for simple assignment statements ("<value> = <expression>). For loops are not supported. 

Type comments should be used only for Python 3.5 and earlier. Python 3.6 introduced proper syntax for variable type annotations. However, this syntax is available only for simple assignment statements, which is why pyright supports type comments only in those cases.

In general, you should never need to use type annotations for for statements as long as the iterator is properly typed. Pyright can infer the proper type of the iterated values if the iterator is typed correctly.
