### ISSUE TITLE
'while True' loop issue with 

### ISSUE THREAD

**Issue by lucidbee** [microsoft/pyright#223]
see function poll() in threaded_vector_env.py

This function has a while True loop that exits in the middle. There is no other way to exit.

pyright did not accept, I had to synthesize a dummy return after the loop. Otherwise it said, function must return a value.

This is  a bug because unreachable code should not need to be added, at some point it could cause a regression.

**Comment by erictraut** [comment]
This turned out not to be related to 'while True' specifically. Instead, it was a more subtle problem having to do with a break statement in an inner nested loop. The code flow engine was propagating the break up to the outer loops, causing it to think that there was a way to break out of the outer 'while True' loop.

This will be fixed in the next version of pyright. Thanks for the bug report!

**Comment by erictraut** [comment]
This bug is now fixed in 1.0.58, which I just published.
