### ISSUE TITLE
Diagnostic shows cannot access member - looks like it cannot find django-stubs 

### ISSUE THREAD

**Issue by ddhanak** [microsoft/pyright#2240]
**Describe the bug**
Pyright LSP doesn't seem to find django-stubs (using neovim + lsp)

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/16140109/131234943-cb36e494-aa52-4f4c-b263-433f87ee9987.png)

**VS Code extension or command-line**
Using through Neovim 0.5.0 and native Neovim LSP.

**Comment by erictraut** [comment]
This is almost definitely an issue with the stubs, not a problem with pyright.

If you provide a minimal, self-contained code sample that demonstrates the problem I may be able to provide more suggestions. I can't really diagnose issues based on screen shots of a partial program.

Also, please specify what version of django and django-stubs you are using.

**Comment by ddhanak** [comment]
Thank you for the quick response.

```python
class CreateUserSerializer(serializers.ModelSerializer):
    def create(self, validated_data):
    user = User.objects.create_user(**validated_data) # Cannot access member "create_user" for type "BaseManager[Any]...
    return user
```

Here is the model:

```python
class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    def __str__(self):
        return self.username
```
I'm using django 3.2.6 & django-stubs 1.8.0

**Comment by erictraut** [comment]
These aren't self-contained code samples. I don't know where symbols `serializers`, `AbstractUser`, `models` or `uuid` come from. I presume that `uuid` is from the stdlib module `uuid`. Could you please include the relevant import statements for the other symbols?

**Comment by ddhanak** [comment]
I basically cloned the following [project](https://github.com/agconti/cookiecutter-django-rest/blob/master/%7B%7Bcookiecutter.github_repository_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/users/serializers.py#L18) - I did not make any additional changes:

from the cli when running `npx pyright`
```bash
users/serializers.py:21:29 - error: Cannot access member "create_user" for type "BaseManager[Any]"
    Member "create_user" is unknown (reportGeneralTypeIssues)
```

**Comment by erictraut** [comment]
If you load this project into VS Code (with Pylance or Pyright installed), it makes it much easier to diagnose type issues. If I hover over `objects`, I see that its type is `BaseManager[Any]`. If I then right-click on it and choose "Go to Declaration", it takes me to the file `django-stubs/db/models/base.pyi`, which declares the instance variable `objects` within the `Model` class. If I then right-click on `BaseManager` and choose "Go to Declaration", I'm taken to `django-stubs/db/models/manager.pyi`. The class `BaseManager` is defined here. It has no method called `create_user`, which is why pyright emits the error you're seeing. 

If you think that `BaseManager` should have a method called `create_user`, then you should file a bug with the maintainers of the `django-stubs` project.

**Comment by ddhanak** [comment]
@erictraut thank you for your kind (and very quick) answers!
