### ISSUE TITLE
Code-blocks in if-statements controled by Literal[False] typed variables are still verified by type-checker

### ISSUE THREAD

**Issue by bijij** [microsoft/pyright#2259]
Not sure if this is a bug, or intended, 

**Descrption**
When a `literal[False]` variable is checked in an `if` statement the type-checker will treat the code as reachable.

given the code below pyright will output
```py
test.py:6:17 - info: Type of "2" is "Literal[2]"
test.py:10:13 - info: Type of "a" is "Literal[False]"
test.py:13:17 - info: Type of "3" is "Literal[3]"
test.py:15:17 - info: Type of "4" is "Literal[4]"
test.py:20:13 - info: Type of "b" is "Literal[False]"
test.py:23:17 - info: Type of "5" is "Literal[5]"
test.py:25:17 - info: Type of "6" is "Literal[6]"
  ```
  
  only omitting the `reveal_type` on line 4

**Expected behavior**

I would expect the code inside the if statement blocks on lines 12, and 22 to also be classified as unreachable.
hence types of `3` and `5` to not be revealed.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/8677174/131976700-369bf40a-1c35-4fe0-a955-b405cffe18ea.png)

**VS Code extension or command-line**
pyright 1.1.165

**Additional Information**
This came up as in a utility module i have a variable `PY_310` equal to `sys.version_info < (3, 10)`
and throughout the library do `if PY_310:` rather than re-importing sys for (in most cases) single use for it.

**Comment by erictraut** [comment]
This is intended behavior. The early stage of the type checker (the "binder" stage) is able to evaluate certain special expressions that affect the control flow graph. The expression `False` and `sys.version_info < (3, 10)` are examples of such expressions. These expressions don't depend on any type information because type analysis doesn't occur until later stages once the code flow graph has been built.
