### ISSUE TITLE
A general type error occurs in version 1.1.166 for the standard library urllib.parse.urlencode

### ISSUE THREAD

**Issue by ChristopherZhong** [microsoft/pyright#2267]
**Describe the bug**

Using the sample code in `test.py`.

```python
import urllib.parse

query_params = {}
urllib.parse.urlencode(query_params, quote_via=urllib.parse.quote)
```

In `pyright@1.1.166`, the following error occurs.

```
test.py:4:48 - error: Argument of type "Overload[(string: str, safe: _Str = ..., encoding: str | None = ..., errors: str | None = ...) -> str, (string: bytes, safe: _Str = ...) -> str]" cannot be assigned to parameter "quote_via" of type "(_p0: str, _p1: AnyStr@urlencode, _p2: str, _p3: str) -> str" in function "urlencode"
    No overloaded function matches type "(_p0: str, _p1: AnyStr@urlencode, _p2: str, _p3: str) -> str"
      Type "(string: str, safe: _Str = ..., encoding: str | None = ..., errors: str | None = ...) -> str" cannot be assigned to type "(_p0: str, _p1: AnyStr@urlencode, _p2: str, _p3: str) -> str"
        Parameter 2: type "AnyStr@urlencode" cannot be assigned to type "_Str"
      Type "(string: bytes, safe: _Str = ...) -> str" cannot be assigned to type "(_p0: str, _p1: AnyStr@urlencode, _p2: str, _p3: str) -> str"
        Function accepts too many positional parameters; expected 2 but received 4
          Parameter 1: type "str" cannot be assigned to type "bytes"
            "str" is incompatible with "bytes"
          Parameter 2: type "AnyStr@urlencode" cannot be assigned to type "_Str" (reportGeneralTypeIssues)
```

But the error does not occur in `pyright@1.1.165`

**To Reproduce**

1. Use `npx pyright@1.1.166 test.py`

**Expected behavior**

Output should be the same as `npx pyright@1.1.165 test.py`

**Comment by erictraut** [comment]
The new behavior is correct in this case. There was a bug that was masking the error in previous versions of pyright. 

Mypy produces the same error as pyright 1.1.166.

I don't know much about the urllib module, but I suspect that it should be using `AnyStr` rather than [a union of `bytes` and `str`](https://github.com/python/typeshed/blob/2620120a909e583da2971801b500ddfb2f518e78/stdlib/urllib/parse.pyi#L7). If I make that substitution, this error goes away. If you agree that this is an appropriate change, please consider filing a bug (or submitting a PR) within the typeshed repo.

**Comment by ChristopherZhong** [comment]
I filed an issue in the typeshed repo python/typeshed#6009

**Comment by erictraut** [comment]
Thanks, I'll close this issue. 

We pull the latest typeshed changes into pyright/pylance every couple of weeks, so you should see this fix shortly after it is merged into typeshed.
