### ISSUE TITLE
Support type narrowing on constructed tuples via pattern matching

### ISSUE THREAD

**Issue by iamkroot** [microsoft/pyright#2292]
**Is your feature request related to a problem? Please describe.**
It is quite common in some contexts to match on an ad-hoc tuple. Currently, pyright doesn't support type narrowing on such elements. Here's a sample snippet of the current behaviour:
```python
def z(a: tuple[Optional[int], Optional[int]], b: Optional[int]):
    # matching directly on tuple works- type of a[0] is narrowed
    match a:
        case (int(_), _):
            reveal_type(a[0])  # int

    # using an if-statement works
    if isinstance(a[0], int):
        reveal_type(a[0])  # int

    # matching on a constructed tuple doesn't work
    match (b, "any variable or literal"):
        case (int(_), _):
            # can't deduce that b should be int
            reveal_type(b)  # Optional[int]

```

**Describe the solution you'd like**
It would be nice to have support for narrowing for elements inside constructed tuples through pattern matching.
One possible way to implement would be to have pyright create a temp variable for the constructed tuple and then to replace all uses of the elements by indexing into the temp variable (not sure how feasible this is):
```python
    _temp = (b, 5)
    match _temp:
        case (int(_), _):
            reveal_type(_temp[0])  # int
            # however, the type narrowing still doesn't apply to b. Maybe this is the root cause?
            reveal_type(b)  # Optional[int]
```

**Comment by erictraut** [comment]
This would be very difficult to implement given the way that type narrowing works for match statements in pyright. It is implemented to handle a single match symbol, but handling arbitrary tuples would require generalizing that to an arbitrary number of symbols (e.g. `match (a, b, c):`).

Mypy doesn't handle this either. (Actually, mypy doesn't yet have any support for match statements.) 

Since match statements are such a new feature, I don't think we have a good feel yet for how it will be commonly used.

Since there are obvious workarounds for this, I'm going to close this for now. We might reconsider at a later time if we have good evidence that this pattern becomes common.
