### ISSUE TITLE
"isinstance not necessary" should not be an error level (a suggestion perhaps)

### ISSUE THREAD

**Issue by dlyubimov** [microsoft/pyright#236]
assert isinstance(x, Tuple)

generates an error "unnecessary isinstance() call" if x is already hinted to be a Tuple. 

Hints are hints, they are not enforced at runtime, it is not an error to double-check runtime compliance.

**Comment by erictraut** [comment]
Static types are not "hints". They're assertions of intent within your code. They specify the assumptions your code is making. If a runtime check were purely redundant in all cases, I would agree with you. However, this case is a frequent source of bugs because the first parameter to the isinstance() can be of any type. By checking for redundant (always-false or always-true) results, the static type checker is able to catch a class of bugs that would otherwise go uncaught.

If you are unsure what type a variable contains (e.g. it's coming from an untrusted source), then you should specify a type annotation of "Any" and perform the necessary runtime checks to validate its type.

If you feel a need to override this behavior in a particular case, you can use `# pyright: reportUnnecessaryIsInstance=false` or `# pyright: reportUnnecessaryIsInstance=warning`. But be aware that disabling this check will potentially leave you vulnerable to bugs that would otherwise be identified within that file.

**Comment by erictraut** [comment]
After talking more with Dmitriy, we decided that use of unnecessary isinstance within assert statements may be legit, so we agree to a compromise of eliminating this check within assert statements.

**Comment by erictraut** [comment]
This is now implemented in 1.0.60, which I just published. This condition is now ignored if it's within an assert statement.

**Comment by rattrayalex** [comment]
Hi Eric, I'm wondering if it might be worth reconsidering this one.

The use-case I have in mind is when you're exposing a library to others, you want an argument to be typed, but you may also want to validate it at runtime to give a good error message. 

My impression is that `assert` is not appropriate for this use-case, as passing the wrong thing should raise a `ValueError` or similar, not an `AssertionError`, and `assert` calls may be ripped out by optimizers while this should stay in.

```py
def say_hello(name: string):
  if not isinstance(name, str):
    raise ValueError("name should be a string")

  print(f"hello {name}")
```

Of course, this toy example is a bit different from what we do in practice.

Personally, I'm fairly happy to use the `# pyright: reportUnnecessaryIsInstance=false` workaround, but I wanted to share this example in case it helps inform your thinking.

**Comment by erictraut** [comment]
@rattrayalex, `reportUnnecessaryIsInstance` is a strict-mode check that is off by default. If you find that it doesn't suit your needs, you don't need to enable it. You can also specify that it should generate a warning or an information diagnostic rather than an error if you prefer. Or, as you point out, you can suppress the diagnostic in specific cases using a `# pyright: ignore`. Or you can disable the check on a file-by-file basis using `# pyright: reportUnnecessaryIsInstance=none`.

**Comment by erictraut** [comment]
@rattrayalex, `reportUnnecessaryIsInstance` is a strict-mode check that is off by default. If you find that it doesn't suit your needs, you don't need to enable it. You can also specify that it should generate a warning or an information diagnostic rather than an error if you prefer. Or, as you point out, you can suppress the diagnostic in specific cases using a `# pyright: ignore`. Or you can disable the check on a file-by-file basis using `# pyright: reportUnnecessaryIsInstance=none`.

**Comment by rattrayalex** [comment]
Fair enough! 

In our case, since we're a library, it may make sense for us to just disable it in our project. (I'd think that Good Libraries should have strict mode on in CI and should also typically disable this rule, but that's totally fine and easy to do).

Thanks Eric!

**Comment by Andrej730** [comment]
> This condition is now ignored if it's within an assert statement.

Would be great if it was a configurable option to have a warning in the cases when `assert` was used for type narrowing but it's not necessary anymore.
Related discussion - https://discuss.python.org/t/report-unnecessary-always-true-assertions/85248

**Comment by erictraut** [comment]
@Andrej730, I don't think that such a warning makes sense for all of the reasons given in the other discussion and for the reason mentioned above in this issue. There are legitimate reasons why asserts exist other than for type checking, so even if a type checker thinks that an assert is unnecessary, that doesn't mean it is. If we were to add such a check, it would need to be off by default even in strict mode, and we generally try not to add such checks because they're hard to discover and are rarely used by anyone.

**Comment by Andrej730** [comment]
Okay, could `reportUnnecessaryIsInstance` docs in https://microsoft.github.io/pyright/#/configuration mention that it's specifically ignoring uses in `assert`? So it will be easier to discover that it's intentionally unsupported.
