### ISSUE TITLE
Auto-import doesn't suggest imported file names

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#241]
`from some_dir import name_of_the_py_file` cases are not supported.
Say, I have a file called `utils.py` in dir `app/helpers`, and common use case would be:
```python
from app.helpers import utils

utils.some_func()
```
But when I type `utils`, pyright not suggesting `from app.helpers import utils`.

There's a lot of use cases like this in our project. please treat the name of pythons file as valid auto-import candidates.

**Comment by erictraut** [comment]
This will be included in the next release.

**Comment by erictraut** [comment]
This is now implemented in 1.0.60, which I just published.

**Comment by giyyapan** [comment]
I can't confirm this fix. Am I doing anything wrong?

#### Minimal steps to reproduce:
1. create a project dir
2. add pyrightconfig.json
3. add `app/utils.py` containing `def some_func():pass`
4. add `app/test.py`
5. type `utils` in test.py, no auto-import suggestion.

![image](https://user-images.githubusercontent.com/3479453/65045666-caf43c80-d991-11e9-8e66-476780392ee1.png)

#### extension version
1.0.62

**Comment by erictraut** [comment]
That's because you typed "utils" in the second file. Auto-import looks for symbols that you can import from other files. In this case, the other file (utils.py) exports one symbol at the module level: "some_func". If you start typing "some_func" in the "test.py" file, auto-import should offer to complete it for you.

**Comment by giyyapan** [comment]
Thanks for the reply, I see what you mean.

Indeed, pyright can offer "some_func", but when I originally reported the bug described in this issue, I meant this usage.

So let me make this clear:
I hope pyright can support the usage that I described above. To be specific, when typing the name of a py file, auto-import can suggest `from [dir of the file] import [the file]`, because I think this is a very common style to manage python import namespace, and we have many codes like that in our projects.

In the example above, when I type `utils` in `test.py`, I hope pyright can suggest `from app import utils`.

Thanks!

**Comment by erictraut** [comment]
No, I don't plan to support that for a couple of reasons. It would be expensive because I'd need to cache a bunch of file system data to avoid hitting the file system in the middle of a completion action. Also, importing individual symbols from a module is a better approach than importing entire module names. Part of my goal with pyright is to encourage better practices in python coding. So while you may see that pattern used in legacy python code, I think auto-import should "do the right thing" rather than perpetuating bad practices of the past.

**Comment by giyyapan** [comment]
Though I may have a different understanding about "the better practice" here, but I get your point.
I'll try to adapt that. Thanks anyway.
