### ISSUE TITLE
Pyrght widens Literal types from __init__ assigned to instance vars

### ISSUE THREAD

**Issue by GBeauregard** [microsoft/pyright#2432]
While (again) working on the rich codebase I came across this case a lot where pyright widens an instance variable `Literal` to a `str` in a situation where `mypy` keeps it a literal. The type of note in the example code is the instance variable `self.fruit`, I've included the example above it for comparison of behavior in various situations.

The difference between `reveal_type(self.fruit)` after assignment and `reveal_type(my_lunch.fruit)` or the `self.fruit` in the instance method makes me think it's a bug.

A workaround for this behavior is to instead do `self.fruit: Fruits = fruit`

If it's not a bug, should this behavior be changed? If it's intended can you elaborate on your thoughts with it? I'm not convinced these variables always need to be annotated when already annotated in the `__init__`, particularly in comparison with how assignment is treated with literals elsewhere.

```python
from typing import Literal


Fruits = Literal["Apple", "Orange", "Mango", "Watermelton"]

my_fruit: Fruits = "Apple"
reveal_type(my_fruit)  # revealed as Literal["Apple"]
your_fruit = my_fruit
reveal_type(your_fruit)  # revealed as Literal["Apple"]


def fruit_printer(fruit: Fruits):
    print(fruit)


class Lunch:
    def __init__(self, fruit: Fruits):
        reveal_type(fruit)  # revealed as Literal["Apple",...
        self.fruit = fruit
        reveal_type(self.fruit)  # revealed as Literal["Apple",...

    def show_fruit(self):
        reveal_type(self.fruit)  # revealed as str ??
        fruit_printer(self.fruit)


my_lunch = Lunch("Apple")
reveal_type(my_lunch.fruit)  # revealed as str ??
my_lunch.show_fruit()
```

**Describe the bug**
An instance variable set to a Literal gets widened to its type if not explicitly annotated. This makes the instance variable type-incompatible to use with functions expecting the Literal type.

**To Reproduce**
Run above code with pyright.

**Expected behavior**
I think it maybe makes more sense to keep it a Literal unless annotated otherwise.

**VS Code extension or command-line**
pyright 1.1.178 Linux commandline

**Additional context**

**Comment by erictraut** [comment]
The current behavior is as designed. We've spent a lot of time tuning the rules for when literal types should be retained and when they should not. [PEP 586](https://www.python.org/dev/peps/pep-0586/#type-inference) specifically discusses the pitfalls of inferring literal types, but it doesn't mandate a particular behavior.

For an instance variable that has no type annotation, pyright infers its type from all of the places where it is assigned. If it is assigned a literal value in one or more of these assignments, that literal value is widened to its non-literal type unless the variable is a constant (either marked `Final` or named in all-caps). That explains why `frult` has an inferred type of `str` in your example above.

Pyright also applies assignment-based type narrowing locally to an execution context. So, although the inferred type of `fruit` is `str`, it is locally narrowed to a literal based on the values that are assigned to it. That's why `reveal_type)` reports what it does in that context.

Changing the behavior in this case to match mypy's would introduce inconsistencies in pyright's inference strategy and would break a lot of false positives with code that currently type checks with pyright, so it's unlikely we'd make such a change unless there was a really compelling reason to do so.

If your intent is for the instance variable `fruit` to be a literal type, it should be annotated as such, as you've suggested in your workaround.

**Comment by GBeauregard** [comment]
Thanks for the explanation as always.

Although I'm not completely convinced the behavior is best in this particular case, I can appreciate the difficulties if it has complex interactions with other parts of the codebase. Your explanation also fills in some gaps in my understanding of your instance variable type inference that wasn't always clear to me.

It's not always clear to me what's best as an issue or discussion so I hope I'm not too much of a bother.

Thanks again.
