### ISSUE TITLE
pyright --watch exits rather than watching

### ISSUE THREAD

**Issue by lpil** [microsoft/pyright#2469]
**Describe the bug**

When I run `npx pyright --watch` or `./node_modules/.bin/pyright --watch` it type checks the codebase once, finds no errors, prints "Watching for file changes..." and then exits successfully.

**To Reproduce**

1. Install pyright 1.1.180 on OSX 11.5.1 on ARM
2. Run `pyright --watch`

**Expected behavior**
I expected the program to wait for changes and then run again.

**Screenshots or Code**

<img width="689" alt="image" src="https://user-images.githubusercontent.com/6134406/138234812-c3ccd9fa-67fb-4d27-bb4d-30d72a1f6721.png">

**VS Code extension or command-line**

CLI pyright 1.1.180 on OSX 11.5.1 on ARM

**Additional context**

Thank you for this amazing project 💜 
Please let me know anything I can do to help, such as enabling and sharing further logging

**Comment by jakebailey** [comment]
I believe the issue is actually caused by a refactor to the file watching code while we were working on getting Pylance into the browser; it looks like the CLI is now getting a no-op file watcher implementation (so, node is happy to exit early as there's no reason to stay alive). I must have missed it in review.

I'm working on a partial revert so the CLI can be restored to the way it used to work. (Though, I'm working on file watching stuff in general, so the code may get changed at some point anyway.)
