### ISSUE TITLE
matplotlib: "colors" is not a known member of module (reportGeneralTypeIssues)

### ISSUE THREAD

**Issue by nschloe** [microsoft/pyright#2516]
(Transferred from https://github.com/matplotlib/matplotlib/issues/21505.)

When running
```sh
pyright --lib dummy.py
```
on
```python
import matplotlib as mpl

mpl.colors
mpl.cm
```
one gets
```sh
  /tmp/dummy.py:3:5 - error: "colors" is not a known member of module (reportGeneralTypeIssues)
  /tmp/dummy.py:4:5 - error: "cm" is not a known member of module (reportGeneralTypeIssues)
```

This is with `pyright 1.1.183` and `matplotlib 3.4.3`.

**Comment by erictraut** [comment]
The `--lib` option is not generally recommended for use with type checking. It was added primarily for use by language servers to provide completion suggestions in cases where type stubs or inlined type annotations are not present. For type checking, you need accurate and complete type information for a library.

I recommend reaching out to the authors of matplotlib to see if they would consider adding inlined type annotations. Increasingly, library authors are doing so. Here is some [guidance](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md) that we've written for library authors.

Pylance (the VS Code language server built on pyright) ships with some basic (still incomplete) type stubs for matplotlib. You could try installing those to see if this addresses your problem. You can find those [here](https://github.com/microsoft/python-type-stubs/tree/main/matplotlib).

Looking at this specific issue in the matplotlib source code, I don't see any place where `matplotlib/__init__.py` directly imports the `color` submodule, so I'm not sure how `color` would end up in the namespace of the primary module, and it would appear that the error provided by pyright is correct in this case. You can reference the `colors` submodule by explicitly referring to the submodule: `import matplotlib.colors` or `from matplotlib import colors`.

**Comment by nschloe** [comment]
Ping @anntzer.

**Comment by anntzer** [comment]
`matplotlib/__init__.py` import `matplotlib.rcsetup`, which imports `matplotlib.colors`.

**Comment by erictraut** [comment]
Yeah, so it's relying on a cross-module import side effect. Pyright does not model such side effects because they're often not intended and in general cannot be modeled statically since they rely on runtime execution order.

This is one of _many_ reasons why it's important for library authors to provide type explicit type information in their libraries.

**Comment by anntzer** [comment]
I'm not really sure if there's anything actionable here?  If you don't want to use `mpl.colors` without explicitly importing it because that upsets pyright, no one is preventing you from explicitly importing it.

The current PoV of Matplotlib devs wrt type hints (https://github.com/matplotlib/matplotlib/issues/20504#issuecomment-867930809) is that we're open to third-parties implementing type hints, but we're not going to do this ourselves.  Moreover, my very uneducated guess this specific import could in fact be modelled statically (the list of relevant imports is statically available at the top of the module sources).

**Comment by JakubSzukala** [comment]
Hi, @erictraut mentioned that this set of stubs can be installed and I would like to ask, how can I do that? 

I managed to install stubs from that exact repo but for cv2 with use of a command provided here https://github.com/microsoft/python-type-stubs/pull/72#issuecomment-873001476 but I am not sure how to reproduce that for installing matplotlib stubs. 

From my understanding of this command, it should be enough to copy stub *.pyi files to the module folder, next to module's *.py files. But after trying that it does not seem to work.
