### ISSUE TITLE
Question / Documentation incomplete: executionEnvironments

### ISSUE THREAD

**Issue by ikamensh** [microsoft/pyright#2518]
The page https://github.com/microsoft/pyright/blob/main/docs/configuration.md mentions `executionEnvironments` and gives examples for such in the sample configs, but gives no definition of what it is. It says "see below" but searching for `executionEnvironments` doesn't help. Did I miss some paragraph or it's indeed not described?

I understood it like "other settings under which types should also check out", like if I'm building library for multiple platforms and python versions. Is this correct?

**Comment by erictraut** [comment]
Check out [this section](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#execution-environment-options) of the documentation. Does that help?

Execution environments can be useful for mono-repos that contain multiple Python programs which use different Python versions.

If you are building a library for multiple platforms and python versions and want to validate your library for all combinations, execution environments will not address your needs because each file within your code base is mapped to only one execution environment. 

To validate your library for all combinations of supported python versions and platforms, you would need to run pyright multiple times (e.g. from a CI script). Pyright allows you to pass a "--pythonversion" and "--pythonplatform" [command-line argument](https://github.com/microsoft/pyright/blob/main/docs/command-line.md). 

If you would like to see an example of this, check out the [typeshed repo](https://github.com/python/typeshed). It uses a github action to iterate through a matrix of platforms and versions. Search for "pyright" within [this yaml file](https://github.com/python/typeshed/blob/master/.github/workflows/tests.yml) for details.

**Comment by ikamensh** [comment]
Thanks for the detailed explanation! I might add that your explanation here is even more clear to me than in the docs. But docs make sense too, just more generic/formal language ("portions of your source tree" vs multiple Python programs in a mono-repo). I've created a PR to have hyperlink in the documentation for people who like me might be aided in searching right section :)
