### ISSUE TITLE
Incorrect handling of client-initiatied progress

### ISSUE THREAD

**Issue by rchl** [microsoft/pyright#2545]
**Describe the bug**
I believe that in this code:

https://github.com/microsoft/pyright/blob/b12f1347b2b3fbfdb1da68583e35226817f7de7b/packages/pyright-internal/src/languageServerBase.ts#L462-L467

the `params.workDoneToken` will always be `undefined` since the LSP library will remove the property in

https://github.com/microsoft/vscode-languageserver-node/blob/859a8ece3e14b130d531c6102b2d108196436bc4/server/src/common/progress.ts#L139-L147

called from:

https://github.com/microsoft/vscode-languageserver-node/blob/859a8ece3e14b130d531c6102b2d108196436bc4/server/src/common/server.ts#L1696-L1698

and pass it through the `workDoneReporter` argument in the pyright handler function.

So the server is never using the client-initiated progress token but always creating server-initiated one.

**Comment by erictraut** [comment]
Thanks for the bug report. Yeah, we never noticed this issue before because VS Code never provides a client-initiated progress handler in this case. The behavior of the LSP library is unfortunate because it makes it difficult for the server to differentiate between a client-initiated progress handler and a dummy (null) handler. 

Here's a PR that attempts to work around this: https://github.com/microsoft/pyright/pull/2546

**Comment by erictraut** [comment]
This is fixed in pyright 1.1.186, which I just published.
