### ISSUE TITLE
Type inference failure when decorating with a `@classmethod` of a `Generic` class

### ISSUE THREAD

**Issue by Tomaz-Vieira** [microsoft/pyright#2552]
**Describe the bug**
When a `@classmethod` shares generic parameters with its class and that `@classmethod` is used to decorate a function, type inference seems to break.

**To Reproduce**
```python3
# pyright: strict

from typing import Callable, Generic, TypeVar
from typing_extensions import ParamSpec

OUT = TypeVar("OUT")
P = ParamSpec("P")

class SimpleWrapper(Generic[P, OUT]):
    @classmethod
    def decorate(cls, method: Callable[P, OUT]) -> Callable[P, OUT]:
        return method

@SimpleWrapper.decorate
def foo(a: int) -> str:
    return "asd"

a: str = foo(123)  # error: Expression of type "OUT@SimpleWrapper" cannot be assigned to declared type "str
```

Incidentally, if `SimpleWrapper` isn't generic (i.e. if only the `decorate` function is made generic), then the inference works just fine.

**Expected behavior**
`foo` to be inferred as (a: int) -> str

**VS Code extension or command-line**
pyright extension version 1.1.186

**Comment by erictraut** [comment]
This behavior is correct, but I can see why you would be confused by the error message.

The problem is that you have defined `SimpleWrapper` as a generic class parameterized by `P` and `OUT`, but you haven't provided a constructor that provides a way to assign types to these class-scoped type variables. The result is that `SimpleWrapper` isn't specialized when you call the class method.

It looks like your intent is to provide method-level type variables for the method `decorate`. You can do this by simply deleting `Generic[P, OUT]` from the `SimpleWrapper` class declaration.

```python
class SimpleWrapper:
    @classmethod
    def decorate(cls, method: Callable[P, OUT]) -> Callable[P, OUT]:
        return method
```
