### ISSUE TITLE
Pyright is changing the type of `type[Any]` to `Any`

### ISSUE THREAD

**Issue by StockerMC** [microsoft/pyright#2566]
**Expected behavior**
The type of the parameter, variable, etc. in the following examples should be kept as `Type[Any]`.

**Screenshots or Code**
```python
from typing import Any

# note that having the type as "type" instead of "type[Any]" produces the correct results for all of the examples

CONVERTER_MAPPING: dict[type[Any], Any] = {}
reveal_type(CONVERTER_MAPPING)
# pyright: dict[Any, Any]
# mypy: dict[Type[Any], Any]

CONVERTER_MAPPING[int]
# pyright: no error
# mypy: Invalid index type "int" for "Dict[Type[Any], Any]"; expected type "Type[Any]"

foo: list[type[Any]] = []
reveal_type(foo)
# pyright: list[Any]
# mypy: list[Type[Any]]

def bar(a: type[Any]):
    reveal_type(a)
    # pyright: Any
    # mypy: Type[Any]

bar('')
# pyright: no error
# mypy: Argument 1 to "bar" has incompatible type "str"; expected "Type[Any]"
```

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool?
Command line (pyright 1.1.187)

**Comment by erictraut** [comment]
Pyright tracks types as either "class instances" or "instantiable classes". `Any` is considered both of these, since all type information is effectively discarded with `Any`. So the current behavior is intended.

I recommend not using `Type[Any]` or `type[Any]`. If your intent is "this is a subclass of the `type` class`, then use `type` as the type annotation.

**Comment by StockerMC** [comment]
Alright, thank you.
