### ISSUE TITLE
How to merge the result of pyright's type inference with the source code file?

### ISSUE THREAD

**Issue by QingYiSun** [microsoft/pyright#2605]
Hello,

I'm using pyright to get the type information of python code(in a "watch" mode).

However, I want pyright to be able to **merge the inferred type annotations with the source file** to get a new file with types.

Is such an operation feasible? Do you have any solutions to the above problem?

Thanks!

**Comment by erictraut** [comment]
No, pyright doesn't have any such mode.

I presume that you're primarily interested in function return type annotations? Pyright doesn't generally do any inference for input parameter types, and annotation of variables is probably not desirable except in specific cases where an annotation is required.

Automatically inserting return type annotations with no user intervention would be highly error prone. We've talked about potentially adding some interactive functionality like a code action that allows you to insert (and then review) missing type annotations for a function. This could include both return types and input parameter types. If we do this, it will be implemented in Pylance rather than Pyright. If that's something you're interested in, I recommend filing a feature request in the [https://github.com/microsoft/pylance-release] issue tracker.
