### ISSUE TITLE
Match generic type matching not fully fixed

### ISSUE THREAD

**Issue by DeviousStoat** [microsoft/pyright#2633]
**Describe the bug**
I posted an issue here: https://github.com/microsoft/pyright/issues/2628 this seems to be fixed however I found another similar case. I am really not sure what's happening there so code would explain better

**To Reproduce**
```python
from typing import TypeVar

T = TypeVar("T")

def plop(t: T) -> str:
    match (t, True):
        case (str(), True):
            return t.lower()  # error: Cannot access member "lower" for type "object*"
        case _:
            return "hello"
```

**Expected behavior**
`t` should be narrowed to a `str` at this point.

**VS Code extension or command-line**
I am using the latest commit from master, with the recent match fix, running it from cli with `cd pyright/packages/pyright && npm run build && node index.js`

**Comment by erictraut** [comment]
This is a different case, and the behavior you're seeing is expected.

Pyright performs type narrowing only on certain types of expressions: name expressions (simple identifiers), member access expressions, and index expressions where the index is a literal integer. The target expression in this case is `(t, True)`. This is a tuple expression, so type narrowing doesn't apply to the expression.

If you want type narrowing to apply to the target expression in your match statements, you'll need to stick to the supported expression forms. For example, the following works fine:

```python
def plop(t: T) -> str:
    match t:
        case str():
            return t.lower()
        case _:
            return "hello"
```

We're unlikely to expand the list of narrowable expression forms because doing so would add significant runtime/analysis costs. Slowing down analysis for everyone just to support this unusual form wouldn't be a good tradeoff.

**Comment by DeviousStoat** [comment]
Oh okay, thanks a lot for your explanation
