### ISSUE TITLE
Should report unreachable code on `if Final[Literal[False]]`

### ISSUE THREAD

**Issue by FaresAhmedb** [microsoft/pyright#2676]
**Describe the bug**
Type hinting a variable with `Final[Literal[False]]` should report unreachable code when using `if X`

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/73843130/145111708-64a20259-9c4e-4155-b08b-dae0751516f7.png)

**Comment by erictraut** [comment]
Yes, this is by design.

Pyright doesn't currently report unreachable code based on type analysis. It does so only based on code flow constructs and specific static expression patterns required by PEP 484. 

You may find this conversation of interest: https://github.com/microsoft/pyright/issues/2672#issuecomment-988268143

**Comment by FaresAhmedb** [comment]
Thank you for the detailed comment. Interesting information!

I'll close this issue (as I think it's a duplicate then).
