### ISSUE TITLE
Function-level import can hide top-level import

### ISSUE THREAD

**Issue by matejcik** [microsoft/pyright#2685]
**Describe the bug**
When importing module `x.y` at top level, and then importing `x.z` in a function, pyright will complain about any usages of `x.y.something()` in the function.

As a workaround, I can:
* `import x.y` again in the function
* just `import x` in the function

**To Reproduce**
`foo/foo.py`:
```python
hello = "hello"
```
`foo/bar.py`:
```python
hello = "hello"
```
`testfile.py`:
```python
import foo.foo

def fn():
    import foo.bar

    print(foo.foo.hello)  # error: "foo" is not a known member of module
```

**VS Code extension or command-line**
pyright 1.1.194

**Comment by erictraut** [comment]
Yeah, this is a known limitation of the way that pyright handles imports. It intentionally does not model temporal side effects of import statements. This is part of the design (a "feature", not a "bug") because temporal side effects lead to code fragility, and the resulting bugs are difficult to debug.

If you import `foo.foo` and `foo.bar` at the module level, pyright will add both `foo` and `bar` to the effective symbol table for `foo`. In other words, it combines the two. In your example, you're importing `foo.bar` in a different execution context (within `fn`), so it's unsafe to combine them. Doing so would mask errors in the following code:

```python
import foo.foo

def fn():
    import foo.bar

print(foo.bar) # Runtime error!
```

In your particular sample, we can see that it is safe because `foo.bar` isn't used outside of `fn`, but it's difficult for a tool like pyright to make that determination.

While the code in your sample is legal Python, it's pretty atypical. If you want it to work with type checking (specifically, with pyright), you'll need to employ one of several workarounds:

1. Move the import of `foo.bar` to the module level.
2. Use an alias for one of the two import statements, such as `import foo.bar as bar`

**Comment by matejcik** [comment]
I understand the "temporal side effects" angle, but it seems to me that my example is not fundamentally different from:
```
import foo

def fn():
    import bar

    print(foo.hello)
```
which typechecks, as it should.

I.e., the function context should not _modify_ the module context, but should _include_ it.

The issue seems to be a bug in the mechanism which ensures that the above typechecks (or a limitation thereof), but it does not seem to be "as designed".

**Comment by matejcik** [comment]
fwiw, the best workaround for my case is to repeat `import foo.foo` on the function level -- that should be virtually costless at runtime and does not otherwise change the code

**Comment by erictraut** [comment]
Yes, that's a fine workaround as well.
