### ISSUE TITLE
isinstance doesn't constrain union type

### ISSUE THREAD

**Issue by fbergroth** [microsoft/pyright#2713]
**Describe the bug**
The code below produces an the error on the last line:
```
test.py:17:14 - error: Cannot access member "index" for type "M"
    Member "index" is unknown (reportGeneralTypeIssues)
```
But at that point, the type of `a` should be `pd.DataFrame`.

Not sure if this is specific to pandas, since changing `M, pd.DataFrame` to `int, str` seems to work.

**To Reproduce**
VVV

**Expected behavior**
No errors.

**Screenshots or Code**
```
from typing import Union, List, Any
from dataclasses import dataclass
import pandas as pd


@dataclass
class M:
    data: List[List[float]]

    def as_df(self) -> pd.DataFrame:
        return pd.DataFrame(self.data)


def f(a: Union[M, pd.DataFrame]) -> Any:
    if isinstance(a, M):
        a = a.as_df()
    return a.index
```

**VS Code extension or command-line**
pyright 1.1.196

**Comment by erictraut** [comment]
I'm not able to repro the problem. 

It's likely that the problem is explained by the fact that the `pd.DataFrame` type is unknown or derives from an unknown class. In such cases, pyright can't safely eliminate it from the union based on an `isinstance` check.

Which version of pandas do you have installed? Do you have any pandas stubs installed?

**Comment by fbergroth** [comment]
Thanks for looking into it! I had `pandas==1.3.3` installed but was missing the stubs. The error went away when installing the stubs.
