### ISSUE TITLE
TypeVar('T', bound=Foo) does not behave like Self

### ISSUE THREAD

**Issue by MathiasSven** [microsoft/pyright#2732]
**Describe the bug**
According to PEP 673, using `T = TypeVar('T', bound=Foo)` to represent `Self` should be equivalent to `Self` however the snipped of code bellow does not show that to be case, with the new type `Self` fixing an issue that TypeVar has.

**To Reproduce**
```python
from typing import Generic, TypeVar, Any, Optional, Protocol, Callable
from typing_extensions import Self
from abc import ABC

T = TypeVar("T")
K = TypeVar("K")

class ClassProperty(Protocol[T, K]):
    def __init__(self, getter: Callable[[T], K]) -> None: ...
    def __get__(self, obj: None, type: type[T] | None = ...) -> K: ...

def classproperty(f: Callable[[T], K]) -> ClassProperty[T, K]: ...

class ItemSet(Generic[T]): ...

T_b = TypeVar('T_b', bound='BaseItem')

class BaseItem(ABC):
    @classproperty
    def set(cls: T_b) -> ItemSet[T_b]: ...

class BaseItemSelf(ABC):
    @classproperty
    def set(cls) -> ItemSet[Self]: ...

class FooItem(BaseItem):
    name: str

class FooItemSelf(BaseItemSelf):
    name: str

reveal_type(FooItem.set)
reveal_type(FooItemSelf.set)
```

**Expected behavior**
Using `TypeVar` does not lead to the correct type while using `Self` does: `ItemSet[FooItemSelf]`
```python
33:21 - error: Cannot access member "set" for type "Type[FooItem]" (reportGeneralTypeIssues)
33:13 - info: Type of "FooItem.set" is "Unknown"
34:13 - info: Type of "FooItemSelf.set" is "ItemSet[FooItemSelf]"
```

**VS Code extension or command-line**
Command-line `pyright 1.1.197`

**Comment by erictraut** [comment]
The problem is that the `@classproperty` decorator is evaluated within the class scope at class declaration time. The `set` method has a function-scoped TypeVar called `T_b@set`. The decorator returns a value of type `ClassProperty[T_b@set, None]`. There's no way to solve for `T_b@set` at this point because it's no longer in scope. This means that the application of the descriptor fails as part of the `FooItem.set` evaluation, and you receive a `Cannot access member...` error message.

So I think this is working correctly, although the error messages might be a bit opaque. Mypy also generates a similar error in this case.

This works with the `Self` example because you're not introducing a function-scoped TypeVar in the `set` method.

Do you need to create your own `ClassProperty`, or will the normal `property` work for you? If so, I recommend switching to the following because pyright has a bunch of special-case logic to handle `property`.
```python
class BaseItem(ABC):
    @property
    @classmethod
    def set(cls: type[T_b]) -> ItemSet[T_b]:
        ...
```

**Comment by MathiasSven** [comment]
Understood, sorry for the issue. I am making stubs for a an external libraries, their implementation will remains the same which involves making a custom descriptor so it is backwards compatible to versions prior to 3.9 which didn't allow this sort of chaining of descriptors. However since it is a stub It should do just fine! Thanks.
