### ISSUE TITLE
Untyped Class Decorator while reveal type disagrees

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [microsoft/pyright#2773]
**Describe the bug**
For the code below it says the decorator is untyped, but it has a full signature that type checks and reveal type shows me expected type for the decorator.

**To Reproduce**
Run pyright on code below. The error message is,

Untyped class decorator obscures type of class; ignoring decorator

**Expected behavior**
No errors.

**Screenshots or Code**
```python
from __future__ import annotations

from typing import Callable, Optional, Tuple, Type, TypeVar

T = TypeVar('T')
Constructor = Callable[..., T]


def configurable(
    constructor: Optional[Constructor[T]] = None,
) -> Callable[[Type[T]], Type[T]]:
    ...

def custom_constructor(x: int, y: int) -> Point:
    return Point((x, y))

reveal_type(configurable(constructor=custom_constructor)) # Callable[[Type[Point]], Type[Point]]

@configurable(constructor=custom_constructor) # error produced
class Point:
    def __init__(self, coordinate_2d: Tuple[int, int]) -> None:
        ...


```

**VS Code extension or command-line**
pyright cli using 1.0.201. current pylance shows the same error too.

**Comment by erictraut** [comment]
This is because you have a circular reference in your code. The function `custom_constructor` uses the forward-declared type `Point` in its signature, but the function `custom_constructor` is used in the decorator call that decorates the `Point` class.

The error message here is opaque and confusing. I previously included an explicit error for circular references like this, but it produced false positives in some cases where circular references didn't otherwise cause any problems. I'll look at whether there's a way that this condition can be detected and reported in a clearer way.

In any event, this circular reference is a bug in your code that you'll need to address if you want it to type check correctly.

**Comment by hmc-cs-mdrissi** [comment]
The code works fine at run time and I'm unsure how to break this kind of circular reference. The constructor argument is intended to define how to create that class from a config file. A longer version of this example that actually does something useful is this,

```
from __future__ import annotations

import json
from typing import Any, Callable, Tuple, Type, TypeVar

from typing_extensions import Annotated

T = TypeVar('T')
Constructor = Callable[..., T]

PARSER_REGISTRY: dict[type, Callable[..., Any]] = {}

def parse_config(config: str, ty: Type[T]) -> T:
    config_dict = json.loads(config)
    parser = PARSER_REGISTRY[ty]
    return parser(**config_dict)


def configurable(
    constructor: Constructor[T],
) -> Callable[[Type[T]], Type[T]]:
    def decorator(cls: Type[T]) -> Type[T]:
        PARSER_REGISTRY[cls] = constructor
        return cls
    return decorator
    

def custom_constructor(x: int, y: int) -> Point:
    return Point((x, y))

@configurable(constructor=custom_constructor)
class Point:
    x: Annotated[int, 'x coordinate']
    y: Annotated[int, 'y coordinate']

    def __init__(self, coordinate_2d: Tuple[int, int]) -> None:
        self._x = coordinate_2d[0]
        self._y = coordinate_2d[1]

    def __repr__(self) -> str:
        return f'Point({self._x}, {self._y})'

point_config = '{"x": 1, "y": 2}'
point = parse_config(point_config, Point)
print(point)
```

**Comment by erictraut** [comment]
It works fine at runtime because you're using deferred type annotation evaluation, so the circular dependency isn't an issue. A static type checker cannot defer type annotation evaluation when it is needed for a dependent type evaluation.

You'll need to find some other way to do this if you want this to work with static type checking.

**Comment by erictraut** [comment]
Here's a potential workaround that breaks the cycle:

```python
def custom_constructor(x: int, y: int) -> _Point:
    return Point((x, y))

class _Point:
    def __init__(self, coordinate_2d: Tuple[int, int]) -> None:
        ...

Point = configurable(constructor=custom_constructor)(_Point)
```

**Comment by hmc-cs-mdrissi** [comment]
Hmm, playing with it another workaround,

```python
def configurable(
    constructor: Constructor[Any],
) -> Callable[[Type[T]], Type[T]]:
  ...

```

works well enough. The constructor relationship to the decorated type isn't included in that type but unsure that's doable. Ideally,

```python
def custom_constructor(...) -> Foo2:
  ...

@configurable(constructor=custom_constructor)
class Foo1:
   ...
```

would be a type error of Foo2 not matching Foo1, but losing that feels reasonable given the cycle. Your workaround does cover that with readability awkwardness. I think I can add a run time type check to cover it at the time decorator executes which feels close enough. The underlying config code already does does a good amount of runtime type introspection for other things.

I'm fine with this issue being closed or scope being limited to clearer error message.
