### ISSUE TITLE
numpy.where loses ndarray dtype information

### ISSUE THREAD

**Issue by NeilGirdhar** [microsoft/pyright#2811]
```python
from typing import Any

import numpy as np
import numpy.typing as npt

RealArray = npt.NDArray[np.floating[Any]]

all_ys: RealArray = np.zeros(10)
reveal_type(all_ys)  # "ndarray[Any, dtype[floating[_64Bit]]]"
all_ys = all_ys + all_ys
reveal_type(all_ys)  # "ndarray[Any, dtype[floating[Any]]]"
all_ys = np.where(True, all_ys, all_ys)
reveal_type(all_ys)  # "ndarray[Any, dtype[Any]]"
```
MyPy says `numpy.ndarray[Any, numpy.dtype[numpy.floating[Any]]]` for all three types.

**Comment by erictraut** [comment]
I think pyright is doing the right thing here given the type information in the latest numpy package.

Here's the overload for `np.where`:
```python
@overload
def where(
    condition: ArrayLike,
    /,
) -> Tuple[NDArray[intp], ...]: ...
@overload
def where(
    condition: ArrayLike,
    x: ArrayLike,
    y: ArrayLike,
    /,
) -> NDArray[Any]: ...
```

Clearly the call expression `np.where(True, all_ys, all_ys)` maps to the second of the two overloads, so the resulting type should be `NDArray[Any]`. Since `NDArray` is a generic type alias that is defined as `ndarray[Any, dtype[ScalarType]]`, `NDArray[Any]` is equivalent to `ndarray[Any, dtype[Any]]`.

If you think this is incorrect, please file a bug with the numpy package maintainers.

**Comment by NeilGirdhar** [comment]
I had a feeling this was probably numpy's bug.  I was curious why `__add__` was preserving the floating point type and why MyPy gets it "right".  Maybe they have a plugin?
