### ISSUE TITLE
OrderedDict unions incorrectly typed as dicts

### ISSUE THREAD

**Issue by tomc-goodrx** [microsoft/pyright#2819]
**Describe the bug**
Since 3.9 dicts support the union operations `x | y` and `x |= y` which applies the values of the latter dict's key to the former dict. This also works with OrderedDicts.

When using union on `OrderedDict`s the resulting type is incorrectly identified as a `dict` not an `OrderedDict` with the following message:

```
Expression of type "dict[str, str]" cannot be assigned to declared type "OrderedDict[str, str]"
  "dict[str, str]" is incompatible with "OrderedDict[str, str]"PylancereportGeneralTypeIssues
  ```

**To Reproduce**
Simple test script below illustrates the issue with Pylance enabled.

**Expected behavior**
It should not be a type error.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/78818968/148317453-7a22d123-41c6-4949-a265-a2f7359dc707.png)

```python
from collections import OrderedDict

x: OrderedDict[str, str] = OrderedDict({})
y: OrderedDict[str, str] = OrderedDict({})

x['a'] = 'a val'
x['b'] = 'b val'
y['a'] = 'another a val'

print(x)  # OrderedDict([('a', 'a val'), ('b', 'b val')])
print(y)  # OrderedDict([('a', 'another a val')])
print(type(x))  # <class 'collections.OrderedDict'>
print(type(y))  # <class 'collections.OrderedDict'>

print(x | y)  # OrderedDict([('a', 'another a val'), ('b', 'b val')])
print(type(x | y))  # <class 'collections.OrderedDict'>

x |= y
print(x)  # OrderedDict([('a', 'another a val'), ('b', 'b val')])
print(type(x))  # <class 'collections.OrderedDict'>
```

**VS Code extension or command-line**
This is just basic VS.Code Python extension using Pylance as the lang server.

**Additional context**

**Comment by NeilGirdhar** [comment]
Not related to the issue, but is there any reason to use `OrderedDict` anymore?  Python 3.6 is end-of-life, and Python 3.7 dicts are ordered.

**Comment by erictraut** [comment]
This is a bug in the typeshed type stub `builtins.pyi`. It declares the `dict` type as follows:

```python
class dict(MutableMapping[_KT, _VT], Generic[_KT, _VT]):
    ...
    def __or__(self, __value: Mapping[_T1, _T2]) -> dict[_KT | _T1, _VT | _T2]: ...
    def __ror__(self, __value: Mapping[_T1, _T2]) -> dict[_KT | _T1, _VT | _T2]: ...
    def __ior__(self, __value: Mapping[_KT, _VT]) -> dict[_KT, _VT]: ...  # type: ignore[misc]
```

Since `OrderedDict` derives from `dict`, it inherits these methods. But these methods return a `dict` rather than a `Self` type.

There are a couple of ways this could be fixed. One is to annotate the `self` parameter with a TypeVar. The other is to define custom versions of these three methods in the `OrderedDict` class (which is declared in `collections/__init__.pyi`).

In any case, this isn't a bug in pyright. I recommend filing a bug (or better yet, a PR) in the typeshed github repo. Pyright regularly picks up new typeshed stubs, so if/when it's fixed there, pyright will include the fix in a subsequent release.
