### ISSUE TITLE
Incorrectly identified unaccessed variable

### ISSUE THREAD

**Issue by ItsDrike** [microsoft/pyright#2822]
**Describe the bug**
When using `__`-prefixed variables when `self` wasn't taken from a method within the class, but instead from a decorator with inner function taking self present in another class, pyright is reporting that `__x` isn't accessed, even though it is, right on the line below.

**To Reproduce**
Use the code in the code section.

**Expected behavior**
This unused name hint shouldn't be present. 
Possibly, this should produce an error of: `Cannot assign member '_Foo__x' for type Bar. Member '_Foo_x' is unknown`, which is what would happen with normal variables, such as if this was setting `self.x`, or even `self._x`.

**Screenshots or Code**
![Screenshot_2022-01-06_18-50-27](https://user-images.githubusercontent.com/20902250/148427730-e1e0d294-2127-4db9-8836-797d9847dec4.png)

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release.

**Comment by ItsDrike** [comment]
Out of curiosity, why did this happen? And how will it be fixed? Will it just stop reporting unused variable hints or will it actually start producing errors that `__x` is unknown?

**Comment by erictraut** [comment]
When pyright determines whether the first parameter of a function is a "self" or "cls", it checks to see whether that function is declared within a class. The bug was that it was not checking to see if it was an inner (local) function declared within a method. So it incorrectly assumed that `inner` was an instance method associated with the `Foo` class. It then assumed that `__x` was an instance variable and entered it into the class's symbol table. This confused the logic that determines whether an instance variable is accessed.

The fix is to correctly identify `inner` as a regular function rather than a method.

The result of the fix is that `__x` will no longer be displayed as "unaccessed" (i.e. no hint will be generated for it).

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.205, which I just published. It will also be included in the next release of pylance.
