### ISSUE TITLE
unresolved import in script for a local file/module in the same directory

### ISSUE THREAD

**Issue by SatyaKomatineni** [microsoft/pyright#283]
**Describe the bug**
*************************************
On windows 10
\somedir

\somedir\myscript.py
\somedir\mod1.py
\somedir\mod2.py

in myscript.py I have

import mod1

This line is highlighted as "unresolved import". The "output" console for pyright is searching everywhere but not in the local directory of the script "\somedir"

At run time python is ok because the 'sys.path' will have the myscript.py local directory.

Does "pyright" not search the path of the script file based on its location? is there a setting in pyright to locate that module?

**To Reproduce**
*************************
Hope the above is clear, if not I will try to upload these files.

**Expected behavior**
*************************
1. pyright could search the same directory where the "script" is located.
2. the module is located in that script directory

**Screenshots or Code**
********************************
import mod1

**VS Code extension or command-line**
***********************************************
VS Code extension
1.0.69

**Additional context**
******************************
This seem like a simple case. Not sure what I am missing.

**Comment by erictraut** [comment]
Please check out issue #272. It explains the behavior you're seeing and provides a couple of options to eliminate the error.

**Comment by SatyaKomatineni** [comment]
Thank you very much. I will read through it.

**Comment by SatyaKomatineni** [comment]
I have read through #272. I am wondering why not follow what python.exe does to resolve that local module import (without being a package) where the "current working directory" of the script file (myscript.py) is looked into as well to locate the "mod1.py"?

python does resolve it when I run.

Just curious.

I will see if I can use relative imports by making it a package.

thanks again for your incredible efforts with pyright and help on this forum

Satya

**Comment by erictraut** [comment]
Pyright doesn't know which files are "scripts" and which are source files that will be imported by other files. It doesn't have that context. This is a case where python's dynamic nature makes it difficult for a static type checker.

Pyright assumes that sys.path will contain the root of your source tree. So if you're script and the files it imports are located in the root directory, it will work as you expect. If you have files that you plan to execute as scripts deeper in the source tree, you need to provide those paths. That's why pyright supports multiple "executionEnvironments" within its config file.

**Comment by SatyaKomatineni** [comment]
Point taken. Pyright do not know if it is a script (as I am not executing at that time). 

Now,
My scripts and what they import are in the same path. 

However that root is not in sys.path. (it is ok for python because it adds that path to the sys.path at run time)

I will look into execution environments to see. Thanks again.

**Comment by SatyaKomatineni** [comment]
After setting the executionEnvironment in the root "pyrightconfig.json" I see the module statement go from "red" to "orange". 

I am able to see the intellisense work. However there is an orange highlight. Also one line says it is a "module" with the right path and another line says "unresolved import" ...python.

Is this expected? 

Are the settings in "pyrightconfig.json" only stay in that file or can they be specified in vscode settings files as well?

when one says "root" directory where the "pyrightconfig.json" resides, does the root mean the "folder" that is explicitly added to the vscode workspace? I am assuming any subfolders cannot contain another pyright.conf.

**Comment by erictraut** [comment]
It sounds like you're running both pyright and the python extension. Pyright's errors and hover text will have "pyright" next to them, and the python extension will show "python". I realize this can be confusing. I'm working with the python extension authors to add the ability to disable the type analysis features in their extension to avoid duplicates. I've submitted a PR but it hasn't yet made it into the extension.

Pyright supports a few settings within VS Code settings, but most of its configuration is done through the pyrightconfig.json file, which is meant to be checked in to your repo and shared among all contributors. VS Code settings tend to be specific to each user (local paths, etc.). This is consistent with other languages like typescript. For details of the supported VS Code settings, see [this documentation](https://github.com/microsoft/pyright/blob/master/docs/settings.md).

**Comment by SatyaKomatineni** [comment]
Ok thank you.

Should I not run both python and pyright extensions? is pyright sufficient?

**Comment by erictraut** [comment]
The python extension provides a lot of good functionality beyond type checking, including debugging, test management, and linting. The problem is that it also provides limited language support (reporting parse errors, limited type checking, hover, type completion), but it doesn't do any of those nearly as well as pyright. So there's some overlap. Thankfully, the python extension is built in a modular way. The part of it that overlaps with pyright is handled through a plugin called the [Python Language Server (PLS)](https://github.com/microsoft/python-language-server). The problem is that there's currently no way to disable the PLS, so it overlaps in functionality with pyright. 

So the short answer is that yes, I recommend running both the python extension and pyright together, but until the python extension provides a way to disable the PLS, you're going to unfortunately see some duplicate errors, hover messages, and text completions. I'm hoping that the necessary change will be released soon.

**Comment by SatyaKomatineni** [comment]
Thank you so very much. This is very comprehensive. I have a much better understanding.
