### ISSUE TITLE
Add equivalent option to report unused type: ignore comments

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#2839]
This was asked for in [#450 ](https://github.com/microsoft/pyright/issues/450)

**Is your feature request related to a problem? Please describe.**
When developing type stubs for pandas, we'd like to know when a `# type: ignore` statement is no longer needed.   When we run `mypy` on our code base, we use the  `--warn-unused-ignores` flag to tell us if we have fixed a typing problem.  In the pandas code base, we have many `#type: ignore` lines and the goal is to get rid of them by fixing the typing in various places in the code.  When you fix a typing issue, then you get the warnings from mypy that means you can remove the `#type: ignore` comment.

Secondly, this can also be useful for testing typing stubs.  Let's say that you have created type stubs for a function that requires a `bool` parameter, e.g. `f(parm: bool)`.  You write a test code that you run through the type checker that has that `bool` parameter in a function call  (e.g., `f(True)`).  You also write a test for the type checker that makes sure that `f("a")` is picked up as a failure, but to do that you put in a `#type: ignore[arg-type]` on that line.  Then a year later, you change the API for function `f` to be `f(parm: Literal["a", "b", "c"])` .  But you forget to fix the two tests.  In this case the call `f(True)` will get picked up by the type checker, but `f("a")` will not, because of the `#type: ignore` comment.  But if you had the option like in `mypy` to find the unused `type: ignore` comments, that would make sure that your testing code was properly fixed.

**Describe the solution you'd like**
Add an equivalent to mypy `--warn-unused-ignores`

**Comment by erictraut** [comment]
I'm still reluctant to add this feature because, as I said in the other thread, I think that `# type: ignore` is a blunt instrument that should be used rarely if ever. I even added a `enableTypeIgnoreComments` to disable the use of `# type: ignore`, and I use that for all of my team's Python code.

If your code base is type checked by multiple type checkers (e.g. pyright and mypy), then `# type: ignore` are going to be even more problematic, as is the equivalent of `--warn-unused-ignores` because errors may be reported differently between type checkers — or reported on different lines.

I realize that some disagree with me and think that it's acceptable to use `# type: ignore` in their code bases, but I stand by my assertion that it's a dangerous practice if you want to use static typing to validate code correctness.

I'll also note that `# type: ignore[arg-type]` is not a standard form. It's specific to mypy. 

I'll think about this more. If other pyright users have thoughts on this, I'd be interested in their thoughts.

**Comment by hmc-cs-mdrissi** [comment]
I'd be interested in` # type: ignore[pyright] ` vs `type: ignore[mypy]`. I'm less interested in `type: ignore[error-name]` although that could potentially be used to handle pyright vs mypy since error names I think all differ. 

My codebase is currently checked by both mypy/pyright. Most of the type errors I type ignore fall into three categories, 

1. An untyped library produces a lot of Any's causing some of the stricter settings to produce type errors. tensorflow and apache beam are two main large untyped libraries that produce type errors on stricter settings. A specific rule that composes poorly with tensorflow is untyped lambda rule. If tensorflow had types then the functional methods it has that accept lambdas would mostly give no errors. But the lack of them leads to more boilerplate or avoid lambdas with tensorflow functions/types. Maybe I should disable this rule, although it is useful in code that isn't tensorflow specific. The untyped base class rule also interacts poorly with tensorflow/beam as they both expect you to subclass some of their classes, but all of their classes look like Any to the type checker.
2. A missing feature in one of the two (paramspec usage for a while with mypy). Recursive type hints I also use on occasion and mypy does not support them so type ignores get needed.
3. A bug in pyright/mypy.

I've listed them in order of frequency. I like trying to be as strict as possible without producing an extreme amount of errors due to tensorflow. I could fix my 1 by dropping a couple flags that behave well normally, but poorly with tf/beam. I've tried using infer types from library code before, but tensorflow does too much dynamic stuff that it still behaves poorly (several basic methods are monkey patched by it).

**Comment by erictraut** [comment]
In my team's code base, we avoid category 1 by maintaining our own type stubs for the subsets of the untyped libraries that we consume. These stubs are by no means complete, but they're complete enough to eliminate all "unknown" types for our usage.

**Comment by hmc-cs-mdrissi** [comment]
That would probably be best solution. I'd estimate 1 as source of 90%+ of type ignores we use. 

I've avoided it hoping all the work on tensor types in typing sig would eventually include type stubs for the major tensor libraries. It's interesting to see work on advanced tensor typing, when basic type coverage of tensor libraries still needs work (although some like numpy have gotten much better). Maybe in a few months I'll just give up and start writing my own stubs and send them to typeshed (or maybe tf will accept them).

**Comment by Dr-Irv** [comment]
I would like this flag (it could be off by default, like in mypy) for these use cases:
1. You have a large legacy code base that is untyped,  and as you convert the large legacy code base module by module, you put in `#type: ignore` to handle places that you're just not ready to deal with yet, so that your CI passes through.  So if you had the option to warn on unused `#type: ignore` lines, as you started adding more and more typing to your legacy code, it will tell you which `#type: ignore` lines you can remove.  (By the way, this is how the pandas dev team and contributors work as we add typing to the pandas source).
2. You are using VS Code, and pandas, and some of the type stubs supplied with pylance have errors, so you put in `#type: ignore` lines to handle that, but as the pandas stubs improve, you would like to know where you can remove them.
3. You are developing a library like pandas, where you are adding in type stubs, and you want to have test code that tests whether the type stubs are too narrow or too wide.  To do that, you create code that you expect to fail in a type checker, so you add `#type: ignore` lines to do that.  As people use your stubs, they report issues of the type stubs being too wide or too narrow, so you add those cases to your set of tests of the type stubs, and the "warn on unused ignore statements" becomes useful to know that if you made some change in the stubs somewhere, that you didn't mess up your set of tests.

With `mypy`, we find their flag (which is off by defalt) for all of those use cases.

@erictraut You wrote:

> I realize that some disagree with me and think that it's acceptable to use # type: ignore in their code bases, but I stand by my assertion that it's a dangerous practice if you want to use static typing to validate code correctness. It's a landmine that will eventually blow up in your face.

I agree with you when you are writing _new_ code.  But when you have legacy untyped code, and you want to start introducing typing, it's a very useful feature.  It also can be useful when adding type stubs to an existing open source library (like pandas).

**Comment by erictraut** [comment]
I'm still not fully convinced that there's every a good reason to use `# type: ignore` in a code base, even an existing code base. I have experience taking a large untyped code base and gradually making it fully typed, and I didn't need to use `# type: ignore` once in that process. I consider it a landmine, and I don't believe in introducing landmines into a code base — especially a shared code base where the landmine is likely to explode in someone else's face at some point.

That said, there seems to be sufficient interest for this feature for it to be justified.

I've added support for a new diagnostic check called `reportUnnecessaryTypeComment`. It applies to `# type: ignore` comments at the end of lines as well as at the top of a file. This diagnostic check is off by default even in strict mode.

**Comment by erictraut** [comment]
This is included in pyright 1.1.206, which I just published. It will also be in the next release of pylance.

**Comment by Dr-Irv** [comment]
> This is included in pyright 1.1.206, which I just published. It will also be in the next release of pylance.

Thanks @erictraut !

**Comment by CaselIT** [comment]
@erictraut the flag `reportUnnecessaryTypeComment` seems to be undocumented. Also it doesn't seem to work anymore at least as of `pyright 1.1.385`

**Comment by erictraut** [comment]
@CaselIT, it's called `reportUnnecessaryTypeIgnoreComment`.
