### ISSUE TITLE
Cannot access numpy.ndarray.real and imag

### ISSUE THREAD

**Issue by NeilGirdhar** [microsoft/pyright#2866]
```python
from typing import Any, Union
import numpy as np
import numpy.typing as npt

ComplexArray = npt.NDArray[Union[np.floating[Any], np.complexfloating[Any, Any]]]

x: ComplexArray = np.array([1j])
print(x.real)  # works great!

def f(x: ComplexArray) -> ComplexArray:
    return x.real  # fails?!
```
This one's a mystery because it works at the top level, but fails in the function.

**Comment by erictraut** [comment]
I think the behavior is correct.

It succeeds at the top level because the type is being narrowed to `NDArray[Any]` based on the assignment. 

Within the function, `x` has the type `NDArray[floating[Any] | complexfloating[Any, Any]]`.

The `ndarray` class declares the `real` property as follows:
```python
    @property
    def real(
        self: NDArray[_SupportsReal[_ScalarType]],  # type: ignore[type-var]
    ) -> ndarray[_ShapeType, _dtype[_ScalarType]]: ...
```

The annotation for `self` is problematic because `NDArray` requires that its first type argument is bound to `generic`,  but `_SupportsReal[_ScalarType]` does not satisfy that bound.

If I remove the `bound=np.generic` from the declaration of type alias `ScalarType` and TypeVar `_ScalarType`, then this works correctly. So I don't think this is a bug in pyright. I think it's a bug in numpy.

**Comment by NeilGirdhar** [comment]
Thank you for the detailed analysis!!  This is way beyond me, but I'll file this as a bug in MyPy.

**Comment by BvB93** [comment]
Some trial and error has shown that the typevar bound is not the problem here and changing it did not fix the issue. As it turned out, the problem was one ndarray's generic parameters being set to `Any`, which is honestly some rather surprising behavior. Quite frankly I still do not understand why this fixes the issue (a bug?).

The diff below seems to fix the issue (note that the `NDArray` type alias is fully expanded here for the sake of clarity).
``` diff
_ShapeType = TypeVar("_ShapeType", bound=Any)
_DType_co = TypeVar("_DType_co", covariant=True, bound=np.dtype[Any])
_ScalarType = TypeVar("_ScalarType", bound=np.generic)

class ndarray(Generic[_ShapeType, _DType_co]):
    @property
    def real(
-        self: ndarray[Any, dtype[_SupportsReal[_ScalarType]]],
+        self: ndarray[_ShapeType, dtype[_SupportsReal[_ScalarType]]],
    ) -> ndarray[_ShapeType, _dtype[_ScalarType]]: ...
```
