### ISSUE TITLE
Allow specifying multiple configuration files

### ISSUE THREAD

**Issue by not-my-profile** [microsoft/pyright#2901]
**Is your feature request related to a problem? Please describe.**
I'd like to have one `pyrightconfig.json` config for development environments like VS Code and one `pyrightconfig-ci.json` for the CI. The config for the CI turns out to be a superset of the other config file and I'd like to avoid having to duplicate the configuration.

**Describe the solution you'd like**
It would be nice if pyright could be invoked with multiple configuration files, e.g:

```
pyright -p pyrightconfig.json -p pyrightconfig-ci.json
```

where settings specified in a later configuration file would override the settings of earlier configuration files.

**Comment by erictraut** [comment]
The configuration logic in pyright is already very complex because it needs to merge config information from pyrightconfig.json, language server settings, and command-line options. 

Merging of multiple configuration files would add more complexity. I don't think it's a simple as one overriding another because some of the configurations options interact with others.

So we don't have any plans at this time to support multiple configuration files.

This could be something we reconsider in the future, but for now you'll need to use duplicate configuration files.

**Comment by efine-vivodyne** [comment]
> it needs to merge config information from pyrightconfig.json, language server settings, and command-line options.

is there a way via the command line to override a setting in pyrightconfig.json?  that would be great, but I couldn't find out how to do that from the documentation
