### ISSUE TITLE
Import settings from .env or plugin env file

### ISSUE THREAD

**Issue by tribbloid** [microsoft/pyright#310]
**Is your feature request related to a problem? Please describe.**

If both python & pyright plugin are installed. The extra pythonpath has to be defined in both .env file and pyrightconfig.json. Otherwise there is a risk of inconsistency between static type check and inspection.

**Describe the solution you'd like**

Import from .env file as a fallback of configuration `executionEnvironments` in pyrightconfig.json

**Additional context**

N/A

**Comment by erictraut** [comment]
I made the intentional choice not to support ".env" files in pyright because it already implements a couple of other ways to specify the pythonpath that is arguably better than what can be provided with ".env" files, which are inherently problematic when it comes to cross-platform development. 

I'm going to close this feature request for now. Based on future upvotes or inquiries, I'm willing to revisit it.

**Comment by remss** [comment]
Supporting the .env would be nice to not have to define extra paths in two places, but it's not the only issue.
In my case pyrightconfig.json is committed with the code to ensure correct settings. So defining extraPaths that are specific the the user workspace is an issue because all developers will have to change the paths to fit their workspace.
On the contrary the .env is never committed and here we can put extra paths to resolve modules correctly.

**Comment by tribbloid** [comment]
Thanks a lot @erictraut 

I wonder if there is a way to specify pythonpath that is **widely acknowledged to be arguably better**, I have no problem with `pyrightconfig.json`, but at least VSCode should support it for things other than static type check

**Comment by cshesse** [comment]
@tribbloid what's the use case for specifying `PYTHONPATH` through an environment variable instead of installing packages in development mode in the current virtual environment?

**Comment by erictraut** [comment]
I was talking with the team responsible for the VS Code Python extension. They are thinking about how to better handle ".env" files in general for all language service extensions. 

For the command-line version of Pyright, you can execute the ".env" to set the PYTHONPATH, and Pyright will pick it up from the env variable.

For the VS Code version of Pyright, the VS Code Python extension will be updated at some point to provide better support for ".env". It will either set the env variables for other extensions (including Pyright) or pass the env variables through the language server interface, in which case Pyright will be updated to accept them.

Closing this issue for now.

**Comment by remss** [comment]
Good to know! If you know which github issue is tracking this feature on vscode-python please add a comment here so we can watch them 👍
