### ISSUE TITLE
Option to ignore the VSCode/pyright provided stubs

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#3120]
**Is your feature request related to a problem? Please describe.**
As you know, I work on the pandas type stubs.  When working on the pandas source in VS Code, I'd like to tell the embedded pyright "Don't use the stubs provided by VS Code, use the (partial) ones that are in the pandas source code I'm working on"

**Describe the solution you'd like**
An option to ignore the VS Code/pyright provided stubs for external libraries like pandas

**Comment by erictraut** [comment]
Pyright ships only typeshed stubs, and these are all searched last in the import resolution paths.

Pylance adds some additional stubs, and they are searched just prior to the typeshed stubs. I'm guessing that these are the ones that are getting in your way.

So you have a couple of options here:
1. Use pyright instead of pylance when you're doing your pandas development
2. Use pylance but manually delete the pandas stubs from the installed pylance extension
3. Add a "py.typed" marker to your in-development pandas stubs so they are resolved

This situation is very specific to you, so I don't think it make sense to add a general setting, but I'll transfer this feature request to the pylance repo for consideration there.

**Comment by erictraut** [comment]
For some reason, I'm not able to transfer this to the "pylance-release" project. I think it's unlikely that the pylance team would add a setting specifically for this purpose, but if you want to submit a separate feature request for pylance, you can do so.
