### ISSUE TITLE
CPU usage spikes to 400%+ after analysis completes

### ISSUE THREAD

**Issue by erictraut** [microsoft/pyright#316]
Chetan sees that the CPU usage on his machine spikes to 400% or more after analysis is complete. This is on MacOS on a 6-core machine. The CPU activity is attributed to the CodeHelper process for the pyright LSP.

**Comment by erictraut** [comment]
Unable to repro currently. Waiting for more information.

**Comment by burknator** [comment]
I had this problem too, changing the config usually fixed it. I only changed the include section and it didn't seem to matter what exactly I changed (i.e. adding or removing folder or the whole setion).

I can't say for certain, but I don't think I had this problem ever since the error message in #386 pops up. But I could be wrong about this.

**Comment by erictraut** [comment]
I've decided to completely disable the file system watcher for source files in the VS Code extension. It's continuing to cause stability problems, high CPU utilization, and other undesirable behavior. Most VS Code users aren't editing their source files outside of VS Code anyway, so it's not providing much value.

**Comment by erictraut** [comment]
This should be fixed in 1.1.11, which I just published.
