### ISSUE TITLE
[attrs] Incorrect argument handling for private attributes

### ISSUE THREAD

**Issue by micimize** [microsoft/pyright#3192]
Pylance/pyright is unaware that private attributes in attrs are [automatically mapped to public arguments](https://www.attrs.org/en/stable/init.html#private-attributes):
![image](https://user-images.githubusercontent.com/8343799/158248058-f7a6da7f-6941-48e8-8cdf-7cd06ed8a28e.png)

```python
@attr.s(auto_attribs=True)
class Foo:
    public: int
    _private: int

    @classmethod
    def build(cls) -> "Foo":
        return cls(public=1, private=2)
```

**Comment by erictraut** [comment]
The attrs library has a number of nonstandard behaviors that cannot be described using the standard Python type system. We have worked with the author of attrs to model the most commonly-used behaviors of attrs through [a new PEP](https://peps.python.org/pep-0681/) that is currently going through the ratification process currently. This particular feature of attrs (that private attributes are mapped to public arguments) is not part of the PEP proposal because it deviates too much from the standard dataclass behavior and was not deemed a frequently-used feature of attrs. As such, this isn't a feature that pyright will support. If you're interested in using attrs with pyright, I recommend that you avoid any reliance on this behavior.
