### ISSUE TITLE
control flow in the VS Code editor

### ISSUE THREAD

**Issue by MamadouSDiallo** [microsoft/pyright#321]
Create a variable in an if statement then use it later in other if statement provokes a "possibly unbound" error message. See small code below.

I did not expect to get an error message.

def foo(var1: int):

    if var1 == 1:
        result = "yes"
    
    for i in range(5):
        if var1==1:
            print(result)

Thanks for this great.

**Comment by erictraut** [comment]
The control flow analysis in any static type checker will have limits. In your example, there is a control flow route by which `result` is unbound. Through manual inspection it can be proven that `result` will never be unbound because you've used the same guard test (`var1==1`) in two different places, and `var1` is not modified in between. However, that determination requires way more sophistication than the pyright code flow engine provides (or any static analysis tool that I've ever seen, for that matter).

There are a few workarounds:
1. You can assign a value to result unconditionally (e.g. `result = ''`) at the top of the function
2. You can refactor your code so you don't need to evaluate the guard condition twice
3. You can suppress the error with a "# type: ignore" comment

**Comment by MamadouSDiallo** [comment]
Note that mypy does not complain. 
Thanks for the info will use one of the suggested workarounds.

**Comment by erictraut** [comment]
That's interesting that mypy doesn't complain in this case. I think that means one of two things:
1. Mypy's analysis engine is smart enough to track guard test equivalency across the control flow graph.
2. Mypy doesn't generate "possibly unbound" errors even in cases where a variable is possibly unbound.

I'd be curious to know whether it complains if you change the first test to `var1 == 2` (or `var1 == 0.5 * 2`) while leaving the second test `var1 == 1`.
