### ISSUE TITLE
bool summing wrongly determined to always evaluate to true

### ISSUE THREAD

**Issue by GBeauregard** [microsoft/pyright#3214]
**Describe the bug**
In some cases of bool summation pyright (incorrectly) always believes the condition will evaluate to true.

**To Reproduce**
```python
# pyright: strict
a = [0, 0, 1]

if sum(bool(i) for i in a) != 1:
    print("test")
else:
    print("uhoh!")
```

```console
/home/gregory/test.py
  /home/gregory/test.py:4:4 - error: Condition will always evaluate to True since the types "bool | Literal[0]" and "Literal[1]" have no overlap (reportUnnecessaryComparison)
```

**Expected behavior**
The code type checks

**VS Code extension or command-line**
Linux commandline 1.1.230

**Additional context**
This appears to be a recent behavior change, but I'm not sure when. You can work around the issue with `int(bool(i))`.

**Comment by GBeauregard** [comment]
This apparently isn't related to the type of `a`, so it isn't as artificial as the example makes it seem:

```python
# pyright: strict
from typing import Any

a: list[Any] = [0, 0, 1]

if sum(bool(i) for i in a) != 1:
    print("test")
else:
    print("uhoh!")
```

**Comment by erictraut** [comment]
This appears to be a bug in the typeshed stubs. It declares `sum` as follows:

```python
    @overload
    def sum(__iterable: Iterable[_T]) -> _T | Literal[0]: ...
    @overload
    def sum(__iterable: Iterable[_T], start: _S) -> _T | _S: ...
```

This means `sum([True, True, False])` will evaluate to type `Literal[0] | bool`, but it should evaluate to `int` in this case.

If you think this is worth fixing in typeshed, please consider filing a bug or a PR there.

This code looks pretty suspect to me in the first place since you're summing boolean values. Most languages would not allow you to do that in the first place since addition is a meaningless operator for boolean values.

As a workaround you could do:
```python
if sum(int(bool(i)) for i in a) != 1:
```

or

```python
if sum(1 if i else 0 for i in a) != 1:
```

**Comment by JelleZijlstra** [comment]
This is because summing two booleans produces an int. This seems difficult to fix in typeshed other than by providing an overload specifically for bools. (Or maybe we can do something clever with a protocol using `__add__`?)

Even so, though, the pyright error is technically wrong: `Condition will always evaluate to True since the types "bool | Literal[0]" and "Literal[1]" have no overlap`. But `True == 1` evaluates to true, so `bool` and `Literal[1]` do have overlap.

**Comment by GBeauregard** [comment]
Indeed, the pyright behavior is wrong:
```python
if True == 1:  # pyright: "Condition will always evaluate to False"
    print("hi")
```
