### ISSUE TITLE
Pyright incorrectly classing code as unreachable and greying it out

### ISSUE THREAD

**Issue by PickledGherkin** [microsoft/pyright#323]
The last couple of Pyright releases seem to incorrectly class code as unreachable and greying it out. This was not happening in previous releases.

To reproduce it I have created the following example:

```
def flibble( first, second ):
    try:
      first = 5
      second = first/0
      return False
    except ZeroDivisionError, e:
        print ("%s" % e)

    return True

def flubble( thingy ):
    print thingy

if flibble(1,2):
    print ("flibble returned True")
flubble("Proving a point")
```

On my system everything is greyed out below the return True in the function flibble. Now I know the exception style above is old but I need to run the code on older versions of python. The screenshot below shows the issue:

![image](https://user-images.githubusercontent.com/15798904/68229273-d3124500-ffee-11e9-9859-01ef83dfb38a.png)

When I run the code I get:

> integer division or modulo by zero
> flibble returned True
> Proving a point
> 

I'm using Windows 10 and the latest version of python extension, pyright and VSCODE.

**Comment by erictraut** [comment]
The issue here is that you have a syntax error that's confusing the parser. The statement `except ZeroDivisionError, e` is invalid syntax according to the python grammar. I think you mean `except ZeroDivisionError as e`. Because of this syntax error, the pyright parser is attempting to recover the parse by swallowing tokens. This causes it to interpret the `return` statement as no longer part of the function and instead part of the module — and therefore infer that the remainder of the module is unreachable. If you fix the syntax error, the problem goes away.

**Comment by PickledGherkin** [comment]
So what is the earliest python version that you support? As I mentioned this has to be compatible with an older python version.

https://stackoverflow.com/questions/1373255/making-python-2-6-exception-backward-compatible

The problem goes away if I remove the return True as well...
