### ISSUE TITLE
Pyright and Mypy[no-redef]

### ISSUE THREAD

**Issue by Ierezell** [microsoft/pyright#3254]
**Describe the bug**
Variable get a warning of type unknow but variable was defined above and mypy would complain of a no-redef if specified

**To Reproduce**
```python
all_final_labels: NDArray[np.int32] = np.array([])
for .... : 
    all_final_labels = np.append(all_final_labels, label)

# Raises a (red wigles on hover):
# (variable) all_final_labels: NDArray[int32]
# Type of "all_final_labels" is unknownPylance[reportUnknownVariableType]
```

```python
all_final_labels: NDArray[np.int32] = np.array([])
for .... : 
    all_final_labels: NDArray[np.int32]  = np.append(all_final_labels, label)

# Is fine for pyright but running mypy would give a 
# error: Name "all_final_labels" already defined on line xxx  [no-redef]
```

**Expected behavior**
Having Pyright using the same behavior and not forcing to re-type variables

**VS Code extension or command-line**
Pyright 1.1.232 in vscode

**Additional context**
I'm using mypy as it's easier to run in a github action (no need to build venvs)

**Comment by erictraut** [comment]
I don't think there's any bug here. This looks like it's probably intended behavior, but I can't say for sure because your bug report doesn't contain enough information for me to repro the behavior you're seeing.

Please provide a minimal self-contained code sample. The samples above reference symbols that are not builtins, so must be imported from one or more libraries. Include the import statements and the library versions you're using — along with any type stub packages that you have for them.

You do not need to redeclare the variable type. Mypy doesn't allow you to specify a type declaration for the same variable more than once. Pyright allows it as long as the declarations refer to exactly the same type, as they do in your second example, but the second declaration is redundant in that case and does not change the behavior. Keep in mind that a type declaration defines the type of values that are permitted for a variable. You are allowed to assign a value with a "narrower" type than the declared value, in which case the effective type of that variable is different from the declared value immediately after the assignment. For more details about type declarations, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md).

**Comment by Ierezell** [comment]
Hi @erictraut,

Thanks for the fast reply !

In my example, the problem comes from the numpy libs that return an `NDArray[unknown]` when using the `append` method...
So the problem is "on their side because they should type their code".

However, as the variable was declared above cannot pyright infer that even if the return of `append` is `NDArray[unknown]` then it should be the same type as it was declared above ?

I will make you a full example snippet that you can use to reproduce this behaviour. 

Thanks for your help 
Have a great day

**Comment by erictraut** [comment]
I don't think this is a bug in pyright, so I'm going to close. If you still think it's a bug and can provide a sample that demonstrates the problem, I'm happy to re-open it and take a look.
