### ISSUE TITLE
"Find All References" Shows Everything Twice

### ISSUE THREAD

**Issue by haytaylan** [microsoft/pyright#326]
**Describe the bug**
When both Python extension for Visual Studio Code and Pyright are activated, whenever "Find All References" are used, the results are shown twice, i.e. every result appears twice, showing the same location on code.

**To Reproduce**
Use "Find All References" or "ctrl+click" on any symbol of code while ms-python and ms-pyright extensions are activated

**Expected behavior**
Every result should be shown once.

**VS Code extension or command-line**
VS Code extension (Vs Code version 1.39.2)
ms-pyright.pyright 1.0.83
ms-pyrhon.python 2019.10.44104
OS: Windows 7

**Comment by giyyapan** [comment]
That's a known issue, please see #201 #197 and https://github.com/microsoft/vscode-python/issues/7010

**Comment by haytaylan** [comment]
Thank you for pointing out

**Comment by erictraut** [comment]
Yes, this is expected behavior of VS Code when two extensions handle the same functionality. It's outside the control of either extension because they have no knowledge of each other. I'm working with the team that develops the Python extension to expose a setting so its type checker can be disabled in favor of pyright. Of course, if you prefer the Python extension's type checker, you can uninstall pyright.
