### ISSUE TITLE
Type inference failure for map

### ISSUE THREAD

**Issue by tamuhey** [microsoft/pyright#328]
```python
def f(x: AnyStr) -> AnyStr:
    return x

a: Any = ["a", "b"] # sometimes this is Unknown
b = map(f, sorted(a, key=len)) # This line cause error
```

The error is:

```
No overloads for 'map(f, sorted(a, key=len))' match parameters
  Argument types: ((x: AnyStr) -> AnyStr, List[Sized])
```

**Comment by tamuhey** [comment]
Adding `typing.cast` but not work.
```python
def f(x: AnyStr) -> AnyStr:
    return x

a: Any = ["a", "b"]
b = map(f, sorted(cast(a, List[str]), key=len))  # add typing.cast
```

**Comment by erictraut** [comment]
I think pyright is doing the right thing in this case.

The variable `a` is typed as `Any`, so the type matching for `sorted(a, key=len)` cannot make any assumptions about `a`. The only clue is has to go from is the `len` function, which takes a `Sized` parameter. The TypeVar matching logic therefore concludes that the result of `sorted(a, key=len)` is of type `List[Sized]`.

The `map` function is defined as follows:
`def map(__func: Callable[[_T1], _S], __iter1: Iterable[_T1]) -> Iterator[_S]: ...`

Function `f` is of type `Callable[[AnyString], AnyString]`, and `AnyString` is a TypeVar that bounds the type to either `str` or `bytes`. When the TypeVar matching logic attempts to "solve for _T1", there are two types it could possibly assign to `_T1`: `Sized` or `AnyStr`, but neither of these work. If it chooses `Sized`, function `f` doesn't match because it says that the input parameter must be an `AnyStr`, and a `Sized` is not assignable to `AnyStr`. If it chooses `AnyStr`, the expression `sorted(a, key=len)` won't match because it evaluates to `List[Sized]`, which isn't assignable to `Iterable[AnyStr]`.

I can see three simple changes you can make to your code to eliminate the error:
1. Change `f` to take a `Sized` parameter and return a `Sized` result.
2. Make sure `a` is properly typed as `List[str]` (e.g. remove the `: Any` type annotation).
3. Replace `key=len` with `key=sort_by_len` and define a new local function:
`
def sort_by_len(x: AnyStr):
    return len(x)
`

**Comment by tamuhey** [comment]
Thank you for your kind reply!

>  If it chooses AnyStr, the expression sorted(a, key=len) won't match because it evaluates to List[Sized]

I think this behavior is incorrect.
Since pyright can infer the type of `_T` as `Sized` from `len` function, also can infer `Sized` as `AnyStr`  from `f: Callable[[AnyStr]...`?

**Comment by erictraut** [comment]
I don't follow what you mean by "infer `Sized` as `AnyStr` from `f: Callable[[AnyStr]`". The `AnyStr` TypeVar is constrained to be either `str` or `bytes`. Those need to match exactly. Subclasses or protocols don't work in this case. `Callable[[str], str]` is compatible with `Callable[[AnyStr], AnyStr]` but `Callable[[Sized], Sized]` is not.

**Comment by tamuhey** [comment]
Thanks, I got it. I was confusing generics inference with subclass inference.  The problem is that `Size` is just an alias for a class.

I understand If I have `len` function as follows, the inference succeeds.

```python
SIZED = Union[str, bytes, List, Tuple]

def f(x: AnyStr) -> AnyStr:
    return x

def len_(x: SIZED) -> int:
    return len(x)

a: Any = ["a", "b"]
b = sorted(a, key=len_)
c = map(f, b) # OK
```

**Comment by HOP2020** [comment]
Excuse?
