### ISSUE TITLE
PYRIGHT performance

### ISSUE THREAD

**Issue by dmey** [Microsoft/pyright#33]
This may be just me -- or not an issue per se -- but I have not noticed a (substantial) improvement in speed when compared to other Python static typing tools (e.g mypy) -- at least when used in small to medium size projects. In VS Code (Windows 10), loading modules' metadata can take several seconds. Is this a known 'issue' or is this type of behaviour expected?

**Comment by erictraut** [comment]
I've soften the performance claims in the README in recognition of the fact that I've done only informal comparative benchmarking and only on a handful of source bases.

When run from a command line, I think most users will observe a substantial performance benefit when running pyright on a medium-to-large source base, but there will naturally be some variation. 

The first time you load a python file in VS Code, pyright needs to parse and analyze about three dozen other typestub files ("builtins.pyi" and its dependencies), so that might account for the several seconds you're seeing. This information is cached in memory, so subsequent files should analyze much faster.
