### ISSUE TITLE
Receiving "not defined" error

### ISSUE THREAD

**Issue by gwww** [microsoft/pyright#3305]
**Describe the bug**
I'm received the following error message from the code below. I don't think I should be receiving the error.

`baderror.py:7:48 - error: "Element" is not defined (reportUndefinedVariable)`

```
from typing import Callable

class Element:
    def __init__(self) -> None:
        self.callback: Callable[[Element], None] | None = None

    def add_callback(self, callback: Callable[[Element], None]) -> None:
        self.callback = callback
```

**To Reproduce**
See above.

**Expected behavior**
I know there's a high chance I'm wrong, but it appears that I should not receive this error.

**Screenshots or Code**
See above.

**VS Code extension or command-line**
Running LSP on neovim, but I get this error just using the command line `pyright baderror.py`

**Comment by erictraut** [comment]
If you run the above code in the Python interpreter, you will receive the following error:
`NameError: name 'Element' is not defined`

Pyright is telling you about this error, which occurs because the type annotation for `add_callback` is evaluated before the class `Element` is defined.

There are two options to fix this problem:
1. Enclose the `"Callable[[Element], None]"` annotation in quotes, which defers evaluation of the expression.
2. Add `from __future__ import annotations` to the top of the file, which defers evaluation of all type annotations.

**Comment by debonte** [comment]
Would replacing `Element` with `Self` also work?

**Comment by erictraut** [comment]
You could use `Self` here, but that has a slightly different meaning if `Element` is subclassed. Also, `typing.Self` isn't part of the stdlib until Python 3.11, which is still under development, so you'd need to use `typing_extensions.Self` instead.
