### ISSUE TITLE
Support multiple paths for type stubs

### ISSUE THREAD

**Issue by BurningLights** [microsoft/pyright#3318]
The current method of having a single directory containing all type stubs does not allow for using forked versions of type stub projects. Each forked repository resides within its own repository folder, which does not play nice with pyright only allowing a reference to a single folder containing a folder for each module. Allowing multiple stub folders would enable being able to use forked type stub repositories. Alternately, pyright could still require a single folder containing all type stubs, but allow the modules to be defined in deeper subfolders, rather than the immediate subfolders of the stubs folder.

**Comment by erictraut** [comment]
I'd like to better understand how you're using forked versions of type stub projects. Do you and your collaborators clone these forked repos separately from the repo that contains your project? If so, where do you clone them? Within your project root directory or outside?

How do you keep the cloned stubs up to date? Do your team members need to remember to pull from all of the individual forked repos?

It's unlikely that we will add support for multiple stub paths, so let's look for existing solutions for your use case. 

Here are some existing options:
1. If the forked version is an installable stub package, you can install it your Python environment either normally or as an editable install.
2. You can use symbolic links within the stub folder to point to alternate paths.
3. You can clone the forked repo into a top-level directory within your project folder, since pyright uses the root directory to resolve imports . Likewise, you can clone the forked repo into a subdirectories and use the "extraPaths" to point to them.
4. You can use git subprojects to make the forked stub repo appear as a child of your main project repo. You can make it appear within the stub directory.

**Comment by erictraut** [comment]
I'm going to close this issue. If I misunderstood your use case and/or the above suggestions don't work for you, let me know and we can continue the conversation.
