### ISSUE TITLE
`__radd__` quirk when right operand is a subclass of the left operand

### ISSUE THREAD

**Issue by MathiasSven** [microsoft/pyright#3368]
Pyright (CLI 1.1.239)
```py
class A:
    def __add__(self, __other) -> int: return 42

class B(A):
    def __radd__(self, __other) -> str: return "foo"

reveal_type(A() + B())  # Type of "A() + B()" is "int"
```
mypy
```py
reveal_type(A() + B())  # Revealed type is "builtins.str"
```
`A() + B() == "foo"` at runtime, but pyright resolves it to `int`

**Comment by erictraut** [comment]
I'm confused by the behavior I'm seeing from this code at runtime.

The [Python documentation](https://docs.python.org/3/reference/datamodel.html#object.__radd__) is quite clear about how `__add__` and `__radd__` work:

> These functions [`__radd__` and other "reverse" forms] are only called if the left operand does not support the corresponding operation [3](https://docs.python.org/3/reference/datamodel.html#id10) and the operands are of different types. [4](https://docs.python.org/3/reference/datamodel.html#id11) For instance, to evaluate the expression x - y, where y is an instance of a class that has an [__rsub__()](https://docs.python.org/3/reference/datamodel.html#object.__rsub__) method, y.__rsub__(x) is called if x.__sub__(y) returns NotImplemented.

In the example above, the left operand _does_ support the corresponding `__add__` operation, so I would expect `A() + B()` to return a value of `42`. But that's not what I'm seeing when I run this code in the interpreter. It returns `"foo"` instead, which seems to indicate that the interpreter looks for an `__radd__` prior to looking for an `__add__` if the types of the two operands don't match. So there's an apparent mismatch between the documented behavior and the actual behavior. If anyone understands what's going on here, I'd appreciate your input.

In general, a type checker cannot know whether two types match exactly. Consider this example, which builds upon the example above.

```python
def func(v1: A, v2: A):
    print(v1 + v2)

func(B(), B()) # prints 42
func(A(), B()) # prints foo
func(B(), A()) # prints 42
```

Within `func`, we don't know whether the parameters `v1` and `v2` are `A` or `B` objects because the type annotation `A` means "`A` or a subtype thereof". 

So if the rules followed by the runtime are as convoluted as it appears they are, there's no way for a static type checker to determine the correct answer statically. I would therefore advise against using a pattern where you have a class hierarchy where the parent implements `__add__` and the child implements `__radd__` or vice versa.

**Comment by MathiasSven** [comment]
This is indeed confusing, I only found out about this today while investigating how to type hint a generic `operator.add` function, but this behavior is in the [Python documentation](https://docs.python.org/3/reference/datamodel.html?highlight=__radd__#object.__ror__):
> Note If the right operand’s type is a subclass of the left operand’s type and that subclass provides a different implementation of the reflected method for the operation, this method will be called before the left operand’s non-reflected method. This behavior allows subclasses to override their ancestors’ operations.

So I believe mypy just special cases for when the RHS is a subclass of the LHS. Unfortunately for my case there is no way to say `T` but not *exactly* `T` with the current available typing operators.

**Comment by MathiasSven** [comment]
> So I believe mypy just special cases for when the RHS is a subclass of the LHS

After having a look at mypy it does seem that this is the [case](https://github.com/python/mypy/blob/d1c061689a330a4fa993f3cadf5cd8bc06756698/mypy/checkexpr.py#L2585-L2626), they explicitly check for that.

Perhaps the most sensible solution would be to not allow `__OP__` and `__rOP__` to have incompatible return types, that way you could still subclass `A` and make `__rOP__` return a more precise type at runtime then `__OP__`. Performing `A` OP `A`, would safely type check as `A`, and `A` OP `B` could type check as the more precise version of the return type of `A.__OP__` given that `B` implements `__rOP__`.

**Comment by erictraut** [comment]
Thanks for pointing out the documentation.

As I noted above, there's no way that a static type checker can handle this case correctly given that the type system doesn't distinguish between types and subtypes. 

Pyright's handling of binary ops is already incredibly complicated (more so in many respects than mypy's) to handle unions (of both operands), bidirectional type inference, constrained type variables, normal and reverse methods, and special casing for several specific operations. I don't think we should add additional special casing for what I consider to be an edge case. Doing so would further complicate the code, slow down type analysis in the common case, and would still produce incorrect results because of the static analysis limitations. 

You'll need to work around this limitation in your code. For example, you could add more restrictive parameter annotations to `__add__` and `__radd__`.

**Comment by MathiasSven** [comment]
My use case is in fact just annotating the operators in the operator module on typeshed, I believe that all the instances of Any could be replaced by overloads of both SupportsOP and SupportsROP to give better type inference and annotations are provided, the only thing that got in the way was this specific issue. Whether pyright handles this or not is not important, just having a consensus on what should and shouldn't be allowed when static typing.
