### ISSUE TITLE
Invariant issues not reported correctly

### ISSUE THREAD

**Issue by YannickAlex07** [microsoft/pyright#3376]
**Describe the bug**

Hey there, I think I've encountered a bug with invariant type checking in combination with abstract classes and subclasses.
When I want to assign a list of subclasses to a variable that is hinted as `list[<abstract-parent-class>]`, Pyright does **not** complain about the assignment as long as it happens in the same line. It seems like Pyright infers the type of the list wrongly.

**To Reproduce**

* Create an abstract class
* Create a subclass based on that abstract class
* Write the following line `x: list[MyParentClass] = [MySubclass()]`

**Expected behavior**

Pyright should complain about the types not matching because of invariants.

**Screenshots or Code**

<img width="1383" alt="Bildschirmfoto 2022-04-24 um 15 48 01" src="https://user-images.githubusercontent.com/25741738/164979668-e08384fc-6a92-4a73-8ba8-811ac1927e4f.png">
<img width="1383" alt="Bildschirmfoto 2022-04-24 um 15 48 26" src="https://user-images.githubusercontent.com/25741738/164979681-94f15e7e-c691-4031-9b39-0c00fe026b32.png">

**VS Code extension or command-line**

I am using the Pylance VSCode extension with version `v2022.4.2` - which seems to include version `1.1.239`.

Interestingly enough, the issue was noticed because the [Pyright GitHub Action by Jake Bailey](https://github.com/jakebailey/pyright-action) caught this error correctly. We ran the action with version `1.1.217` and `lib = True`.

**Comment by erictraut** [comment]
This is correct behavior. When the assignment occurs on the same line, [bidirectional type inference](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#bidirectional-type-inference-expected-types) is used to infer the type of a list expression on the right-hand side (RHS). A list expression effectively constructs a new list, and it "starts life" as the inferred type, so there is no type violation in this case. If you attempt to assign an already-constructed list whose type has already been established, then invariant types will be rejected.

For future bug reports, I'd appreciate it if you could paste the text of the code rather than (only) providing screen shots, especially for longer samples. It avoids the need to retype a bunch of code from the screen shot.

**Comment by YannickAlex07** [comment]
Okay if this is indeed the correct behavior, can we then assume that version `1.1.217` reported that wrongly and is therefore causing our CI to complain?

And yes, I am sorry, in the future I will supply the code directly as well.
