### ISSUE TITLE
Type enum member as a `Union` of the types of all variants

### ISSUE THREAD

**Issue by Tomaz-Vieira** [microsoft/pyright#3380]
**Is your feature request related to a problem? Please describe.**
One reason to prefer enums over `Literal`s is the ability to write methods for the `enum`. When writing such methods, though, `self.value` is typed as `Any`.

**Describe the solution you'd like**
I would like the type of `self.value` in a `enum` method to be a `Union` of all member types.

**Comment by erictraut** [comment]
Enums in Python are complex and already involve a lot of special casing in the type checker. I'm reluctant to add more complexity here. 

This seems also seems like a very unusual use case for Enums. Most Enum classes use either `int` or `str` values, and the `value` member is properly typed if you use the `IntEnum` and `StrEnum` classes. Very few enum classes that I have seen have custom methods. So the feature you're proposing here would apply only the the case where an enum class uses non-int and non-str values or a mixture of value types _and_ defines custom methods on the enum class, a rare and unusual combination.

This feature would also require overriding type information provided in the typeshed stubs, something I generally like to avoid because it tends to lead to compatibility and maintenance issues.

I'm going to close this feature request for now, but we might reconsider it in the future if we receive sufficient signal from others (in the form of thumbs-up reactions or comments).
