### ISSUE TITLE
GLIBC_2.28 not found with node 18

### ISSUE THREAD

**Issue by ultmaster** [microsoft/pyright#3414]
pyright crashes with the following error after node 18 has been released.

```
> pyright myproject
 * Install prebuilt node (18.0.0) ..... done.
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
```

I'm running ubuntu 18.04. There seems to be no obvious (/convenient) way to upgrade my glibc 2.27 to 2.28. After a little digging, I found that pyright is using nodeenv to create a clean node environment under `/tmp/pyright.username`, and nodeenv automatically looks for latest stable. Unfortunately, although nodeenv provides way to restrain the node version, pyright didn't expose such ability.

A possible solution is to constrain the node versions in pyright. I did that by hacking pyright's python package.

```python
def _install_node_env() -> None:
    log.debug('Installing nodeenv to %s', ENV_DIR)
    args = [sys.executable, '-m', 'nodeenv', str(ENV_DIR), '--node=16.15.0']  # I added node version here
    log.debug('Running command with args: %s', args)
    subprocess.run(args, check=True)
```

I was hoping that pyright could address that natively.

**Comment by erictraut** [comment]
I've confirmed that pyright runs fine with node 18, so this appears to be an issue with installation of node on your system. 

It looks like you're using the community-maintained Python wrapper to install pyright rather than installing it directly using npm. The Python wrapper published in pypi isn't part of this project. It's maintained by Robert Craigie as part of [this project](https://github.com/RobertCraigie/pyright-python). Please file a bug in that project so he's aware of this issue.
