### ISSUE TITLE
Performance regression in 1.1.243: 10 seconds -> 90 seconds

### ISSUE THREAD

**Issue by ottumm** [microsoft/pyright#3427]
**Describe the bug**
In my codebase (225 source files, Python 3.10) Pyright CLI version 1.1.242 takes 10 seconds to run, and version 1.1.243 (and 1.1.244) take 90 seconds to run. All three versions report no errors or warnings.

**To Reproduce**
Hopefully this is reproducible in other codebases (I can't share mine as its private). If not, I'm happy to run with whatever diagnostic settings/tools are helpful.

**Expected behavior**
Roughly-equivalent run-time to 1.1.242.

**VS Code extension or command-line**
Command-line: reproduced this with both 1.1.243 and 1.1.244.

**Additional context**
`pyproject.toml` settings:

```
[tool.pyright]
include = ["src", "script"]
strict = ["src", "script"]
reportImportCycles = true
pythonVersion = "3.10"
```

**Comment by erictraut** [comment]
Thanks for reporting the problem. I was worried that [this fix](https://github.com/microsoft/pyright/commit/3bce53eabf32602c8980a1911599043e19cc573c) would have a negative impact on performance. 

Is your source base in a public repo? If so, I can take a look a it. If it's not public, I'd appreciate your help in diagnosing this. In particular, we'll need to localize the code affected by this change. I'm presuming that there is a particular module in your code base that accounts for most of that added analysis time. It's possible though that the analysis time increased across many modules.

**Comment by ottumm** [comment]
@erictraut thanks for the quick response! Unfortunately, the source base isn't public (and is proprietary). I'm very happy to help diagnose this. Let me know what to do.

**Comment by erictraut** [comment]
If my theory is correct, there's one module (or perhaps a handful of modules) where the analysis time increased significantly. I'm thinking we could binary search the code base to determine where the additional 60 seconds comes from. You can do this by updating your pyproject.toml to specify subsets of your project to include in the analysis. For example, it looks like you have two top-level directories specified in the "include" statement. I'm guessing you have subdirectories under "src", so perhaps break those out individually within the "include" statement and then eliminate them until you find the one that accounts for the bulk of the analysis time.

A few additional questions that might help home in on the issue:
1. Is your source base type annotated for the most part? I'm guessing it is, since it looks like you have "strict" type checking enabled.
2. Do you use the "--lib" command line option? If so, that tells pyright that it should evaluate types from untyped library code, so it expands the list of potential modules that could be adding to the analysis time.

**Comment by ottumm** [comment]
Ok, I'll do the binary search and report back.

> Is your source base type annotated for the most part?

Yes, almost completely.

> Do you use the "--lib" command line option?

No.

**Comment by erictraut** [comment]
I've fixed a couple of performance issues in pyright 1.1.245, which I just published. These could address the perf regression you reported. Please let me know if it does.

**Comment by erictraut** [comment]
The next version of pyright (1.1.246) will include a new feature that logs the analysis time for each file. This will make it much easier to zero in on performance issues like this. If 1.1.245 doesn't address the performance problem, don't waste your time binary searching. You can use the new logging facility in 1.1.246 (once it's released) to quickly find which file(s) are associated with long analysis times.

**Comment by ottumm** [comment]
1.1.245 did indeed fix my performance regression, thank you! Really nice work — I appreciate it and am impressed with your responsiveness.
