### ISSUE TITLE
Issue with mix of implicit and explicit namespace packages

### ISSUE THREAD

**Issue by alicederyn** [microsoft/pyright#3430]
**Describe the bug**
When using a top-level implicit namespace in my project, and a top-level explicit namespace of the same name exists in site-packages, pyright emits errors of the form "Could not import '...'" for absolute imports of project code.

**To Reproduce**
I am using an in-house product that sets up VSCode in WSL-2 via the Remote - Containers plugin so I'm not clear on the best way to reproduce -- am happy to grab any logs needed though, or describe any setup. The rough structure is:

```
workspace/
  \-- company/
        \-- projecta/
              |-- file.py
              \-- file2.py # contains import company.projecta.file, which pyright cannot resolve
site-packages/
  \-- company/
        |-- __init__.py  # contains __path__ = __import__("pkgutil").extend_path(__path__, __name__)
        |-- projectb/
        .
        .
```

Changing `file2.py` to use `from . import file` resolves the issue, as does creating an explicit namespace package at `workspace/company/__init__.py`, or deleting `site-packages/company/__init__.py`.

**Expected behavior**
Pyright resolves absolute imports when a mix of explicit and implicit namespaces is used 

**VS Code extension or command-line**
VSCode Pylance v2022.4.3 plugin (I had the same issue with previous versions)

**Additional context**
Looking through the code, I see that https://github.com/microsoft/pyright/commit/8894e181a11b992a501288cc31b84a35d5db855b#diff-81d67b2637abe4f01bfed3e5ddffc08258efc91e5e82812e57230b9fda05745fR572 introduced a change where, if any part of the route to the file is an implicit namespace, the final ImportResult is flagged as a namespace package, which doesn't seem right. If I understand the code correctly, this means that my `site-packages/company` folder is treated as the correct location for `company.projecta` even though it is only a partial resolution of that name, while my `workspace/company/projecta` folder is discarded because it is (incorrectly?) considered to be a namespace package.

**Comment by erictraut** [comment]
I think pyright is doing the right thing here. I replicated the files and directories as indicated, then I created a file at the top level of the workspace called `test.py` that contains `from company.projecta.file2 import foo`. When I run this in the python interpreter, I receive the following exception: `ModuleNotFoundError: No module named 'company.projecta'`. So the python interpreter is also unable to resolve this import. If I delete `site-packages/company/__init__.py`, then pyright and the python runtime are able to resolve the import. That makes sense because both packages are then namespace packages, whereas the presence of an `__init__.py` makes one of the two packages a traditional (non-namespace) package.

The rules for resolving partial namespace packages are not well documented (which are further complicated by the import resolution rules documented in PEP 561 for stubs). We've had to do a bunch of reverse engineering to replicate the behaviors of the runtime. In this case, I think pyright is doing the right thing.

**Comment by alicederyn** [comment]
As I said, the `__init__.py` file declares an explicit namespace package. " the presence of an __init__.py makes one of the two packages a traditional (non-namespace) package." is not true. Please reopen

**Comment by erictraut** [comment]
Dynamic (runtime) manipulation of `__path__` isn't supported by pyright or other static analysis tools. You'll need to find another solution if you want this to work.

**Comment by alicederyn** [comment]
Actually, isort does exactly this

**Comment by alicederyn** [comment]
mypy also send to have no problem, though I haven't looked into the code to determine why

**Comment by alicederyn** [comment]
I should say, I understand not wanting to add this complexity for a legacy feature. I'd be totally happy with just a note in the docs suggesting this as a possible cause of the error message, as that would have saved me a bunch of time figuring out the problem, and I could link others to it easily.

**Comment by alicederyn** [comment]
One other thought: it's odd that your logic supports a pair of explicit namespace packages, when it doesn't detect explicit namespaces. Does this mean the logic would find `company.projecta` if both `company` folders had a blank `__init__.py` file? Because I don't think python would support this.
