### ISSUE TITLE
Not access variable in signature of function only greyed but not reported

### ISSUE THREAD

**Issue by crsegerie** [microsoft/pyright#3473]
Hi, Thanks for this library! Really better than mypy. 

I want to see directly in VS Code all the unused variables, especially variable declared in the signature of the function, but not used afterwards.

See this example:
klklklklkl = 2 is underlined in red and is correctly reported
model_path above is only greyed but not reported.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/38733898/169073247-a2be8649-fcfd-41ef-88ab-6f7f3fe881de.png)

My toml file contain the parameter : reportUnusedVariable = true

I do not think it's a bug, it was certainly a conscious choice on your part,  but how can we achieve this goal ?

**Comment by crsegerie** [comment]
"There are many legitimate uses for parameters that need to be present but are not used" → can you give me an example? I think 90% of the time, it would be a bad practice.

If so, reportUnusedVariable = true is misleading. In my use case, an error would really be helpful.

Thank you.

**Comment by erictraut** [comment]
The term "variable" in this context is distinguished from "parameter", which is why we chose the name "reportUnusedVariable" for this diagnostic check.

Can you explain your use case more? Why do you want these to be flagged as errors? Is there a class of bugs that you think it would detect?

We could consider adding a new "reportUnusedParameter" diagnostic check, but we would do so only if we received sufficient signal from users that it would be broadly applicable. We certainly wouldn't be able to enable such a check by default, even if "strict" mode is enabled.

I'm going to close this for now. We could revisit if there is sufficient demand (in the form of additional comments or thumbs up reactions).

**Comment by crsegerie** [comment]
ok, thanks for the explanation. 

I have a class base with a number of arguments. And I have several child classes.

Thanks to the parameter reportIncompatibleMethodOverride, we can check that the methods of the child classes have the same arguments as the parent class.

But then, we have to check that these arguments are used, which is not possible now.
