### ISSUE TITLE
`Union` of `TypedDict`s not narrowed by `in` properly

### ISSUE THREAD

**Issue by GrantGryczan** [microsoft/pyright#3506]
**Describe the bug**
The `in` operator does not narrow `Union`s of `TypedDict`s properly.

**To Reproduce**
```py
from typing import TypedDict


class Point2D(TypedDict):
    x: int
    y: int


class Point3D(TypedDict):
    x: int
    y: int
    z: int


Point = Point2D | Point3D

point: Point = None  # type: ignore

if "z" in point:
    print(point["z"])  # Error: Could not access item in TypedDict   "z" is not a defined key in "Point2D"
```

`point` is still considered a `Point` inside the `if` statement.

**Expected behavior**
I expect `point` in the above example to be narrowed to `Point3D`, since I've checked that `point` has a `"z"` key, which `Point2D` does not have.

**VS Code extension or command-line**
Pyright v1.1.248 as VS Code extension

**Comment by erictraut** [comment]
Yes, this is by design. The problem is that `Point2D` refers to an instance of `Point2D` or any subclass thereof. There's no way for a type checker to know whether a subclass adds a `z` member to the TypedDict, so it cannot safely eliminate it when performing type narrowing.

If you mark the `Point2D` class as `@final`, then there's no way it can be subclassed, and pyright will narrow it in this situation.

```python
@final
class Point2D(TypedDict):
    x: int
    y: int
```

**Comment by GrantGryczan** [comment]
Thank you.
