### ISSUE TITLE
Type narrowing for Literals with `if myliteral in ["foo", "bar"]` is not properly recognized?

### ISSUE THREAD

**Issue by ldorigo** [microsoft/pyright#3524]
Repro code (there's probably a simpler way to show it but this is a generic version of the usecase in which I encountered the bug):

```python
from typing import Literal, overload

@overload
def foo(a: ..., b: ..., return_type: Literal["number", "integer"]) -> int:
    ...

@overload
def foo(a: ..., b: ..., return_type: Literal["string"]) -> str:
    ...

def foo(a: int, b: int, return_type: Literal["number", "integer", "string"]) -> int | str:
    return a + b if return_type in ["number", "integer"] else str(a + b)

def dosomething(return_type: Literal["number", "integer", "string"]) -> None:

    if return_type in ["number", "integer"]:
        t = foo(1, 2, return_type=return_type) # t is if type str|int, not int as it should be
```
I read somewhere that you are selective with the type narrowing patterns you support so maybe this is not something you want to allow? Just mentioning it in case you decide it's worth supporting.

**Comment by erictraut** [comment]
This is intended behavior. The problem is that you're using a list in the `in` subexpression. The inferred type of the list expression `["number", "integer"]` is `list[str]`. If you change this to a tuple (`("number", "integer")`), literals will be retained, and the `in` type narrowing will work as you are hoping.

For more details about pyright's type inference behavior for tuples and lists, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#tuple-expressions).
