### ISSUE TITLE
--verifytypes does not resolve local directory

### ISSUE THREAD

**Issue by tommyjcarpenter** [microsoft/pyright#3528]
The context for this bug is in this thread: https://github.com/microsoft/pyright/issues/2320

**Describe the bug**

```
pyright indexapi
```
works fine and analyzes my 29 files:
```
pyright installed: nodeenv==1.6.0,pyright==1.1.251
pyright run-test-pre: PYTHONHASHSEED='3105655527'
pyright run-test: commands[0] | pyright indexapi
No configuration file found.
pyproject.toml file found at /Users/tommycarpenter/Development/python-indexapi.
Loading pyproject.toml file at /Users/tommycarpenter/Development/python-indexapi/pyproject.toml
Assuming Python version 3.10
Assuming Python platform Darwin
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath /Users/tommycarpenter/Development/python-indexapi/typings is not a valid directory.
Searching for source files
Found 29 source files
0 errors, 0 warnings, 0 informations
Completed in 1.456sec
__________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________
  pyright: commands succeeded
  congratulations :)
```
 
but 

```
pyright --verifytypes indexapi
```
errors:
```
Module name: "indexapi"
Package directory: ""
Module directory: ""
  error: Module "indexapi" cannot be resolved

Symbols used in public interface:

Symbols exported by "indexapi": 0
  With known type: 0
  With ambiguous type: 0
  With unknown type: 0
  Functions without docstring: 0
  Functions without default param: 0
  Classes without docstring: 0

Other symbols referenced but not exported by "indexapi": 0
  With known type: 0
  With ambiguous type: 0
  With unknown type: 0

Type completeness score: 0%

Completed in 0.111sec
```

**To Reproduce**
This comment: https://github.com/microsoft/pyright/issues/2320#issuecomment-974655523

Here is the LS of my directory, again `pyright indexapi` works fine, but `pyright --verifytypes indexapi` does not
```
.rw-r--r--   53k tommycarpenter 31 May 20:00 .coverage
.rw-r--r--    40 tommycarpenter 27 Oct  2021 .coveragerc
drwxr-xr-x     - tommycarpenter  1 Jun 10:42 .git
.rw-r--r--   294 tommycarpenter 22 Dec  2021 .gitignore
drwxr-xr-x     - tommycarpenter  1 Jun 10:31 .mypy_cache
drwxr-xr-x     - tommycarpenter 26 Aug  2021 .pytest_cache
.rw-r--r--     7 tommycarpenter  9 Feb 06:47 .python-version
drwxr-xr-x     - tommycarpenter  1 Jun 10:42 .tox
drwxr-xr-x     - tommycarpenter 16 May 10:38 build
.rw-r--r--   32k tommycarpenter  1 Jun 06:25 Changelog.md
drwxr-xr-x     - tommycarpenter 27 May 10:43 dist
.rw-r--r--  2.5k tommycarpenter 27 May 10:43 Dockerfile
drwxr-xr-x     - tommycarpenter 27 May 12:08 docs
drwxr-xr-x     - tommycarpenter 30 Apr 06:44 helm
drwxr-xr-x     - tommycarpenter 21 May 07:22 htmlcov
drwxr-xr-x     - tommycarpenter  1 Jun 06:25 indexapi
drwxr-xr-x     - tommycarpenter  1 Jun 10:31 indexapi.egg-info
drwxr-xr-x     - tommycarpenter 27 May 10:43 integration_tests
.rw-r--r--  4.6k tommycarpenter 27 May 10:44 Makefile
.rw-r--r--    39 tommycarpenter 30 Apr 06:44 MANIFEST.in
.rw-r--r--  1.7k tommycarpenter 15 Nov  2021 pylintrc
.rw-r--r--  1.0k tommycarpenter 27 May 10:43 pyproject.toml
.rw-r--r--   370 tommycarpenter 12 Mar 10:43 README.md
.rw-r--r--  2.1k tommycarpenter  1 Jun 06:25 requirements.txt
.rw-r--r--  1.7k tommycarpenter  1 Jun 06:25 setup.py
drwxr-xr-x     - tommycarpenter 31 May 16:16 tests
.rw-r--r--  4.9k tommycarpenter  1 Jun 10:42 tox.ini
```

**Expected behavior**
it analyzes missing types in the `indexapi` folder

**Comment by tommyjcarpenter** [comment]
I can try to produce a tarball but this is company code and will take me a bit of time, thats why I was hoping that other issue thread is enough context.

**Comment by erictraut** [comment]
The `--verifytypes` command is not meant to work with a local directory. It is designed to work with an installed library. Many libraries must be installed to have the proper directory layout for import resolutions. Imports will not resolve as intended prior to installation.

You will need to install the library in your local environment before you run `--verifytypes` on it. If your library supports an editable install, that might be the most convenient approach.

**Comment by erictraut** [comment]
`--verifytypes` is designed to verify libraries in their already-installed form. It is meant for library authors who want to validate that the library — once installed — is type complete. As I said, the directory layout of many libraries is modified as part of the installation process, and imports will not resolve correctly prior to installation.

The `--verifytypes` command analyzes the _public interface_ of a library and ensures that it is fully typed, including return type annotations for all functions and methods.

Pyright (when used without the `--verifytypes` mode) runs on all code in a code base, and it uses its normal type inference rules to infer types of unannotated return types, variables, etc. So it serves a very different purpose than `--verifytypes`.

If your intent is to verify that your internal code implementation has no type violations, you should use `pyright` (without `--verifytypes`). If your intent is to verify that the public interface of your py.typed library is fully typed and doesn't rely on any type inference rules that may vary across type checkers, you should use the `--verifytypes` option.

Did you try performing an editable install prior to running `--verifytypes` on your library? Did that work?

**Comment by tommyjcarpenter** [comment]
OK, that helps. We arent using a py.typed file and this isn't a library, it's an end application. 

I was looking for a way to replace `mypy --strict` where the difference between `mypy` and `mypy --strict` is that strict will complain about any missing type defs or returns. 

Running simply `pyright` seems to not complain about missing typedefs - only that there are no logical inconsistencies with what *is* tyoed. 

Maybe what would be helpful is a pyright flag `requireFullTyping` that simply checks if there are any missing type or return type annotations - and fail with exit code 1 if so, that can be used outside of the context of libraries/py.typed files. `mypy --strict` provides this and is basically the one reason we havent replaced it completely with `pyright`.

**Comment by vberlier** [comment]
In my experience `--verifyTypes` doesn't like it if you're running the command from your project directory, even if the package is properly installed. I use Poetry, which takes care of installing the package in my virtualenv but using `poetry run pyright --verifyTypes mypackage` doesn't work as pyright gets confused about my source directory. If I rename my source directory to something other than `mypackage` or if I go into a temporary directory before running pyright then it works. See my workaround [in the previous issue](https://github.com/microsoft/pyright/issues/2320#issuecomment-974655523).

**Comment by erictraut** [comment]
@tommyjcarpenter, pyright's normal type checking mode doesn't enforce the presence of type annotations because pyright has a sophisticated and capable type inference engine. In cases where types can be inferred, there's no reason to require annotations in the code. Mypy's philosophy is similar for local variables and instance variables, but it doesn't (currently) extend this capability to function return types.

So I don't think the goal should be "require annotations for every symbol within the code base". The goal should be "make sure the type checker doesn't have any blind spots when it's verifying type consistency".

Pyright does have a strict mode. Have you tried enabling that? It will flag any cases where an `Unknown` (i.e. an implied `Any`) type is used. These represent potential blind spots.

**Comment by hmc-cs-mdrissi** [comment]
It’s unclear to me why many type errors existing is bad. My team had an existing codebase of 100k lines untyped. We added pyright with several of stricter rules. It produced many thousands of type errors. So we made CI gradual. All prs must not increase error count. For core maintainers they must decrease error count by 5 of files touched. For non core maintainers they don’t need to decrease it. A file having 100 errors does not mean you must fix all of them in one pr.

Now that a year has passed most type errors in codebase have gone away. I think we had roughly 30k errors initially and are down to 5k. 

Implementation wise I made small wrapper python script that called pyright twice once on pr branch and once on master and then compared the two error counts.

**Comment by erictraut** [comment]
@tommyjcarpenter, pyright does have an option `reportUnknownParameterType` that will report an error when an input parameter is missing an annotation. That's important because the type of an input parameter cannot be inferred except in very special circumstances. Perhaps that solves most of your problem without using `mypy --strict`?

Pyright doesn't have an option to emit an error for missing return type annotations because return types can be inferred accurately in most cases. In my team's code base, we include return type annotations for less than 25% of all functions and methods; adding them in all cases would be unnecessary and redundant, and I don't want to make my developers do unnecessary work if I can help it.

I understand your point that some tools don't have pyright's inference capabilities and therefore require explicit return type annotations. That sounds like a compelling argument to switch to pyright and pylance. :)

The approach suggested by @hmc-cs-mdrissi is interesting. I think that's a viable approach to incrementing typing, but it depends on your philosophy. In my case, I have a "zero error / zero warning" philosophy for my team. I want my team's developers to have the attitude that when the tools are telling them that there's a problem, they need to fix it, period. So my approach to incremental typing was to enable a subset of diagnostic rules and then expand that over time. Once we cleaned up all of the errors for a particular diagnostic rule, we enable it for the code base to prevent future errors of that class. Over time, we were able to enable all of the strict-mode checks for the entire code base. So the end result was the same as what @hmc-cs-mdrissi described, but the approach was a bit different.

**Comment by tommyjcarpenter** [comment]
@hmc-cs-mdrissi that's an interesting model! well done

I would say we have taken the model that @erictraut has mentioned. We now have basic pyright with only a few ignores enabled in all repos, and are working on those (although many of them are external import ignores, packages like pandas drive pyright nuts - we cant control those). 
after that, I will look into some additional rules that strict enables, and try to get there over time. 

but that's kind of orthognal to the original intention of this issue.

it sounds like `reportUnknownParameterType` will solve half the battle - function definitions.

no one has yet to comment on @vberlier  comment - I can try to get `--verifytypes` running via `tox` with installation enabled - but if that comment is accurate, this really _does_ sound like a pyright bug. That is, if there is a local folder with the same name as the installation package, which would definteily be the case here (im going to try it), and that confuses pyright, isnt that a bug?

**Comment by erictraut** [comment]
@tommyjcarpenter, `--verifytypes` is specifically intended to verify the type completeness of an installed py.typed library. It looks only at the symbols that comprise the public interface contract for a library and ignores internal implementation details. Based on what you've said about your use case, `--verifytypes` is completely the wrong tool. It will not do what you want because it was not designed for that purpose. 

@vberlier, if you are using `--verifytypes` to verify the type completeness of an installed py.typed library and believe that there is a bug in the way that pyright handles this situation, please file a separate issue.

**Comment by vberlier** [comment]
@erictraut Hmm now it appears to be working correctly. I've been using the trick with the temporary directory for a while but I just checked again with the latest Pyright and it worked without issues. I haven't changed my setup for the package I used for testing so I guess the bug just disappeared.

Successful action run: https://github.com/vberlier/tokenstream/runs/6716757827?check_suite_focus=true#step:10:1

Apologies for bringing this up again without testing.
