### ISSUE TITLE
Pyright not enforcing consistent TypeVar 

### ISSUE THREAD

**Issue by GabrielCappelli** [microsoft/pyright#3587]
**Describe the bug**
Pyright not enforcing consistent TypeVar on a function definition

**To Reproduce**
Write a function that receives `type[T]` and a `Callable[[], T]` that returns T. Call that function with inconsistent types, e.g with str as a type and a callable that returns a int.

**Expected behavior**
Pyright reports a type issue.

**Screenshots or Code**
```python
from typing import TypeVar, Callable

T = TypeVar("T")


def create(type_: type[T], factory: Callable[[], T]) -> T:
    return factory()


def foo_factory() -> str:
    return "foo"


def int_factory() -> int:
    return 123


var = create(str, foo_factory)
another_var = create(str, int_factory)
```

![image](https://user-images.githubusercontent.com/6148081/174448822-3cd41043-ba65-4d25-98a3-ebf42765b272.png)

![image](https://user-images.githubusercontent.com/6148081/174448806-c2147c6d-f731-4a79-8265-c0e68b9edd26.png)

**VS Code extension or command-line**
```
pyright --version
pyright 1.1.254
```

**Additional context**

**Comment by GabrielCappelli** [comment]
MyPy reports this issue as expected:

```
mypy .\example.py
example.py:20: error: Argument 2 to "create" has incompatible type "Callable[[], int]"; expected "Callable[[], str]"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by erictraut** [comment]
I think pyright's behavior is correct here. In the Python type system, type variables are "solved" given a set of constraints. In the example above, there is a valid solution for type `T` when evaluating the expression `create(str, int_factory)`. That solution is a union of `str` and `int`. The type `str | int` satisfies all of the constraints of the call. I know this is behavior can be unexpected if you're unfamiliar with type theory.

I can't explain mypy's behavior in this case. This looks to me like a bug in mypy. Its behavior is inconsistent with the typing standards. It's also inconsistent with its own behaviors in similar use cases. Consider the following example where mypy solves the type variable using a combination of the input types, although its use of a "join" operator rather than a "union" operator produces a solution of `object` rather than `str | int` in this case.

```python
def func2(a: T, b: Sequence[T]) -> T:
    ...

x2 = func2(1, [""])
reveal_type(x2) # mypy: object, pyright: str | int
```

**Comment by erictraut** [comment]
Here is additional evidence that this is a bug in mypy. If I swap out the `Callable` with an equivalent callback protocol, mypy no longer generates an error and finds a valid solution for `T` as I would expect.

```python
from typing import Protocol, TypeVar

T = TypeVar("T")
T_co = TypeVar("T_co", covariant=True)

class Factory(Protocol[T_co]):
    def __call__(self) -> T_co:
        ...

def create(type_: type[T], factory: Factory[T]) -> T:
    ...

def int_factory() -> int:
    return 123

another_var = create(str, int_factory)
reveal_type(another_var) # mypy: object, pyright: str | int
```

**Comment by GabrielCappelli** [comment]
Okay, I understand. `str | int` indeed would be a valid type for `T` in this scenario.

Is there any way to set a constraint so `T` cannot be resolved using a UnionType ? 

Worst case scenario I can do the required validations during runtime.

**Comment by erictraut** [comment]
The only mechanisms you have for specifying additional constraints on a TypeVar are through the use of an "upper bound" (i.e. the `bound` keyword argument) and a set of explicit type constraints (a "constrained TypeVar"). 

```python
# TypeVar with upper bound
T = TypeVar("T", bound=str)
```

or

```python
# Constrained TypeVar
T = TypeVar("T", str, int)
```

I don't know enough about your use case to say whether either of those are applicable in this case.
