### ISSUE TITLE
Pyright forgets that a type has gotten narrowd

### ISSUE THREAD

**Issue by mmohaveri** [microsoft/pyright#3594]
**Describe the bug**
In the following code pyright (VSCode extension) knows that a variable type has gotten narrowed in one line, and forgets about it in the next line:

```python
import numpy as np
from typing import TypeVar, List
from dataclasses import dataclass
from numpy.typing import NDArray

T = TypeVar("T", np.string_, np.bool_)

@dataclass
class ReleaseData[T]:
    np_data: NDArray[T]

    def __contains__(self: "ReleaseData[np.string_]", other: "ReleaseData[np.string_] | str | List[str]") -> "ReleaseData[np.bool_]":
        # self.np_data is a 2D numpy array like: np.array([[["A", "B"], ["C", ""]], dtype=np.string_)

        if not isinstance(other, ReleaseData):
            if isinstance(other, str):
                raise NotImplementedError("rest is not important...")

            def _is_in_row(row: NDArray[np.string_]) -> NDArray[np.bool_]:
                other # here hint knows that other is List[str]
                return np.array([(bytes(item, "utf8") in row) for item in other]).all() # here it complaints that ReleaseData[np.string_] does not have an __iter__ function, which means it has forgotten about the `other` type getting narrowd!

            np_data=np.apply_along_axis(_is_in_row, 1, self.np_data).astype(np.bool_)
            return ReleaseData(np_data=np_data)

        raise NotImplementedError("rest is not important...")
```

I'll have the same issue if instead of using a closure function use a lambda function.

**Expected behavior**
I expect it to not forget about the type getting narrowd.

**Screenshots or Code**

![Screenshot from 2022-06-20 19-40-28](https://user-images.githubusercontent.com/6017468/174632148-68fbe3aa-c361-470e-ae14-7f1b658bd8ba.png)
![Screenshot from 2022-06-20 19-40-50](https://user-images.githubusercontent.com/6017468/174632158-78e7095c-2367-4a29-a85e-bb80ae57453a.png)

**VS Code extension or command-line**
VS Code extension, version 1.1.255

**Comment by erictraut** [comment]
This is expected behavior. In general, type narrowing is not maintained within a closure because the static type analyzer doesn't know when that function or lambda is going to be invoked. The type of the variable could be modified after the creation of the function or lambda.

Other type checkers like mypy never retain the narrowed type in this case. Pyright contains some special-case logic that allows the narrowed type to be retained in certain cases where it can prove that the symbol is not modified along any path or used within a loop. In your example, the first reference to `other` within `_is_in_row` is allowed to retain its narrowed value, but the second reference is used within a `for` loop within a list comphrehension, so pyright is unable to verify that it is safe to retain the narrowed type.

The recommended workaround in this case is to assign the narrowed value to a new variable that can then be captured within the inner function or lambda.

```python
            other_str = other
            def _is_in_row(row: NDArray[np.string_]) -> NDArray[np.bool_]:
                return np.array([(bytes(item, "utf8") in row) for item in other_str]).all()
```
