### ISSUE TITLE
Add an official pre-commit hook

### ISSUE THREAD

**Issue by diepala** [microsoft/pyright#3612]
It would be great if there was an official pre-commit hook for pyright. The only one I have been able to find is [this](https://github.com/necaris/pre-commit-pyright), but it seems it is not maintained anymore.

**Comment by erictraut** [comment]
Most pyright users are on github and use this [github action for running pyright in CI](https://github.com/jakebailey/pyright-action). If you're not using github, you can follow the instructions [here](https://github.com/microsoft/pyright/blob/main/docs/ci-integration.md) for setting up a git pre-commit hook.

**Comment by ssbarnea** [comment]
@erictraut I am really curious what were the reasons for refusing advertising pyright as a pre-commit hook. The current documentation sample is mostly a temporary measure for enabling someone to run a pre-commit hook when the official tool/linter does not have the hook definition included in it.

It can be considered an anti-pattern because it break the ability of pre-commit tool to automatically upgrade new the hooks with pull-requests when a new release is made. That is not possible if you add a local hook or if you point to an intermediary wrapper repository that defines the hooks, basically because they will not magically get the release tags.

I looked at git history o and I seen that back in 2020 the pre-commit hook was added, but only to be later removed.

The thing with "most pyright are on github" seems bit weird in the context of that change and makes me even wonder if the removal was a trick to force users to only use github to test their changes -- which would be a very bad coding practice. Engineers are expected to also test changes locally before starting to flood CI/CD with their... typos.

I should also note that based on your last sentence, you might not be aware that pre-commit tool is not a git-hook, this being only an opt-in feature of it, and probably one of the least important ones. By default the tool does not install any git-hooks and can be used just as a CLI linter, (I personally prefer to call it a lint-orchestrator).

When defined inside this repository the hook definition needs no maintenance at all as it would not have any version mentioned in it.

We hope that the closing of this issue was more of an accident than a deliberate move towards cripping the use of pyright outside GHA, especially as its was made such quickly.

**Comment by hmc-cs-mdrissi** [comment]
I think existing instructions are good. Having pyright support pre-commit as a non local hook is problematic since pyright depends on current environment. Similar to mypy/pylint, you should have your local code installed before running pyright. Pre-commit’s normal venv isolation doesn’t fit here. https://pre-commit.com/#repository-local-hooks 

> Hooks require state that is only present in a built artifact of your repository (such as your app's virtualenv for pylint).

Most python tools that use environment (mypy, pylint) do not have a hook defined in their repo.

**Comment by ssbarnea** [comment]
What @hmc-cs-mdrissi mentions is a know limitation but one that is easy to compensate for unless the linter code changes its dependencies very often. Currently we keep the required on duplicated inside the pre-commit config for mypy and pylint. As an additional step one could make use of `export PIP_CONTRAINTS=constraints.txt` in order to force pre-commit to use specific versions of these tools everywhere, while not having to update versions inside hook definitions.

I am sure that this works and probably we still use it in one project or two but the reality is that the need to update mypy/pylint deps there is very rare so we did not bother to use it on other projects.

Another approach, which I do not personally recommend, is to just disable the import checks on these tools. I guess there is no need to explain why, especially for type checking.

**Comment by erictraut** [comment]
@ssbarnea, I admit that this is not my area of expertise. It sounds like I may be using the wrong terminology. Isn't a "pre-commit hook" a git concept — something that git runs prior to a commit to a repo? Are you saying that a "git pre-commit hook" is not a type of "git hook"?

My assumption is that git pre-commit hooks are used to run tools on the server as part of CI. It sounds like you are using them for other workflows like running tools locally. Could you explain a bit more about your desired workflow and how you would configure it?

**Comment by ssbarnea** [comment]
I happen to have a quite old article posted at https://sbarnea.com/posts/lint-via-pre-commit-tool/ which seems to be still valid. I hope that will give you some insights on how pre-commit tool can be used. In case my article is too long, I would try summarize a very simple workflow:

- clone repo, make the change you want
- run `pre-commit run -a`, and eventually fix your mistakes
- run `gh pr create` to create a pull request or similar

As you can see, there is no hook involved. For projects using tox, there is a slight variation, user is expected to run `tox -e lint` instead of running pre-commit itself, but what happens is basically the same thing, the only difference is that user would not have to install pre-commit tool.

Obviously that this workflow does not conflict in any way with CI/CD integration, where we expect to run the same command in one of the pipelines. Still, pure reliance on CI/CD is bad practice, especially for basic checks like linters.

**Comment by erictraut** [comment]
If my understanding is correct, `pre-commit` is a separate tool that's unrelated to git. Based on its download numbers, it looks like it's pretty widely used.

@jakebailey, do you have any thoughts on adding a `.pre-commit-hooks.yaml` file to the pyright repo? Any concerns?

**Comment by jakebailey** [comment]
I would reread #862; I don't think anything has changed since then, unfortunately.

The main concern is that any pre-commit hook (or any use of pyright, really) should not be cloning this repo and trying to install/build it. That'll take about a minute on a machine like a GHA builder.

Reading the pre-commit docs, that is still how pre-commit expects things to work for node hooks; the target repo is cloned, then `npm install .` is run, and then the package should be executable.

This is "fine" for a pure-JS package that can actually be run from source, but isn't enough for a package written in TS (or any other build step for that matter). TypeScript-based packages overwhelmingly do not run `tsc` in a post-install script, instead opting for a `prepack` or other build step before publish, as the published package to npm is pure-JS and should not be doing any building.

Additionally, pyright is a monorepo, so installing at the top level `package.json` will not do the right thing as that's the package where things like eslint or lerna are installed, so that's another hurdle.

With that in mind, my best idea so far to make pre-commit work is to create a separate repo with a package.json something like this:

```json
{
    "name": "pyright-pre-commit",
    "private": true,
    "bin": "node_modules/pyright/index.js"
    "dependencies": {
        "pyright": "*"
    }
}
```

This would be a functional pre-commit node package, as it "works" with only an "npm install`, but, has no ability pin a specific pyright version. Potentially, this package could do something like my GitHub Action and download a version directly instead of relying on npm.

Another option might be for the pre-commit config to be placed on the unofficial PyPI package for pyright, though that will subvert pre-commit's own node binary.

Another option, if people aren't concerned about time, would be to fix pre-commit to support monorepos and running `prepack` before it tries to run the package. But, this sounds the most complicated to me.

**Comment by NorthIsUp** [comment]
I created one that "just works"

it uses a pre-commit node type to install and it also "prettifies" the output to be more like other python tooling, check it out:

https://github.com/NorthIsUp/pyright-pretty
