### ISSUE TITLE
Warning for missing return annotations that are simple

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#3615]
**Is your feature request related to a problem? Please describe.**
Large partially/un-annotated code bases have a lot of missing return annotations that are very simple (None or any other concrete type). Emitting warnings to add those return annotations could help developers to add them which could then speed up future type checking (and could also make functions "eligible" for type checking if unannotated functions were previously ignored). xref https://github.com/pandas-dev/pandas/pull/47497

**Describe the solution you'd like**
Pyright already infers missing return annotations. If the return type is a single concert type (not any/unknown/union; excluding unions because functions that return unions often would need a more complex overload), it would be great to emit a warning to nudge people to add those simple annotations.

**Comment by erictraut** [comment]
We've thought about adding this as a language server feature for pylance — as an interactive code action that offers the recommended (inferred) return type.

I don't think it's appropriate to add this feature to pyright as a warning or error because there's nothing wrong with omitting a return type annotation given pyright's ability to accurately infer return types in most cases. My team's code base, which is strictly-typed, has return type annotations on only about a third of its functions and methods. 

So if we were to add this capability, it would need to be off by default (even in strict mode), and very few pyright users would even know it exists. We generally don't add such diagnostic checks because they end up being discovered by a handful of users.

**Comment by twoertwein** [comment]
Would you recommend using

```sh
 pyright --createstub pandas
 grep -R "# ->" typings/pandas/
```

to easily find the missing return annotations inferred by pyright?

**Comment by erictraut** [comment]
My recommendation is to add a return type annotation only if and when it is necessary. In the majority of cases, they are unneeded.

The one place where return type annotations are important is in the public interface for a "py.typed" library. The `--verifytypes` command-line option for pyright is designed to detect and report this condition.
