### ISSUE TITLE
Hover does not always show docstring

### ISSUE THREAD

**Issue by jw3126** [microsoft/pyright#3632]
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

**Describe the bug**
Hover does not always give back the docstring. A concrete example would be `torch.sum`. The function is implemented in C++ and pyright only finds the signature, while IPython does find this docstring.

**To Reproduce**
Hover `torch.sum`

**Expected behavior**
Docstring of `torch.sum` shows up. Instead only signature shows up.

**Screenshots or Code**
* pyright:
![image](https://user-images.githubusercontent.com/7261506/176388277-431cfb01-9fa3-48bb-933b-1cf8504e66ab.png)
* ipython
![image](https://user-images.githubusercontent.com/7261506/176388431-e63d974d-eaac-43a8-a4ee-4ffd055fc525.png)

**Comment by erictraut** [comment]
Yes, this is expected behavior. IPython has access to the runtime docstring because it loads and executes the code in the binary library. Pyright is a static analyzer and operates only on Python source code. It never runs the libraries that it analyzes.

Typically, type information for symbols implemented in other languages are described in a type stub file. That is the case for torch.sum. The author of a stub file can choose to include a docstring in the stub definition, in which case pyright will include it in the hover text. In this case, the torch maintainers have evidently chosen not to include a docstring in the stub.
