### ISSUE TITLE
Possible to have smarter stub generation?

### ISSUE THREAD

**Issue by wch** [microsoft/pyright#3644]
Here is an example Python file, `test.py`:

```py
class Test:
    def __init__(x: int):
        self.x = x

y = "abc"
```

After running `pyright --createstub test` on it, this is the resulting `typings/test/__init__.pyi` file:

```py
"""
This type stub file was generated by pyright.
"""

class Test:
    def __init__() -> None:
        ...
    


y = ...
```

This loses the type information for the `Test` class's instance attribute `x`, and for the plain variable `y`.

I know that when _not_ using stubs -- when using the package directly with a `py.typed` file, Pyright can:
* infer the type for `y`
* infer the existence and type of `x` (as an instance var).

I'm wondering: is there a reason for not using the same logic when generating stubs? 

*****

FWIW, `stubgen` can do some of this. This is the output from `stubgen`:

```py
from _typeshed import Incomplete

class Test:
    x: Incomplete
    def __init__(x: int) -> None: ...

y: str
```

So it can infer the type of `y` and the existence of `x`, but not the type of `x`.

**Comment by erictraut** [comment]
Pyright's stub generator follows the general principle that type information emitted by the generator should be accurate. If it is not guaranteed to be accurate, then it should be omitted. Stubs produced by the stub generator are meant to be a "first draft", and it is assumed that the author will need to do manual cleanup. If the stub generator emits "guesses" for some types, it makes it difficult for the author to determine what needs to be fixed. As such, it is conservative about what it emits.

For instance variables, it's often not clear from the code whether the author intends for the variable to be a class variable, an instance variable, or an instance variable that is "backed" by a class variable. These need to be handled differently by a type checker because they have different runtime semantics.

```python
class Foo:
    x: ClassVar[int] = ...
    y: int = ...

    def __init__(self):
        z: int = ...
```

For function return types, pyright's stub generator emits a comment indicating its "best guess" based on inference. For example, if the input is:

```python
def return_list():
    return [1, 2, 3]
```

The output is:
```python
def return_list(): # -> list[int]:
    ...
```

This gives the author the opportunity to verify the inference and remove the comment if it looks correct.

Other stub generators may be based on different philosophies, and you should feel free to use whatever stub generator best meets your needs.

**Comment by wch** [comment]
I think there are a few different use cases for stub generation:

* Generate stubs for third party packages which I have no control over.
* Generate stubs for my own package, which I will then tweak to make more accurate.
* Generate stubs for my own package, which I do not want to tweak.

In the first case, it makes sense not to infer too much from the code.

For the second case... well, I'm not sure why someone would want to work that way, since the stub generation happens once, but then it requires manual maintenance over time to keep in sync with the actual code. Maybe this makes sense for people who aren't ready to fully commit to typing?

The third case is what I'm trying to do -- my hope is that the generated stubs would contain the same typing information as the original code, but in a more compact representation. (I'm using the stubs in a somewhat resource-constrained environment.) This makes sense to me, but I'm starting to get the sense that this is actually an unusual use for stubs?

**Comment by erictraut** [comment]
Yes, this isn't a targeted use of pyright's stub generator. I recommend that you include type information in your code, not attempt to maintain it on the side. As you point out, this is expensive to maintain, and even with automation, it's difficult to ensure that separate type information won't deviate from the implementation.

You may find that other stub generation tools better support your use case.

**Comment by LordAro** [comment]
FWIW, I have an additional workflow that applies to @wch's third case - the actual source is Cythonised and otherwise unavailable to the type checker.

With pyright generated stubs this results in an awful lot of `Attribute "foobar" is unknown` errors (as opposed to mypy, which doesn't)

**Comment by lukaspiatkowski** [comment]
I understand that the stub generator in pyright outputs only types that it is very sure of (or none?) leaving the rest unknown. And I guess that pyright infers types for untyped packages that lack stubs in a more flamboyant fashion to be generally more useful. What would be nice is for the stub generator to support outputting the types that pyright infers, because sometimes those types are "almost there" but for few little tweaks. Would the resulting stub be inaccurate? Yes. Would it be useful to the project, help with typing, save time on not writing the stubs from scratch and from putting `pyright: ignore` all over the place? Also yes. 

I get the point about existence of `stubgen`, but it won't generate the types that Pyright infers and might result in causing more work for developer to bring it to a satisfying level. If you have been working with pyright and an untyped library for a very long time and suddenly there is an update and one tiny type is wrongly inferred then you have to essential recreate the types that pyright already knows in a stub to fix a small issue.

**Comment by erictraut** [comment]
The stub files that pyright (or stubgen) generate from source code are often incomplete and incorrect, so I consider them a "first draft". You should always go through them and manually fix any errors before relying on them. 

Pyright outputs its inferred return types in comment form. As part of the manual fix-up process, you can review the inferred type and delete the `#` if it appears correct.

**Comment by lukaspiatkowski** [comment]
> The stub files that pyright (or stubgen) generate from source code are often incomplete and incorrect

Incomplete and incorrect might still be useful and is still better than nothing. Pyright attempting to infer types from untyped packages is a living example of this. I think it would be a nice extension of Pyright's current capabilities to be able to take those incomplete types and be able to improve them slightly, so that they are still incomplete, but a bit more useful in the context of the project that uses the untyped package.

> Pyright outputs its inferred return types in comment form.

AFAIS that is only for return types, it doesn't emit them for arguments or even constant globals. Pyright does infer the types of `__title__` and `reverse` in the following example correctly to be `Literal["my package"]` and `bool`, but in autogenerated stubs I see no mention of that:
```
.py:
__title__ = "my package"

def foo(l, reverse=False):
    sorted(l, reverse=reverse)
----
.pyi
__title__ = ...

def foo(l, reverse=...): # -> None
    ....
```
Also the stubs generated by Pyright, as opposed to stubgen,  don't emit imports using [re-exporting import conventions](https://typing.readthedocs.io/en/latest/spec/distributing.html#import-conventions) or the `__all__` symbol and you have to manually fix this as well.

I would expect it to be possible to generate the stubs with Pyright and get the exact same type errors on my project that I did have before I generated the stubs. But now, to get from Pyright inferred types to an equivalent stub files declaration is a lot of work, which ideally the stub generator could do for us.  If the process of generating the stubs require some modifications that I can do with a simple additional command (e.g. as of now, apply all the type suggestions on return types from comments with something like `sed 's/: #/`') then that is fine.
