### ISSUE TITLE
asyncio.gather() return type is aways tuple[()]

### ISSUE THREAD

**Issue by exherb** [microsoft/pyright#3655]
**Describe the bug**

await asyncio.gather() return type is `tuple[()]`

**To Reproduce**

save code below as file, then run `pyright -p .`

`Expression of type "tuple[()]" cannot be assigned to declared type "tuple[str | Exception | None]`

**Expected behavior**

lint pass

**Screenshots or Code**

```
import asyncio
from typing import Awaitable, List, Tuple, Union

async def foo():
    return ""

futures: List[Awaitable[str]] = [foo()]
exceptions: Tuple[
  Union[str, Optional[Exception]]
] = await asyncio.gather(*futures, return_exceptions=True)
```

**VS Code extension or command-line**

`pyright -p .`

**Comment by erictraut** [comment]
This happens because of the way `asyncio.gather` is declared in the typeshed stub `tasks.pyi`.

I'll copy it here for reference.

```python
    @overload
    def gather(*, return_exceptions: bool = ...) -> Future[tuple[()]]: ...

    @overload
    def gather(__coro_or_future1: _FutureLike[_T1], *, return_exceptions: Literal[False] = ...) -> Future[tuple[_T1]]: ...

    @overload
    def gather(
        __coro_or_future1: _FutureLike[_T1], __coro_or_future2: _FutureLike[_T2], *, return_exceptions: Literal[False] = ...
    ) -> Future[tuple[_T1, _T2]]: ...
    # ... omitted additional overloads for brevity
```

The expression `futures` is a list, so a type checker cannot statically determine its length. When you unpack it, it will unpack to zero or more items. That means it could potentially match any of several overloads. In this event, pyright picks the first overload that potentially matches. That happens to be the first one, which has a return type of `Future[tuple[()]]`.

So I think pyright is doing the right thing here given the type information provided.

I can offer a few suggested workarounds.

1. Avoid using an unpack operator if possible here.
2. If you want to use an unpack operator, switch from a list to a tuple with a statically-specified length. Pyright can then determine how many positional arguments the unpack operator will produce.

**Comment by exherb** [comment]
OK, thanks
