### ISSUE TITLE
Pyright generates unclear error message when using `__class_getitem__`

### ISSUE THREAD

**Issue by yaxum62** [microsoft/pyright#3660]
When defining a classwith `__class_getitem__` method to mimic typing.Generic, pyright generates a seemingly unrelated error message at such class is used. 

Consider following example:
```python
class MyList:
    def __class_getitem__(cls, arg: type) -> types.GenericAlias:
        return types.GenericAlias(cls, (arg,))

```

When using that list for annotate a generic function, Pyright generates a error:

```python
T = TypeVar("T")
def func(l: MyList[T])  -> T:
#                          ^ TypeVar "T" appears only once in generic function signature
  ...
```

I know this is a little beyond the scope, but such practice is already well defined by python doc ([1](https://docs.python.org/3/reference/datamodel.html#object.__class_getitem__)) ([2](https://docs.python.org/3/library/stdtypes.html#generic-alias-type)) and widely used in cpython built-in types like `list.__class_getitem__` and `dict.__class_getitem__`.

If custom `__class_getitem__` is not supported, a more reasonable error message would be helpful, something like `Expected class type but received runtime GenericAlias` when using `MyList[T]` as type hint.

**VS Code extension or command-line**
vscode extension pylance v2022.6.30

**Comment by erictraut** [comment]
This isn't supported, and it's a very niche use case. See [this documentation](https://docs.python.org/3/reference/datamodel.html#the-purpose-of-class-getitem) which recommends that you inherit from stdlib classes that implement `__class_getitem__` rather than implementing it yourself.

Closing the issue because I don't think it's worth addressing.
