### ISSUE TITLE
TypeVars cannot be assigned to each-other through `ParamSpec`

### ISSUE THREAD

**Issue by thesadru** [microsoft/pyright#3671]
```py
import typing

P = typing.ParamSpec("P")
T = typing.TypeVar("T")

class Stuff(typing.Generic[P, T]):
    def __init__(self, callback: typing.Callable[P, T]):
        self.callback = callback

    def method(self, *args: P.args, **kwargs: P.kwargs) -> T:
        return self.callback(*args, **kwargs)

def foo(obj: T) -> T:
    ...

def bar(obj: T) -> T:
    # Expression of type "T@foo" cannot be assigned to return type "T@bar"
    #   Type "T@foo" cannot be assigned to type "T@bar"
    return Stuff(foo).method(obj)
```

**Comment by erictraut** [comment]
I think the current behavior is correct.

Type variables must be "solved" in the context of the scope in which they are declared. In your example, type variable `T@foo` is scoped to `foo`, so it must be solved in the context of `foo` — i.e. through a call to `foo`. You are using `T@foo` to parameterize class generic class `Stuff`. But `T@foo` is no longer in scope when you call `method`, so there's no way to solve it when calling `method`.

Pyright does make one exception to the "type variable must be in scope" rule — in the case where a function returns a `Callable` type that includes a type variable that appears nowhere else in the function signature outside of the return type annotation.

```python
def func1() -> Callable[[T], T]: ...
```

In this case, `T` is assumed to be scoped to the `Callable` rather than to `func1`, so it can be solved later when the callable is used in a call expression.

But your example is quite different. The type variable `T@foo` is clearly out of scope at the point where `method` is called.
