### ISSUE TITLE
Make `dataclass_transform` respect return type.

### ISSUE THREAD

**Issue by BlueGlassBlock** [microsoft/pyright#3677]
**Is your feature request related to a problem? Please describe.**
Currently most of dataclass decorators return `Callable[[Type[_T]], Type[_T]`, however, some solutions like `pydantic.dataclasses` returns a `Callable[[Type[Any]], Type[MixinDataclass]]` to add custom properties. Since Python currently doesn't have an easy way to declare something like `SubType[T, MixinDataclass]`, pyright could treat it in a better way.

**Describe the solution you'd like**
```py
if TYPE_CHECKING:
    DataclassT = TypeVar('DataclassT', bound='Dataclass')

    class Dataclass:
        __my_info_field__: ClassVar[List[str]]

        @classmethod
        def __validate__(cls: Type['DataclassT'], v: Any) -> 'DataclassT':
            pass

@dataclass_transform(kw_only_default=True)
def my_data(
    *,
    init: bool = True,
    repr: bool = True,
    eq: bool = True,
    order: bool = False,
    unsafe_hash: bool = False,
    frozen: bool = False,
    config: Type[Any] = None,
) -> Callable[[Type[Any]], Type['Dataclass']]: # here we treat it as a (cls: Type[T]) -> SubType[T, 'Dataclass']
# SubType[T, 'Dataclass'] means it "inherited" from both.
    ...
@my_data(eq=True)
class V:
    a_field: str
inst = V(a_field="string")
inst.a_field # str
V.__my_info_field__ # List[str]
V.__validate__({"a_field": "string"}) == inst # True
```

**Additional context**

**Comment by erictraut** [comment]
The `dataclass_transform` mechanism is meant to apply a transform to a decorated class according to dataclass semantics. It is not meant to return some other class unrelated to the class that it's decorating, as in your example above. It wouldn't make sense to apply dataclass behaviors to `V` and then ignore the modified `V` and return a completely different class `Dataclass` in its place. That would defeat the purpose of the `dataclass_transform`.

The `dataclass_transform` mechanism is defined by [PEP 681](https://peps.python.org/pep-0681/). If you would like to propose changes or additions to it, please do so in the context of the [typing-sig mailing list](https://mail.python.org/archives/list/typing-sig@python.org/) or the [python/typing discussions forum](https://github.com/python/typing/discussions). I think it's unlikely that what you're proposing here would be adopted as a standard because it appears to be pretty hacky, and the semantics are unclear.

If I understand your intent, you want to indicate that your decorator is transforming a class in a manner that goes beyond what a normal `@dataclass` decorator does, such as adding additional class attributes. That goes beyond the purpose and intent of the `dataclass_transform` mechanism.

**Comment by BlueGlassBlock** [comment]
Thanks, I think using class inheritance might be enough, and maybe function based transformations shouldn't overlap the ability that class inheritance based transformation provides (according to the Zen of Python) :)
