### ISSUE TITLE
inspect.isawaitable not respected

### ISSUE THREAD

**Issue by aersamkull** [microsoft/pyright#3690]
**Is your feature request related to a problem? Please describe.**

The following code is an error though I'd expect it to work:
```python
from typing import Awaitable, Union
import inspect


a: Union[Awaitable[str], str] = "asd"


async def test():
    if inspect.isawaitable(a):
        i = await a
    else:
        i  = a
    i.upper() # Error here because type guard is not understood
```

**Describe the solution you'd like**
It should understand the if inspect.isawaitable Type Guard

**Additional context**
Python 3.9
Windows
Pyright 1.1.259

Would be really awesome for pyright to support this fancy stuff ;)

**Comment by erictraut** [comment]
Yes, as Jelle explained, this is the expected behavior in this case.

**Comment by Pwuts** [comment]
It would be safe to treat `inspect.isawaitable` like:

```python
def awaitable(object: Awaitable[T] | T) -> TypeGuard[Awaitable[T], T]
```
right?

At the moment, it behaves like:
```python
def awaitable(object: object) -> TypeGuard[Awaitable[Any]]
```
which means when I pass in a variable of type `str | Awaitable[str]`, it will come out as either `Any` or `Awaitable[Any]`, losing typing information which is undesirable.

**Comment by erictraut** [comment]
`TypeGuard` accepts only a single type argument, so `TypeGuard[Awaitable[T], T]` is an illegal annotation. Perhaps you mean `def awaitable(obj: Awaitable[T] | object) -> TypeGuard[Awaitable[T]]: ...`?

It's kind of moot at this point because `inspect.isawaitable` was recently changed in typeshed to use the new `TypeIs`, which nicely solves your problem.

```python
def isawaitable(object: object) -> TypeIs[Awaitable[Any]]: ...
```

Code sample in [pyright playground](https://pyright-play.net/?code=GYJw9gtgBAlgdgZwA4FMDGAXWElhFmBAQwHciYMiAjAGxQFgAoUSKDATyXgHNtd8oAQTIVqdJkwAmKYFGABXOGgAUADwBcUBBhBQAPkJGVaKANraQAXQCU6plAexZhUuWN01t%2B458gUANxQiGgB9DlRPKABiQzcxMwtLbwcUGgQUO0YfXwCg0PCUSJiLJiA)

```python
from inspect import isawaitable
from typing import Awaitable

def func(x: str | Awaitable[str]):
    if isawaitable(x):
        reveal_type(x) # Awaitable[str]
    else:
        reveal_type(x) # str

```
