### ISSUE TITLE
Strange behavior of typeguard

### ISSUE THREAD

**Issue by thesadru** [microsoft/pyright#3740]
Either the type is not fully inferred (maybe a typeshed bug?) or left in its original state.

```py
import typing
import inspect

def func(x: typing.Union[int, typing.Awaitable[int]]) -> None:
    if inspect.isawaitable(x):
        reveal_type(x)  # Type of "x" is "Awaitable[Any]"
    else:
        reveal_type(x)  # Type of "x" is "int | Awaitable[int]"
```

**Comment by erictraut** [comment]
What part do you think is incorrect here? It looks correct to me. I'm not sure what you mean by "left in its original state". Are you referring to the type narrowing behavior in the "else" clause? If so, that's by design. `TypeGuard` does not perform narrowing in the negative case. For details, refer to [PEP 647](https://peps.python.org/pep-0647/).

**Comment by thesadru** [comment]
Ah, that is unfortunate. What is supposed to be done in those cases though? I often happen to need to check `if not isawaitable()` in my code and casts are making it fairly hard to read.

I do not think `Awaitable[Any]` should have `Any`. Shouldn't it be `int` instead?

**Comment by erictraut** [comment]
The typeshed stub explicitly specifies `Awaitable[Any]`. If you think that should be different, please file a bug or a PR in the typeshed repo.
