### ISSUE TITLE
Literal from string library now a LiteralString, cannot be indexed

### ISSUE THREAD

**Issue by ntaylorwss** [microsoft/pyright#3786]
**Describe the bug**
This is as much a question as a bug report.

With a recent update to PyRight, this basic functionality has started raising an error:
```
import string

string.ascii_lowercase[0]
```
`"__getitem__" method not defined on type "LiteralString`

I'm trying to understand a couple things:

- When I reproduce by creating a variable `S = "abc"` and trying to access an element of that, it works fine because S is a Literal["abc"]. The string standard library does not annotate `ascii_lowercase`, so why is it not a Literal["abcdef..."]?
- Why in general can I not access elements of a LiteralString? I couldn't find any mention of this in PEP 675.
- If I edit the example to `S: LiteralString = "ABC"` and reveal_type on S, it still says it's a Literal["ABC"]. Yet, if I open a different file and import S from this module, it becomes a LiteralString. What is happening there?

**Comment by erictraut** [comment]
A `LiteralString` is the union of all `Literal` `str` types. Obviously, there's a limitless number of such literal strings, so there's no way to enumerate them all. A `LiteralString` should be assignable to a `str`, and it should support all of the same methods as a `str`. The error you're seeing here with `__getitem__` is a bug.

The statement `S: LiteralString = "ABC"` declares the type of `S` to be `LiteralString`, but it also performs local type narrowing based on the assigned value. The type `Literal['ABC']` is narrower than `LiteralString` (which is narrower than `str`). When you use `reveal_type`, it displays the type of the symbol _at that point in the code flow_, including any type narrowing that has been applied to it. That's why you're seeing a revealed type of `Literal["ABC"]`. If you open a different file and import S from this module, local type narrowing doesn't apply (unless, of course, you use a local assignment to reassign the value to a literal str value).

**Comment by ntaylorwss** [comment]
Thanks for the detail as always!

**Comment by erictraut** [comment]
This will be addressed in the next release.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.266, which I just published. It will also be included in a future release of pylance.
