### ISSUE TITLE
`x is Ellipsis` doesn't narrow `x`'s type

### ISSUE THREAD

**Issue by GrantGryczan** [microsoft/pyright#3829]
**Describe the bug**

If a variable's type is a union that includes the ellipsis type, then checking if the variable `is ...` or `is Ellipsis` doesn't do anything.

Currently you have to `from types import EllipsisType` and then use `isinstance(x, EllipsisType)` instead, which is a bit less readable, and it makes it confusing to readers why the developer wouldn't just use `x is ...` or `x is Ellipsis` instead.

**To Reproduce**

```py
x = random.choice([..., 2])
reveal_type(x)  # ellipsis | int
if x is ...:
    reveal_type(x)  # ellipsis | int
else:
    reveal_type(x)  # ellipsis | int
```

**Expected behavior**

```py
x = random.choice([..., 2])
reveal_type(x)  # ellipsis | int
if x is ...:
    reveal_type(x)  # ellipsis
else:
    reveal_type(x)  # int
```

**VS Code extension or command-line**

VS Code extension: Pylance v2022.8.20

**Comment by erictraut** [comment]
This is expected behavior. The `x is ...` expression pattern is not currently a supported type guard pattern. For a full list of supported patterns, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards).

Each new type guard pattern requires custom logic that must be implemented and maintained. We do occasionally add support for new patterns but only in cases where we have evidence that it's a commonly-used pattern. I've never seen this particular pattern used before, and I think it's quite uncommon. As further evidence that it's not common, mypy also doesn't support this type narrowing pattern.

I'm going to close this feature request for now, but we might reconsider it in the future if the issue receives a sufficient number of upvotes (in the form of thumbs-up reactions).

In the meantime, you can easily work around the issue above by changing your code to:
```python
    if isinstance(x, int):
        reveal_type(x)  # int
    else:
        reveal_type(x)  # ellipsis
```

**Comment by GrantGryczan** [comment]
Just so you know, the example I gave was just a minimal example, and in reality, the type I'm using is more complicated than `EllipsisType | int` and has lots of aliases in it, and I have an early `continue`, not an `else`.

**Comment by Andrej730** [comment]
For anyone coming across this, support for this was added in https://github.com/microsoft/pyright/releases/tag/1.1.288
