### ISSUE TITLE
Version 1.1.268 complains about unknown jax members

### ISSUE THREAD

**Issue by JulianGoeltz** [microsoft/pyright#3882]
**Describe the bug**
Pyright@1.1.268 complains about unknown member of `jax.numpy` arrays. This was not the case for the previous version 1.1.267.

**To Reproduce**
Install pyright and jax and execute and check a MWE like [here](https://github.com/JulianGoeltz/MWE_pyright_20220830/blob/main/src/test.py)
The test of this file with the two pyright versions can be seen [here for 1.1.267](https://github.com/JulianGoeltz/MWE_pyright_20220830/runs/8101437117?check_suite_focus=true) and [here for 1.1.268](https://github.com/JulianGoeltz/MWE_pyright_20220830/runs/8101436979?check_suite_focus=true)

```python
#!python
"""Testing"""
import jax
import jax.numpy as jnp


x = jnp.arange(5)
print(x.shape)

y  = jnp.arange(5).shape
print(y)

z = jnp.array([3, 4])
print(x[0])
```

**Expected behavior**
I expect there to not be an error reported, as the `shape` member is a regular member of a `DeviceArray`. This was the observed behaviour with pyright@1.1.267.

**Screenshots or Code**
see above.
I used the newest `jax` (version 0.3.16) but it also doesn't work with one older version ([0.3.5](https://github.com/JulianGoeltz/MWE_pyright_20220830/runs/8101388270?check_suite_focus=true))

**~~VS Code extension or~~ command-line**

**Additional context**
I hope this is the correct way to report this, and that it is not a problem of `jax`, but the fact that it worked with the previous version makes me believe it is unwanted behaviour.
I looked quickly through the release of 1.1.268 but didn't make anything out that could be the problem.

**Comment by erictraut** [comment]
In pyright 1.1.268, I increased a constant that specifies a "code complexity threshold" for return type inference. Beyond this threshold, pyright will not attempt to infer the return type of a function that lacks a return type annotation. 

The jax library claims to be typed (i.e. it has a "py.typed" marker), but many of its functions lack return type annotations. The `jax.numpy.arrange` function is one such example. Because 1.1.268 had a lower code complexity threshold, it didn't attempt to analyze this function and infer the return type. Instead, it assumed a return type of `Unknown`. With the higher threshold, its return type is now inferred. This is generally good, but it can lead to additional type violations like the ones you're seeing. This isn't a bug, it's a feature. :)

The real problem here is that jax is missing type information. When I run `pyright --verifytypes jax`, I receive this summary:

```
Symbols exported by "jax": 3957
  With known type: 1371
  With ambiguous type: 422
  With unknown type: 2164

Type completeness score: 34.6%
``

That's a pretty low percentage. The jax maintainers have made some good progress, but they have significant work to do still before the library is fully annotated.

**Comment by wookayin** [comment]
On JAX's side: see https://github.com/google/jax/issues/6743. It's quite complicated issue in JAX, and the roadmap is going to span over a long-term future...
