### ISSUE TITLE
Fails to lint commands split to multiple lines

### ISSUE THREAD

**Issue by thomasnal** [microsoft/pyright#3906]
**Describe the bug**
See the screenshot.
![image](https://user-images.githubusercontent.com/17355467/188288206-32750fd9-817a-48c1-9432-b6b9b6bfd034.png)

**Comment by erictraut** [comment]
I can't tell what I'm looking at in this screen shot. I'm happy to look at an issue if you provide a minimal self-contained code sample and clear details about what you expect to see versus what you're seeing. If your sample relies on imports from other libraries, please provide the versions of those libraries. I'm going to close this issue because it doesn't contain the details requested in our issue template. Feel free to open a new one.
