### ISSUE TITLE
#pyright: ignore for a whole imported modules

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [microsoft/pyright#3909]
I'm in the process of rewriting a project from scratch and would like the project to be strictly typed everywhere however the project uses NumPy a lot. 
This is an issue as noted in #1717, as NumPy only has ~15% (now up to 27%) coverage therefore `reportUnknownMemberType` errors occur a lot.

In #1717, there are a couple of recommended solutions but I would like to just turn off pyright for only NumPy. 
My propose is to allow `import X  #pyright: ignore` that makes pyright ignore all type warnings from module X.

Reading through the [comments documentation](https://github.com/microsoft/pyright/blob/main/docs/comments.md), only file or line ignore support exists currently and I couldn't find an issue that requests this already.

I understand this is radical request to be able to turn all type hinting for a module but I would prefer this to having to add "#pyright ignore" to every other line in cases and for non-numpy type issues to be missed.

**Comment by erictraut** [comment]
I understand what you're trying to do, but a `# pyright: ignore` comment on the import line isn't an appropriate solution. It would be inconsistent with how `# pyright: ignore` works elsewhere (which is both a problem for consistency and for a potential implementation). 

It also wouldn't make sense given how types are analyzed. Diagnostic errors are the result of type analysis, and types are propagated and mutated (narrowed, generated through TypeVar solving, combined into unions, etc.) through the type checking process, so there's no way to track a type back to a particular import statement.

If you want your project to be strictly typed everywhere — and have confidence that your code is type safe, you're going to need to provide the missing type information in the form of your own type stubs. This is needed only the functions, classes and methods that your project happens to use, not the entire library. For example, your project probably uses a very small subset of numpy's classes and methods. This is the technique I use for my team's ~250K-line source base. It's strictly typed with no typing checking holes because we've built up our own local type stubs for the library classes and methods that we consume.

If you don't want to invest time in creating your own local stubs, the next option I can suggest is to write type stubs for numpy that simply resolve all numpy types to `Any`. This will eliminate errors in strict mode, but it will leave you vulnerable to type errors — and give you a false sense of confidence that your code is actually type safe. Anywhere an `Any` type is used, it will effectively "blind" the type checker.

Here's how you would do this:
```python
# typings/numpy/__init__.pyi
def __getattr__(name: str) -> Any: ...
```

If neither of those ideas are appealing to you, I recommend abandoning the idea of using strict type checking in your project. Stick with basic type checking rules plus a few select strict-mode rules that you enable manually. You just won't be able to enable the `reportUnknownXYZ` family of diagnostic rules. For a full list of rules, refer to [this table](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#diagnostic-rule-defaults).

**Comment by pseudo-rnd-thoughts** [comment]
Looking at the problem more, I think the issue is with numpy as the type studs that numpy has do not satisfy the pyright strict mode. 
Before raising an issue for numpy, I just want to check that my understanding is correct. 

When using a numpy function, pyright strict raises an error saying `UnkownMemberType` 
```
Type of "issubdtype" is partially unknown
  Type of "issubdtype" is "(arg1: dtype[Any] | type | _SupportsDType[dtype[Any]] | str | Tuple[Any, int] | Tuple[Any, Unknown | Sequence[Unknown]] | List[Any] | _DTypeDict | Tuple[Any, Any] | None, arg2: dtype[Any] | type | _SupportsDType[dtype[Any]] | str | Tuple[Any, int] | Tuple[Any, Unknown | Sequence[Unknown]] | List[Any] | _DTypeDict | Tuple[Any, Any] | None) -> bool"
```

For example, with a local copy of numpy, if I add `pyright: strict` at the top of [fromnumeric.pyi](https://github.com/numpy/numpy/blob/main/numpy/core/fromnumeric.pyi) then a large number of issues appear.  

I attempted to solve this issue by writing my own `.pyi` files to be used as well. But I don't think that I did them correctly.

**Comment by erictraut** [comment]
Are you sure you're using the latest version of numpy (1.22.4)? I wouldn't expect to see the error above with the latest version, so I suspect that you're using an outdated version. The numpy maintainers have been diligently adding more type information over time.

If you right click on `issubdtype` and choose "Go To Declaration", it should take you directly to the type declaration in the numpy type stub. It should look like this:
```python
def issubdtype(arg1: DTypeLike, arg2: DTypeLike) -> bool: ...
```
And if you now show the declaration for `DTypeLike`, it should look like this:
```python
DTypeLike = Union[
    DType[Any],
    None,
    Type[Any],
    _SupportsDType[DType[Any]],
    str,
    _VoidDTypeLike,
]
```
That doesn't match what I'm seeing in the error message you posted above.

Some additional details... When you use `# pyright: strict`, you are effectively enabling a bunch of diagnostic rules, many of which are disabled by default. The table I linked to above lists which diagnostic rules are enabled in strict mode. It includes several rules whose names start with `reportUnknown...`. These are the rules that will cause you problems if you use a library that claims to be typed but is missing some type annotations for symbols that you are using. If a parameter is missing an annotation or a type argument for generic classes is omitted, pyright assumes the type is `Unknown`. The `Unknown` type is the name that pyright gives to an implicit `Any` type (as opposed to an `Any` that appears explicitly in a type annotation).

**Comment by Telofy** [comment]
I can see that a `# pyright: ignore` statement next to the import won't work and would be unintuitive. That was my first idea too. But how about a setting in a configuration file with a list of modules, paths, or glob patterns to define the parts of the code (third-party libraries) where `Unknown` should be assumed to be `Any`?

I think I would just use strict mode for my own code and define the whole of `side-packages` as `Unknown == Any` territory. That would come with all the drawbacks you describe, but it still feels like a decent trade-off compared to the effort that would go into creating the stub files.
