### ISSUE TITLE
False positive on PEP 604 inside `TYPE_CHECKING` block

### ISSUE THREAD

**Issue by PerchunPak** [microsoft/pyright#3961]
**Describe the bug**
If we use `|` with `__future__.annotations`, pyright will ignore that we are in `TYPE_CHECKING` block.

**To Reproduce**
```
$ cat file.py
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    a = str | int
$ cat pyrightconfig
{
  "pythonVersion": "3.9"
}
$ pyright file.py
Loading configuration file at C:\Users\perch\Desktop\programming\mcstatus\pyrightconfig.json
Assuming Python platform Windows
stubPath C:\Users\perch\Desktop\programming\mcstatus\typings is not a valid directory.
Searching for source files
Found 1 source file
pyright 1.1.270
C:\Users\perch\Desktop\programming\mcstatus\file.py
  C:\Users\perch\Desktop\programming\mcstatus\file.py:6:13 - error: Alternative syntax for unions requires Python 3.10 or newer
1 error, 0 warnings, 0 informations
Completed in 0.518sec
```

**Expected behavior**
No error to happen.

**Comment by erictraut** [comment]
This is intended behavior, not a bug. The `TYPE_CHECKING` symbol is a way to "lie" to the type checker. Pyright analyzes all code under `TYPE_CHECKING` checks as though they are executed at runtime. 

I strongly discourage the use of `TYPE_CHECKING` conditionals in your code because you are lying to the type checker, which means that you're vulnerable to false negative errors that will result in issues at runtime. If you can avoid using `TYPE_CHECKING`, that's strongly advised.
