### ISSUE TITLE
various issues around watching file changes

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pyright#398]
I am not sure whether live update on file/directory changes outside editor is main supported scenario or not (since in many cases, it is one of scenarios that creates perf issues without much benefit compared to explicit refresh/reload command especially for third party code such as libraries), but it looks like pyright has code to detect such situation, so opening this bug.

there seems to 2 ways to track changes live
one is https://github.com/microsoft/pyright/blob/f6ebcd9243ac3bb004a49467e2afabd04c595e53/server/src/analyzer/service.ts#L127 or
https://github.com/microsoft/pyright/blob/f6ebcd9243ac3bb004a49467e2afabd04c595e53/server/src/analyzer/service.ts#L555

and the other is
https://github.com/microsoft/pyright/blob/f6ebcd9243ac3bb004a49467e2afabd04c595e53/server/src/analyzer/service.ts#L703

but I still couldn't figure out how to start pyright server or attach to existing one, so couldn't debug through yet.

...

anyway, one of example around file watch is this
microsoft/python-language-server#944

it looks like pyright didn't watch directory name changes even if it can affect semantic of other dependent modules.

and I am not sure what is workaround (triggering rescan) except opening folder in vscode again.

**Comment by erictraut** [comment]
Yes, this is a supported scenario, although I've been having a lot of problems with the file system watcher implementation on MacOSX lately — it's causing lots of performance and stability issues. Detection of live updates outside of the editor is less important for the VS Code extension, but it's most important for the command-line version of pyright, which supports a "watch" mode (similar to the watch mode supported by the typescript compiler).

Pyright installs file system watchers on the pyrightconfig.json file. It also installs a recursive file system watcher on each root directory provided in the "include" section of the config file (or the root directory of the workspace if no include section is provided). See `_createDirectoryWatcher` for details.

The method `markFilesChanged` is no longer used. I'll delete it.

The method `_updateTrackedFileList` updates the list of files that are part of the "program". Depending on whether the `markFilesDirtyUnconditionally` is true, it marks all files dirty (i.e. requiring reparsing). If this parameter is false, only files whose contents have changed are marked dirty. It's necessary to mark all files dirty when something occurs that can affect every file (e.g. config file updates).

The method `_updateSourceFileWatchers` is called when one or more of the file system watchers is potentially obsolete. This can occur when the config file changes (e.g. the user updates the "include" section of the config).

You're correct that the code doesn't currently provide any special-case handling for directory name changes or deletions. This would be relatively straightforward to add since the file system watcher provides different event types. We could call `this._updateTrackedFileList(true);` if we see such an event. We'd also need to call `this._importResolver.invalidateCache();` since the import resolver cache is no longer valid when directories change.

If you think this is an important scenario to handle, feel free to submit a PR. Or if you'd prefer, I can make the change.

**Comment by erictraut** [comment]
> but I still couldn't figure out how to start pyright server or attach to existing one, so couldn't debug through yet.

You can launch an instance of the pyright extension in debug mode by hitting F5. Once it's launched, you can attach the debugger to the server instance. Just go to the debug menu at the top of the debug panel and choose "Pyright Language Server", then press the play button to attach. A this point, you should be able to set breakpoints anywhere in the server, step through the code, etc. Let me know if you're not able to get it to work.

**Comment by erictraut** [comment]
Closing this ticket for now. If there are specific enhancements or bugs relating to file watching, let's split them out into their own tickets.
