### ISSUE TITLE
Few errors in the VSCode console when switching between files

### ISSUE THREAD

**Issue by kinow** [Microsoft/pyright#4]
Hi,

Installed VSCode to try out pyright. Then opened the folder of [the project I am currently working](https://github.com/cylc/cylc/). Installed the Python extension, and then pyright latest version from git (i.e. installed by choosing the binary created after `npm run package`).

I noticed now that when I open a file, like `lib/cylc/__init__.py` for instance, the VS Code console says

```
/home/kinow/Development/python/workspace/cylc/lib/cylc/__init__.py opened.
file:///home/kinow/Development/python/workspace/cylc/lib/cylc/__init__.py closed.
[Error - 6:37:33 PM] Notification handler 'textDocument/didClose' failed with message: Cannot read property 'isTracked' of undefined
```

When I open another file such as `lib/cylc/network/__init__.py`, sometimes it says:

```
/home/kinow/Development/python/workspace/cylc/lib/cylc/network/__init__.py opened.
file:///home/kinow/Development/python/workspace/cylc/lib/cylc/network/__init__.py closed.
```

But sometimes after opening other files first, it says:

```
/home/kinow/Development/python/workspace/cylc/lib/cylc/network/__init__.py opened.
Error performing analysis: {}
file:///home/kinow/Development/python/workspace/cylc/lib/cylc/network/__init__.py closed.
[Error - 6:40:26 PM] Notification handler 'textDocument/didClose' failed with message: Cannot read property 'isTracked' of undefined
```
I suspect there is some state data being kept between files opened in the editor, and switching between files seems to trigger some case where the previous object is `undefined`?

Had a look at the code, and was going to try to write a test, but `npm run test` in the `/server/` folder is failing for me.

Thanks for pyright BTW!

Cheers
Bruno

**Comment by kinow** [comment]
Haven't had time to learn how to debug the server and connect the client from VSCode, but that should be doable I assume.

So resorted to the ol' `console.log` everywhere.

```
BRUNO SAYS fileInfo2: [object Object]
BRUNO SAYS fileInfo2: [object Object]
BRUNO SAYS fileInfo1: undefined
[Error - 7:03:13 PM] Notification handler 'textDocument/didClose' failed with message: Cannot read property 'isTracked' of undefined
```

So apparently the server `program.ts` may receive a call to `_isFileNeeded(fileInfo)` with a null `fileInfo`.

Found a few usages, but without a debugger attached and without knowing more how the code works, I am not able to pinpoint where it is coming from.

Just in case that helps,
Bruno

**Comment by erictraut** [comment]
Thanks for the report. I downloaded your project, and I'm not able to repro what you're seeing. 

Are you using a recent version of VS Code? I'm using 1.32.3. That's probably not the issue, but I figured I'd ask.

It might be worth installing the VS Code extension from the marketplace to see if that resolves your problem. I just published 1.0.1 from the master sources an hour ago. 

The opened/closed console logs are printed when the Pyright language server receives an open or close message from VS Code. Opens typically occur when you first bring a tab to the foreground. VS Code also temporarily opens and closes files to follow declarations (e.g. if you press command/control while hovering over an externally-defined symbol in the editor).

The "Error performing analysis" message is the most troubling because it means a fatal condition occurred in the bowels of the type analyzer. I'd like to figure out what's causing that.

**Comment by erictraut** [comment]
You should be able to debug the client by opening the Pyright sources in VS Code and pressing F5. That will launch a second copy of VS Code and attach the debugger to it. Then go to the debug panel and find the popup at the top. Select "Pyright Language Server" and press the green debug triangle. That will attach a separate debugger instance to the server process.

**Comment by erictraut** [comment]
Ah, I just found the cause of the "textDocument/didClose" error. Fix will be coming shortly.

**Comment by kinow** [comment]
Tried that, but it complained about the missing `launch` configuration I think. I'm using another IDE (former Java developer - Eclipse, now working on Python - PyCharm). Might need to spend a bit longer learning more about VSCode before I have the development environment.

But the docs so far have been great, and the code structure is not really complicated. Kudos! :clap:

**Comment by kinow** [comment]
>Ah, I just found the cause of the "textDocument/didClose" error. Fix will be coming shortly.

Brilliant! Thanks!
