### ISSUE TITLE
Infer type of function that is a `TypeGuard` based on the argument

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#4044]
**Is your feature request related to a problem? Please describe.**
We'd like to test if a function annotated as `TypeGuard[some_type]` has a value of `True` when an object of `some_type` is passed.
```python
from __future__ import annotations

from typing_extensions import TypeGuard, reveal_type


def fun(x: int | str) -> TypeGuard[int]:
    return isinstance(x, int)


reveal_type(fun(3))
reveal_type(fun("abc"))
```
I would have expected the type of `fun(3)` to be `Literal[True]` and the type of `fun("abc")` to be `Literal[False]`, but pyright says that both of them are `bool`

For testing purposes in the pandas stubs, we would use `assert_type(fun(3), Literal[True])` 

**Describe the solution you'd like**
Narrowing of the type of the function to `True` or `False`, when possible

**Comment by erictraut** [comment]
I think you are misunderstanding how `TypeGuard` works. The decision of whether to return `True` or `False` is determined by the logic in the type guard function. If the type guard function returns `True`, then the runtime logic is indicating the type of the first argument can be narrowed to the `TypeGuard` type.

The type of any call to `fun` will statically evaluate to `bool`. After all, that function's logic is allowed to return either `True` or `False`. There's no way for a static type analyzer to know differently because it doesn't actually execute the code within the type guard function.

If you want to test the type guard, you will need to write a unit test for it that determines whether its logic produces `True` or `False` under the correct conditions.
