### ISSUE TITLE
Completion on modules in import statement suggests folders that are not modules

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/pyright#405]
**Describe the bug**
Completion on modules in import statement suggests folders that are not modules.
![image](https://user-images.githubusercontent.com/12820357/70554964-ff136f80-1b32-11ea-8e3a-9953c57050c7.png)

**To Reproduce**
Install versioned module like numpy, scipy, etc. Type `import s`, observe `dist-info` suggested.

**Expected behavior**
Only real modules should appear in the list.

**Comment by jakebailey** [comment]
The easiest thing is probably to never recognize modules with illegal names (dots, dashes), at least not during completion. You don't want to lock off module names with dashes wholesale due to people having scripts with dashes (which are unimportable but runnable), or untitled files with URIs like `untitled:Untitled-1`.

**Comment by MikhailArkhipov** [comment]
Well, you don't want to suggest `__pycache__` either...
![image](https://user-images.githubusercontent.com/12820357/70557574-ece80000-1b37-11ea-9118-075b119b1548.png)

**Comment by erictraut** [comment]
Good point. Here's a change. https://github.com/microsoft/pyright/commit/5b9a25cfad77425f9e8a15bd3f52087722d4264b

**Comment by jakebailey** [comment]
I'd also be checking for `-`, since that's also illegal. Just so I can understand it, the commit only affects suggestions, correct? (The modules wouldn't ever be able to resolve normally, since the parser would have already split them up tokenwise, I'd think.)

**Comment by MikhailArkhipov** [comment]
Technically there can be any folders. One of the cases if user has module `A` with subfolders `B` and `C` where `B` is a module and `C` is not (empty folder, some random data storage).  On the other hand, not sure if edge cases are interesting.

**Comment by erictraut** [comment]
OK, makes sense that we should exclude hyphens. https://github.com/microsoft/pyright/commit/126a0fb0a067e8d898722f6122f8c8ca1a0c5615

Jake, you're correct that this commit affects only suggestions. The logic is in the "importResolver" module because it's similar to (and uses common subroutines with) the logic that resolves imports.

**Comment by jakebailey** [comment]
Yeah, I was also going to mention completely empty directories, but you'd have to recursively check to see if there is actually an importable path (since you can have a deeply nested python file that's importable without there being any `__init__.py`s or similar in the tree above. Probably more expensive and I can't recall off the top of my  head how MPLS does this.

**Comment by jakebailey** [comment]
Actually, empty is easy (if there's nothing, then there's nothing), it's if you wanted to handle cases where a directory contains files but not python code (and thus wouldn't be imported).

**Comment by MikhailArkhipov** [comment]
MPLS scans the entire structure off all supplied roots and locates importable things. See PathResolverSnapshot.

**Comment by erictraut** [comment]
Does it do the scan at the time the completion is being resolved? Latency is critical for completions, so there's a tradeoff to consider between accuracy and responsiveness.

**Comment by jakebailey** [comment]
Maybe I'm misreading that part our code (more of Alex's wheelhouse), but I'm not sure if it does an immediate scan of the world; we have a "path resolver snapshot", which is an immutable structure that starts with search paths, and changes over time when you give it files to add to the structure (returning the module path, and new snapshot with the correct state). I think that when you go to resolve something is when the work is done (any FS accesses), from my reading. Willing to be wrong.

**Comment by MikhailArkhipov** [comment]
It scans at start time and each time search paths change or file watcher discovers changes to libraries (such as when `pip install` happens).

Basically this:
https://github.com/microsoft/python-language-server/blob/master/src/Analysis/Ast/Impl/Modules/Resolution/ModuleResolutionBase.cs#L108

coming from
https://github.com/microsoft/python-language-server/blob/master/src/Analysis/Core/Impl/DependencyResolution/PathResolverSnapshot.cs

and ending in
https://github.com/microsoft/python-language-server/blob/master/src/Analysis/Core/Impl/DependencyResolution/PathResolverSnapshot.cs#L471

**Comment by erictraut** [comment]
This is now fixed in version 1.1.10, which I just published.
