### ISSUE TITLE
Support for setting `venv` at command line

### ISSUE THREAD

**Issue by sureshjoshi** [microsoft/pyright#4051]
**Is your feature request related to a problem? Please describe.**
I'm able to set the `venv-path` at the command line, but that value appears to be ignored in the event I don't have a configuration file + the `venv` field specified. 

I'm attempting to integrate `pyright` into [Pants](https://pantsbuild.org/) as a type checking plugin. It works great fantastically, with the exception of 3rd party dependencies. I'm unable to point at my pre-cached venvs without creating a "dummy" configuration file with the `venv` field (and nothing else), while I can set all the other fields I'm interested in at the command line.

Users can use their own configurations, of course - but I'd like to setup sane defaults and a command-line `venv` is the missing piece (unless there is a command line workaround?).

**Describe the solution you'd like**
Allow setting `venv` via the command line.

**Comment by erictraut** [comment]
This isn't how `venv` and `venv-path` are intended to be used, so I don't think it would make sense to add such a command-line option.

The `venv-path` configuration option is meant to allow individual developers to specify a machine-specific directory that they use for their virtual environments, whereas `venv` is meant to be a way for a common (shared) venv name to be shared across a group of developers. The `venv` therefore belongs in a configuration file, which is typically checked in to the repo. It wouldn't make sense to specify a different `venv` at the command line.

The more typical way to use virtual environments in pyright is to simply activate the desired venv before invoking the type checker. Since you know the full path of the venv you're targeting, could you use this approach?

**Comment by sureshjoshi** [comment]
Thanks for the quick reply!

> This isn't how venv and venv-path are intended to be used, so I don't think it would make sense to add such a command-line option.

This was the vibe I got reading through the other tickets - but I didn't know if a `venv` command line was off the table or not. 

I can take a look at activating the venv, but it's a bit tricky - with the `mypy` plugin, we specify the python executable shim, which discovers the fully qualified venv path and then uses that python interpreter/env. I didn't see an equivalent configuration here.

I can keep using my workaround for now - until I can come up with something better!
