### ISSUE TITLE
Default `None` parameters showing issue when not explicitly typed as Optional

### ISSUE THREAD

**Issue by nayaverdier** [microsoft/pyright#4052]
**Is your feature request related to a problem? Please describe.**
The core problem I am having is the following:
```python
def foo(s: str = None): ...
```

Which gives the following issue:
```
Expression of type "None" cannot be assigned to parameter of type "str"
  Type "None" cannot be assigned to type "str" (Pyright reportGeneralTypeIssues)
```

When I add this configuration to my pyproject.toml, it is no longer an issue:

```toml
[tool.pyright]
strictParameterNoneValue = false
```

However, I want to change this functionality globally rather than needing to specify in each of my projects.

I have also tried setting this in my `coc-settings.json` (I am using coc-pyright with vim) however it had no effect:
```json
  "python.analysis.diagnosticSeverityOverrides": {
    "strictParameterNoneValue": "none"
  }
```

Other issues that may be related:
- #233
- https://github.com/fannheyward/coc-pyright/issues/817

**Describe the solution you'd like**
I would like some way to globally disable Pyright issues appearing when a function parameter has a default of `None` but is not explicitly typed as `Optional` (but would like the type of that variable to implicitly be `Optional` for further type checking).

**Comment by erictraut** [comment]
The current behavior is intended. The behavior provided by `strictParameterNoneValue = false` is deprecated according to PEP 484, so you should not rely on it in your code. The option is provided only for older code bases that have not yet been converted to the new behavior. Since this was deprecated many years ago, such code bases should be increasingly rare. Eventually, we may remove support for `strictParameterNoneValue = false` altogether.

**Comment by sayyid5416** [comment]
@erictraut Basically, you are saying I should start writing like `def foo(bar: str | None = None):` instead of `def foo(bar: str = None):` ?
