### ISSUE TITLE
Argument inference for decorated function

### ISSUE THREAD

**Issue by betafcc** [microsoft/pyright#4057]
Pyright has a nice lookahead inference for inline lambdas [described here](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#lambdas)

That same inference is not present when we use decorator syntax instead of lambdas:

```python

def float_sort(comp: Callable[[float, float], bool]): ...

float_sort(lambda a, b: False if a < b else True) # inference works here

@float_sort
def compare(a, b):
    reveal_type((a, b)) # Type of "(a, b)" is "tuple[Unknown, Unknown]"
```

**Additional context**

Quite frequently I use decorators for 'providing context for known functions signature', eg:

```python
def provide_context_for_queriers(credentials: str):
    def _provide_context_for_queriers(f: Callable[[Context, int, str, bool], A) -> Callable[[int, str, bool], A]:
        return lambda *args: f(fetch_context(credentials), *args)

    return _provide_context

@provide_context_for_queriers(env['credentials'])
def query_api(context, row_count, table, ascending):
    ...
```

Which is a reasonably pythonic use for decorators, but without the inference, I have to repeat annotations frequently when using those, or do some verbose workaround like keeping a TypeVar with function signature and manipulation using `Concat` and `Unpack` operators.

**Comment by erictraut** [comment]
The current behavior is by design. 

By "argument inference", I think you mean type inference for parameters. For clarity, _arguments_ are passed to a call, and _parameters_ are symbols that are scoped to a function that receive the arguments at runtime.

What you're proposing here would violate a core assumption within pyright's design. The code within a function body is a separate "execution context" from the code that calls it, and execution contexts are analyzed independently from each other. Parameter types must therefore be know at the time the function's body is analyzed; they cannot be inferred based on the way the function is used.

Pyright uses type inference in the opposite direction from what you're suggesting. It uses the declared type of a parameter to influence the inference of the argument expression that corresponds to that parameter. This is called [bidirectional type inference](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#bidirectional-type-inference-expected-types).

Pyright uses a bunch of special-case logic to handle bidirectional type inference for lambdas. It does so by speculatively evaluating the lambda return expression — something that is very expensive but is required for lambdas because there's no way to declare parameter types. By "speculative", I mean that the results cannot be cached, and multiple iterations of evaluation are often required. For lambdas, the expense is not too great because a lambda involves a single expression, not an arbitrary number of statements. For functions defined with a `def` statement, it would be computationally very expensive (infeasibly so in many cases) to evaluate the types for the entire body in a speculative manner.

If you want to use static type checking for the body of a function, you should supply type declarations for its parameters.
