### ISSUE TITLE
Completions suggest keywords and modules after ...

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/pyright#407]
**Describe the bug**
Completions suggest keywords and modules after ...

**To Reproduce**
Type 
```python
def foo(): ...
```
**Expected behavior**
No completions after ...

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/12820357/70589540-cef4bc80-1b84-11ea-8126-7f808fc594e5.png)

**Comment by erictraut** [comment]
This is similar to #411. Closing as "won't fix" for the same reason.

**Comment by jakebailey** [comment]
I don't think this is exactly the same as #411. That one's about improving the keyword completion based on context, but this one is just about what comes after `...`, which should be nothing (since it's a constant, or at least constant-like; no value can be obtained by completing after `...`).

We fixed this in MPLS because our completion code got a completion request for `.` being typed, looked at the position, and since that's a weird place start returning a bad list. https://github.com/microsoft/python-language-server/pull/1344
