### ISSUE TITLE
Nested `TypedDict` doesn't work

### ISSUE THREAD

**Issue by stevenwdv** [microsoft/pyright#4070]
**Describe the bug**
I use [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) for VSCode and after v2022.10.30 (Pyright v1.1.275) it complains about nested `TypedDict` types. This seems like a bug to me; am I correct?

**To Reproduce**
```py
from typing import TypedDict
MyType = TypedDict('MyType', {'some_key': TypedDict('OtherType', {'other_key': int})})
# Pylance:                                ^ Illegal type annotation: call expression not allowed
```

**Expected behavior**
Accepted.

**VS Code extension or command-line**
Pylance v2022.10.30: Pyright v1.1.275

**Additional context**
It could be that this is intented behavior and that I need to create an alias for `OtherType` first, not sure.

**Comment by erictraut** [comment]
No, this is not a bug. Call expressions are not legal within type annotations. Mypy generates the same error in this case.

Nested TypedDicts are allowed, but you need to declare them like this:
```python
from typing import TypedDict
OtherType = TypedDict('OtherType', {'other_key': int})
MyType = TypedDict('MyType', {'some_key': OtherType })
```

**Comment by stevenwdv** [comment]
@erictraut Got it. It's a pity that the short nesting form isn't allowed and I don't really understand why `TypedDict` is defined to work differently than other types like `dict[...]` or `list[...]` which can be nested easily and don't require a name. I guess it's just because of compatibility with the class form.

**Comment by erictraut** [comment]
@tevenwdv, the reason you can refer to `dict` or `list` in an annotation is because those classes are already created and are declared elsewhere. You are simply referring to these existing classes by name in the type annotation. If you want to refer to a class that doesn't yet exist, you wouldn't be able to do so within a type annotation. You'd need to declare this new type elsewhere and then refer to it by name within your annotation. The `TypedDict` function call is a class declaration. It's creating a new class. Normally when you create a new class, you use the `class` keyword. `TypedDict` provides an alternate syntax for for this, but you can think of it as an equivalent to a `class` statement.

**Comment by stevenwdv** [comment]
@erictraut That makes sense, thanks. Same idea with `NamedTuple` then.
