### ISSUE TITLE
Importing a submodule doesn't initialize the parent module

### ISSUE THREAD

**Issue by Aran-Fey** [microsoft/pyright#4077]
**Describe the bug**
When importing a submodule, like `import foo.bar`, Pyright doesn't properly initialize the contents of `foo`.

**To Reproduce**
```python
import requests.exceptions

requests.Session  # error: "Session" is not a known member of module
```

**Expected behavior**
The import should be equivalent to `import requests`.

**VS Code extension or command-line**
Command line, version 1.1.276

**Comment by erictraut** [comment]
Yes, this is by design. The Python import loader has many implicit side effects, many of which cannot be modeled statically because they change based on temporal ordering. Pyright intentionally does not model any of these implicit side effects and considers it a bug if your code relies on them. If you want to use pyright to analyze your code, you'll need to make imports explicit. In the example above, that means including an `import requests` statement.

You may disagree with this principle, but but we're unlikely to change our stance on this point.
