### ISSUE TITLE
Applying transformations to `TypeVarTuple` before unpacking

### ISSUE THREAD

**Issue by ozars** [microsoft/pyright#4109]
Applying transformations to `TypeVar` is a common pattern. For example, it is used for converting a template object type to a template object instance:

```python
T = TypeVar("T")

def f1(tp: type[T]) -> T:
    return tp()
```

A similar behavior for `TypeVarTuple`s would be useful:

```python
Ts  = TypeVarTuple("Ts")

def f2(tps: tuple[Unpack[type[Ts]]]) -> tuple[Unpack[Ts]]:
    return tuple(tp() for tp in tps)
```

Current behavior as of 1.1.276:

```
type_trial.py:12:31 - error: TypeVarTuple not allowed in this context
type_trial.py:12:19 - error: Expected TypeVarTuple or Tuple as type argument for Unpack
```

Another example:

```python
def checked(val: T | None) -> T:
    assert val is not None
    return val

def f3(vals: Tuple[Unpack[Ts | None]]) -> Tuple[Unpack[Ts]]:
    return tuple(checked(v) for v in vals)
```

...and as usual thank you for such a great library!

**Comment by erictraut** [comment]
I'm not sure what you mean by "transform". The expression `type[T]` isn't really a transform. It's a specialization of a generic class `type`. The class `type` accepts a single type parameter. The expression `type[T]` provides a type argument `T` for that class. This expression form and its meaning are well defined and documented in PEP 484 and the type documentation.

The expression `type[Ts]` doesn't make sense because `type` accepts a single type parameter, and `Ts` is an unpacked variadic type var.

The behaviors of TypeVarTuple are spelled out clearly by [PEP 646](https://peps.python.org/pep-0646/), and pyright implements the documented behaviors. An earlier draft version of PEP 646 included a `Map` mechanism that might have a technique to accomplish what you're trying to do here, but `Map` was removed from the final version of PEP 646 because it was already very complex. There has been some discussion about adding `Map` back at some point.

If you would like to propose extensions to the Python type system, that would need to go through a similar standardization process including a draft PEP authoring, sponsorship, review and acceptance. If that's something you'd like to pursue, a good place to start is the [python/typing discussions forum](https://github.com/python/typing/discussions).
