### ISSUE TITLE
Some completions inside function call parameters are not applicable in the context

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/pyright#411]
**Describe the bug**
When typing inside function call parameters like `foo(a|)` completions come with suggestions like `await` or `abstractmethod` that are not applicable inside the list of parameters.

**To Reproduce**
- Define a function
- Type call to it

**Expected behavior**
Only completions that are applicable to the current context.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/12820357/70591467-2007af00-1b8b-11ea-834b-78d11d0d2803.png)

**Comment by erictraut** [comment]
Why are `await` and `abstractmethod` not appropriate here? Any arbitrary expression can be used in the context of a call argument, and `await` and `abstractmethod` are perfectly applicable within an expression.

**Comment by MikhailArkhipov** [comment]
But `def` or `class` unlikely.

**Comment by erictraut** [comment]
Yeah, my principle for type completions — especially when it comes to keywords — is to provide a list that's plausible. I decided not to strive for perfection because I don't think that provides much utility for users. If we wanted to include only keywords that are syntactically plausible for a given insertion point, we'd need to implement the equivalent of a full parser within the type completion provider. That's doable, but seems like high cost with little or no value to users. If you disagree, you're welcome to continue to add more logic to the completion provider as you see fit.
