### ISSUE TITLE
Support type narrowing of union of type dicts in match statement

### ISSUE THREAD

**Issue by xixixao** [microsoft/pyright#4155]
This errors out:

```py
# Setup
import typing

class Foo(typing.TypedDict):
    name: typing.Literal["Foo"]
    anything: str

class Bar(typing.TypedDict):
    name: typing.Literal["Bar"]
    something_else: int

FooBar = Foo | Bar
# End of setup

def test(x: FooBar):
    match x['name']:
        case 'Foo':
            foo(x) # Here we get a type error

def foo(x: Foo):
    pass
```

But if I change `test` to this, there is no error:

```py
def test(x: FooBar):
    match x['name']:
        case 'Foo':
            assert(x['name'] == 'Foo')
            foo(x)
```

It seems trivial and logical that Pyright should assume the `case` restricts the field value, and type narrow the `dict` to the appropriate type.

This is a classic "tagged union" pattern (I'm not sure how common it is in Python but it's extremely common in JS for example).

**Comment by erictraut** [comment]
This isn't a trivial change. The problem is that the target expression (in this case `x['name']` is a complex expression. Its type is evaluated as `Literal['Foo', 'Bar']`. This literal type can be (and is) narrowed by the catch statement, but applying  narrowing to `x` is not at all straightforward. The subexpression `x` is completely divorced from the type `Literal['Foo', 'Bar']` at the point where the narrowing occurs (i.e. in the case statements).

Pyright is able to handle tagged union narrowing in a simple "if" statement because it looks specifically for the expression of the form `x[K] == V` (where K and V are literal expressions). This is possible because all of the information is part of the expression at the location where the type narrowing occurs (within the if statement).

Since this isn't at all straightforward and would involve significant hacks to make it work even in specific cases, I'm not inclined to add this support. For comparison, mypy also doesn't provide narrowing in this case.

You'll need to find some other workaround in your code. One way is to use an if/else test rather than a match statement.

```python
def test(x: FooBar):
    if x['name'] == 'Foo':
        foo(x)
```

**Comment by xixixao** [comment]
@erictraut Thanks I appreciate you taking the time to reply. But I don't really buy the argument. To the user (code author), this code:

```py
def test(x: FooBar):
  match x['name']:
    case 'Foo':
      foo(x)
```

is a modern way of writing 

```py
def test(x: FooBar):
    if x['name'] == 'Foo':
        foo(x)
```
that avoids the repetition that comes when there are multiple branches.

> Pyright is able to handle tagged union narrowing in a simple "if" statement because it looks specifically for the expression of the form x[K] == V 

Why couldn't Pyright also look for the statement of the form `match x[K]`, and if `case`s are string literals apply the same type narrowing logic?

Would you be open to accept a PR for this?

**Comment by erictraut** [comment]
The approach your suggesting won't work. You'll have to take my word that this isn't really feasible given the current type narrowing approach used in pyright.
