### ISSUE TITLE
Using __getitem__ to slice over a sequence returns the wrong type

### ISSUE THREAD

**Issue by dalyIsaac** [microsoft/pyright#417]
**Describe the bug**
When using `__getitem__` for slicing over a `Sequence`, the newly created `Sequence` has the inferred type of the return value of `__getitem__`, instead of the class of which `__getitem__` is a method of.

**To Reproduce**
- Create a class which has uses `__getitem__`.
- Use slicing to create an object based on the class.

**Expected behavior**
The object created should have the class of which `__getitem__` is a method of, not of the return type of `__getitem__`.

**Screenshots or Code**

``` Python
from typing import Sequence


class IterableThingy:
    def __init__(self, thingy: Sequence[int]):
        self._thingy = thingy

    def __getitem__(self, index):
        return self._thingy[index]
    
    def __iter__(self):
        return self._thingy


obj = IterableThingy([1, 2, 3])

# Correct
single_item = obj[1] # Correctly said to be an `int`
print(single_item) # 2

# Incorrect
items = obj[1:] # `items` is said to be `int` when it should be `IterableThingy`
print(items) # [2, 3]
```

**VS Code extension or command-line**

Pyright v1.1.9 running as an extension for VS Code.

**Comment by erictraut** [comment]
The problem here is that your `__getitem__` method has no input parameter annotations. Pyright therefore needs to assume that the `index` parameter has an `Any` type. There's also no return parameter annotation for the `__getitem__` method, so pyright attempts to infer the return type. It does this by evaluating the type of the expression `self._thingy[index]`. Since `self._thingy` is a `Sequence`, we have to look at how the `__getitem__` method is defined for `Sequence`.

```
    @overload
    def __getitem__(self, i: int) -> _T_co: ...
    @overload
    def __getitem__(self, s: slice) -> Sequence[_T_co]: ...
```

Because `index` is assumed to have an `Any` type, it matches the first overload, which returns an `int` type in this case.

If you want your `__getitem__` method to work with both `int` and `slice` input parameters, you will need to define overloads for your `__getitem__` method.
```
    def __getitem__(self, index: int) -> int:
       raise NotImplementedError()
    @overload
    def __getitem__(self, index: slice) -> Sequence[int]:
       raise NotImplementedError()
    def __getitem__(self, index):
        return self._thingy[index]
```

**Comment by dalyIsaac** [comment]
Wow, thank you!
