### ISSUE TITLE
Discrepancy with mypy on TypeVar constrained with Union

### ISSUE THREAD

**Issue by supersergiy** [microsoft/pyright#4179]
**Describe the bug**
Discrepancy with mypy on the following example.

**To Reproduce**
([playground link](https://pyright-playground.decorator-factory.su/?gzip=H4sIAFuObWMC_11POw7CMAzdc4qnMtBI5QKVQBwisCCG0DqVJepUiRl6e9KiCoG397OfQ4ojdJ5YBvA4xaRw80RXnxpchKMY43DcuHrv9g1YtEHWzXHb8N0a01NAiLH2LZzF4QTXGpThAM4sWb10VPvVbz_SMon0lQR-JeiZ6Sv5nKm0-k2Xk_Y_XLjaW-zWsqgKrNB5kah40LKGB6EeGpd_i8GdS9HqDTAjaBIBAQAA))
```python
from typing import TypeVar, Union

T = TypeVar('T', int, str, Union[int, str])

def foo(a: T) -> T:
    if isinstance(a, str):
        return a
    else:
        assert isinstance(a, int)
        return int(a) # Type "int" cannot be assigned to type "T@foo"
```

Same code results in no error with mypy ([mypy playground link](https://mypy-play.net/?mypy=latest&python=3.10&gist=034cef7e4216bdb56606633d47680ebd))

**Comment by erictraut** [comment]
Yes, there will inevitably be some inconsistencies between mypy and pyright when it comes to constrained TypeVars. The two type checkers handle constrained TypeVars very differently.

When mypy analyzes a function that uses constrained TypeVars, it analyzes the function multiple times, once for each constraint. (And if more than one constrained TypeVar is involved, it needs to analyze it once for each combination of constraints!) You can see evidence of this if you add a `reveal_types(a)` to your sample code. Mypy will emit three different outputs, one for each time it analyzes `foo`. Mypy's approach here has certain advantages, but it also has many disadvantages.

Pyright cannot use the same approach as mypy. Pyright is the basis for a language server and is a lazy type evaluator rather than a multi-pass evaluator. When a user hovers over a symbol in their editor, pyright needs to provide a single type to display; it can't run three different analysis passes and generate three different answers. This led me to explore a different approach for constrained TypeVars. The approach is what I call a [conditional type](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#constrained-type-variables-and-conditional-types). It's effectively an intersection type between a TypeVar and one or more of its constraints. For example, in the `if` block within your sample, the narrowed type of `a` is an intersection between `T` and `str`. If you insert a `reveal_type`, you'll note that the narrowed type is denoted as `str*`.

I'll take a closer look at this particular case, but this may end up being an inevitable consequence of the way that pyright handles constrained TypeVars.

Out of curiosity, why are you using a union in a constraint. That's very atypical and is usually unnecessary. If you remove the union here, the error goes away.

**Comment by supersergiy** [comment]
Thanks for the explanation, this is very interesting.

For the sake of being exhaustive, here's 4 alternative typing annotations for what I'm trying to do:

```python
from typing import TypeVar, Union, overload

class C:
    pass 

###############################
### Alternative 1: overload ###
###############################
@overload
def over(a: str) -> str:
    ...

@overload
def over(a: C) -> C:
    ...
    
def over(a: Union[str, C]) -> Union[str, C]:
    if isinstance(a, str):
        return a
    else:
        return C()

def over_user(a: Union[str, C]) -> Union[str, C]:
    return over(a) 

#########################################
# Alternative 2: constrained with Union #
#########################################
T_with = TypeVar('T_with', C, str, Union[str, C])

def tv_with(a: T_with) -> T_with:
    if isinstance(a, str):
        return a
    else:
        return C() # Type "C" cannot be assigned to type "T_with@tv_with"
    
def tv_with_user(a: Union[str, C]) -> Union[str, C]:
    return tv_with(a) 

############################################
# Alternative 3: constrained without Union #
############################################
T_without = TypeVar('T_without', C, str)

def tv_without(a: T_without) -> T_without:
    if isinstance(a, str):
        return a
    else:
        return C()

def tv_without_user(a: Union[str, int]) -> Union[str, int]:
    return tv_without(a) # Type "str | int" is incompatible with constrained type variable "T_without"

#####################################
### Alternative 4: bound to Union ###
#####################################
T_bound = TypeVar('T_bound', bound=Union[str, C])

def tv_bound(a: T_bound) -> T_bound:
    if isinstance(a, str):
        return a
    else:
        return C() # Type "C" cannot be assigned to type "T_bound@tv_bound"
        
def tv_bound_user(a: Union[str, int]) -> Union[str, int]:
    return tv_bound(a)
```

Alternative 1 is using overload and works for both mypy and pyright. We do have quite a few functions that would need to be overloaded this way though, and actual overload signatures are a lot more bulky. So we were looking for a way to achieve the same with TypeVars...
Alternative 2 uses the union constraint, which works for mypy but not pyright.
Alternative 3 is dropping the union constraint. In this case, both mypy and pyright don't like it when the exact input type is not narrowed down beyond the union.
Alternative 4 also fails for both mypy and pyright.

**Comment by erictraut** [comment]
I see. Yes, `@overload` is the correct tool for this job. I understand that it is adds some verbosity, but this is what overloads were designed for. You're trying to use a screwdriver to pound in a nail. :)

I don't know if you have an option to refactor your interface. If so, you might want to avoid writing polymorphic methods because they don't play well with static typing. `@overload` is the penance you pay for polymorphism. ;)

**Comment by erictraut** [comment]
I looked at making this work. It's possible, but it adds some expensive code to some very performance-critical routines in the type checker. Handling this case (which I consider an iffy edge case) will slow down perf analysis for common cases. I don't think that's a good tradeoff, so I'm not going to check in this fix. 

As I mentioned above, I think the right answer is to use `@overload` in this case.

If you really want to use the constrained TypeVar that includes a union that overlaps (i.e. is a subtype of) other constraints, then you could use a `cast` call to avoid the type error.

**Comment by supersergiy** [comment]
We'll stick to `@overloads` then -- we're building something akin to [einops](https://github.com/arogozhnikov/einops), where a big chunk of utility comes from the interfaces being polymorphic.

Thanks a lot for the explanations and for the great work on pyright.
