### ISSUE TITLE
Signature of `__init__` synthesized by `dataclass` lost by subsequent class decorators.

### ISSUE THREAD

**Issue by supersergiy** [microsoft/pyright#4183]
**Describe the bug**
Signature of `__init__` synthesized by `dataclass` lost by subsequent class decorators.

**To Reproduce**
```python
import dataclasses
from typing import Protocol, Type, ParamSpec

P = ParamSpec("P")

class Prot(Protocol[P]):
    def __init__(self, *args: P.args, **kwargs: P.kwargs):
        pass

def decorator(cls: Type[Prot[P]]) -> Type[Prot[P]]:
    ...

@decorator
class B:
    def __init__(self, a: int):
        self.a = a

reveal_type(B.__init__) # Type of "B.__init__" is "(self: Prot[(a: int)], a: int) -> None"


@decorator
@dataclasses.dataclass
class C:
    a: int

reveal_type(C.__init__) # Type of "C.__init__" is "(self: Prot[()]) -> None"
```
[Playground Link](https://pyright-playground.decorator-factory.su/?gzip=H4sIAMvvbmMC_32R3WrEIBCF7-cpBntjltQHCLQsm_sitHchhCExizSJQWWXfftqfjfQ1hud0XPOp-p-NNZjQ57qjpxTDlprevSPUQ9X1PO2tMab2nQpfj1GlaIkS_3nqGoAiW97yZlkCcDkNIn4qixkmWSAYTSqxarSg_ZVxZ3q2hRPZK8uQyniHMrT933tzKtFGscYrAGiSaNqY8kby-sunI1kRYwLUWWCr-_HzuwghAA4b8qF9PInGWWoB_8UH9uCwp0JwKqboq4KT6X4RazKBF-mZDQtsr3NUDtkk202PU3BF_Nyi4nQH2ZQDA6Q56ffEdt6Yc9nttnhyJT_zpT_x5SUO8UPT-xAaRwCAAA%3D)

`__init__` signature is respected by mypy ([playground](https://mypy-play.net/?mypy=latest&python=3.10&gist=e9cded020f447ddb823fe00a79b676b2))

**Expected behavior**
Same revealed type for  `B.__init__` and `C.__init__` OR a warning explaining the limitation to be issued.

**Comment by erictraut** [comment]
Pyright's behavior here is correct. Your class decorator is returning a `Prot[P]`, not the original class.

I think what you intended to do here was this:

```python
T = TypeVar("T", bound=Prot)

def decorator(cls: Type[T]) -> Type[T]:
    ...
```

This happens to work in mypy because it doesn't implement support for class decorators and simply ignores them.

**Comment by supersergiy** [comment]
Beautiful, thank you so much!

Sorry for being dense, but could you please explain why the `dataclass` case is fundamentally different from the vanilla case?

**Comment by erictraut** [comment]
This happens to work with non-dataclass classes, but that's just by chance. I wouldn't recommend using that approach even for non-dataclass classes.

In the case of dataclasses, the `__init__` method is synthesized only after all decorators are applied to the class declaration. That's because it's possible for for the types of the fields in the dataclass to refer to the type of the class itself, and these type references need to take into account all decorators.

Consider the following (admittedly contrived) example where the dataclass field `x` has a declared type of `"Foo"`. This refers to the symbol `Foo`, which must take into account the `@make_bar` decorator.

```python
from dataclasses import dataclass

class Bar: ...

def make_bar(x: type) -> type[Bar]:
    ...

@make_bar
@dataclass
class Foo:
    x: "Foo"
```

Pyright internally handles these cases by deferring the synthesis of the `__init__` method until after all decorators have been applied to `Foo`. That means the decorators can't rely on the signature of the synthesized `__init__` method.

**Comment by erictraut** [comment]
I see what you're trying to do, but I wouldn't recommend it. You say that you're "surgically adding a method" to the decorated class, but that's not really what's happening. You're obscuring all of the other methods in that class by replacing it with another class (a protocol). Consider, for example, what would happen if `A` happened to also have a method called `baz`. This method would appear to no longer be accessible after your decorator was applied (even though it is presumably available at runtime).

I don't see a way to accommodate your use case for `dataclass` without breaking other (arguably more legitimate) use cases. Sorry.

The reason `P1` doesn't work is because the `__init__` method is not yet synthesized at the time the decorator is applied. As explained above, it cannot be synthesized until after all decorators are applied because some fields' type declarations may contain forward references to the class being decorated. This is a legitimate use case as well, and I specifically needed to add code to defer method synthesis to support it.

> That means the decorators can't rely on the signature of the synthesized __init__ method.

Yes, that's the correct conclusion here.

If someone really wants to use your method with a dataclass, they could create their own custom `__init__` method for the dataclass rather than relying on the synthesized version.
