### ISSUE TITLE
(member) function checking for None isn't recognized as a guard

### ISSUE THREAD

**Issue by FederAndInk** [microsoft/pyright#4246]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem.

```python
class T
  ...
  def is_empty(self):
    return self.binf is None or self.bsup is None

t = T()
if not t.is_empty():
  x = t.binf + t.bsup
```

isn't recognized as a guard and gives `Operator "+" not supported for types "float | int | Unknown | None" and "float | int | Unknown | None"`

**Describe the solution you'd like**

Recognize or have a way to flag a (member) function as a guard of some (member) variables also `not self.guard_fn()` should work too

**Additional context**

**Comment by erictraut** [comment]
Type narrowing for conditional type guards is not applied across function boundaries, so the guard logic within `is_empty` doesn't apply to the caller of that function. For more details about type guards, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards).

You may be interested in [user-defined type guards](https://peps.python.org/pep-0647/), which were designed to handle something similar to what you're doing in your code. Your particular usage is beyond the ability of a user-defined type guard because you are validating multiple instance variables in your `is_empty` function, and there's no way to express in the type system "an object of type `T` whose instance variables `binf` and `bsup` are not `None`".

You'll need to rethink your approach if you want it to work with static typing. One option is to include the references to `t.binf` and `t.bsup` directly in the conditional expression:

```python
if t.binf is not None and t.bsup is not None:
    x = t.binf + t.bsup
```

**Comment by FederAndInk** [comment]
I've seen and tried type narrowing with TypeGuard but I didn't come up with a working solution, like you said it's not possible.
This is really unfortunate though and defeats the point of functions, requiring to make sometimes lengthy if statement conditions and code duplication.

wouldn't that be possible to consider in the future though?

thanks for the quick and detailed answer anyway 👍
