### ISSUE TITLE
Missing docstring for stdlib functions with C impls

### ISSUE THREAD

**Issue by fifty-six** [microsoft/pyright#4250]
**Describe the bug**
Functions such as `itertools.combinations` and `itertools.combinations_with_replacement` don't have their docstrings displayed with the signature.

**To Reproduce**
- Use pyright as the LSP in nvim, vsc, helix, etc.
- Hover over `combinations_with_replacement` or add the `(` after to get the signature while typing
- Get type information but no docstring

**Expected behavior**
I expected to see the docstring

**Screenshots or Code**
![vsc](https://user-images.githubusercontent.com/10470872/204709777-54dbfe3f-5992-458f-babd-a4d5916c2b53.png)
![nvim](https://user-images.githubusercontent.com/10470872/204709813-115c6059-2494-41aa-84b1-b84b6c931005.png)

```python
from itertools import combinations_with_replacement

combinations_with_replacement(
```

If your code relies on symbols that are imported from a third-party library, include the associated import statements and specify which versions of those libraries you have installed.

**VS Code extension or command-line**
vsc: v1.1.281
cli: pyright 1.1.281

**Additional context**
I noticed that this one is defined in C [here](https://github.com/python/cpython/blob/8bb2303fd75c299d8fc85229889ac75e867c135c/Modules/clinic/itertoolsmodule.c.h#L542) and similarly I looked at `signal.alarm` defined [here](https://github.com/python/cpython/blob/8bb2303fd75c299d8fc85229889ac75e867c135c/Modules/clinic/signalmodule.c.h#L49) and had similar issues.
![image](https://user-images.githubusercontent.com/10470872/204710999-d032cbdd-845c-4f25-923c-23bdbe73db17.png)

**Comment by erictraut** [comment]
Yes, this is by design. Pyright displays docstrings associated with type declarations. For stdlib symbols, the declarations come from typeshed stub files, and they do not contain any docstrings.

Pylance is Microsoft's Python language server for VS Code built on top of pyright, and it includes additional functionality that includes docstrings for stdlib symbols. We don't have any plans to port this functionality to pyright, which is focused primarily on type checking.

If you want docstring support for stdlib, I recommend that you switch to Pylance.
