### ISSUE TITLE
Parse docstrings for type information

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/pyright#432]
**Is your feature request related to a problem? Please describe.**
Similar to https://github.com/microsoft/python-language-server/issues/1236
Some docstrings contain type info (as opposed to stubs or type annotations). This info should be parsed and used best-effort.

There are many different possible formats; numpy, google, epydoc, etc.

See also: https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

With examples that look like:
```
:param path: The path of the file to wrap
:type path: str
:param field_storage: The :class:`FileStorage` instance to wrap
:type field_storage: FileStorage
:param temporary: Whether or not to delete the file when the File
   instance is destructed
:type temporary: bool
:returns: A buffered writable file descriptor
:rtype: BufferedFileStorage
``
But also:
```
Args:
    path (str): The path of the file to wrap
    field_storage (FileStorage): The :class:`FileStorage` instance to wrap
    temporary (bool): Whether or not to delete the file when the File
       instance is destructed

Returns:
    BufferedFileStorage: A buffered writable file descriptor
```
Types are often not qualified, though, so may require some heuristic to figure out what type we actually think is being used.

**Describe the solution you'd like**
Types extracted from comments if stub is missing or being created.

**Comment by erictraut** [comment]
Pyright already contains most of this. See https://github.com/microsoft/pyright/blob/master/server/src/analyzer/docStringUtils.ts for the implementation details. Feel free to fill in any gaps that you see.

Currently, these are used only for signature help. 

I'm reluctant to use these comment-based types for type stub generation because I find that they are frequently inaccurate and incomplete. Misleading and incorrect types are arguably worse than no types.

**Comment by erictraut** [comment]
Closing this suggestion as per our conversation.
