### ISSUE TITLE
Support file-scoped `# pyright: off`, `# pyright: ignore`

### ISSUE THREAD

**Issue by smackesey** [microsoft/pyright#4321]
**Is your feature request related to a problem? Please describe.**

Two issues. [Here](https://github.com/microsoft/pyright/blob/main/docs/comments.md) are the pyright docs on comments. They tell you to put `# pyright: basic` and `# pyright: strict` at the top of a file to apply that ruleset to the file. However:

- `# pyright: off` does not work-- surprising since it's the third setting for `typeCheckingMode`
- `# pyright: ignore` does not work-- surprising since `# type: ignore` _does_ work. Also it would be useful to be able to suppress errors in a whole file using the same syntax `# pyright: ignore [someErrorRule]` used to do this on individual lines-- especially since `# pyright: <something>` comments are already used to do _some_ file-scoped stuff.

**Describe the solution you'd like**

- Make file-scoped `# pyright: off` turn off checking for a file.
- Make file-scoped `# pyright: ignore` turn off checking for a file.
- Make file-scoped `# pyright: ignore [code]` turn off codes for a file.

**Comment by erictraut** [comment]
There's no need for a `# pyright: ignore [someErrorRule]` rule. There's already a comment form that supports this (`# pyright: someErrorRule=false` or `# pyright: someErrorRule=none`).

Can you explain the situation where you would want to use a file-level `# pyright: ignore` rather than `# type: ignore`?

Likewise, can you explain the situation where you would want to use `# pyright: off`?

**Comment by smackesey** [comment]
>There's no need for a # pyright: ignore [someErrorRule] rule. There's already a comment form that supports this (# pyright: someErrorRule=false or # pyright: someErrorRule=none).

I am indifferent as to the form, but it would be a simpler API with no loss of function if the same comment format worked for line-scoped and file-scoped comments. The status quo is that the line-scoped and file-scoped comments use arbitrarily different formats to accomplish the same thing. This is unintuitive.

>Can you explain the situation where you would want to use a file-level `# pyright: ignore` rather than `# type: ignore`?

It's best to keep static analyzer directive comments as consistent as possible. We are using `# pyright: ignore` throughout our codebase to disable individual errors on lines. It is simply confusing that you can do basically everything with `# pyright` comments _except_ turn off `pyright` in a file, for which you have to use an arbitrarily different prefix with `# type: ignore`.

>Likewise, can you explain the situation where you would want to use # pyright: off

To turn off type-checking in a file using an API that is obvious given that `# pyright: strict` and `# pyright: basic` work, and there is a `typeCheckingMode` setting where the three options are `strict`, `basic`, and `off`.

**Comment by erictraut** [comment]
You've cited consistency as a reason for implementing these new suggested features. By itself, I think that's insufficient justification for adding new features like these.

There are good reasons why the current functionality exists as it does, even if it might not be immediately obvious to you.

I'm interested in understanding whether there's a real need here — something that is blocking you getting in your way. When requesting new features, it's good to start with the "why" — the motivation for the feature. It's OK to also suggest a proposed solution as well, but without first understanding the motivation for the feature, it's difficult to say whether the proposed solution is the best approach. You've suggested a few proposed solutions, but I'd like to better understand the problem you are proposing to solve here.

**Comment by smackesey** [comment]
>I'd like to better understand the problem you are proposing to solve here.

The problem I am proposing to solve is making pyright easier to use.  The more consistent the API, the less cognitive burden is imposed by the tool. Ease of use matters a lot for ensuring a tool will be used correctly and to its full capacity by a team of developers of varying degrees of expertise.

>You've cited consistency as a reason for implementing these new suggested features. By itself, I think that's insufficient justification for adding new features like these.

I suppose that's where we differ.  Increased API consistency with no loss of function is always a boon to users,. If I were a pyright maintainer, I would therefore seek to make my APIs as consistent as possible. If you disagree, I guess that's the end of it. I have no further case to make.

**Comment by erictraut** [comment]
I agree that there is value in consistency and that it reduces cognitive burden, but we need to weigh that against the cognitive burden (and support burden) associated with redundant and duplicative mechanisms. For that reason, I don't think it makes sense to support `# pyright: ignore [someErrorRule]` at the file level because there's already a well-defined and supported syntax for controlling diagnostic rules at the file level.

I think the file-level `# type: ignore` comment is an ill-conceived mechanism. Mypy implemented this because it is constrained to `# type: ignore` comments because it relies on a hack in the Python parser, which includes `# type: ignore` comments in the AST. This is an example of an implementation detail surfacing as an unfortunate user interface. Pyright supports a file-level `# type: ignore` because it was included in PEP 484, but that doesn't mean it's a good idea. I don't think it's wise to extend this mechanism for `# pyright: ignore` comments.

Adding support for `# pyright: off` wouldn't make sense given the way that `# pyright: basic` and `# pyright: strict` are defined. The `# pyright: basic` and `# pyright: strict` override the configured ruleset only in cases where those rules _increase the severity_ of the diganostics associated with that rule. For example, if your pyrightconfig.json config file indicates that the "basic" diagnostic ruleset should be enabled, you can use a `# pyright: strict` to add additional diagnostics for that file. However, you cannot do the opposite. If the pyrightconfig.json config file indicates that the file should use the "strict" ruleset, `# pyright: basic` will have no effect. Therefore, a `# pyright: off` wouldn't make sense because it would have no effect.

**Comment by smackesey** [comment]
Thanks for the thorough response.

>Adding support for # pyright: off wouldn't make sense given the way that # pyright: basic and # pyright: strict are defined. The # pyright: basic and # pyright: strict override the configured ruleset only in cases where those rules increase the severity of the diganostics associated with that rule. 

Interesting, I was not aware that `# pyright: {basic,strict}` is "unidirectional"-- the comment docs don't mention this: https://github.com/microsoft/pyright/blob/main/docs/comments.md#file-level-type-controls
