### ISSUE TITLE
Submodule imports do not cause side effects on parent modules

### ISSUE THREAD

**Issue by jakebailey** [microsoft/pyright#439]
Note: I had trouble splitting this up into individual issues, since "side effects" can interact with so many things and I wanted to present the whole issue (even though I know it's a lot of text). I don't expect any single change to fix everything.

## Background

Given an import like:

```python
import foo.bar.baz
```

There is a variable in scope called `foo` which necessarily must have a member `bar`, which must have `baz`, and so on.

In Python, `foo` _is_ the module `foo`. This import appearing has wider implications:

1. If one part of the code does `import foo.bar`, then _all_ refrences to `foo` contain the submodule `bar`. This breaks the overall idea that the members of a module can be determined without knowing how it's referenced. You can construct examples where the same code either works or doesn't work based on this behavior.
1. If `foo` contains a variable called `bar`, then it is no longer accessible if _any_ code in the process ever does `import foo.bar`.

Unfortunately, this makes modules hard to reason about alone, as they are no longer closed objects. It's likely not possible to handle every case. 

However, there are specific behaviors that can be handled to ease some of these cases. From reading pyright's import code, I believe some of this is intended to work but appears not to be fully working.

Much of this was fixed in microsoft/python-language-server#1565, and can be used as a reference.

## Side effects constrained to a module's own submodule tree

`torch/__init__.py`:

```python
import torch.nn
```

This file _is_ the module `torch`. It's importing `torch.nn`, but not using it. The effect of this import is that one can do `import torch` and then immediately do `torch.nn`. The fix here is to see that this module is `torch`, recognize imports of submodules, and add them as variables for the current scope. MPLS does this. It's correct because if `torch` is loaded, then you know for certain it loaded `torch.nn`, as opposed to some external code forcing the load.

Examples of this behavior in the wild:

- https://github.com/pytorch/pytorch/blob/8f3c0d541eeaf7316d2e62f98cb1337080144206/torch/__init__.py#L299
- https://github.com/pandas-dev/pandas/blob/95e1a63dd3382db6663bc8a2b334b422b93dd7fe/pandas/__init__.py#L181

## Side effects within "user" code

Consider a library where the following is allowed:

```python
import foo.bar.baz
```

Each module consists of `__init__.py` files without imports. Doing a plain `import foo` would not mean that `foo.bar` is valid. But, the user expects that `foo.X`, `foo.bar.Y`, and `foo.bar.baz.Z` are all valid ways to access things.

This is legal because Python actually does the following when `import foo.bar.baz` is written:

1. Load `foo`
1. Load `bar`, add `bar` to `foo`.
1. Load `baz`, add `baz` to `bar`.

The solution here is to construct (at least for the module where this import appears) a "variable module", where these accesses are valid; i.e. a specialized module for the context that includes extra members. MPLS does this (it's called `PythonVariableModule`).

## Side effects from conflicting variable names and module names

Given the tree:

```
.
|-- app.py
`-- top
    |-- __init__.py
    `-- sub1
        |-- __init__.py
        `-- sub2
            `-- __init__.py
```

Where all `__init__.py` files are empty except `sub1`'s, which contains `sub2 = 3`

There can be conflicts around what `top.sub1.sub2` means. If one writes:

```python
import top.sub1
top.sub1.sub2
```

Then `top.sub1.sub2` is the `int`. However:

```python
import top.sub1.sub2
top.sub1.sub2
```

Then `top.sub1.sub2` is the module `top.sub1.sub2` _in all modules_ (except local to `top.sub1`). This also affects `*` imports:

```python
from top.sub1 import *
import top.sub1.sub2

print(sub2) # 3

import top.sub1.sub2
from top.sub1 import *

print(sub2) # module!
```

Cases where variables have the same name as submodules don't appear to be a common case, probably because it's a big footgun. MPLS solves this by always preferring the submodule if the submodule exists (except within the module which contains the variable), but this one will have to take some care.

**Comment by jakebailey** [comment]
Some test cases I compared with MPLS; some are annotated with reasons for failure, but some aren't. This is mainly for reference.

[pyright_import_test.zip](https://github.com/microsoft/pyright/files/3985718/pyright_import_test.zip)

**Comment by erictraut** [comment]
I very intentionally don't model the side effects of cross-module imports. In fact, I have a bunch of code in place to avoid modeling cross-module import dependencies. This is for a couple of reasons:
1. If code relies on such side effects, it should be considered a bug in that code. It's almost never the intention of the author to rely on such side effects. It's very fragile, and the behavior can change due to unrelated code changes in other modules. A static analyzer should call out these conditions for what they are: bugs.
2. Lazy evaluation cannot and should not rely on any module import resolution ordering.

So I will push back hard on any suggestion that we should attempt to model the dynamic behavior of cross-module import side effects.

In cases where the import behavior is deterministic and not based on cross-module initialization ordering, I'm a bit more open to adding support, although I still think we should treat some of these as errors and flag them as such. By doing so, we will help our users improve the readability, maintainability, and robustness of their code.

It's important to keep in mind that just because something is "legal" and happens to work within Python doesn't mean that it shouldn't be flagged as an error or a warning. Any language toolchain needs to make judgement calls about what is legitimate and what's not. That's arguably even more important for a language and runtime like Python, which is very "loose" in how it's defined. Many of Python's behaviors were not intended (or specified) but are side effects of the way a feature was implemented in the early days of the language.

**Comment by jakebailey** [comment]
I agree that we shouldn't try and model every possible situation (the variable naming one is likely a "whatever", I don't have a specific example off the top of my head).

I think the first two are pretty deterministic, however, and have clear solutions because they're constrained to the module in which they operate. MPLS had to do these to get these popular libraries to behave properly.

I'm not entirely certain how we could provide feedback for some of these, though, since they require knowing intent. For example, torch's `import torch.nn` with the expectation that `nn` is available for downstream users; I don't know how that expectation could be known. They might have just done `torch.nn` for later use in the file and really want people to write `import torch.nn` or something. Empirically, people do `import torch; torch.nn` and it's in their examples.

**Comment by erictraut** [comment]
One of the main goals of Pyright is to help developers make their code more robust, deterministic, and maintainable. Developers shouldn't be relying on subtle side effects of the Python loader. 

Python started as a scripting language, and it's now growing up to become a full programming language. Tools providers need to do our part to help it grow up. That involves flagging fragile, unspecified, non-deterministic, or non-statically-verifiable behaviors as errors. If we don't flag these as errors, these idioms will continue to propagate, and the Python ecosystem will not improve over time.

In cases where a popular OSS library make use of these idioms, we can submit PRs to improve them — or ignore the issue and rely on proper type stubs.

For those reasons, I'm reluctant to "fix" any of the above issues in Pyright. I think the current implementation is consistent with the principles and goals I mentioned above.

**Comment by erictraut** [comment]
I reread your response above, and I think I misunderstood some of the scenarios you were describing. I'll take a more detailed look at the test cases you linked and go through the failures on a case-by-case basis.

**Comment by erictraut** [comment]
I've looked at all the examples above in more detail, and I stand by my previous statements.

Code that relies on side effects — especially those that involve module load ordering or cross-module behaviors — should be considered bugs in the code.

*Side effects constrained to a module's own submodule tree*: This relies on the tenuous assumption that the module can import its own submodules by the top-level module name. This makes the code fragile because it now relies on the name of the top-level folder and the import paths that are configured at runtime. If this code intends to make `nn` available to any file that includes the statement `import torch`, the implementation should be changed to `import .nn as nn` or `from . import nn as nn`. This is what the latest version of pytorch appears to do.

*Side effects within "user" code*: User code should explicitly import the modules and submodules it wants to access. It shouldn't rely on side effects of the loader. If a file wants to access `foo.X`, it should contain an explicit `import foo` statement, not rely on the side effects of `import foo.bar.baz`. 

*Side effects from conflicting variable names and module names*: This case is especially tenuous because it involves cross-module side effects. A statement in one module can affect the behavior of a completely independent second module. This should definitely be considered a bug.

I'm going to (re)mark this bug as "as designed" and closed.

**Comment by jakebailey** [comment]
If possible, I'd like part of this to be reconsidered. My first item is actually given as an example in PEP 484's "additional notes on stub files" (which I was reading for another reason), which implies that this is a behavior that stubs (and regular code) should have:

> Just like in normal Python files [importdocs], submodules automatically become exported attributes of their parent module when imported. For example, if the spam package has the following directory structure:
```
spam/
    __init__.pyi
    ham.pyi
```
> where `__init__.pyi` contains a line such as `from . import ham` or from `.ham import Ham`, then ham is an exported attribute of spam.

Note how the second example doesn't even bring `ham` the module into scope, but a member of the module, and the product is that `spam.ham` exists simply because `ham` was loaded at all.

I don't mind not trying to do this via external user code, but this example is in-spec.

**Comment by jakebailey** [comment]
I have no idea how prevalent this is in something typeshed, however, nor how we could verify how often this specific spec item has been used.
