### ISSUE TITLE
Kinder validation on pythonPath containing spaces and newlines

### ISSUE THREAD

**Issue by Lilja** [microsoft/pyright#4408]
**Describe the bug**
Using the neovim lsp config, i managed to put this configuration:

```
{
  analysis = {
    autoSearchPaths = true,
    diagnosticMode = "workspace",
    useLibraryCodeForTypes = true
  },
  pythonPath = "/Users/lilja/Library/Caches/pypoetry/virtualenvs/temp-poetry-dQ9vvjfb-py3.10/bin/python\n"
}
```
Notice the stray newline in the end of `pythonPath`

**To Reproduce**
Include a newline to pythonPath.

**Expected behavior**
An error or something yelling at me from pyright's side.

**Comment by erictraut** [comment]
Spaces are not illegal in paths. Newlines are illegal in most file systems, but I don't think it's the job of pyright to validate your settings paths. 

Pyright already emits logging output to help you diagnose problems like this. If the standard logging is insufficient, it also includes a `verboseOutput` configuration option that emits much more logging information.

In VS Code, almost no one uses the `pythonPath` setting to configure their environment because VS Code's Python extension offers a simple selector menu to choose the desired Python environment.
