### ISSUE TITLE
multiprocessing.context.DefaultContext.Pipe is identified as wrong type on Linux/WSL

### ISSUE THREAD

**Issue by ashb** [microsoft/pyright#4450]
This test code:

```python
import multiprocessing
from multiprocessing.connection import Connection


ctx = multiprocessing.get_context()
p1, p2 = ctx.Pipe()
reveal_type(p1)

x: Connection = p1
```

![image](https://user-images.githubusercontent.com/34150/212308839-8cd916c9-8726-400d-a253-657a8cdd07a9.png)

Error text: 

> Expression of type "PipeConnection" cannot be assigned to declared type "Connection"
  "PipeConnection" is incompatible with "Connection"

The type stub for this has an `if sys.platform != "win32":` https://github.com/microsoft/pyright/blob/8544b19923adcf0cd5329e42f9e17422aa8c7ba3/packages/pyright-internal/typeshed-fallback/stdlib/multiprocessing/context.pyi#L54-L57

Could this be due to the fact that Pyright is I'm editing a file on WSL? (I'm not able to reproduce this error when running `pyright` installed via pip on the command line)

**Comment by erictraut** [comment]
Unless otherwise specified, pyright will assume that you're running the code on the same platform as you're developing the code. In your case, that's incorrect because you're developing on Windows but (effectively) running it in a Linux environment. You'll need to tell pyright that you want it to assume Linux instead. To do so, you'll need ti edit your pyrightconfig.json (or pyproject.toml) config file and specify "pythonPlatform" should be "Linux".

**Comment by ashb** [comment]
This feels like a bug or something that VSCode/Python extension should handle for me when I'm editing a project in WSL?

**Comment by ashb** [comment]
@erictraut There is a `workspacePlatform` context key https://github.com/microsoft/vscode/issues/131467

> The new workspacePlatform context key is meant to allow extensions to determine the platform of the data-side extension host (for instance for displaying getting started content specific to a platform). 

Please can Pyright/pylance be change to use that instead?

**Comment by erictraut** [comment]
You could file a feature request in the [pylance-release issue tracker](https://github.com/microsoft/pylance-release/issues).
