### ISSUE TITLE
type narrowing does not carry over from parent class methods

### ISSUE THREAD

**Issue by aspizu** [microsoft/pyright#4458]
```py
class Parent:
    member: int | None

    def foo(self):
        assert isinstance(self.member, int)
        _ = self.member + 1


class Child(Parent):
    def foo(self):
        super().foo()
        _ = self.member + 1 # Operator "+" not supported for "None"
```

**Comment by erictraut** [comment]
This is by design. Type narrowing is performed locally within an execution context. It does not track side effects across function calls. This is how all type checkers work in all languages that I'm familiar with.

If you want your code to work with static typing, you'll need to change the approach you're using.

**Comment by aspizu** [comment]
how would you refactor this?

**Comment by erictraut** [comment]
That depends on whether you have control over the code in the base class.

Here are some options:
1. In the base class, always initialize `member` to be a valid `int` rather than sometimes being an `int` and sometimes being `None`. For example, you could initialize it to `0`.
2. Introduce a property in the base class to access `member`. This property could include the `assert` statement.
3. Replicate the `assert` statement in the child class(es).

**Comment by aspizu** [comment]
thanks
