### ISSUE TITLE
ignore unused_variable

### ISSUE THREAD

**Issue by Freed-Wu** [microsoft/pyright#4512]
**Is your feature request related to a problem? Please describe.**
By default, pyright will warn if a variable is unused.
![screen-2023-01-24-00-47-01](https://user-images.githubusercontent.com/32936898/214099113-2c18b5dd-7d75-449d-bb8f-6e72bea6bbb8.jpg)

**Describe the solution you'd like**
Like deepsource to ignore any variable names started with `unused` and `_unused`
![screen-2023-01-24-00-46-48](https://user-images.githubusercontent.com/32936898/214099083-6ae49c4f-8b31-4362-b0d7-4bf9749d7a31.jpg)

**Comment by erictraut** [comment]
Pyright never emits warnings or other diagnostics for unused parameters. It does emit a "hint" if the language client (i.e. the editor) requests it. This hint is used in some editors (e.g. VS Code) to display text in a "grayed out" manner. This is by design.

It looks like the editor you're using is requesting this hint but is then displaying it in a manner that makes it look like a diagnostic. I recommend reporting that to the maintainer of your LSP plugin or editor.

Pyright is working as designed here.
