### ISSUE TITLE
Surprising unknown import symbol when importing a module and content from module

### ISSUE THREAD

**Issue by jenshnielsen** [microsoft/pyright#4520]
**Describe the bug**

When importing both trace from opentelemetry and symbols from opentelemetry.trace 
a unknown symbol error is raised. 

Removing the module import makes the error go away

**To Reproduce**

Run pyright on the snippet below

results in

```
❯ pyright .\debug_typing.py --verbose
No configuration file found.
No pyproject.toml file found.
stubPath C:\Users\jenielse\source\repos\typings is not a valid directory.
Assuming Python platform Windows
Search paths for C:\Users\jenielse\source\repos
  C:\Users\jenielse\AppData\Roaming\npm\node_modules\pyright\dist\typeshed-fallback\stdlib
  C:\Users\jenielse\source\repos
  C:\Users\jenielse\source\repos\typings
  C:\Users\jenielse\AppData\Roaming\npm\node_modules\pyright\dist\typeshed-fallback\stubs\...
  c:\Users\jenielse\Miniconda3\envs\pyrightdebug\DLLs
  c:\Users\jenielse\Miniconda3\envs\pyrightdebug\Lib
  c:\Users\jenielse\Miniconda3\envs\pyrightdebug
  c:\Users\jenielse\Miniconda3\envs\pyrightdebug\Lib\site-packages
Searching for source files
Found 1 source file
pyright 1.1.290
C:\Users\jenielse\source\repos\debug_typing.py
  C:\Users\jenielse\source\repos\debug_typing.py:2:33 - error: "INVALID_SPAN" is unknown import symbol (reportGeneralTypeIssues)
  C:\Users\jenielse\source\repos\debug_typing.py:2:47 - error: "INVALID_SPAN_CONTEXT" is unknown import symbol (reportGeneralTypeIssues)
  C:\Users\jenielse\source\repos\debug_typing.py:2:69 - error: "get_current_span" is unknown import symbol (reportGeneralTypeIssues)
3 errors, 0 warnings, 0 informations
Completed in 0.715sec
```

Deleting the first line makes the issue go away.

**Expected behavior**

Code to typecheck.

**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
```python
from opentelemetry import trace
from opentelemetry.trace import INVALID_SPAN, INVALID_SPAN_CONTEXT, get_current_span
```

with opentelemetry-api=1.15.0 installed

**VS Code extension or command-line**

pyright commandline  version 1.1.290 on windows 11 installed with npm

**Additional context**

This code is minimized from an actual example where the imports are in different modules. but the result is the same

**Comment by erictraut** [comment]
The problem here is that the `opentelemetry` has a bug. It is a implicit namespace package — i.e. it doesn't have an `__init__.py` at the top level. It has a number of submodules including `trace`, `context`, etc. The top-level package contains a "py.typed" marker file, but PEP 561 (which introduced the concept of a "py.typed" marker) states:

> For namespace packages (see [PEP 420](https://peps.python.org/pep-0420)), the py.typed file should be in the submodules of the namespace, to avoid conflicts and for clarity.

This means there should be a "py.typed" marker in each of the submodules within the implicit namespace package. Alternatively, it could add a top-level `__init__.py` file so it is a traditional package (as opposed to a namespace package).

If I add a "py.typed" marker file to the `trace` directory, pyright is able to resolve the types correctly.

I recommend filing a bug with the maintainers of `opentelemetry`.

In the meantime, you can enable `useLibraryCodeForTypes` in pyright. That tells it to infer types from the library code even if the module is not marked as "py.typed". Pyright is currently treating `opentelemetry.trace` as non-py.typed because of the bug above.

**Comment by jenshnielsen** [comment]
Thanks that makes sense. However, it's not very clear from the error message that this is what happens. 
If I enable `reportMissingTypeStubs` that becomes more clear as the module is clearly labeled as not typed. 
It would be great if the default behavior gave a more meaningful error message.

It is also surprising that 

```
from opentelemetry.trace import get_current_span
get_current_span()
```

triggers a tub file not found for "opentelemetry.trace" error 

while

```
from opentelemetry import trace
trace.get_current_span()
``

type checks without any error. From the users perspective it seems like pyright considers `opentelemetry.trace` marked untyped in the first example but marked typed in the latter
