### ISSUE TITLE
pyright does not accept `Pattern[AnyStr]`

### ISSUE THREAD

**Issue by agateau-gg** [microsoft/pyright#4534]
**Describe the bug**

pyright does not accept `Pattern[AnyStr]`.

**To Reproduce**

Given this test file:

```python
from typing import AnyStr

from re import Match, Pattern

def check_re_search(pattern: Pattern[AnyStr], string: AnyStr) -> Match[AnyStr]:
    match = pattern.search(string)
    if match is None:
        raise ValueError(f"'{string!r}' does not match {pattern!r}")
    return match
```

pyright reports the following error:

```
No configuration file found.
No pyproject.toml file found.
stubPath /home/agateau/tmp/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 1 source file
pyright 1.1.291
/home/agateau/tmp/crs.py
  /home/agateau/tmp/crs.py:6:21 - error: Could not bind method "search" because "Pattern[AnyStr@check_re_search]" is not assignable to parameter "self"
    "Pattern[AnyStr@check_re_search]" is incompatible with "Pattern[str]"
      TypeVar "AnyStr@Pattern" is invariant
        Type "AnyStr@check_re_search" cannot be assigned to type "str" (reportGeneralTypeIssues)
  /home/agateau/tmp/crs.py:6:21 - error: Could not bind method "search" because "Pattern[AnyStr@check_re_search]" is not assignable to parameter "self"
    "Pattern[AnyStr@check_re_search]" is incompatible with "Pattern[bytes]"
      TypeVar "AnyStr@Pattern" is invariant
        Type "AnyStr@check_re_search" cannot be assigned to type "bytes" (reportGeneralTypeIssues)
```

The same code works fine if one replaces all `AnyStr` with either `str` or `bytes`.

**Expected behavior**

pyright should accept the example code.

**VS Code extension or command-line**

pyright 1.1.291, running from the command-line.

**Comment by erictraut** [comment]
This won't work given the way `Pattern` is defined in the typeshed stub and the way that pyright implements constrained TypeVars. (See [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#constrained-type-variables-and-conditional-types) and [this documentation](https://github.com/microsoft/pyright/blob/main/docs/mypy-comparison.md#constrained-type-variables) for details.) The `search` overload contains annotated `self` parameters, and these do not match `Pattern[AnyStr]`. The typeshed stubs happen to work with mypy because of how mypy implements constrained TypeVars, but they won't work with pyright.

The fix for this would require an additional overload within the typeshed stubs. Something like this:
```python
    @overload
    def search(self, string: AnyStr | ReadableBuffer, pos: int = ..., endpos: int = ...) -> Match[AnyStr] | None: ...
```

Please consider reporting this issue in the typeshed issue tracker.

**Comment by agateau-gg** [comment]
Thanks, just opened the typeshed issue.

**Comment by erictraut** [comment]
Good news — the change was accepted into typeshed, and I've pulled the latest typeshed stubs into pyright. This issue will therefore be addressed in the next release.

**Comment by agateau-gg** [comment]
Great, thanks!
