### ISSUE TITLE
All elements in tuples with unpacked tuple are treated as union

### ISSUE THREAD

**Issue by Hackrrr** [microsoft/pyright#4542]
**Is your feature request related to a problem? Please describe.**
Pyright currently treats all elements in tuple with unpacked tuple as union of all possible types. This affectes both "plain" tuples and `TypeVarTuple`.

**Describe the solution you'd like**
It would be nice if pyright was able to "understand" prefixed and suffixed unpacked tuples. This would make it much easier to write functions with unpacked tuples as it would eliminate need to `#type: ignore` or `cast()` every time you use type from prefix or suffix of unpacked tuple.

Example of desired behaviour:
```python
from typing import TypeVarTuple, Unpack
Ts = TypeVarTuple("Ts")

def f(tpl: tuple[int, Unpack[Ts]]) -> tuple[int, Unpack[Ts]]:
    reveal_type(tpl)  # Actual: "tuple[int, *Ts@f]" (as expected)
    reveal_type(tpl[0])  # Expected "int", actual "int | Union[*Ts@f]"
    reveal_type(tpl[1])  # Expected "Union[*Ts@f]", actual "int | Union[*Ts@f]"
    return tpl

def g(tpl: tuple[int, Unpack[tuple[str, ...]]]):
    reveal_type(tpl)  # Actual: "tuple[int, *tuple[str, ...]]" (as expected)
    reveal_type(tpl[0])  # Expected "int", actual "int | str"
    reveal_type(tpl[1])  # Expected "str", actual "int | str"
```

**Additional context**
Example with `TypeVarTuple` *partially* worked in pyright 1.1.283 (not in 1.1.284) - pyright was able to determine `tpl[0]` as `int` (I guess that this behaviour was changed by addressing #4299).

**Comment by erictraut** [comment]
This is by design.

Pyright contains special-case logic to handle the evaluation of specific indexed elements within a tuple type in the following situation: 1) the index is a positive or negative integer literal expression, 2) the tuple's length is known statically, and 3) the index is within range of the tuple.

In your example above, condition 2 is not met, so pyright falls back on the more general union approach.

**Comment by Hackrrr** [comment]
I don't argue about wrong behaviour or about existence of bug. Pyright isn't really wrong here. What I'm saying is that it can better/improved. That's reason why I marked it as "enhancement request".

**Comment by erictraut** [comment]
This is something we might consider extending in the future if there is sufficient demand, but this is already very complicated code, and what you're asking here is very specialized. I'm going to leave the request closed for now because we don't currently have plans to extend it. We might consider re-opening it in the future if we receive signal (e.g. in the form of a sufficient number of upvotes).
