### ISSUE TITLE
Cyclic(?) imports might prevent discovery of module

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#4544]
**Describe the bug**
I wanted to update pyright from 1.1.276 to 1.1.291 on the pandas CI. Pyright reports these two new errors:

>   [pandas/core/frame.py:1968](https://github.com/pandas-dev/pandas/blob/main/pandas/core/frame.py#L1968):14 - error: Import "pandas.core.methods.to_dict" could not be resolved (reportMissingImports)
>   [pandas/core/generic.py:168](https://github.com/pandas-dev/pandas/blob/main/pandas/core/generic.py#L168):6 - error: Import "pandas.core.methods.describe" could not be resolved (reportMissingImports)

These functions exist but I could imagine that something cyclic is happening there.

**To Reproduce**

```sh
git clone git@github.com:pandas-dev/pandas.git
pyright
```

**Comment by erictraut** [comment]
The issue is that the `methods` directory in the pandas repo doesn't contain an `__init__.py` file, so `methods` is not a proper (traditional) module. Rather, it's an implicit namespace package (as per [PEP 420](https://peps.python.org/pep-0420/)). All of the other submodules with `pandas.core` contain an `__init__.py` file, so I'm guessing this is simply an unintentional omission. Adding the missing `__init__.py` addresses the issue.

PEP 420 doesn't provide much clarity in how import resolution works when multiple partial resolutions are possible and one of the resolutions involves an implicit namespace package. I've attempted to reverse engineer the runtime behavior, but it is very nuanced and seemingly inconsistent. I've tweaked pyright's import resolution logic since version 1.1.276 to address specific bug reports in this area, so that would explain why the behavior changed between 1.1.276 and 1.1.291.

Unless you have a good reason not to add an `__init__.py` to the `methods` directory, that's the approach I recommend.
