### ISSUE TITLE
pyright-langserver from PyPI fails to start up if username contains `@` symbol

### ISSUE THREAD

**Issue by denisw** [microsoft/pyright#4561]
**Describe the bug**

On my work laptop, my username is my email address. When I install the `pyright` PyPI package through `pip` and then  try to run `pyright-langserver`, I get the following error (I replace the original email address with `name@example.com`):

```
npm ERR! Invalid name: "pyright-python-langserver.name@example.com"
```

The issue is that the `langserver.py` wrapper script of the `pyright` PyPI package (which seems to be missing in this repository?) includes the username (as returned by [`getpass.getuser()`](https://docs.python.org/3/library/getpass.html#getpass.getuser)) in the name of a temporarily generated NPM package. As `@` is not a valid character for an NPM package name, the above error occurs.

**To Reproduce**

Set `LOGNAME` to a username with an `@` character.

```sh
# This fails:
LOGNAME=alice@example.com pyright-langserver --stdio
 
# This works as expected:
LOGNAME=alice pyright-langserver --stdio
```

**Expected behavior**

The language server starts up no matter what the username is.

**Screenshots or Code**

This is the relevant part of `langserver.py`:

```python
from getpass import getuser

def get_temp_dir() -> Path:
    try:
        suffix = f'.{getuser()}'
    except Exception:
        suffix = ''

    return Path(tempfile.gettempdir()) / f'pyright-python-langserver{suffix}'
```

**VS Code extension or command-line**

Command-line (installed with `pip`)

**Comment by umurdualima** [comment]
The error message "npm ERR! Invalid name: "
***@***.***"" suggests that you are trying
to set an invalid name for a package in your Node.js project. The name of
an npm package must be less than 214 characters and only contain lowercase
letters, numbers, and hyphens. The "@" symbol and dots are not allowed in
package names, which is why the error message is being generated. To
resolve this issue, you should choose a different name for your package
that follows the naming convention.

Pada tanggal Rab, 1 Feb 2023 pukul 17.59 Debby Pramana <
***@***.***> menulis:

**Comment by Gobot1234** [comment]
This should probably be submitted to the actual repo for the pyright PyPi project https://github.com/RobertCraigie/pyright-python no?

**Comment by erictraut** [comment]
As @Gobot1234 mentioned, this should be submitted to the [pyright PyPi project](https://github.com/RobertCraigie/pyright-python) which is maintained by Robert Craigie.
