### ISSUE TITLE
Infer `Callable` shape for rhs of `+=` when `__iadd__` accepts a `Callable[]`

### ISSUE THREAD

**Issue by cspotcode** [microsoft/pyright#4583]
**Is your feature request related to a problem? Please describe.**

I have implemented an event subscription mechanism that can be used like this:

```python
object.event += lambda arg_a: arg_a.field
object.event.append_listener(lambda arg_a: arg_a.field)
```

However, the type of `arg_a` does not infer in the `+=` usage, only for `append_listener`.  It would be nice to get type inference in both cases.

Here is a complete reproduction:

```python
from __future__ import annotations

from typing import Any, Callable, cast, ParamSpec

P = ParamSpec('P')

def decorator(obj, type=None):
    return Descriptor()

class Descriptor:
    def append_listener(self, handler: Callable[[Foo], Any]) -> Descriptor:
        return self

    def __iadd__(self, handler: Callable[[Foo], Any]) -> Descriptor:
        return self
    
class Foo:
    field: int

class Reproduction:
    foo = Descriptor()

reproduction = Reproduction()

reproduction.foo.append_listener(lambda infers_correctly_as_foo: infers_correctly_as_foo.field) # <-- tab completion suggests `field`
reproduction.foo += lambda does_not_infer_correctly: does_not_infer_correctly.f # <-- tab completion does not work here
```

**Describe the solution you'd like**

It would be nice if the parameter type for `__iadd__` was used to apply inference for the right-hand-side of a `+=`.  As far as I know, `+=` and `.append_listener(` are equivalent, so type-checking can apply the same inference in both cases.

**Additional context**

**Comment by erictraut** [comment]
This would be a significant change to support this, and implementing this would likely break other more common use cases. Currently, pyright doesn't support bidirectional type inference for binary operator magic methods (like `__iadd__`). It always evaluates the type of the left and right operands before evaluating the operator. This is done because of the complex interactions between normal and "right" variants of operators (e.g. `__add__` and `__radd__`).

For these reasons, it's unlikely we'd implement the requested support. I'm going to close the request for now, but we could revisit in the future if there is sufficient signal from pyright users.

**Comment by cspotcode** [comment]
I see, thanks for the explanation.  I'd been focused on `__iadd__` and had not realized how complicated it is to consider `__add__` and `__radd__`.  I didn't even know `__radd__` was a thing.
