### ISSUE TITLE
No error report when a function or lambda captures yet-to-be-defined variables

### ISSUE THREAD

**Issue by Tomaz-Vieira** [microsoft/pyright#4591]
**Describe the bug**
A function or lambda can capture variables that have not yet been defined, causing a runtime exception if called before the variable definition.

**To Reproduce**
```python
# pyright: strict
my_lambda = lambda: k
print(my_lambda()) # NameError: free variable 'k' referenced before assignment in enclosing scope
k = 123
```
or
```python
# pyright: strict
def inner() -> int:
    return k
print(inner()) # NameError: name 'k' is not defined
k = 456
```

**Expected behavior**
An error on the usage of `k` in the function/lambda's body

**VS Code extension or command-line**
pyright extension version 1.1.292

**Comment by erictraut** [comment]
This is by design. Static type checkers evaluate execution contexts independently of each other. The lambda's execution context is separate from that of the context in which it is defined. The order of execution for a lambda (or any function, for that matter) cannot be determined statically in the general case.
