### ISSUE TITLE
issubclass(t, u) causes t to change from "Type[V]" to "type*", losing the type argument

### ISSUE THREAD

**Issue by kyle-query** [microsoft/pyright#4608]
**Describe the bug**

Passing a variable `x` to `issubclass(x, ...)` causes pyright to infer `x: type`, even though it previously was annotated `x: Type[V]`, where `V` is a type variable.

**To Reproduce**

```python
from typing import Generic, Type, TypeVar

V = TypeVar("V")

class Test(Generic[V]):
    def foo(self, t: Type[V]) -> None:
        a = t # Type[V]

        if issubclass(t, int):
            return

        b = t # type*
```

**Expected behavior**

It seems like pyright allows `x: Type[X]` to be assigned to `y: type` because it permits the `issubclass(__cls: type, ...)` call. That's what I would expect; however, I don't think pyright should infer `x: type`.

**VS Code extension or command-line**

Neovim + pyright 1.1.293

**Comment by erictraut** [comment]
This is by design. The narrowed type in this case is a "conditional type" — effectively an intersection between the original type (`type[V]`) and the type `type[int]`. This is why you see the type `type*`. The asterisk implies that it's a conditional type.

For more details about conditional types, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#constrained-type-variables-and-conditional-types).
