### ISSUE TITLE
Type issue with __set__ dunder method

### ISSUE THREAD

**Issue by AiroPi** [microsoft/pyright#4610]
**Describe the bug**
When typing `__set__` method (with a list[union] type), pyright seems confuse.
It says `list[int]` isn't compatible with `list[int | str]`
MyPy hasn't problem here.

**To Reproduce**
```py
class Test:
    def __set__(self, instance, value: list[str | int] | None):
        pass

class Foo:
    test = Test()

foo = Foo()

foo.test = [1]  # warn
```

**Expected behavior**
No warning

If your code relies on symbols that are imported from a third-party library, include the associated import statements and specify which versions of those libraries you have installed.

**VS Code extension or command-line**
Extension, but also reported within the playground :
https://pyright-playground.decorator-factory.su/?gzip=H4sIAKyZ5mMC_y2NvQqAMAyE9zxFRgURXAVXRyc3kVJqCkJpxEQnH974c8txfNxdSF4ERxJtAU0LRXROSJ0rhFKscM2iPgeq8PTpoBbTKjqJ7ngZ09ls4Ezl13-02SRAeJd75g-oXWD3PhUlQGS2ZPQP9c-nZoYbK768CJQAAAA%3D

**Comment by erictraut** [comment]
Yes, this is by design. The expression `[1]` evaluates to type `list[int]`, and this is not type compatible with `list[str | int]`. Bidirectional type inference is not used for `__set__` methods. Adding such support would require a major rewrite of a very complicated section of pyright, so it's not something we're likely to do.
