### ISSUE TITLE
`analyzeUnannotatedFunctions=false` causes autoimport/autocomplete to not work inside unannotated functions

### ISSUE THREAD

**Issue by smackesey** [microsoft/pyright#4611]
**Is your feature request related to a problem? Please describe.**

We just transitioned our CI to `pyright` from `mypy` at [Dagster](https://github.com/dagster-io/dagster). As a transitional step, we have set `analyzeUnannotatedFunctions=false` in our shared repo config to match mypy's behavior-- without this setting, we still have thousands of type errors.

Our goal in turning off `analyzeUnannotatedFunctions` was to suppress type errors from unannotated functions. But an unexpected side effect has been that language server features like autocomplete and autoimport no longer work inside unannotated functions.

I wasn't sure whether this was intentional or not-- either way, it significantly hampers pyright's functionality when running as a language server with `analyzeUnannotatedFunctions=false` (which we do to retain parity between CI errors and what is seen in editor diagnostics).

**Describe the solution you'd like**

Ideally `analyzeUnannotatedFunctions=false` just suppresses errors and doesn't interfere with indexing symbols or prevent autocomplete from working inside an unannotated function.

**Comment by erictraut** [comment]
This is by design. When you specify `analyzeUnannotatedFunctions`, pyright doesn't perform any type analysis within these functions. The main reason I added `analyzeUnannotatedFunctions` was not to suppress errors but rather as a performance optimization. That means you don't get the benefits of any language server features that depend on type analysis, such as hover text, completion suggestions, etc. You can't have your cake and eat it too. :)
