### ISSUE TITLE
Give warnings on invalid type/pyright comments or config values

### ISSUE THREAD

**Issue by jakkdl** [microsoft/pyright#4630]
**Is your feature request related to a problem? Please describe.**
As i noted in #4617 I experimented with `pyright: basic, someflag=value` and `type: ignore`, and was occasionally confused when pyright didn't give any type of warnings when I give invalid configurations.

**Describe the solution you'd like**
Give warnings / information in some or all of the following scenarios:
1. A `# type: ignore` not at the top of the file, so it does nothing.
2. A `# pyright: xxx` comment, where xxx is not "basic" or "strict"
3. A `# pyright: xxx someflag=somevalue` comment, where `someflag` is not a valid flag and/or `somevalue` is not a valid value for that flag. ~~as if that invalid value was in the config~~
4. Huh, I'm really surprised that invalid config lines (in a `tool.pyright` section in a pyproject.toml file) aren't treated as errors either.

**Additional context**
I suppose there might be conflicts with other tools on the 1st one (although PEP484 is quite explicit about that), and 2-4 might be hard depending on how the config parsing is set up, but I tried searching for an issue about this and didn't find any - so thought it worth bringing up as a QoL.

**Comment by erictraut** [comment]
There is already an option called `reportUnnecessaryTypeIgnoreComment` that reports unused or unnecessary `# type: ignore` or `# pyright: ignore` comments. That covers item 1 in your list.

Item 4 is not really possible because pyright isn't a language server for `.toml` files, so it cannot report such errors via the LSP interface. It does report configuration value errors through its log output. Plus, if you use the JSON form of the configuration file (pyrightconfig.json), pyright ships with a JSON schema, and VS Code (and perhaps other editors?) will provide validation and completion support for the config file. There is no equivalent for `.toml` files. It is for this reason that I personally prefer `pyrightconfig.json` over `pyproject.toml`.

I think that 2-3 are worth considering.

**Comment by erictraut** [comment]
I've implemented 2 and 3 from your list above. This will be included in the next release.

**Comment by jakkdl** [comment]
Ah, I assumed `strict` would've enabled that. It makes sense that `type: ignore` aren't checked even with `strict` due to tool differences, but maybe would make sense to split off `pyright: ignore` into a separate diagnostic rule that's enabled with `strict`.

Makes sense that toml files are tricky, although I randomly checked the other project we're configuring with toml, and https://github.com/codespell-project/codespell does throw errors on unrecognized arguments - though they're parsing it with argparse.

Thanks for the quick implementation of 2+3! :rocket:

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.294, which I just published. It will also be included in a future release of pylance.
