### ISSUE TITLE
Pyright doesn't detect newly added modules (modules that were added to the working directory after the language server had started) unless I restart the language server.

### ISSUE THREAD

**Issue by anthony-S93** [microsoft/pyright#4635]
**Describe the bug**
I am using Pyright on Neovim (v0.8.3) alongside Neovim's native lsp. If I add a new file to my project directory when Pyright is running and then try to import that new module in a file, Pyright reports an error—it is as if Pyright couldn't see that new file.  

**To Reproduce**
Let's say I have the following directory structure: 

![2023-02-15-000727_480x244_scrot](https://user-images.githubusercontent.com/69449791/218792781-bcda380d-6937-46df-a6af-39c4f8ac95f5.png)

If I open `test.py` with Neovim and try to import `mod.py`, everything works as expected (the completion engine detects the module `mod`; and Pyright reports no errors).  

![2023-02-15-001112_504x274_scrot](https://user-images.githubusercontent.com/69449791/218793772-fedbe70f-bf4e-49c6-b853-e6d3e3e255a2.png)

Let's now add a new module into the project directory while keeping the neovim and Pyright session running.
 
![2023-02-15-001415_757x1044_scrot](https://user-images.githubusercontent.com/69449791/218794469-91f84dac-d27d-40c1-abb9-38543213e6b3.png)

Next, I will try to import `newmodule.py` using the same neovim and Lsp session.  And, as can be seen from the following screenshots, the completion engine doesn't detect the `newmodule.py` file, and Pyright reports that the import could not be resolved.

![2023-02-15-001703_417x204_scrot](https://user-images.githubusercontent.com/69449791/218795220-085383c7-750c-44ea-9ecd-8c0459f23451.png)

![2023-02-15-001812_714x182_scrot](https://user-images.githubusercontent.com/69449791/218795541-d99b1bbb-9a10-4d5d-ae65-3708a2433001.png)

If I close neovim and open a new neovim session (or restart the language server with `:LspRestart`), Pyright is able to detect `newmodule.py` again. 

**Expected behavior**
I expect Pyright to be able to watch for any changes made to the project directory. 

**VS Code extension or command-line**
I am running Pyright using Neovim's native LSP. 

**Additional context**
This doesn't appear to be an issue with Neovim's [lspconfig plugin](https://github.com/neovim/nvim-lspconfig). Other language servers (such as jdtls) works expected with `nvim-lspconfig`. Only Pyright has this issue AFAIK. But, just in case, I have also reported this issue to the devs over at `nvim-lspconfig`. The post can be found [here](https://github.com/neovim/nvim-lspconfig/issues/2460).

**Comment by erictraut** [comment]
For a language server to know about file creations or deletions, it needs to make use of a facility called a "file watcher". This allows it to receive events from the underlying file system and respond accordingly. There are two main ways that language servers can use a file watcher: 1) install their own, or 2) leverage a common file watcher capability built in to the client (editor). Pyright used to install its own (technique 1), but this was problematic because many file systems allow a limited number of file watcher registrations per process, and we would often hit this limit. We switched to option 2, which allows all language servers to share a common file watcher in the client.

It sounds like perhaps neovim or its LSP plugin does not support the file watching mechanism. It works fine with VS Code.

The capability that we rely on is `capabilities.workspace.didChangeWatchedFiles.dynamicRegistration`. If the client doesn't support this capability, then pyright won't be able to respond to file watcher events. Please check with the lspconfig plugin maintainers to see if they would consider adding this capability.

**Comment by anthony-S93** [comment]
@erictraut Thank you for clarifying and for the detailed explanation. It is confirmed that neovim's native lsp client indeed doesn't support `capabilities.workspace.didChangeWatchedFiles.dynamicRegistration`. However, it is currently being worked on. https://github.com/neovim/neovim/pull/21293
