### ISSUE TITLE
Object attribute cannot be used for type declaration

### ISSUE THREAD

**Issue by rhynzler** [microsoft/pyright#4646]
## Environment data

-   Language Server version: 2023.2.30
-   OS and version: Manjaro 22.0.3
-   Python version: 3.10.9

## Description

Some libraries like Flask-SQLAlchemy embed certain classes and types in a main instance that is accessed from other files in the application.

When updating the version of `Pylance` (2023.2.21 -> 2023.2.30), an approach similar to the following stopped working: When a data type or class is assigned to an attribute of an instance, It cannot be used for the declaration of a type of a variable. The following code demonstrates the above:

![Screenshot_20230216_131557](https://user-images.githubusercontent.com/70046048/219452999-0a9d8ce4-4238-4cd1-942e-4c370a6e4430.png)

It should be noted that the setting of the `A_class` attribute of `B` is done dynamically (without explicitly defining it in the `__init__` method as in the demo) and to detect the type of the attribute, the definition of class `B` was done using stubs.

**Comment by erictraut** [comment]
No, this isn't a regression. Variables are not allowed in type annotations, regardless of whether they are local or imported. Pyright previously contained a bug where it didn't properly flag an error when an imported variable was used in a type annotation. That was recently fixed.

In the example above, the statement `db = SQLAlchemy(app)` is assigning a value to a variable called `db`. Since you cannot use a variable in a type annotation expression, you should receive an error if you attempt to use `db` in such an expression.
