### ISSUE TITLE
Unpacking iterable into function incorrectly generates an error

### ISSUE THREAD

**Issue by Gobot1234** [microsoft/pyright#4651]
**Describe the bug**
Unpacking an iterable into a function call always generates an error

**To Reproduce**
https://pyright-playground.decorator-factory.su/?gzip=H4sIAFmF72MC_0tJTVNIy8_XKC1OLdJRAJFGOgpJiXl5qSmaVlwKQKCnp8fFxQVSoxVtqKNgFKuj4JaYU5yqyQUAzz7SZzwAAAA%3D

**Expected behavior**
No error to show up, can be avoided by passing banned=False to the snippet above.

**VS Code extension or command-line**
pyright 1.1.293

**Comment by erictraut** [comment]
This is by design. Pyright assumes that an unpacked operator used for call argument and an operand whose type does not provide a known length (such as `list[int]`) will fill all remaining positional arguments. If you use a tuple of known length, pyright will apply the unpack operator only for the specified number of parameters.

```python
foo(*(1, 2), False)
```

Mypy makes the same assumption and produces the same error here.
