### ISSUE TITLE
Is it possible to disable type inference?

### ISSUE THREAD

**Issue by Lunarmagpie** [microsoft/pyright#4657]
**Is your feature request related to a problem? Please describe.**
I prefer to not have type inference in my projects at all. 
Is it possible for me to disable pyright's type inference for function return values, instance variables, class variables, and globals? I couldn't find anything in the config docs. Note I am using `typeCheckingMode = "strict"` so I didn't expect this feature to be enabled.

**Comment by erictraut** [comment]
We previously had a request for a way to disable return type inference. After much internal discussion, we decided against implementing this because it would provide little or no value.

We've never before received a request to disable all type inference. We'd be very unlikely to ever implement such an option. Doing so would do nothing to increase type safety, so it would simply generate unnecessary noise.

You are welcome to provide type annotations for return types, instance variables and class variables in cases where you want, but in many cases they are completely unnecessary and add no value.
