### ISSUE TITLE
Untyped constructor causes `assert_type()` to fail

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#4694]
**Describe the bug**
`assert_type()` reports there is a mismatch between a class and itself

**To Reproduce**
```python
from typing_extensions import assert_type


class DecimalArray:
    def __init__(self, values) -> None:
        self._values = values


def test_constructor() -> None:
    arr = DecimalArray([1, 2])
    reveal_type(arr)
    reveal_type(DecimalArray)
    assert_type(arr, DecimalArray)

```
pyright 1.1.295 (command line) with python 3.10 reports:
```text
test_decimal.py:12:17 - information: Type of "arr" is "DecimalArray"
test_decimal.py:13:17 - information: Type of "DecimalArray" is "Type[DecimalArray]"
test_decimal.py:14:17 - error: "assert_type" mismatch: expected "DecimalArray" but received "DecimalArray" (reportGeneralTypeIssues)
```

**Expected behavior**
No error from `assert_type()`

Note:  If you change `__init__()` to declare `values: list`, then the error goes away, but I think this should work if `values` has no type.

**VS Code extension or command-line**
pyright command line 1.1.295
python 3.10
typing_extensions 4.4.0
O/S Windows 10

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next version.

In case you're interested in the root case, it's because of a special inference feature that pyright implements for classes whose constructors are unannotated. In this case, pyright treats the class as though it's a generic class with one type parameter for each parameter in the `__init__` method. Since constructor parameter values are often assigned to instance variables, the inferred type of these instance variables then takes on the value of the type parameter rather than `Unknown`. In your example, the `DecimalArray` class was internally treated as though it was generic with a single type parameter, and the `assert_type` was comparing the type `DecimalArray[list[int]]` with `DecimalArray[Unknown]`. To fix the bug, the `assert_type` logic needs to ignore this internal type difference.
