### ISSUE TITLE
if-elif vs case-match performance

### ISSUE THREAD

**Issue by excubo-jg** [microsoft/pyright#4728]
**Describe the issue**

Python 3.10 introduces case-match statements. Before, switch case had to be coded with if-elif. pyright evaluates two equivalent code samples with quite different speed before throwing an error (v 1.1.296):

a) if-elif

if a == 1: b = 2
elif a == 2: b = 3
elif a == 3: b = 4
...

Time needed to analyze a file with a cases:
100 Completed in 1.044sec
200 Completed in 1.763sec
300 Completed in 3.59sec
400 Completed in 6.987sec 
500 Completed in 12.368sec
550 Completed in 17.102sec
600 error: Code is too complex to analyze

b) case-match

match a:
    case 1: b = 2
    case 2: b = 3
    case 3: b = 4
...

Time needed to analyze a file with a cases:
100 Completed in 0.977sec
200 Completed in 1.074sec
300 Completed in 1.232sec
400 Completed in 1.44sec 
500 Completed in 1.656sec
550 Completed in 1.788sec
600 error: Code is too complex to analyze

**Expected behavior**
Analyzing match-case structures does not cause exponentially growing processing times and code analysis need not be limited by cyclometric complexity.

**Screenshots or Code**
[elifs.py.txt](https://github.com/microsoft/pyright/files/10889350/elifs.py.txt)
[matches.py.txt](https://github.com/microsoft/pyright/files/10889351/matches.py.txt)

**Comment by erictraut** [comment]
Thanks for the bug report. This will be addressed in the next release. The perf is now comparable between match and if/elif chains.

**Comment by excubo-jg** [comment]
Many thanks for the fix. Changing the code to a sequence of ifs

if a == 1: b = 2
if a == 2: b = 3
if a == 3: b = 4
if a == 4: b = 5

yields for a==550 Completed in 5.705sec and again throws the code too complex error for a == 600. I am a bit amiss about what is driving the complexity in this case. (not opening a new issue for this question)

**Comment by erictraut** [comment]
There are limits to what pyright can analyze in a reasonable amount of time. The challenge is determining whether code meets this complexity threshold before attempting to analyze it. Pyright uses a modified "cyclomatic complexity" calculation based on the number of edges in the code flow graph. If that number exceeds some amount, pyright refuses to analyze any of the code in that function. This is a heuristic, and there are times when it's too conservative, but there are times when it's not conservative enough. I've worked to tune the complexity calculation and threshold, but I haven't found anything better at this point.

If your function has grown to exceed the complexity threshold in pyright, then you should consider refactoring it.

The sequence of `if` statements is much more expensive for pyright to analyze because it needs to explore all combinations of the taken and not-taken code paths, since each `if` statement is independent of all others. This results in a O(2^n) explosion (where `n` is the number of `if` statements). Contrast that to an `if/elif` chain where only one `if/elif` block will be executed rather than an arbitrary combination of blocks. The `if/elif` chain should be O(n) complexity to analyze. There was a performance bug that caused it to be O(n!). That bug is now fixed.
