### ISSUE TITLE
Add configuration option to enable strict enforcement of typing.override (PEP 698)

### ISSUE THREAD

**Issue by NeilGirdhar** [microsoft/pyright#4788]
Will Pyright be implementing the [strict enforcement](https://peps.python.org/pep-0698/#strict-enforcement-per-project) of typing.override described in PEP 698?

**Comment by erictraut** [comment]
I've added a new optional diagnostic check called `reportImplicitOverride`. It's off by default even in strict mode. When enabled, it implements strict enforcement of PEP 698. 

One open question that's not addressed in PEP 698 is whether `__init__` and `__new__` should be exempt from this check. For now, I've opted to _not_ exempt these methods, but I could be convinced that they should be exempted since they are exempt from LSP checks.

**Comment by NeilGirdhar** [comment]
> I've added a new optional diagnostic check called `reportImplicitOverride`.

Oh, my mistake!  Somehow, I missed this when I checked the documentation.

> but I could be convinced that they should be exempted since they are exempt from LSP checks.

I share the same logic.  If you don't exempt them, users will have to always mark them as `@override`, which doesn't seem that helpful?

**Comment by erictraut** [comment]
I'll close the issue once the next version of pyright is published.

**Comment by erictraut** [comment]
This is included in pyright 1.1.300, which I just published. It will also be included in a future release of pylance.
