### ISSUE TITLE
Literal types lost in attributes

### ISSUE THREAD

**Issue by brentyi** [microsoft/pyright#4828]
Hi Eric!

We're running into an issue where an attribute is assigned to a `Literal[]` type in a constructor, but shows up as just `str` when referenced later.

Here's a quick example:

```python
from typing import Literal, reveal_type


def test(a: Literal["a", "b"] = "a") -> None:
    ...


class Test:
    def __init__(self, a: Literal["a", "b"]) -> None:
        self.a = a
        reveal_type(self.a)  # Literal["a", "b"]

    def func(self):
        reveal_type(self.a)  # str
        test(self.a)  # error!
```

If we replace the literal with something like `Literal["a", 0]`, the second `reveal_type()` gives us `int | str`.

Is this intentional?

cc @tancik

**Comment by erictraut** [comment]
Yes, this is by design. The type of instance variable `a` is not declared, so its type is inferred based on assignments. Pyright never infers literal types. After all, if your constructor included the statement `self.a = 0`, you wouldn't expect `a` to have an inferred type of `Literal[0]`. 

Locally, within the constructor, the type is narrowed to a literal type, but outside of the constructor, it takes on its inferred (unnarrowed) type.

If your intent is for `a` to have a literal type, you should declare it as such.

```python
AOrB = Literal["a", "b"]

class Test:
    def __init__(self, a: AOrB) -> None:
        self.a: AOrB = a
```

The reasoning for this is explained, in part, in [this documentation](https://microsoft.github.io/pyright/#/mypy-comparison?id=assignment-based-narrowing-for-literals).

**Comment by brentyi** [comment]
> After all, if your constructor included the statement `self.a = 0`, you wouldn't expect a to have an inferred type of `Literal[0]`.

This makes sense; appreciate the clear example!
