### ISSUE TITLE
Auto-import of Completions no loneger working in 1.1.300

### ISSUE THREAD

**Issue by kassick** [microsoft/pyright#4836]
**Describe the bug**

Up until 1.1.299, when pyright offered as completion a symbol that had not yet been imported, a `import` statement would be added in the file (if `python.analysis.autoImportCompletions` is true)

In 1.1.300, pyright does offer to import the symbol in the completions, but does not add the import statement.

I'm observing this behaviour in emacs with `lsp-pyright-20230225.1118` (https://github.com/emacs-lsp/lsp-pyright/tree/54a2acddfdd7c3d31cb804a042305a3c6e60cf81), which is the latest version.

The issue is present only in 1.1.300. I've tested 1.1.296 though 1.1.299 and none presented the issue.

**To Reproduce**

1.  Type the name of some symbol that has not yet been imported (cursor at `|`)

         def some_function(m: Mapping|)

2.  The editor frontend asks for completions to the language server -- pyright offers a

        Mapping  Auto-import typing (class)
    
    with a description of `from typing import Mapping`

3.  Accept the completion

**Expected behavior**

A import statement is added to the file 

**Screenshots or Code**

[Gravação de tela de 2023-03-24 09-14-17.webm](https://user-images.githubusercontent.com/21071/227530278-6384b216-813b-4e14-8bd7-974ca3e90490.webm)

**VS Code extension or command-line**

Pyright as Language Server to Emacs via lsp-pyright:
- pyright 1.1.300
- lsp-pyright-20230225.1118 (https://github.com/emacs-lsp/lsp-pyright/tree/54a2acddfdd7c3d31cb804a042305a3c6e60cf81)
- emacs 29.0.60 (built from git)

**Additional context**

The logs of the server shown in the screencast (loglevel=`trace`) did not show any message indicating some problem, neither did the editor logs.

I've checked the changelog from 1.1.299 to 1.1.300 for possible changes in this regard, but found nothing obvious. If there has been some breaking change on how clients must handle the server response in this case, please let me know so I can forward the issue to lsp-pyright.

**Comment by erictraut** [comment]
I'm not able to repro the problem you're seeing, at least not in VS Code. Were there any changes to lsp-pyright in this timeframe?

**Comment by erictraut** [comment]
We didn't make any changes to the completion provider logic in 1.1.300 that could explain such a change. The only issue that I see that couple potentially have an impact here is that we upgraded "vscode-languageserver" (a library that handles the LSP protocol from the server side) from a prerelease version of "8.1.0" to the final version.

I recommend reaching out to the maintainers of lsp-pyright and asking them to repro and debug the issue. If it turns out to be a bug in pyright, they can provide details about what issue they're seeing. I'm going to close this bug for now, but I'll reopen if there are additional details to act upon.

**Comment by rouge8** [comment]
I've been seeing similar (intermittent) issues in neovim. No changes in nvim-lspconfig that I know of.

**Comment by rouge8** [comment]
Seems to be working again in 1.1.301
