### ISSUE TITLE
Type narrowing not applied in case of equality

### ISSUE THREAD

**Issue by gramster** [microsoft/pyright#4874]
**Describe the bug**

Might be asking too much, but in this code:

![image](https://user-images.githubusercontent.com/2762632/228988086-f451d307-7177-4aa3-b0ee-8b1fef37eec6.png)

the two fields both have type `datetime|None`, and we narrow one to `datetime`, but then the equality check should also narrow the other as well, so that the `date_diff` function call (which expects two `datetime`s) doesn't get squiggled.

**Comment by erictraut** [comment]
Ah, I see what you mean. Yes, this is not a supported type narrowing pattern. In general, it's unsafe to assume much of anything with respect to the `==` operator because any class can override `__eq__`, and most classes (including the `object` class) accept any `object` argument to the `__eq__` method. So it would be unsafe for a type checker to make type narrowing assumptions in this case.
