### ISSUE TITLE
Type narrowing TypedDict not working on class attribute within inner scope

### ISSUE THREAD

**Issue by tianze0926** [microsoft/pyright#4888]
Type narrowing worked fine with ordinary variables, but not with class attributes within function scopes.

```python
from typing import TypedDict, Literal

class Foo(TypedDict):
    type: Literal['foo']

class Bar(TypedDict):
    type: Literal['bar']

def foo(foo_or_bar: Foo | Bar):
    if foo_or_bar['type'] == 'foo':
        reveal_type(foo_or_bar) # Foo
        lambda : reveal_type(foo_or_bar) # Foo
        def t():
            reveal_type(foo_or_bar) # Foo

class BarClass:
    def bar(self):
        self.foo_or_bar: Foo | Bar
        if self.foo_or_bar['type'] == 'foo':
            reveal_type(self.foo_or_bar) # Foo
            lambda : reveal_type(self.foo_or_bar) # Foo | Bar
            def t():
                reveal_type(self.foo_or_bar) # Foo | Bar
```

Pyright output:

```
pyright 1.1.301
**/test.py
  **/test.py:11:21 - information: Type of "foo_or_bar" is "Foo"
  **/test.py:12:30 - information: Type of "foo_or_bar" is "Foo"
  **/test.py:14:25 - information: Type of "foo_or_bar" is "Foo"
  **/test.py:20:25 - information: Type of "self.foo_or_bar" is "Foo"
  **/test.py:21:34 - information: Type of "self.foo_or_bar" is "Foo | Bar"
  **/test.py:23:29 - information: Type of "self.foo_or_bar" is "Foo | Bar"
```

**Comment by erictraut** [comment]
Yes, this is working as designed. In general, a narrowed type is not retained for inner-scoped functions or lambdas because it is unsafe to do so. Pyright contains some advanced analysis logic that allows narrowed types to be retained for simple captured variables if it can prove that the variable cannot be modified after the inner-scoped function or lambda is defined. This is why you're seeing the value narrowed in function `foo`. In the case of instance variables, there's no feasible way for pyright to prove that it's safe because the instance variable could be written through other code paths. 

Note that mypy doesn't retain narrowed types for any inner-scoped function or lambda under any circumstance.

If you want the type narrowing to apply in the case of `bar`, you will need to assign the narrowed value to a local variable, which can then be captured by the inner-scoped function and lambda.

```python
class BarClass:
    def bar(self):
        self.foo_or_bar: Foo | Bar
        if self.foo_or_bar["type"] == "foo":
            x = self.foo_or_bar
            reveal_type(x)  # Foo
            lambda: reveal_type(x)  # Foo

            def t():
                reveal_type(x)  # Foo
```
