### ISSUE TITLE
`reportMissingSuperCall` should not report an `__init__` that doesn't call `super().__init__()` in a class with no base class (aside from `object`)

### ISSUE THREAD

**Issue by tylerlaprade** [microsoft/pyright#4893]

**Comment by erictraut** [comment]
Why? What is the justification for not calling `super().__init__()` in this case?

The `reportMissingSuperCall` is not enabled by default even in in strict mode, and it's very opinionated in how it works. If you don't like the way it works, you can choose not to enable it.

**Comment by erictraut** [comment]
Actually, looking closer at the code, there's a good reason why `reportMissingSuperCall` requires you to call `super().__init__()` even if the class doesn't have base classes. If the class is combined with other classes in a multi-inheritance hierarchy, calling `super().__init__()` may be important.

Pyright does not report this error if the class is decorated with `@final` because it cannot be used in a multi-inheritance hierarchy in that case.

**Comment by tylerlaprade** [comment]
I see, thanks for the clarification. Just so I understand, the justification is that even if a given class doesn't need to call it, something that inherits from it would need it to? I'm having trouble visualizing what the inheritance tree would look like that requires this.
