### ISSUE TITLE
Pyright accepts illegal import with implicit namespace packages

### ISSUE THREAD

**Issue by adampauls** [microsoft/pyright#4935]
**Describe the bug**

Pyright fails to identify a bad import if it is missing a prefix (example below). I do not know if this bug is related to our use of [implicit namespace packages](https://peps.python.org/pep-0420/) but I know other tools have struggled with them. 

**To Reproduce**
Files: 
```
namespace
└── pkg
    ├── __init__.py
    ├── module1
    │   ├── __init__.py
    │   └── module1.py
    ├── module2
    │   ├── __init__.py
    │   └── module2.py
    └── py.typed
```

with 
```
cat namespace/pkg/module1/module1.py
def module1_def():
   return

cat namespace/pkg/module2/module2.py
# correct: from namespace.pkg.module1.module1 import module1_def
from pkg.module1.module1 import module1_def
def module2_def():
  return module1_def()	
```

Then run `pyright namespace`.

**Expected behavior**
I would expect an error like 

```
 error: Import "pkg.module1.module1" could not be resolved (reportMissingImports)
```

This error happens if there is a misspelling in the import name. Also, `mypy -p namespace` fails with 
```
error: Cannot find implementation or library stub for module named "pkg.module1.module1"  [import]
```

`pyright` will in fact accept deleting `pkg.` as well, but going all the way to `from module1 import module1_def` results in
```
error: "module1_def" is unknown import symbol (reportGeneralTypeIssues)
```

**Additional context**
When running with `--verbose`, I see

```
Search paths for $CWD
  $HOME/.cache/pyright-python/1.1.302/node_modules/pyright/dist/typeshed-fallback/stdlib
  $CWD
  $CWD/typings
  $HOME/.cache/pyright-python/1.1.302/node_modules/pyright/dist/typeshed-fallback/stubs/...
  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11
  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload
  $CWD/.venv/lib/python3.11/site-packages
```

**Comment by erictraut** [comment]
This is by design. Pyright used to be much stricter about its import resolution, but we got feedback from many pyright and pylance users that they wanted it to be more lenient. The import resolution mechanisms in Python are incredibly complex and then depend in part on the working directory at the time you invoke the Python interpreter. Users were often frustrated by the fact that they were able to run their code without errors (by invoking the interpreter from a subdirectory in their project) but pyright would complain about import resolution problems. 

We addressed this feedback by doing additional import resolution attempts when the initial attempt fails. In particular, we attempt to resolve the import starting from each of the directories between the importing file and the root of the project. In your case, the import succeeds when resolved from the `namespace/pkg` directory.

This is a case where we opted to introduce potential false negatives to eliminate a bunch of false positives. I think that's the right tradeoff.

**Comment by adampauls** [comment]
Would it be possible to place a stricter option behind a flag? Although I'm somewhat new to Python, it is my understanding that typical development is done with strong assumptions about where the interpreter is invoked from?

**Comment by adampauls** [comment]
Failing that, am I right that this behavior ought to be documented at https://github.com/microsoft/pyright/blob/main/docs/import-resolution.md?

**Comment by erictraut** [comment]
> Would it be possible to place a stricter option behind a flag

That's something we might consider in the future if there's sufficient signal from pyright users (e.g. in the form of upvotes).

**Comment by adampauls** [comment]
I assume the right thing would be for me to file a feature request then?

**Comment by erictraut** [comment]
No need to file a new issue. This one can serve as the feature request.
