### ISSUE TITLE
Type 'List[str]' cannot be assigned to type 'Union[List[str], List[int]]'

### ISSUE THREAD

**Issue by iansan5653** [microsoft/pyright#497]
**Describe the bug**
In a parent class, I have an abstract method which returns a 2D list of type `List[Union[List[str], List[int]]]`. In the extending class, I override this method with a method that returns type `typing.List[typing.List[str]]`. These should be compatible (a list of lists of strings is assignable to a list of lists of strings or numbers) but Pyright errors.

**Screenshots or Code**
```py
import typing


class Example():
    def sample_function(
            self
    ) -> typing.List[typing.Union[typing.List[str], typing.List[int]]]:
        return [[1]]


class ExtendsExample(Example):
    def sample_function(self) -> typing.List[typing.List[str]]:
        return [["A"]]
```

The error thrown is:
![image](https://user-images.githubusercontent.com/2294248/73553346-c9df1b80-4417-11ea-8d59-7d543d964634.png)

**VS Code extension or command-line**
I'm running the VSCode extension v1.1.21 on VSCode 1.42.0-insiders.

**Comment by iansan5653** [comment]
I'm running into the same issue when attempting to add (concatenate) lists. I would expect if I add a list with a broad type and a list with a specific type, the resulting list would have the broad type. Instead, it errors:
```py
x = [1, 3, "A", "C"]
y = [4, 5]
z = x + y
```
Error:
![image](https://user-images.githubusercontent.com/2294248/73557590-7cff4300-441f-11ea-8564-3007b49de5d4.png)

**Comment by erictraut** [comment]
These are two very different issues. The first one is "as designed". Subclasses that override a method should provide the exact signature that is provided by the base class, not something that is simply runtime compatible. This is very intentional — and a core tenet of good object oriented design patterns. If you don't like this rule, you can disable reportIncompatibleMethodOverride locally in that file (`# pyright: reportIncompatibleMethodOverride=false`).

The second issue is due to the built-in definition for the add operator in the `list` class. It is defined as follows:
```
_T = TypeVar('_T')
class list(MutableSequence[_T], Generic[_T]):
    def __add__(self, x: List[_T]) -> List[_T]: ...
```

Although this might not match your expectations or intuitions, I think Pyright is correctly applying the type rules in this case. I'm going to investigate it more to convince myself of that fact. In the meantime, you can work around the issue by doing the following:
```
x = [1, 3, "A", "C"]
y: List[Union[str, int]] = [4, 5]
z = x + y
```

**Comment by iansan5653** [comment]
I see, thanks for the reply. I knew overriding methods should have matching signatures, but I figured a more specific override would be acceptable. Thanks for the info.

The workaround for the second is what I'll have to do for now, but it does make things a bit awkward as I'll have to create variables where I might not have before. Ie, this is not allowed:
```py
x = [1, 3, "A", "C"]
z = x + [4, 5]
```

**Comment by erictraut** [comment]
I've confirmed that Pyright is doing the right thing here. `List` is a mutable sequence, so element types must match exactly for one list to be compatible with another. In more formal terms, the type parameter for `list` must be invariant for one list to be assignable to the other.

Here's a simplified example that demonstrates why this is the case:
```
a: List[Union[int, str]] = []
b: List[int] = []
a = b # This is an error
b = a # This is also an error
```

**Comment by tlelson** [comment]
Thanks for the explaination @erictraut. On this and other issues you've been extremely patient.

In your above example I can see how the assignment `b = a` is an error but why is `a = b` one?

**Comment by JelleZijlstra** [comment]
Because this would be legal:
```
a: List[Union[int, str]] = []
b: List[int] = []
b = a  # unsafe
a.append("a string")
for x in b:
    print(x + 1)  # boom, x is a str, not an int
```
