### ISSUE TITLE
Provide a way to `resolveAliasDeclaration` even if aliasDecl.path points to `unneeded` file.

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pyright#5025]
**Is your feature request related to a problem? Please describe.**
currently, when [resolveAliasDeclaration](https://github.com/microsoft/pyright/blob/main/packages/pyright-internal/src/analyzer/typeEvaluatorTypes.ts#L396) is called, it internally calls `program._lookUpImport` to follow up `alias` symbol. Since the system is lazy, if it sees the file to follow up is not bound yet (https://github.com/microsoft/pyright/blob/main/packages/pyright-internal/src/analyzer/program.ts#L2887), it will attempt to bind it. but it has this `perf optimization` where it will check whether the file is actually needed (rooted by either user file or opened in editor transitively) and if not, it will just bail out at that point.

this works fine for regular case where all library files are rooted to one of those, but it doesn't work if library symbol we want is not rooted by any of those.

some of examples would be https://github.com/microsoft/pylance-release/issues/3700, or our `go to definition` on pytest builtin fixture which doesn't require `explicit` import statement or if we ever support `find all reference` on closed library files as some user wanted.

This one can also be mixed with [this issue]( https://github.com/microsoft/pyright/pull/5023 ) and cause even more headaches.

**Comment by erictraut** [comment]
If I understand you correctly, you're talking about a case where the specified file is not explicitly imported anywhere. If this file is resolved, we'd need to create a `SourceFile` object for it. Would you expect that the file would be added to the program? I think it would need to be, but I'm not sure what its lifetime would be.
* It can't be considered a "tracked" file. Tracked files are explicitly imported, and if their "importedBy" count drops to zero, they are automatically removed from the program.
* It can't be considered a "shadowed file" because their lifetime is defined by the file they are shadowing. 
* If it is opened in the editor, it could be marked as "isOpenByClient", and its lifetime would then be controlled by when the user closes the file, but it sounds like you want to follow entire alias chains, even in cases where you don't intend to open the intermediate files in the alias chain. So I'm not sure how that would work.
 
Maybe it's OK to allocate a new (temporary) SourceFile that is not associated with the program, but that will probably break a bunch of existing assumptions in the code. Alternatively, we could create a new "temporary" category of SourceFile (e.g. add an `isTemporary` flag to the `SourceFileInfo` structure) and define the lifetime as "the duration of a `resolveAliasDeclaration` call". We'd then clean up any temporary SourceFile instances at the end of the call.

Any other ideas?

**Comment by heejaechang** [comment]
currently, those `lookup` happens on files that are already loaded by `_updateSourceFileImports` (since we always load in one level deep) so, `SourceFileInfo` should be already there, but in `unbound` state. but when `lookupImport` tries to bind it, `isFileNeeded` will say, it doesn't need it since it is not rooted by any of user files. and bail out. more specifically, symbol table will be empty so, `resolveAlias` bail out.

my thinking was adding `a flag` to `lookupImport` and `resolveAliasDeclaration` so, `bindFile` skip checking `isFileNeeded` if asked.

For lifetime, I believe these `SourceFileInfo` will go away when `removeUnnecessaryFiles` are called next time since it is not rooted by anything.

...

but that said, let's say we added the flag to just bind file when flag is given. when it is fixed with this issue (https://github.com/microsoft/pyrx/pull/3436/) where the library file it is trying to bind is opened in editor already, those `bindFile` call can create wrong `FileInfo` due to wrong flag set in `SourceFileInfo` and `SourceFile`

I feel like pyright shouldn't assume library file can only be brought in by `_updateSourceFileImports`.

**Comment by erictraut** [comment]
> currently, those lookup happens on files that are already loaded by `_updateSourceFileImports`

I don't think I follow you. We're talking about resolving files that are not explicitly imported, so `_updateSourceFileImports` won't know about these files. The file that contains a pytest fixture, for example, won't be added through `_udpateSourceFileImports` because it's not explicitly imported by any files.

I'm OK with adding a flag to `lookupImport` and `resolveAliasDeclaration`. Rather than adding one boolean parameter, I'd prefer to add an `options` parameter that references an object. That will allow us to easily add more flags in the future if necessary.

I think we should be careful how and where we use this flag. Using it for implicit imports (e.g. for pytest fixtures) is fine. Using it to open up random files whose paths happen to be specified in string literals like in [this feature request](https://github.com/microsoft/pylance-release/issues/3700) is much more problematic. We shouldn't be adding random files to the program. They should be treated as 

> I feel like pyright shouldn't assume library file can only be brought in by _updateSourceFileImports.

The challenge is that all other code paths that add source files (e.g. `setFileOpened`, which is called when a file is opened in the editor) do not have the necessary information to properly set the `isThirdPartyPyTypedPresent` flag. This flag is available only when we go through the import resolver. So, we might be able to set `isThirdPartyImport` properly for some random file that is opened in the editor, we won't be able to set `isThirdPartyPyTypedPresent` correctly, and that will lead to its own set of problems. That's why I think it's best if these files are added to the default workspace rather than the project's workspace if they are opened in the editor.

**Comment by heejaechang** [comment]
> I'm OK with adding a flag to lookupImport and resolveAliasDeclaration. Rather than adding one boolean parameter, I'd prefer to add an options parameter that references an object. That will allow us to easily add more flags in the future if necessary.

will do.

> We're talking about resolving files that are not explicitly imported, so _updateSourceFileImports won't know about these files.

sure, for my specific case, to call `resolveAliaseDecls` I need a `aliasDecl` at the first place, to get it, I need to parse a file that has the `alias symbol`. by parsing the file through `program`, it will do `updateSourceFileImports` for the file I got `aliasDecl` from. that means `SourceFileInfo` for the `lookupImport` (one pointed by aliasDecl.path or implicitImport) will be already there.

that's what I meant.

> the challenge is that all other code paths that add source files (e.g. setFileOpened, which is called when a file is opened in the editor) do not have the necessary information to properly set the isThirdPartyPyTypedPresent flag

ya, so, I was looking to see whether I can get one without calling `resolveImport` to get `ImportResult`, and we actually already call `_getImportNameForFile` everytime we create SourceFileInfo. and it actually uses `ImportResolver.getModuleNameForImport` and that seems to have enough data to figure those flags out.

might be wrong, but wondering whether we can change `getModuleNameForImport` to return those flags.
