### ISSUE TITLE
Expand type variables in generic NamedTuple and TypedDict created with the function call syntax

### ISSUE THREAD

**Issue by hamdanal** [microsoft/pyright#5078]
**Describe the bug**
Generic `NamedTuple` and `TypedDict` created with the function call syntax do not expand their type variables.

**To Reproduce**
Run pyright on the code snippet below.

**Expected behavior**
No errors and all types revealed as `int`.

**Screenshots or Code**
```python
from typing import Generic, TypeVar
from typing_extensions import NamedTuple, TypedDict

T = TypeVar("T")

NT1 = NamedTuple("NT1", [("x", int), ("y", T)])
TD1 = TypedDict("TD1", {"x": int, "y": T})

class NT2(NamedTuple, Generic[T]):
    x: int
    y: T

class TD2(TypedDict, Generic[T]):
    x: int
    y: T

nt1 = NT1(1, 2)
nt2 = NT2(1, 2)
td1 = TD1(x=1, y=2)  # mypy: ok, pyright: error: Argument of type "Literal[2]" cannot be assigned to parameter "y" of type "T@TD1" in function "__init__"
td2 = TD2(x=1, y=2)

reveal_type(nt1.y)  # mypy: int, pyright: T
reveal_type(nt2.y)  # mypy: int, pyright: int
reveal_type(td1["y"])  # mypy: int, pyright: T@TD1
reveal_type(td2["y"])  # mypy: int, pyright: int
```

**VS Code extension or command-line**
```console
$ pyright --version
pyright 1.1.306
```

**Comment by erictraut** [comment]
Pyright is correct here. You're using a `TypeVar` in an incorrect manner. TypeVars must be associated with a class or function scope using a `class` or `def` statement.

If you want to define a generic `NamedTuple` or `TypedDict`, you need to use the class form. You cannot use the function syntax because there's no way to bind the TypeVar with the resulting class.

**Comment by erictraut** [comment]
That's correct. The class form of `TypedDict` requires that all key names are legal identifiers.
