### ISSUE TITLE
Sqlachemy "Session" cannot be used with "with" because it does not implement __aexit__ (reportGeneralTypeIssues) error in pyright 1.1.306 but not in pyright 1.1.266 

### ISSUE THREAD

**Issue by vamshiaruru32** [microsoft/pyright#5081]
**Describe the bug**
Hi, I recently updated pyright version's in one of my code bases from 1.1.266 to 1.1.306, and all of a sudden I am seeing this new error. Note that I am using **sqlalchemy2.0** (exact version: sqlalchemy = "^2.0.9") so typing support is in built to the library.

**To Reproduce**
put this code in a file, lets say test.py
```python
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

engine = create_async_engine(
    "<database_dsn>",
    pool_size=10,
    pool_pre_ping=True,
)

AsyncSessionLocal = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)  # type: ignore


async def test():
    async with AsyncSessionLocal() as session:
        raise NotImplementedError()

```
Then run
```
pyright test.py
```

**Expected behavior**
Behaviour across versions must be consistent

**Screenshots or Code**
With latest pyright:

<img width="982" alt="Screenshot 2023-05-09 at 8 36 51 AM" src="https://user-images.githubusercontent.com/101561852/236984030-48282086-3d1d-42ae-adb7-158023b6d985.png">

With older pyright:

<img width="982" alt="Screenshot 2023-05-09 at 8 39 53 AM" src="https://user-images.githubusercontent.com/132186130/236984640-41f9fd97-b66b-4dee-8739-e932800bfec5.png">

**VS Code extension or command-line**
Using as command-line tool, exact versions being checked or 1.1.266 and 1.1.306

Please let me know if I am missing something, thanks in advance.

**Comment by erictraut** [comment]
I recently changed the behavior of overload evaluation in error conditions, and that's causing the difference in behavior that you're observing. I don't consider this a bug in pyright.

The root of the problem is in the type error that you suppressed with a `# type: ignore` in your code. If you remove this comment, you'll see that you are calling `sessionmaker` with arguments that are not valid according to the type information in SQLAlchemy. I suspect this is a bug in the SQLAlchemy implementation. It looks like `session.py` should include `AsyncEngine` in the `SessionBind` union and in the bound for the `_S` TypeVar. If I make those two changes in the SQLAlchemy sources, both type errors in your code go away. I recommend that you report the problem to the maintainers of SQLAlchemy.
