### ISSUE TITLE
Allow specifying pythonPath for pyright CLI

### ISSUE THREAD

**Issue by moskupols** [microsoft/pyright#5111]
**Is your feature request related to a problem? Please describe.**
In my project we generally use a custom installation of CPython which is not found as `python` or `python3` on PATH.
This works well with pyright language server since there we can just configure python.pythonPath to the interpreter we want. This does not seem to be possible with pyright CLI.

**Describe the solution you'd like**
Add a new command line option `--python-path` which conflicts with `--venv-path`. Use the value given there the same way language server uses python.pythonPath variable from the server config.

**Comment by erictraut** [comment]
I've implemented the proposed solution, although I've called the option `--pythonpath` instead of its hyphenated counterpart.  The current command-line options are inconsistent in their use of hyphens, and I've deprecated the hyphenated versions in favor of non-hyphenated.

This functionality will be included in the next release.

**Comment by erictraut** [comment]
This is included in pyright 1.1.309, which I just published. It will also be included in a future release of pylance.
