### ISSUE TITLE
Renaming imports

### ISSUE THREAD

**Issue by last-partizan** [microsoft/pyright#5148]
**Is your feature request related to a problem? Please describe.**
Today i was trying to rename imported name, but instead pyright renamed a class.

```
from app.models import Book
```

I tried to rename it to `SpecialBook`, and instead of changing import to `Book as SpecialBook`, pyright renamed my target class.

**Describe the solution you'd like**
I would like it to change import, not target class.

**Additional context**
This would be expected behaviour, becouse other LSP servers (like volar for vue) are using similar approach.

**Comment by JanEricNitschke** [comment]
I feel like this is a pylance and not a pyright issue, right?

**Comment by erictraut** [comment]
Pyright is focused on type checking capabilities. It has some basic language server features, but features like the one you're asking for here are out of scope for pyright. If you're a VS Code users, I recommend using pylance, which is Microsoft's fully-featured language server that builds on pyright's type checking features. Pylance has more sophisticated renaming capabilities, and you can submit additional functionality requests in the [pylance-release project](https://github.com/microsoft/pylance-release).

**Comment by last-partizan** [comment]
> I feel like this is a pylance and not a pyright issue, right?

No, this is pyright issue. I don't use VS Code, but it works the same way in VS Code. This tells me, that code for renaming is pyright specific, and just reused by pylance.

@erictraut does it makes sense to create issue in pylance project, if i interested in changes to pyright rename capabilities?

**Comment by erictraut** [comment]
Pyright is focused on type checking features and serves as the foundation for other language servers that want to build on top of it. Pylance is one such language server. We have no plans to add new language server features to pyright directly, and we're not accepting any PRs for new language server features. 

The feature you're requesting here falls in the gray zone between a bug fix and a feature request. If the pylance team wants to treat it as a bug fix in the existing pyright "rename" feature, then you would benefit from that bug fix. I think it's more likely that they'll see this as a new language server feature and will consider it for inclusion in pylance only. 

I think it's worth filing an issue in the pylance-release project to get their feedback. If they decide that it's a new feature rather than a bug in the current pyright implementation, then your only recourse is to appeal to the maintainer of your editor's pyright LSP plugin. For example, the maintainer of [coc-pyright](https://github.com/fannheyward/coc-pyright), which supports pyright in neovim, has added additional language server features on top of the basic features provided by pyright.
