### ISSUE TITLE
Passing `Callabe[[], NoReturn]` to a function expecting `Callable[[], Awaitable[None]]` passes type checking.

### ISSUE THREAD

**Issue by rowillia** [microsoft/pyright#5217]
**Describe the bug**
Passing `Callabe[[], NoReturn]` to a function expecting `Callable[[], Awaitable[None]]` passes type checking

**To Reproduce**

test_noreturn.py:
```python
from typing import Awaitable, Callable, NoReturn


def no_return():
    raise Exception("Oh No")

def return_none() -> None:
    raise Exception("Oh No")

async def await_thing(func: Callable[[], Awaitable[None]]) -> None:
    await func()

async def main() -> None:
    await await_thing(no_return)
    await await_thing(return_none)
```
`pyright test_noreturn.py`

**Expected behavior**
An error on line since the return type of that function doesn't implement `__await__`.  Note that changing the return type to `None` correctly flags the error.

**Comment by erictraut** [comment]
This is expected behavior, not a bug. The `NoReturn` type in the Python type system is compatible with all other types. That means `NoReturn` is compatible with `Awaitable[None]`. 

This makes sense if you consider that `NoReturn` implies that the function will never return control back to the caller.

Not surprisingly, mypy generates the same output for the above code snippet.
