### ISSUE TITLE
Union of Literal types

### ISSUE THREAD

**Issue by mgmira** [microsoft/pyright#5227]
**Is your feature request related to a problem? Please describe.**
In the following example 

```python
T1 = TypeVar("T1")
T2 = TypeVar("T2")
StatusT: TypeAlias = Literal["OK", "KO"]


def f(a: T1, b: T2) -> T1 | T2:
    ...


def g(a: StatusT, b: StatusT):
    return f(a, b)


reveal_type(g)
```

The function g is inferred as `(a: Literal['OK', 'KO'], b: Literal['OK', 'KO']) -> str`.
As if pyright decide to prefer [join over union](https://microsoft.github.io/pyright/#/mypy-comparison?id=unions-vs-joins) in this case. I couldn't find in the repo anything related to this, or anything that would justify this choice.

**Describe the solution you'd like**
I would like the inferred type of g to be `(a: Literal['OK', 'KO'], b: Literal['OK', 'KO']) -> Literal['OK', 'KO']` in that case.
And more globally the union of `Literal[a1, a2, ...]` and `Literal[b1, b2...]` to be `Literal[a1, a2, ..., b1, b2, ...]`

**Additional context**
pyright version is 1.1.311

**Comment by mgmira** [comment]
Thanks for the explanation. This leads to some counter-intuitive results 

```python
StatusT: TypeAlias = Literal["OK", "KO"]

def first(status_list: Generator[StatusT, None, None]):
    first = next(status_list)  # revealed_type is  Literal["OK", "KO"]
    first_with_default = next(status_list, "OK")  # revealed_type is  str
```

**Comment by mgmira** [comment]
Maybe there should be a difference between an inferred Literal and a Literal that is explicitely annotated as so ?
```python
reveal_type(foo(1))  # i would be surprised if this was Literal[1] indeed
x: Literal[1] = 1
reveal_type(foo(1))   # but not here since this is my intention
```

**Comment by flisboac** [comment]
@erictraut the revealed type of `v2` confuses me. Shouldn't it be `Any`, because `func2` doesn't have any return type declared? I vaguely remember from PEP-484 that any element not annotated with a type would have type `Any`. But I admit I may be wrong here, it has been a long time since I checked for any updates on the type checking rules. (Unless there's some exception for return types, or maybe PyRight is smart enough to analyze the function's implementation to determine the return type?)

Regardless...

> There are tradeoffs to both approaches, but pyright is consistent in how it treats literals.

I agree that consistency is important, but I argue that practicality is even more so. What's the use of a proper TypeAlias or argument/return typing when the type checker refuses to propagate it to provide a better type checking experience?

> Its constraint solver retains them only in cases where there is a constraint that forces them to be retained. In other cases, the type is widened to its non-literal form.

In most cases, this would be a good thing. However, not propagating TypeVar-captured types prevents Pyright from doing a better type checking job in later portions of the code. The end result is a bad user experience.

Moreover, the widening of literals when using a TypeVar defeats its purpose. A TypeVar is used exactly for propagating a type that's not known beforehand. The user defined a literal type for specific values. One would expect those specifications to be respected and passed on, out of the box.

Let's run another example, to justify my argument:

```python
MyValue: TypeAlias = Literal['on', 'off']

def ensure_not_null(x: T | None) -> T: ...
"""Raises an exception if `x` is none, otherwise return `x`."""

def get_value() -> MyValue | None: ...
"""Gets some value of type `MyValue`."""

# Problem 1: Cannot type this as `MyValue` whilst
# assigning the return of any TypeVar-typed function.
# There's absolutely no reason for this limitation.
#
x = ensure_not_null(get_value())

reveal_type(x) # str

# As the type of `x` was inadvertently widened to `str`,
# this erroneous assignment is not caught by the static
# type checker.
#
x = "ON1"
```

I just don't understand Pyright's decision. There're no reasonable justifications given in the documentation, other than just stating that "MyPy is inconsistent." Why is PyRight the better implementation for the users, in this specific case? If anything, PyRight is the surprising (and counterintuitive) implementation here -- regarding specifically the use of TypeVar, of course.

**Comment by flisboac** [comment]
@erictraut What me and the OP were trying to suggest is something else.

My opinion is that the source of a type aliased through a type variable dictates whether widening should occur. Otherwise, the purpose of a properly typed codebase is defeated. For example:

1. If a literal is passed, the type is not directly specified. Therefore, there's no normative source for that type, and it should be widened at the type variable.
2. If any other typed element is passed instead (variable, function call, cast, etc.), and the element is typed, the type is directly specified. It should therefore be preserved and passed along.

Under this scenario, v1 would be correct (typed as `list[int]`), but not v2 and v3, because the inputs to `make_list` are strictly typed as specific literals.

Does that make sense?

> Its constraint solver retains literals in some cases but not in others.

Isn't this exactly what's happening here? You have literals as inputs to the function, and those are dropped because of either invariance or usage of a type variable. Unless type variables are defined as widening constructs (which I'm not sure, tbh), if consistency is to be achieved, literals should always retain its narrower types. So, under the consistency lens, an argument could be made for v1, v2 and v3 to be lists of literals.

Just as a quick note, as of version 1.15.0, MyPy's behaviour is exactly as you describe in the example (https://mypy-play.net/?mypy=latest&python=3.12&gist=c557968d4922a51a2b583f095cfb759e).

**Comment by flisboac** [comment]
@erictraut Thank you so much for even entertaining the idea!

I must admit I'm not knowledgeable enough to understand the nuances of implementing such a functionality. I'm not sure if most of the hurdles come from a theoretical standpoint (e.g. will complicate or prevent static analysis further in ways I'm indeed not foreseeing) or from a more practical standpoint (e.g. related to implementation, capacity to expand the codebase in the future, etc.), or a mixture of both.

(I'm not sure if I can comment here, or if I should comment on the new issue from now on.)
