### ISSUE TITLE
Pyright doesn't show the incompatible fields with decorators with protocol arguments

### ISSUE THREAD

**Issue by Ovsyanka83** [microsoft/pyright#5246]
**Describe the bug**
```python
from typing import Protocol, TypeVar, Callable

class MyProtocol(Protocol):
    foo: str

Self = TypeVar("Self", bound=MyProtocol)


def my_decorator(func: Callable[[Self], None]):
    pass


class MyCls:
    foo: int
    
    # Error is confusing
    @my_decorator
    def bar(self):
        pass

# Expected
def my_func(obj: MyProtocol):
    pass

my_func(MyCls())
```

**Expected behavior**
Look at the error message on the call of "my_func". It specifically describes what the problem is unlike the place with the decorator. 

**VS Code extension or command-line**
Both vscode extension (latest stable pylance) and latest pyright cli. (sorry for no specificity. I can add them later if necessary)

**Comment by erictraut** [comment]
These are very different cases. In the `my_func` example, you're attempting to assign a `MyCls` instance to `MyProtocol`. This fails because `MyCls` doesn't conform to the protocol, and pyright's error message indicates as such.

In the `my_decorator` example, you're trying to do the reverse. You're trying to assign a type of `(self: MyCls) -> None` to `(self: MyProtocol) -> None`, which means that `MyProtocol` is needs to be assignable to `MyCls` (since input parameters are contravariant, and their assignability is swapped). So, in this case, you're attempting to assign the protocol class `MyProtocol` to a concrete class `MyCls`. This doesn't involve protocol matching since it's in the opposite direction, so it wouldn't be appropriate for pyright to report incompatible fields in this case.
