### ISSUE TITLE
Aliasing type names from typing produces confusing messages

### ISSUE THREAD

**Issue by jakebailey** [microsoft/pyright#532]
**Describe the bug**

I'm writing a stub for something which has a class called `Iterator` which conforms to `typing.Iterator`. My first attempt was to import `Iterator` from `typing`, then specify it as a base class, but this seems to produce weird results.

**To Reproduce**

A reduced example:

```python
# pyright: strict
from typing import Iterator

class Image: ...

class Iterator(Iterator[Image]):
    def __init__(self, im: Image) -> None: ...
    def __getitem__(self, i: int) -> Image: ...
```

Gives me a bunch of strange errors on the `Iterator` inside the class list. I then tried something like:

```python
# pyright: strict
from typing import Iterator

_Iterator = Iterator

class Image: ...

class Iterator(_Iterator[Image]):
    def __init__(self, im: Image) -> None: ...
    def __getitem__(self, i: int) -> Image: ...
```

But the results were the same. Go-to-def on `Iterator` (even the one in the import statement itself) produces multiple results, one in the typing stubs an the other in this file, which then let me know what was happening (somehow `Iterator` is _both_ classes).

I can avoid this by not attempting to use the name `Iterator` at all, just fully qualify the typing one or `import as` another name. This is fine.

**Expected behavior**

I would have thought that code flow would have made my use of `Iterator` unambiguous. I know that it's inadvisable to shadow names, and I will just fully qualify the name, but I'm curious if there's something that can be done to make this more obvious. Feel free to re-label this as not a bug.

**Screenshots or Code**

An example of the tooltips:

![image](https://user-images.githubusercontent.com/5341706/74792727-1f6a5380-5273-11ea-989d-01640c7b267d.png)

And when I do the "right" thing and don't shadow and things work out:

![image](https://user-images.githubusercontent.com/5341706/74793008-e5e61800-5273-11ea-984b-a90168e92504.png)

**VS Code extension or command-line**

Extension, 1.1.22.

**Additional context**

**Comment by erictraut** [comment]
Type aliasing in Python is very problematic. I don't think that the authors of the typing support in Python thought that case through very well. Unlike most languages, Python has no "type" keyword to indicate that a type alias is intended. Instead, it uses normal variable assignments. Variable assignments are interpreted within code flow order, but all other type-checking operations occur in arbitrary order, allowing for forward references. Because of this, there are a bunch of cases where use of type aliases produces unexpected or confusing results. I don't know how to resolve this problem without either 1) going back in time and providing feedback on the original typing spec or 2) trying to introduce a new mechanism into the Python spec that doesn't suffer from these problems.

As for your specific issue, I can think of two solutions:
1. The one you already mentioned is to use typing.Iterator
2. Use an "as" clause in your import statement (`from typing import Iterator as BaseIterator`)

**Comment by jakebailey** [comment]
FWIW I don't think `import as` is a solution given the rules around what gets exposed via stubs; importing something "as" will re-expose the value explicitly via the current module so I wouldn't want to do that. Fully qualifying is the thing that works.

I filed this knowing it would be something weird, just wanted to see if you thought there was a way to better indicate that one name is referring two to different things.

**Comment by erictraut** [comment]
That's a good point about "as" being re-exposed. However, if you choose a local alias that starts with "_", it would not be exposed — at least it should probably work that way.

**Comment by jakebailey** [comment]
I think the `_` doesn't matter (the spec only talks about the `as` syntax), but I'm not 100% certain.

**Comment by erictraut** [comment]
The spec isn't all that clear or explicit (about a lot of things), but PEP 8 does indicate that "_" is meant to indicate "private". And if you look in the stdlib typeshed stub files, they clearly use "_" for symbols that are not meant to be exported.

**Comment by jakebailey** [comment]
I was specifically talking about things that were the product of imports, not locally-created names (which are definitely excluded by default), but I do see a few examples in typeshed where they import `_` things with `_` names, so it would appear to be the case.
