### ISSUE TITLE
Regression regarding **kwargs

### ISSUE THREAD

**Issue by mgmira** [microsoft/pyright#5351]
**Describe the bug**
I think there's a regression regarding functions that use **kwargs. In the example below, pyright reports
```
Argument of type "bool" cannot be assigned to parameter "code" of type "str | None" in function "func"
  Type "bool" cannot be assigned to type "str | None"
    "bool" is incompatible with "str"
    Type cannot be assigned to type "None"
```

but the code works fine at runtime.

```python
# pyright: strict

from __future__ import annotations

from typing import Any


def func(code: str | None = None, name: str = "", **options: Any):
    print(code, name, options)


func(
    name="test", **{"fast": True}
)  # Argument of type "bool" cannot be assigned to parameter "code" of type "str | None" in function "func"
```

**To Reproduce**
Steps to reproduce the behavior.

**VS Code extension or command-line**
pyright 1.1.315

**Comment by erictraut** [comment]
This is an intended change in behavior. Both the prior behavior and the new behavior are defensible, but pyright's behavior now matches mypy, which also gives an error in this case.

**Comment by erictraut** [comment]
When an argument passed to a function uses a dictionary unpack operator (`**`) and the operand is a mapping with unknown keys (as opposed to a `TypedDict` where the keys are specified explicitly along with their corresponding value types), the unpacked type is now assumed to apply to all keyword parameters that are not otherwise specified as keyword arguments in the call expression. 

In your code sample, the expression `{"fast": True}` evaluates to the type `dict[str, bool]`. When a dictionary unpack operator is applied, pyright (and mypy) will validate that all target keyword parameters in `func` that are otherwise not specified as keyword arguments accept a value of type `bool`.

As I mentioned above, both behaviors are defensible. And in general, I don't mind deviating from mypy's behaviors if there's a good justification for doing so. However, this behavior difference can lead to different overload matching behaviors, which makes it difficult for library authors to provide overload signatures that work with both mypy and pyright.

You have a couple of options to work around this new behavior:
1. Provide an explicit value for the `code` parameter:
```python
func(code=None, name="test", **{"fast": True})
```
2. Define a `TypedDict` type for the supported options.
```python
class FuncOptions(TypedDict, total=False):
    fast: bool

def func(code: str | None = None, name: str = "", **options: Unpack[FuncOptions]):
    print(code, name, options)

func_options: FuncOptions = {"fast": True}
func(name="test", **func_options)
```

**Comment by erictraut** [comment]
Yes, a positional-only arg is another good workaround.

I've also opened [this enhancement request](https://github.com/microsoft/pyright/issues/5358) which would make it possible to use your original call expression (with no need for a separate annotated variable).
