### ISSUE TITLE
use of nonlocal does not affect type of variable

### ISSUE THREAD

**Issue by zsorizs** [microsoft/pyright#5374]
**Describe the bug**
Using nonlocal in an inner function seems to be ignored in the outer function and pyright comes to a wrong conclusion about the type of the variable.

**To Reproduce**
```python
def outer() -> str:
    var: str|None = None
    exc: Exception|None = None

    def inner():
        nonlocal var, exc
        var = "foo"
        exc = Exception("bar")

    inner()

    if var is None:
        return ""
    else:
        reveal_type(var)

    if exc is None:
        return "no exception"
    else:
        raise exc
```

The `reveal_type(var)` says that var is Never.
`raise exc` gives error that you cannot throw Never.

**Expected behavior**
I would expect for the `reveal_type(var)` to say that var is `str`.
And I would expect for no error for the raise.

**VS Code extension or command-line**
Using pyright from the command line. Version: 1.1.315

**Comment by erictraut** [comment]
This is by design, not a bug.

Static type checkers like pyright, mypy, or the TypeScript compiler do not narrow the type of a variable modified by calls to other execution contexts (subroutines, lambdas, etc.). In the general case, this isn't possible in a static type checker because the dynamic order of execution cannot be determined in the general case. In your particular example, it would be theoretically possible, but it's not something anyone does. 

If you want this to work with static typing, you should avoid side effects in your inner function. For example, you could do this:

```python
    def inner():
        return "foo", exc

    var, exc = inner()
```

**Comment by rmorshea** [comment]
Another option here would be to force Pyright to treat `var` and `exc` as `Optional` with `cast`:

```python
var = cast(str | None, None)
exc = cast(Exception | None, None)
```

This way Pyright won't assume `var` and `exc` are actually `None` until they're assigned.
