### ISSUE TITLE
site-packages path issue

### ISSUE THREAD

**Issue by rrelict** [Microsoft/pyright#54]
**Describe the bug**
Seems like the `site-packages` path can be different.
According to [Python 3 venv spec](https://docs.python.org/3/library/venv.html):
```
It also creates an (initially empty) lib/pythonX.Y/site-packages subdirectory 
(on Windows, this is Lib\site-packages).
```

Also [virtualenv spec](https://virtualenv.pypa.io/en/stable/userguide/) says:
```
Packages installed in this environment will live under ENV/lib/pythonX.X/site-packages/.
```

My reading of this part of the [code](https://github.com/Microsoft/pyright/blob/5cde770e9ddb4de12f2b8f675db7aa124fe378c3/server/src/analyzer/pythonPathUtils.ts#L52-L53) is that only one path is used.
Could you please recheck it?  

  
**To Reproduce**
macOS 10.14
python 3.7
pyright 1.0.8

Create a virtual env with:
```python3 -m venv ~/.venv/dev```

`site-packages` path:
```~/.venv/dev/lib/python3.7/site-packages```

**Expected behavior**
pyright checks the `~/.venv/dev/lib/python3.7/site-packages` patch.

**Comment by erictraut** [comment]
It looks like the current code in Pyright might fail under Windows, but that doesn't explain the problem you're seeing since you're on MacOS. I think it's a configuration issue in your case. You need to tell Pyright two pieces of information:
*venvPath*: The directory that contains your virtual environments (in your case, "~/.venv")
*venv*: The virtual environment you want to use (in your case, "dev")
You can specify both of these in the pyrightconfig.json file, but you can't use shell notation "~", so you'd need to expand the venvPath manually (e.g. "/Users/rrelict/.venv"). You can also specify the venvPath in your VS Code settings, and Pyright will pick it up from there.

**Comment by rrelict** [comment]
Eric, thanks for the datails.

My `pyrightconfig.json` seems correct:
```
{
    "venvPath": "/Users/rrelict/.venv", 
    "venv": "dev"
}
```

venv dir structure is:
```
~/.venv> ls dev/lib/*/
dev/lib/python3.6/:
site-packages

dev/lib/python3.7/:
site-packages
```


VSCode shows a problems output:
```
Import 'sqlitedict' could not be resolved
't' is not bound
Import 'telegram.ext' could not be resolved
```
There are not resolved imports.

To fix it I did a symlink:
```
~/.venv> cd dev/lib/
~/.v/d/lib> ln -s python3.7/site-packages/ ./site-packages
```


After restarting of VSCode the problems output is:
```
't' is not bound
```

It solved my issue with not resolved imports.
As referenced above the problem may be in the `pyright` code:
https://github.com/Microsoft/pyright/blob/5cde770e9ddb4de12f2b8f675db7aa124fe378c3/server/src/analyzer/pythonPathUtils.ts#L52-L53

**Comment by erictraut** [comment]
Ah, it looks like you've installed two python environments (3.6 and 3.7) into the same virtual environment. Pyright found "python3.6" because that's the first that was returned by the file system. The whole purpose of virtual environments is to isolate different python installations, so I think it's considered an error to install two python environments in the same venv. If you really need two versions, you should create two parallel venvs (e.g. "dev36" and "dev37").
