### ISSUE TITLE
inline typeddict causes bare typevar

### ISSUE THREAD

**Issue by GreyElaina** [microsoft/pyright#5410]
**Describe the bug**
```py
X = TypeVar("X")

def p(m: dict[{"a": X}]):
    return m["a"]

reveal_type(p({"a": 1}))  # -> X
```

pylance say: Type of "p({ "a": 1 })" is "X"

**To Reproduce**

**Expected behavior**
return "int" or "Literal[1]"?

**Code or Screenshots**

**VS Code extension or command-line**
pylance latest

**Additional context**

**Comment by erictraut** [comment]
Inlined TypedDicts are not a supported feature in the Python type system. I added provisional support to inform the usability of a proposed inline mechanism. This was added about six months ago. Since then, the discussion about inlined TypedDict forms has quieted down, and no one has moved forward with a PEP. I'll leave the current support in a bit longer, but if there is no further motion within the next few months, I'll remove it from pyright. Please don't write code that relies on this feature because it's likely to be removed or modified.

I don't plan to invest time in extending the feature (e.g. adding support for generics) unless progress is made in formalizing the mechanism.
