### ISSUE TITLE
Namedtuple: unnecessary/incorrect error report (reportGeneralTypeIssues)

### ISSUE THREAD

**Issue by nevzatseferoglu** [microsoft/pyright#5423]
**Describe the bug**
Giving unnecessary error message.

**Expected behavior**
There should not be any error.

**Code or Screenshots**
![Screenshot 2023-07-03 at 01 14 36](https://github.com/microsoft/pyright/assets/43863606/326f3c6f-0178-4385-86b3-0727278af1be)

**Additional context**
[Namedtuple](https://docs.python.org/3/library/collections.html#collections.namedtuple)

According to the namedtuple doc, if the given name is a keyword in Python, it cannot be used. If rename parameter is set as True, it will create _index name for the invalid names.

Shouldn't pyright also scan the namedtuple content based on that rule and don't give an error ?

**Comment by erictraut** [comment]
This is a pretty esoteric feature for a static type checker to support. Mypy doesn't have this functionality, for instance. 

It turned out not to involve that much logic, so I added partial support for `rename=True`. There are still edge cases that won't work, but I don't plan to go any deeper on this issue. I recommend that you avoid using keywords in your named tuple definitions.

**Comment by erictraut** [comment]
This is included in pyright 1.1.317, which I just published. It will also be included in future releases of pylance.
