### ISSUE TITLE
Provide more detailed document by pydoc

### ISSUE THREAD

**Issue by Freed-Wu** [microsoft/pyright#5437]
## This is documents provided by pyright:

![Screenshot from 2023-07-06 23-53-25](https://github.com/microsoft/pyright/assets/32936898/9b2fda71-ad5d-47d2-8b6a-807bf6a11ff0)
![Screenshot from 2023-07-06 23-53-02](https://github.com/microsoft/pyright/assets/32936898/a2df2540-ec45-4422-99b9-dcb938f4f9b1)
![Screenshot from 2023-07-06 23-52-44](https://github.com/microsoft/pyright/assets/32936898/8a506305-fd90-4495-911a-dd7e615fbd76)

## This is documents provided by jedi:

![Screenshot from 2023-07-06 23-52-12](https://github.com/microsoft/pyright/assets/32936898/abcfc05d-7dea-4dd3-92e9-48d1f67c48ed)
![Screenshot from 2023-07-06 23-52-03](https://github.com/microsoft/pyright/assets/32936898/c63d1858-6869-4c31-95c4-948e10a948a9)
![Screenshot from 2023-07-06 23-51-30](https://github.com/microsoft/pyright/assets/32936898/7567efcd-1da5-45d1-b546-837066efd2b3)

These details provided by jedi comes from `pydoc`. **Can pyright provide more detailed document?**

**Comment by erictraut** [comment]
Pyright is a static analyzer. Unlike jedi, it doesn't run the code it analyzes or perform any runtime introspection. This is by design.

Pylance, which is the VS Code language server that builds upon pyright, bundles doc strings for stdlib modules. So if you want this functionality, you can switch to Pylance. We have no plans to include this functionality in pyright, which is focused on type checking. Pyright does include some basic language server features, but it's really focused on type checking.

**Comment by Freed-Wu** [comment]
Oh, I use [coc.nvim](https://github.com/neoclide/coc.nvim) which only have extension for `pyright` but doesn't have any extension for `pylance`. :cry:
