### ISSUE TITLE
High CPU usage using neovim on MacOS Ventura

### ISSUE THREAD

**Issue by fellipeh** [microsoft/pyright#5459]
I'm using pyright with AstroNVim, and with one of my project, which has lot of files, `pyright`  is consuming a lot CPU, see:
![image](https://github.com/microsoft/pyright/assets/2904206/9412c01c-a583-4ac7-9e16-d3b27d5de513)

I'm using MacOS Ventura, latest update, and only happens with a huge project, with huge files.

Any advice?

**Comment by erictraut** [comment]
Large projects and files will naturally take commensurately longer to analyze than small projects and files. If you're seeing something that takes incommensurately longer, then it's something that's worth investigating further.

Is your source base in a public repo? If so, please paste the link and the repro instructions. If not, you'll need to narrow down the problem yourself by finding a file that takes longer than expected to type check, then commenting out portions of it (binary search) until you find the method or line(s) that cause the problem. Then create a minimal, self-contained code sample that isolates the problem for me to investigate further.

I'm going to close this issue because there's not enough information for me to go on, but if you provide more details, I'm happen to reopen it.
