### ISSUE TITLE
Inconsistent behavior?

### ISSUE THREAD

**Issue by eykamp** [microsoft/pyright#548]
Given the code:

    def is_list(var) -> bool:
        return isinstance(var, list)
   
    var = 1
    
    xvars = var if is_list(var) else [var]              # First
    xvars = var if isinstance(var, list) else [var]     # Second
    
    for v in xvars:
        print(v)

Commenting out the lines marked "First" and "Second" should produce an equivalent program.  However, they are treated differently by pyright.  Commenting out First produces a code with no marked errors, commenting out Second generates the error shown below:

![image](https://user-images.githubusercontent.com/1133323/75421233-a57b3f80-58ee-11ea-87a2-0169034d2d99.png)

The obvious solution is just use the code in Second, but that becomes messy in a less simplified context.  I can see why the parser might be confused, and I've tried various type declarations to try to clarify the situation.

Is this a bug?  Is there an elegant workaround?  Is this just life?

Using pyright 1.1.25 on a Win10 machine.

**Comment by erictraut** [comment]
This isn't a bug. It's expected behavior for a type checker.

Pyright has a powerful code flow analysis engine that can "narrow" types based on conditional statements, but code flow analysis is local to a function. It knows about the semantics of certain built-in operations like `isinstance`. But it can't determine the semantic intent or side effects associated with user-defined functions like `is_list`. I'm not aware of any type checker in any language that's able to do that.
