### ISSUE TITLE
Insert inferred annotations

### ISSUE THREAD

**Issue by cassanof** [microsoft/pyright#5506]
Is there a way to statically insert the inferred annotation into the code, and output it to some destination? If not, how much work would it require to hack it up?

**Comment by erictraut** [comment]
Pyright is a static analyzer, and it would be outside of its intended scope to modify your code.

Pylance, which is Microsoft's premium Python language server built on pyright, allows you to view inline type annotations for inferred types and provides a code action for inserting them one at a time. This gives you a chance to review the inferred type and verify that it's correct. This isn't something that should be automated complete because it is error prone.

If pyright is able to correctly infer the type of a symbol then there is typically no reason to add an explicit type annotation in the code.

**Comment by cassanof** [comment]
There is a reason. This is for training large language models. In general, we want to output code that is correctly typed. It's easier for a large language model to infer the correct type of a function signature if it's fully typed. I understand that this is none of your concern, but thanks for clarifying.

**Comment by erictraut** [comment]
I see. Thanks for the additional details.

You could build a custom tool based on pyright's sources that leverages its type inference capabilities. This is effectively what pylance does to display inlined types. Such a tool would probably need to be done as a fork, and you'd be responsible for updating it as pyright is updated. Unlike the typescript compiler, pyright doesn't have a stable, documented API that can be used for accessing inferred types. It does have an internal interface that is similar to typescript's, but this interface can (and does) change from time to time.

**Comment by cassanof** [comment]
I built something much much dumber: https://github.com/cassanof/testright
It infers type annotations using assertions.

Thanks for your helpful insights :)
