### ISSUE TITLE
reportUnnecessaryTypeIgnoreComment for only pyright-specific ignores

### ISSUE THREAD

**Issue by twoertwein** [microsoft/pyright#5652]
**Is your feature request related to a problem? Please describe.**
Similar to #4243 but when a project prefers using the pyright-ignore comments only when mypy doesn't need the general ignore comment, i.e., pyright uses both ignore comments. In that case, reportUnnecessaryTypeIgnoreComment will flag ignores needed by mypy. 

**Describe the solution you’d like**
`"reportUnnecessaryTypeIgnoreComment": "pyright"` to flag only pyright-specific ignore comments, while pyright still uses the general ignores for all other rules, i.e., `"enableTypeIgnoreComments": true`.

**Comment by erictraut** [comment]
All of the `reportXXX` configuration settings in pyright allow you to specify the diagnostic severity (`"error"`, `"warning"`, `"information"`, or `"none"`). They also support `true` as an alias for `"error"` and `false` as an alias for `"none"`. It wouldn't make sense to accept a value of `"pyright"` since that's not a valid diagnostic severity.

If you want pyright to ignore `# type: ignore` comments, you can use `"enableTypeIgnoreComments": false`. This works in conjunction with `reportUnnecessaryTypeIgnoreComment` as you would expect.
