### ISSUE TITLE
Incorrect assumed return type of complex reduces, which are sliced

### ISSUE THREAD

**Issue by Natan-P** [microsoft/pyright#5653]
**Describe the bug**
I have an initial list, `ls1`, containing `tuple`s of `int`s. The list has a type annotation, of `list[tuple[int, int]]`.
I use a `reduce` (from `functools`) which creates a new list, which is a copy of `ls1`, but has the first tuple element of the next tuple at the end of each tuple, with the very last tuple cut off. (e.g. if `ls1 = [(1, 2), (3, 4), (5, 6)]` then `ls2 == [(1, 2, **3**), (3, 4, **5**)]`)
The type annotation of `ls2` should be `list[tuple[int, int, int]]`, but according to pyright, it is `list[tuple[int, int]] | list[tuple[int, int, int] | tuple[int, int]]`.
Even if instead of dropping the last element, we just take the first element, the type of it is still incorrect, as it would under no circumstances contain only two ints; the very last element is the only one that could contain that.

It seems pyright is not advanced/complicated/convoluted enough to properly resolve what happens after a list slice of a union typed list.
This bug can be worked around by putting dummy values in at any point in the reduce that could contain a tuple of two, therefore maintaining a constant tuple length of 3.

**Code or Screenshots**

```python
from functools import reduce

ls1: list[tuple[int]] = [(1,2), (2,3), (3,4), (4,5)]
ls2 = reduce(lambda acc, i: acc[:-1] + [(*acc[-1], i[0])] + [i], ls1[1:], [ls1[0]])[:-1] # improper assumed return type, shows an error in the IDE if the proper type hint is placed
print(ls2[2]) # shows an error in the IDE (index out of bounds), but no such error occurs during runtime
ls3 = reduce(lambda acc, i: acc[:-1] + [(*acc[-1][:-1], i[0])] + [(*i, int(-1))], ls1[1:], [(*ls1[0], int(-1))])[:-1] # shows the proper return type, with three elements in the tuple
# the dummy value is wrapped in int() so as to make its type `int`, and not `Literal[-1]`, which is not equivalent to `int` in 1.1.320, though this worked without the int() wrapping before upgrading. i sadly cannot provide the version in which this worked, because i do not know in which log this is saved - maybe i'll do some digging and open another bug report about this.
# the dummy value of -1 is never seen in ls3, as it is usually cut out in the reduce, or left in the very final tuple then cut out
# one can also replace -1 with the logical continuation in the last tuple (in this case, 4)
```

**VS Code extension or command-line**
I am using pyright in neovim, through CoC - the plugin `coc-pyright` - plugin version 1.1.320, which I assume is also the version of pyright used.

**Comment by erictraut** [comment]
If I paste the code from your sample above into my editor, the first line is flagged with a type violation, as it should be. I suspect that's just a typo because your explanation includes the correct annotation `list[tuple[int, int]]`. So I assume the first line in the sample should be:

```python
ls1: list[tuple[int, int]] = [(1,2), (2,3), (3,4), (4,5)]
```

If my above assumption is incorrect, please let me know because the rest of my analysis is based on this assumption.

Rather than using a lambda, let's switch to a `def` statement to define a function. That way, we can supply explicit type parameter annotations. If I understand your intent, I think it should be annotated as follows. Do you agree?

```python
def reduce_callback(acc: list[tuple[int, int, int]], i: tuple[int, int]): ...
```

The problem is that your implementation of this callback doesn't conform to these types.

```python
def reduce_callback(acc: list[tuple[int, int, int]], i: tuple[int, int]):
    a = acc[:-1]  # list[tuple[int, int, int]]
    b = [(*acc[-1], i[0])]  # list[tuple[int, int, int, int]]
    c = [i]  # list[tuple[int, int]]
    r = a + b + c # list[tuple[int, int, int] | tuple[int, int, int, int] | tuple[int, int]]
    return r
```

Is this what you intended?

The `functools.reduce` function is defined in typeshed with two overloaded signatures. Only one of them applies in this case because you're supplying an argument for the `initial` parameter.

```python
def reduce(function: Callable[[_T, _S], _T], sequence: Iterable[_S], initial: _T) -> _T:
    ...
```

Pyright's constraint solver is able to find a valid solution for both `_T` and `_S` here, so it doesn't find any type violation.

Everything looks correct here to me. I don't see any bug in pyright.

Were you expecting to see a type error for this code?
