### ISSUE TITLE
regression: Django ForeignKey does not check argument types when used in migration

### ISSUE THREAD

**Issue by last-partizan** [microsoft/pyright#5691]
**Describe the bug**

When used in migration, `models.ForeignKey` allows it default argument to be anything, but this is incorrect.
I think this happens because `migration.AlterField` uses `field: models.Field[Any, Any]`, and pyright infers `ForeignKey[Any]` for an argument, but in reality it should be limited to subclasses of `models.Model`.

It was working in 1.1.320.

**Django example**

(this is full example almost like in my production app, if you want stripped down example without extra deps, scroll down)

`pip install django django-types`

```python
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Book(models.Model):
    # That's expected error.
    # error: Argument of type "Literal[1]" cannot be assigned to parameter "default"
    # of type "_M@ForeignKey | (() -> _M@ForeignKey)" in function "__new__"
    author = models.ForeignKey(settings.AUTH_USER_MODEL, models.CASCADE, default=1)


class Migration(migrations.Migration):

    operations = [
        migrations.AlterField(
            model_name="Book",
            name="author",
            field=models.ForeignKey(
                default=3,  # Here should be the same error, but there is none
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
```

**Minimal example**

```python
from typing import Any, Generic, TypeVar

T = TypeVar("T", bound=str)


class Field(Generic[T]):
    def __init__(self, to: T):
        ...


class Model:
    f_ok = Field("f")  # Correct
    f_error = Field(1)  # Error


def add_field(f: Field[Any]):
    ...


add_field(Field(1))  # Error expected
```

**VS Code extension or command-line**

* pyright 1.1.321

**Comment by erictraut** [comment]
The current behavior in pyright 1.1.321 is correct. The older behavior (in 1.1.320) was a false positive error. So I don't consider this a regression. For comparison, mypy also doesn't emit an error in this case.

The issue is that the constructor for `AlterField` declares the type of the `field` parameter as `Field[Any, Any]`. `ForeignKey` derives from `Field`, so it can be shown that `Field[Any, Any]` is the equivalent to `ForeignKey[Any]`. That means the type variable `_M` used in `ForeignKey` is not constrained, so anything will match it. No error therefore be generated when you pass a value of `3` for the `default` parameter, which is annotated as `_M | Callable[[], _M] | None`.

Here's an even more minimal example to demonstrate the issue:

```python
from typing import Any, Generic, TypeVar

T = TypeVar("T", bound=str)

class Field(Generic[T]):
    def __init__(self, to: T):
        ...

x1 = Field(1)  # Error reported
x2: Field[Any] = Field(1)  # Error not reported
```

Both pyright 1.1.321 and mypy produce an error for `x1` but not for `x2`.
