### ISSUE TITLE
Programmatic Access to Extract Type Information with Pyright

### ISSUE THREAD

**Issue by nashid** [microsoft/pyright#5734]
I'm currently working on a project where I need to analyze a Python codebase programatically to extract type information for several variables. As pyright is a robust type-checker, I am keen on utilizing it for this purpose.

**Objective:** My goal is to use pyright programmatically to analyze Python code and obtain type information for specific variables.

**Approaches Considered:** As pyright can function as a language server, I am thinking to set up a LSP client, initiating the pyright language server, and subsequently dispatching LSP requests to gather type data. However, I am not sure about the viability of this strategy.

Direct Utilization of Pyright: I am curious if there's a simpler way to leverage it directly as a library format  for Python code analysis and extract type information extraction.

**Questions:**

1. Is there a recommended way to do programmatic type extraction using Pyright?
2. Are there any internal APIs or tools within Pyright that could be leveraged for this purpose?

**Comment by erictraut** [comment]
The short answer is no, there's no good way to do this with pyright. It's not designed for this purpose.

You could use the LSP interface — specifically the "hover provider" facility — to request that pyright return the textual representation of the type for a given offset in the file. The text representation is probably not what you're looking for, however.

Internally, pyright has functions for extracting type information in programmatic form. This is how the hover provider is implemented. However, these interfaces are internal to pyright and are not designed as externally-supported APIs. We currently have no plans to create, document, or support external APIs as this would be a big undertaking, and this goes well beyond the intended use of pyright.

Since pyright is open source, you could fork it and build on top of it. But you would then be responsible for maintaining it, incorporating updates, and fixing problems when the internal interfaces change (which they frequently do).

Mypy is another type checker in the Python ecosystem, and it has a plugin interface that is (somewhat) documented and supported. You might want to look into that option to see if it better meets your needs.
