### ISSUE TITLE
`NotRequired` in a `TypedDict` always raises an error on access, even when existence is confirmed, if confirmed with .`keys()`

### ISSUE THREAD

**Issue by tigerhawkvok** [microsoft/pyright#5779]
**Describe the bug**
`NotRequired` in a `TypedDict` always raises an error on access, even when existence is confirmed via an assertion. Consider a `TypedDict`:

```python
class SearchParamDef(TypedDict):
    StreetNumber: str
    StreetName: Union[str, List[str]]
    StreetSuffix: Optional[str]
    StreetType: Optional[Union[str, List[str]]]
    StreetDirection: NotRequired[Optional[str]]
    Zip: NotRequired[Optional[str]]
    PostCode: NotRequired[Optional[str]]
    CountryCode: str
    OSMAddress: NotRequired[Optional[str]]

```

**Code or Screenshots**
When verifying a `NotRequired` key exists, it should work with either type of `in` check.

Instead, Pyright errors when explicitly checking `.keys()`:

![image](https://github.com/microsoft/pyright/assets/165937/9076ed47-57f7-4804-9188-6227297c298f)

Just searching presence more generally still works:

```python
    assert "Zip" in d["searchParams"]
    assert d["searchParams"]["Zip"] == "38128"
```

If your code relies on symbols that are imported from a third-party library, include the associated import statements and specify which versions of those libraries you have installed.

**VS Code extension or command-line**
Extension; ms-python.vscode-pylance ; `v2023.5.10`

**Comment by erictraut** [comment]
Could you please provide a self-contained minimal code sample that demonstrates the problem? The code snippet that you've posted above references a symbol `d` that is not defined. I can't tell from the partial screen shot how it is declared or where it comes from.

I suspect that you're attempting to use a type guard pattern that is not supported by pyright. For a full list of supported type guard patterns, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards).

**Comment by shner-elmo** [comment]
@erictraut Honestly it's kinda bizarre that a builtin type is not supported for performance reasons. The obvious solution would be to not write the performance-intensive library in TypeScript, perhaps in a more performant language. Or at least the core of Pyright.

**Comment by erictraut** [comment]
@shner-elmo, the performance issue I'm referring to here is algorithmic and is not related in any way to the language in which the algorithm is implemented. Javascript is actually very performant — much more so than Python. Rewriting pyright in a compiled language would have little or no impact on the performance of its core algorithms. As evidence of my assertion, consider mypy and pyre, two other Python type checkers that are both written in compiled languages. (Mypy is written in typed Python but is transpiled to C and then compiled.) Pyright is significantly faster than both of these other type checkers on most code bases.

I'm also not sure what you mean by "a builtin type". The issue here is not related to a *type* but to a *type guard pattern*. There are an infinite number of expression forms that could be used in `if` statement and potentially narrow the type of a subexpression. As explained above, support for each type guard pattern requires custom logic in a type checker. Pyright already implements more of these forms than [other Python type checkers](https://microsoft.github.io/pyright/#/mypy-comparison?id=type-guards). If you would like to see support for additional type guard forms that pyright doesn't currently support, you can up-vote the issue by adding a thumbs-up reaction to it. Currently, this issue has received no up-votes.
