### ISSUE TITLE
`reportMissingModuleSource` should not report missing sources when used inside `if TYPE_CHECKING` block

### ISSUE THREAD

**Issue by hamdanal** [microsoft/pyright#5819]
**Is your feature request related to a problem? Please describe.**
When `reportMissingModuleSource` is used, it flags imports from stubs inside `if TYPE_CHECKING` block. Here is a small reproducer:

![reportMissingModuleSource](https://github.com/microsoft/pyright/assets/93259987/3c6d60bd-67bd-421e-a1f9-4d3a9a7067ab)

The file `compat_for_missing_types.pyi` is a file that contains some typing definitions that should exist in some third party stubs but are actually missing from those stubs. I don't want to recreate all the third party stubs so I added this file so that I can use it locally to type check my code using the missing constructs. I thought about making this compatibility file a `.py` instead but I think this not the correct thing to do as its content must be used for type checking only.

**Describe the solution you’d like**
I think this option should only flag imports that would cause an error at runtime. Since the type checking block never runs, it should be treated as a stub file in this context and not report an error.

**Comment by erictraut** [comment]
The current behavior is "as designed". 

The `TYPE_CHECKING` mechanism is designed as a way to "lie" to the type checker about what occurs at runtime. It is meant to be a workaround for cases that cannot be used at runtime but that you want to treat as such. It would therefore be inappropriate for a type checker to special-case any code within it and treat it as though it is not executed at runtime. This is an important principle that I have strictly adhered to, so it's unlikely that we'd implement any feature like the one you're suggesting here.

My recommendation is to avoid the use of `TYPE_CHECKING` in your code if at all possible. It makes your code much less robust because the type checker is now validating code that's different from what the interpreter sees at runtime. There are rare cases where it cannot be avoided, but I've seen it abused in many cases — used for reasons that are highly suspect and unnecessary.

In your use case, you can use a `# type: ignore` or `# pyright: ignore` comment to suppress the error within the `TYPE_CHECKING` block.
