### ISSUE TITLE
running against a python env inside a docker container?

### ISSUE THREAD

**Issue by dcsanx** [microsoft/pyright#582]
rather than using virtualenv, we develop with a python env contained in a custom docker image.
I'm wondering if pyright can see into that built image to look for installed modules?

where the dockerfile looks something like this:

```
FROM python:3-stretch

RUN pip install --upgrade pip

ADD submodules/xyz/package /tmp/dpl
RUN cd /tmp/dpl && python setup.py sdist bdist_wheel
ENV PIP_FIND_LINKS=/tmp/dpl/dist

ADD requirements.txt ./
RUN pip install -r requirements.txt

```

**Comment by jakebailey** [comment]
Have you used [VS Code's dev containers](https://code.visualstudio.com/docs/remote/containers)?

I believe it's common to use VS Code's remote mode to ensure the editor bits are running in the right environment. I'm not sure it's feasible to get the editor to use a container's filesystem without actually running in it.

**Comment by erictraut** [comment]
Are you running Pyright (the command-line version) inside of the docker container? We run Pyright inside of a docker container for our CI (continuous integration) pipeline. Or are you looking to run the VS Code extension outside of the docker container but point to the docker container for your installed Python environment?

Pyright should be able to use any Python environment as long as it's accessible through a file system path.

**Comment by ReHoss** [comment]
hello @erictraut,

Supposing I have a python package (`firedrake`) that can only be installed in a python virtual environment inside a Docker container.

Which simple CI practice would you recommend in that case?

Should we do `git commit`, `push` and others from within the container and forget about doing anything outside?

I have been working with local virtual environments so far, and I used to tell `pyright` where the python packages are located with a `pyrightconfig.json`

```json
{
  "venvPath": "path/to/venv",
  "venv": "my_venv"
}
```

Should I work locally (_i.e._ from outside the container) and replace `"path/to/venv"` with `"path_to_container/path/to/venv"` ? Otherwise, should I develop and work on source code from inside the container?

Thank you very much:)
If you have any references regarding this question, please share
