### ISSUE TITLE
Ensuring Optional value is not None doesn't work

### ISSUE THREAD

**Issue by tcztzy** [microsoft/pyright#586]
**Describe the bug**
[Pip](https://github.com/pypa/pip) use [a type guard method to ensure the `Optional[Kind]` value is not `None`](https://github.com/pypa/pip/blob/69cc55831d529aaec13e0fb42c763ed103edd457/src/pip/_internal/configuration.py#L182-L263), and Pyright cannot detect that, but if I put the method codes before type evaluation line instead of calling method, Pyright can find that is not `None`

**To Reproduce**
https://github.com/pypa/pip/blob/69cc55831d529aaec13e0fb42c763ed103edd457/src/pip/_internal/configuration.py#L182-L263

**Expected behavior**
No complains about this kind of type guard method.

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/12420478/77535897-5ff26800-6ed6-11ea-9c8f-edb0095b3d70.png)

**VS Code extension or command-line**
![image](https://user-images.githubusercontent.com/12420478/77535989-8f08d980-6ed6-11ea-8ed3-09e1c033f9fd.png)
![image](https://user-images.githubusercontent.com/12420478/77536029-a2b44000-6ed6-11ea-8451-4ab7b4bf105a.png)

**Comment by erictraut** [comment]
Type guards are evaluated locally to a function. There is no provision in the standard Python type mechanisms for specifying user-defined type guard functions. ([TypeScript](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) provides this, but it's a relatively new feature, and this is the only language where I've seen it introduced. Maybe Python will follow at some point if type checking becomes more popular. ).

There are two workarounds in Python:
1. Add a check that narrows the type within the function where the expression is used. This normally takes the form of an `assert` statement. In your example above, you would add the statement `assert self.load_only is not None` somewhere above the point where you use `self.load_only`.
2. Return the validated value from the method that ensures that it's not None. In your case, you would return a value `from self._ensure_have_load_only` that is never None. This would look like the following: `load_only = self._ensure_have_load_only()`. You can then use the local variable `load_only` safely because it's guaranteed not to contain None.
