### ISSUE TITLE
Inference of `cls` type on a custom `classmethod`

### ISSUE THREAD

**Issue by kwsp** [microsoft/pyright#5865]
**Describe the bug**

Consider a custom implementation of `classmethod` named `restricted_classmethod`, where I assume is typed correctly ([since I took the types from typeshed](https://github.com/python/typeshed/blob/f28cb8b8562ccc382d018129ba4886f241c6db9c/stdlib/builtins.pyi#L146-L160)). Pyright infers the first parameter of a method marked with `@restricted_classmethod` as `Self@C`.

I suspect what's happening now is that pyright doesn't actually check the type annotation of the decorator, but instead marks a method as `classmethod` by looking up the builtin. I'm not too familiar with the pyright internals. So this could be considered as either a bug or a feature request.

https://github.com/microsoft/pyright/blob/900fbd865ebd9ed9156d12d91bd95f3e5376b5cf/packages/pyright-internal/src/analyzer/decorators.ts#L228-L253

**Code or Screenshots**
If possible, provide a minimal, self-contained code sample (surrounded by triple back ticks) to demonstrate the issue. The code should define or import all referenced symbols.

```python
from typing import Callable, Concatenate, Generic, ParamSpec, TypeVar


class RestrictedClassmethodError(Exception):
    """
    This exception raised when a `restricted_classmethod` is invoked on an instance
    instead of a class type.
    """


_T = TypeVar("_T")
_P = ParamSpec("_P")
_R_co = TypeVar("_R_co", covariant=True)

class restricted_classmethod(Generic[_T, _P, _R_co]):
    """
    Custom `classmethod` that raises a RestrictedClassmethodError when the decorated method
    is called on an instance and not the class type.
    """

    def __init__(self, method: Callable[Concatenate[_T, _P], _R_co]) -> None:
        self.method = method

    def __get__(self, instance: _T, cls: type[_T]) -> Callable[_P, _R_co]:
        if instance is not None:
            raise RestrictedClassmethodError(
                f"The classmethod `{cls.__name__}.{self.method.__name__}` cannot be invoked on an instance. Please "
                f"invoke it on the class type and make sure the return value is used."
            )
        return self.method.__get__(cls, cls)


from typing import Type, Self

class C:
    @restricted_classmethod
    def f1(cls): ...   # cls inferred to be `Self@C`

    @restricted_classmethod
    def f2(cls: Type[Self]): ...   # pyright error: Type of parameter "cls" must be a supertype of its class "C".
```

**VS Code extension or command-line**
Are you running pyright as a VS Code extension, a language server in another editor, integrated into Pylance, or the command-line tool? Which version?

mason.nvim, pyright 1.1.303

**Comment by erictraut** [comment]
Python static type checkers must necessarily treat `classmethod` and `staticmethod` as special cases (hard coded) because there's nothing in the type system that otherwise indicates what special behaviors these decorators confer when applied. There is no provision in the type system for defining "custom" equivalents of `classmethod` or `staticmethod`. If that's something you think is important enough to add to the Python type system, you could champion such an extension. That would require going through some standardization process culminating in a PEP which would need to be ratified by the Python steering council. If that's something you would like to pursue, I recommend that you start by posting an informal proposal in the [python/typing discussion forum](https://github.com/python/typing/discussions).

Another suggestion is to use stacked decorators. You could apply the normal `classmethod` and then apply your custom decorator on top of it.

```python
@restricted_classmethod
@classmethod
def f1(cls): ...
```

In any case, I think pyright is working correctly here, so I don't consider this a bug. Not surprisingly, mypy works the same in this case.

**Comment by kwsp** [comment]
> There is no provision in the type system for defining "custom" equivalents of classmethod or staticmethod.

Except there is, as I demonstrated in the code above, by [implementing descriptors](https://docs.python.org/3/reference/datamodel.html#descriptors).

Doesn't the code here in typeshed type a classmethod correctly and completely? It looks right to me, so please let me know where its insufficient.

https://github.com/python/typeshed/blob/f28cb8b8562ccc382d018129ba4886f241c6db9c/stdlib/builtins.pyi#L146-L160

**Comment by kwsp** [comment]
Correct me if I'm wrong, but doesn't this implement `classmethod` correctly in pure python? Therefore there are ways we can exploit `__get__` to override behaviour.

```python
class restricted_classmethod(Generic[_T, _P, _R_co]):
    """
    Custom `classmethod` that raises a RestrictedClassmethodError when the decorated method
    is called on an instance and not the class type.
    """

    def __init__(self, method: Callable[Concatenate[_T, _P], _R_co]) -> None:
        self.method = method

    def __get__(self, instance: _T, cls: type[_T]) -> Callable[_P, _R_co]:
        if instance is not None:
            raise RestrictedClassmethodError(
                f"The classmethod `{cls.__name__}.{self.method.__name__}` cannot be invoked on an instance. Please "
                f"invoke it on the class type and make sure the return value is used."
            )
        return self.method.__get__(cls, cls)
```

**Comment by kwsp** [comment]
Let me make myself clear - I think the problem is that Pyright doesn't recognize the static types applied to the `__get__` method in the custom decorator, and therefore type the first argument to the decorated method correctly.

**Comment by erictraut** [comment]
You're making some erroneous assumptions.

To help explain, I'm going to make a small change to your code sample. This will make it clearer what's going on inside a type checker when it applies normal (user-defined) function decorators.

```python
class C:
    def __f1(cls) -> None: ...

    f1 = restricted_classmethod(__f1)
```

For a type checker to determine the type of `f1`, it needs to evaluate the expression `restricted_classmethod(__f1)`. That means it first needs to evaluate the type of `__f1`. The type of `__f1` comes from the `def` statement. When a type checker sees that a class-scoped `def` statement has not been decorated with `@staticmethod` or `@classmethod`, it assumes it's an instance method and that its first parameter will be a `self` parameter. If the first parameter of an instance method has no explicit annotation, its type is inferred as `Self`. So the type of `__f1` is properly evaluated as `(cls: Self) -> None`.

Now that the type of `__f1` is known, the type checker can evaluate the type of the expression `restricted_classmethod(__f1)`. When evaluating this call, `_T` is specialized with the type `Self@C`, `_P` is specialized with `[]` (a zero-parameter function signature), and `_R_co` is specialized with `None`. The result is an instance of the class `restricted_classmethod[Self@C, [], None]`.

If you attempt to call `C.f1()`, you'll receive an error because your type annotation for `__get__` has a small bug. You need to change the annotation for the `instance` parameter from `_T` to `_T | None`. Once you fix that issue, calls to `C.f1()` will then type check without a problem. But the code within the `__f1` method will not type check because the pre-decorated method is assumed to be an instance method with a `self` parameter. The fact that you've passed this method to a decorator call doesn't change this.

The built-in `@classmethod` and `@staticmethod` are special-cased inside type checkers like pyright, mypy, and pyre. They cause the type checker to assume that the method should be treated not as an instance method but as a class method (where the first parameter is of type `type[Self]`) or a static method (where the first parameter is not treated as special in any way).

**Comment by kwsp** [comment]
Thanks for the detailed explanation. I understand that in a `def` inside a `class`, assuming the first parameter is `Self` is correct unless certain conditions are violated (i.e. if the method is decorated with `@classmethod` or `@staticmethod`). My question is then - if we parsed that in the `__get__` of the custom decorator, the class type is passed in as the first argument, is it possible for a static type checked to infer the first argument to the decorated method should not be `Self` but instead `type[Self]`?

**Comment by erictraut** [comment]
You're suggesting that the type of the argument, when used within a call expression (or a decorator, which is simply a special form of a call expression) should change the type of the argument? No, that would be backward. The type of the argument needs to be evaluated before the call expression is evaluated, not the other way around.

Have you tried my suggested approach of stacking decorators — using a standard `@classmethod` and then applying your own custom decorator on top of it? That approach should work at runtime and be compatible with static type checking.

**Comment by kwsp** [comment]
Stacking ‘@classmethod‘ does resolve the static type checking problem, but defeats the whole purpose of my custom decorator- I'm trying to raise an exception when a method that's supposed to be called as a classmethod is called from an object, instead of the class type. By stacking ‘@classmethod‘, the decorator's ‘__get__()‘ can no longer see if it's called from an instance.

**Comment by kwsp** [comment]
My problem could be a XY problem. 
* X problem: in python there is no way to enforce that the return value of a method is not discarded, like C++'s `[[nodiscard]]`
* Y problem: a popular paradigm in Python is to use `@classmethod` to define an alternative constructor. However, sometimes it's hard to infer from the method name if it's a classmethod, or if it modifies an object in place with the new parameters. Hence, it's a common UX problem where users cannot figure out why the object they're using isn't in a desired state after calling the classmethod. I propose for certain classmethod, we raise an exception if the classmethod is called on an instance as a proxy to catch usage errors.

**Comment by erictraut** [comment]
Thanks for the additional context. Here's a solution that works with both pyright and mypy (and should work with any other standards-compliant type checkers). Starting with your code above, rename your class `restricted_classmethod` to `_restricted_classmethod`. Then simply add the following:

```python
if TYPE_CHECKING:
    restricted_classmethod = classmethod
else:
    restricted_classmethod = _restricted_classmethod
```

This fools the type checker into believing that it's using a standard `@classmethod` when at runtime it's using your custom `_restricted_classmethod`.
