### ISSUE TITLE
Add `"reportTypedDictGetUndefinedKey"` rule that defaults to `"none"` to make working with `NotRequired` keys more ergonomic

### ISSUE THREAD

**Issue by kylebebak** [microsoft/pyright#5883]
## Problem

Consider the following code, with a `TypedDict` and a `NotRequired` key:

```py
from typing import NotRequired, TypedDict


class D(TypedDict):
    foo: str
    bar: NotRequired[str]


d = D(foo="abcd")

s = d["foo"]
# str

s_2 = d.get("bar")
# str | None
```

Here's a typo that the type checker doesn't catch, I guess because there are use cases for calling `get` with a key not defined in the typed dict:

```py
s_3 = d.get("bear")
# Any | None
```

Because `Any` is assignable to `str` (to anything), the type checker can't be configured to flag this:

```py
def fn(s: str):
    pass


# This is very likely not what the user intended
# Either fn will never get called because of the typo
# Or, if there's an unexpected "bear" key in `d`, fn could get called with an argument with the wrong type
if s_3:
    fn(s_3)
```

AFAICT, the only way to access bar that's not vulnerable to typos or runtime `KeyError`s is like this:

```py
try:
    s_4 = d["bar"]  # pyright would helpfully flag typos here, e.g. "bear" 
except KeyError:
    s_4 = None
# s_4 has type str | None
```

This works, but it's not ergonomic, and makes working with `NotRequired` keys a pain. One line becomes 4 every time the programmer wants to access a `NotRequired` key.

## Proposed Solution

I like the way TypeScript handles this. Accessing an object property that's not present in the object's `interface` is a type error, and this can be done in a single line, e.g. `obj.prop`.

Ideally, calling `d.get("bear")` could be configured to be an error, because this key isn't defined in the typed dict. I don't see many use cases for getting undefined keys on `TypedDict`, and if there are, they can always be ignored on a line by line basis.

Something like a `"reportTypedDictGetUndefinedKey"` rule that defaults to `"none"`.

**Comment by erictraut** [comment]
Pyright already issues an error if you access an undefined key within a TypedDict.

```python
s_3 = d["bear"] # Type error: "bear" is not a defined key in "D"
```

In that regard, it works in a manner that is entirely analogous to TypeScript.

The `get` method on a `TypedDict` (or any `dict`, for that matter) is intended to be a safe way to access a key that may not be present on a Mapping object. That includes `NotRequired` keys defined within your `TypedDict` but also keys outside the `TypedDict` definition.

The `get` method comes from the `Mapping` class. All `TypedDict` classes are subtypes of `Mapping`. Internally, pyright synthesizes special overloads for `get` based on a `TypedDict` definition so it can provide more detailed type information for known key/value pairs, but it also provides a fallback overload for `get` to handle the case where you are accessing unknown key/value pairs. That's by design, and it's why you don't see any error if you pass an unknown key name to `get`.

I don't think it would make sense for pyright's type checking logic to have special-case knowledge of the `get` method for `Mapping` or `TypedDict`. It's simply a method call, and it's type checked like any other method call. I can't think of any other cases where pyright's core type checker logic special-cases a particular method on a particular class and somehow treats it specially.

If there's a way to address this issue by modifying the synthesized `get` overloads, that's something I might entertain — assuming it doesn't create other problematic side effects. The synthesized fallback overload for the `get` method previously had a return result of `Unknown | None`, but this unfortunately resulted in [false positive errors](https://github.com/microsoft/pyright/issues/5452) when used with strict mode, so I changed it to `Any | None`.

**Comment by kylebebak** [comment]
Thank you for the quick response!

> Pyright already issues an error if you access an undefined key within a TypedDict.

```py
s_3 = d["bear"] # Type error: "bear" is not a defined key in "D"
```

The problem with this is that if you want the type checker to catch typos, the only way to safely access a `NotRequired` key is to wrap it in a `try/except`:

```py
try:
    s_3 = d["bar"]
except KeyError:
    s_3 = None
```

This takes 4 lines per key. It's impractical if you're working with a typed dict with many keys that are `NotRequired`, or with `total=False`.

In TypeScript, let's say you have an interface analogous to the TypedDict above, e.g. like this:

```ts
interface D {
  foo: string
  bar?: string
}
```

You can access the possibly undefined `bar` key in a single line, without worrying about an uncaught error. Its type correctly resolves to `string | undefined`:

```ts
const d: D = {foo: 'abcd'}
d.bar  // string | undefined
d.bear  // Property 'bear' does not exist on type 'D'
```

This makes working with interfaces that have possibly undefined keys much easier than working with `TypedDict`s that have `NotRequired` keys, or `total=False`.

---

Python of course has no `undefined`. Special treatment of `dict.get` for `TypedDict` seems like a good compromise, especially if it's opt-in. E.g. if `"reportTypedDictGetUndefinedKey"` is `"error"`, `pyright` could flag `d.get("bear")`:

```py
class D(TypedDict):
    foo: str
    bar: NotRequired[str]


d = D(foo="abcd")


s = d.get("bar")
# str | None
s_1 = d.get("bear")  # Could not get item in TypedDict, "bear" is not a defined key in "D"
```

This way we can safely access a `NotRequired` keys in typed dicts using `get`, with the certainty that `pyright` will flag typos for us.

**Comment by erictraut** [comment]
I would be loathe to special-case the `get` method in this manner. There have been a few other cases where we've special-cased functions (never methods) with much stronger justification than this, and I've regretted almost every one of those instances. They end up being maintenance problems because the special-casing logic tends to interact poorly with other type features. It also tends to break when typeshed stubs are updated. For these reasons, I think it's unlikely that we'd implement a feature that would require such special casing. It's something we might reconsider in the future if there's sufficient demand, but even then I would look for alternate ways to address the problem that wouldn't involve special-case logic for a specific method in a particular class.

**Comment by kylebebak** [comment]
Thank you for the explanation. Before I created this issue I was actually going to create an issue proposing we do the opposite of what was done to resolve [the issue you linked to above](https://github.com/microsoft/pyright/issues/5452). I'll comment on that idea in 5452
