### ISSUE TITLE
[LSP]: Provide auto-complete suggestions for Literal and string union

### ISSUE THREAD

**Issue by RobertCraigie** [microsoft/pyright#5952]
**Is your feature request related to a problem? Please describe.**

Some APIs have fields that in the vast majority of cases will be a certain set of values but they could also be any arbitrary value. For example see the `model` param in the [OpenAI API](https://platform.openai.com/docs/api-reference/chat/create#model).

Ideally in cases like this, consumers of these types would be able to trigger auto-complete in their editor and see the pre-defined values while still being able to assign any arbitrary value without receiving type errors.

Naively modelling this behaviour in a function like this:
```py
def foo(arg: Literal["enum1", "enum2"] | str) -> None:
    ...
```

Results in pyright narrowing the type of `arg` to just be `str` which then doesn't provide any auto-complete, e.g. `foo(arg='|')` does not provide any suggestions.

**Describe the solution you’d like**

Ideally there would be some way for Pyright would be able to retain the `Literal` type internally instead of removing it here.

Separately, if I'm missing something and there is a different way to define the union type that still uses strings and provides auto-complete that would also be a good solution.

**Alternatives**

Representing the `Literal` type with an `Enum` type instead does work but we don't want to use `Enum`s as we think `Literal` string types provide a better DX as they don't require an additional import and the auto-complete support when not used with `| str` is really helpful.

<details>
<summary>Example</summary>

```py
import enum

class Model(enum.Enum, str):
    enum1 = enum.auto()
    enum2 = enum.auto()

def foo(arg: Model | str) -> None:
    ...

foo(arg=Model.enum1)
```

</details>

**Additional context**

This is possible in TypeScript using a quirk of its type system, e.g.

```ts
model: (string & {}) | 'enum1' | 'enum2'
```

Whereas this will not provide suggestions:

```ts
model: string | 'enum1' | 'enum2'
```

---

Apologies if this has been discussed before, I couldn't find anything.

**Comment by erictraut** [comment]
The type `Literal["enum1", "enum2"] | str` is the same type as `str`, so from a type perspective, it's correct for a type checker to treat them the same. Pyright performs this simplification for internal efficiency reasons when forming unions. There are cases where many literals appear in a union, and some type operations on unions are O(n^2) or at least O(n), and simplifying unions helps with performance.

I'm not convinced that it would be a good tradeoff to change this behavior. The technique you're proposing isn't at all obvious, wouldn't be discoverable, and I doubt if anyone but you would ever attempt to use it. So while it might help you, such a change would have a net negative impact for pyright users overall.

As a workaround, you can achieve a similar effect using an `overload`.

```python
from typing import Literal, overload

@overload
def foo(arg: Literal["enum1", "enum2"]) -> None:
    ...

@overload
def foo(arg: str) -> None:
    ...

def foo(arg: str) -> None:
    ...
```

**Comment by rattrayalex** [comment]
Hey Eric,

Thanks for your consideration here.

Unfortunately an overload wouldn't be appropriate for our actual use-case (Robert provided a simpler case for clarity). We also tend to avoid overloads wherever possible because some typecheckers don't provide good error messages when a user has a type error.

For what it's worth, I would dispute the claim that nobody besides us would ever do this. From what I've seen, it's sadly common for folks working with data to have `"special_string_a" | "special_string_b" | any arbitrary string` and expect that the vast majority of cases will fall into one of the documented buckets (but for backwards-compatibility or other reasons, other strings are allowed).

We certainly do understand the efficiency needs of this, though, so we may need to consider a strict union with documentation that tells users to cast nonstandard strings to `Any` (Robert would hate this). The alternative – where someone using a library provided by OpenAI can't autocomplete `model='gpt-4'` – is a pretty disappointing user experience.

I wonder if there might be a simple way for a type author to indicate that a given union of string and string literals shouldn't be collapsed… probably not…

**Comment by RobertCraigie** [comment]
@rattrayalex actually one solution could be to use `NewType` in the fallback case.

```py
Model = NewType('Model', str)

def foo(*, model: Literal['gpt-4'] | Model) -> None:
  ...

foo(model='gpt-|')  # would autocomplete + pass type checks if the string matches
foo(model='my-custom-model')  # would error
foo(model=Model('my-custom-model'))  # would pass type checks
```

This could be a pretty reasonable tradeoff, the downsides of this approach being that:
- Users now have to import one of our types to be able to pass a param (which we don't generally do)
- It's maybe not obvious that you would have to write `Model('my-model')`
- It's less forwards-compatible, users on old versions that want to use a just-released model will have to use the `Model` fallback

For context, the error that Pyright would report is this:
```
  example.py:14:11 - error: Argument of type "Literal['my-custom-model']" cannot be assigned to parameter "model" of type "Model | Literal['gpt-4']" in function "foo"
    Type "Literal['my-custom-model']" cannot be assigned to type "Model | Literal['gpt-4']"
      "Literal['my-custom-model']" is incompatible with "Model"
      "Literal['my-custom-model']" cannot be assigned to type "Literal['gpt-4']" (reportGeneralTypeIssues)
```

**Comment by rattrayalex** [comment]
That could work!
