### ISSUE TITLE
Error for calls to `Any()`

### ISSUE THREAD

**Issue by JelleZijlstra** [microsoft/pyright#5992]
I found some code in our internal codebase that did `Any(some_value)` instead of `cast(Any, some_value)`. This fails at runtime.

Mypy detects it (https://mypy-play.net/?mypy=latest&python=3.10&gist=6f42c8210666ac2f018928399a60c953):
```
main.py:3: error: Any(...) is no longer supported. Use cast(Any, ...) instead  [misc]
main.py:3: error: "object" not callable  [operator]
```

But pyright does not. I think this is a plausible mistake and it would be useful for pyright to emit an error here.

**Comment by erictraut** [comment]
I really don't like adding special-case error handling like this unless there's good evidence that it's a problem. There are many ways that `Any` can be used incorrectly and will result in unexpected ways at runtime, including crashes.

I did some searches in github and on google, and I couldn't find anything that seemed to indicate that developers were under the mistaken impression that `Any` can be used in a call expression.

I'm going to close this request for now, but I'm willing to revisit it in the future if there's evidence that this issue is a problem for developers or if we receive signal from other pyright users (e.g. in the form of upvotes).
