### ISSUE TITLE
TypeVar not assignable to itself in steam.py

### ISSUE THREAD

**Issue by Gobot1234** [microsoft/pyright#6009]
**Describe the bug**
I think I've managed to get myself down to [the last few type bugs in my library](https://github.com/Gobot1234/steam.py/actions/runs/6283510493/job/17064043045) and the last one that's confusing me is a TypeVar that's not assignable to itself when joining types to the return types.

![image](https://github.com/microsoft/pyright/assets/50501825/744a5379-184b-4578-a34b-a9c442a66f84)
but it is joinable when I use cast even though it should be for the same TypeVar. Unfortunately I can't figure out a minimal repro for it (sorry to keep sending these things I can't find minimal repros for).

**Code**
1. `git clone https://github.com/Gobot1234/steam.py`
2. `poetry install`
3. open steam/chat.py scroll to a function involving MemberT

**VS Code extension or command-line**
pyright 1.1.328

**Comment by erictraut** [comment]
This is because you have a snarl of circular dependencies in your code.

* The type `MemberT` has a bound of `Member`.
* `Member` is parameterized by `GroupT`.
* `GroupT` has a bound of `Group | None`.
* `Group` uses `GroupChannel` as a type argument.
* `GroupChannel` derives from `Chat`.
* `Chat` derives from `Channel` which is parameterized with `ChatMessageT`.
* `ChatMessageT` has a bound of `GroupMessage | ClanMessage`.
* `GroupMessage` derives from `ChatMessage`.
* `ChatMessage` is parameterized by `MemberT`.
And we're in a cycle.

Pyright already handles many forms of circular dependencies, but it doesn't handle this one. I'll look for ways to extend the logic to handle this.

I noticed that you're importing a bunch of symbols under a `TYPE_CHECKING` conditional check. I'm guessing you did this to try to avoid runtime import circularities. That's just masking the fact that your code is not well layered. I recommend looking for ways to refactor your code so you can eliminate these `TYPE_CHECKING` conditions and eliminate circular dependencies. Consider enabling the `reportImportCycles` check and eliminating those errors.

**Comment by Gobot1234** [comment]
I'll see if I can get rid of them going forwards but I feel like there's not much I can do bar put everything in one massive file

**Comment by erictraut** [comment]
I'm going to close this as "won't fix". Try to eliminate the circular dependencies within your code.
