### ISSUE TITLE
TypedDict not inferred when using dict constructor

### ISSUE THREAD

**Issue by tekumara** [microsoft/pyright#6051]
```python
from typing import TypedDict


class Movie(TypedDict):
    name: str
    year: int


def accept(m: Movie) -> None:
    ...


# works
accept({"name": "Alien", "year": 1979})

# error: Argument of type "dict[str, str | int]" cannot be assigned to parameter "m" of type "Movie" in function "accept"
accept(dict(name="Alien", year=1979))
```

pyright 1.1.329
python 3.11.4

**Comment by erictraut** [comment]
This is working as intended.

The `dict` constructor (as specified in `builtins.pyi`) has multiple overloads, but the one that applies in this case is:
```python
class dict(MutableMapping[_KT, _VT], Generic[_KT, _VT]):
    ...
    def __init__(self: dict[str, _VT], **kwargs: _VT) -> None: ...
```

The resulting return type is `dict[str, str | int]` which is not type compatible with a `TypedDict`.

Type checkers contain special logic to handle dictionary expressions, which is why this works in that case. If you want to use a `TypedDict`, you'll need to use dictionary expressions.
