### ISSUE TITLE
Type narrowing on bool with `Literal[True]` only works with `==` operator

### ISSUE THREAD

**Issue by rayansostenes** [microsoft/pyright#6113]
**Code or Screenshots**
```python

from typing import Literal, Union
from typing_extensions import assert_type


class TypeA:
    type: Literal[True]
    only_a: str

class TypeB:
    type: Literal[False]
    only_b: str


def test_type1(a_or_b: Union[TypeA, TypeB]):
    if a_or_b.type == True and a_or_b.only_a:
        assert_type(a_or_b, TypeA)

def test_type2(a_or_b: Union[TypeA, TypeB]):
    if a_or_b.type == False and a_or_b.only_b:
        assert_type(a_or_b, TypeB)

def test_type3(a_or_b: Union[TypeA, TypeB]):
    if a_or_b.type and a_or_b.only_a: # Cannot access member "only_a" for type "TypeB"
        assert_type(a_or_b, TypeA) # "assert_type" mismatch: expected "TypeA" but received "TypeA | TypeB"
```

**Comment by erictraut** [comment]
Yes, this is by design. You're using a type guard pattern called "discriminated unions" to distinguish between one of two types based on the literal type of one of the fields. This type narrowing pattern is supported only for `==` and `!=` operators. For a full list of type guard patterns that pyright supports, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards). 

It would be theoretically possible to extend support for discriminated unions via the "falsy/truthy" type guard pattern, but in practice this would measurably impact type analysis performance for all code. That wouldn't be a good tradeoff, so it's unlikley we'd consider doing this.

The workaround is to use `x.y == L` or `x.y != L` (where `L` is a literal value) in your conditional statement. Alternatively, you can use `x.y is L` or `x.y is not L` for `enum` and `bool` literals.

I'll point out that it's unusual to use `bool` literals for discriminated unions. More typically, a `str` literal is used.

```python
class TypeA:
    type: Literal["a"]
    only_a: str

class TypeB:
    type: Literal["b"]
    only_b: str

def test_type3(a_or_b: TypeA | TypeB):
    if a_or_b.type == "a" and a_or_b.only_a:
        assert_type(a_or_b, TypeA)
```

**Comment by rayansostenes** [comment]
Thanks for the fast response.
Yes, this is a little unusual, I discover that using django `HttpRequest` class.

**Type stubs**
```python
class AbstractBaseUser:
    @property
    def is_authenticated(self) -> Literal[True]: ...

class AnonymousUser:
    @property
    def is_authenticated(self) -> Literal[False]: ...

class HttpRequest(BytesIO):
    # ...
    user: Union[AbstractBaseUser, AnonymousUser]
```

**My use case**
```python
def my_django_view(request: HttpRequest):
   if request.user.is_authenticated and request.user.something:
      # do something here
```
