### ISSUE TITLE
Inconsistent behavior of type guards in the fall-through (else) case.

### ISSUE THREAD

**Issue by minmax** [microsoft/pyright#6140]
`__bool__` method produce a "good" fall-through (else) case, but TypeGuard function is not.

pyright version: git main 0d8e18cfbd318d34389fa402d4ba287a1c9cac2b Thu Oct 12 12:49:48 2023 -0700

```python
class Tr:
    def __bool__(self) -> Literal[True]:
        return True

class Fl:
    def __bool__(self) -> Literal[False]:
        return False

def is_tr(obj: object) -> TypeGuard[Tr]:
    return isinstance(obj, Tr)

TorF = Tr | Fl

def get_t_or_f() -> TorF: ...
val = get_t_or_f()


if is_tr(val):
    reveal_type(val)  # Tr
else:
    reveal_type(val)  # Tr | Fl --- Tr is unwanted here

if val:
    reveal_type(val)  # Tr
else:
    reveal_type(val)  # Fl
```

ps maybe its better to update [6129](https://github.com/microsoft/pyright/issues/6129), instead of create new issuer? What should i do next time with similar cases?

**Comment by erictraut** [comment]
This isn't a bug. Pyright is working correctly here.

Refer to [PEP 647](https://peps.python.org/pep-0647/#typeguard-type) for details about `TypeGuard`. User-defined type guards do not narrow types in the negative (else) case.

You may also be interested in [PEP 724](https://peps.python.org/pep-0724/), which is still in the draft stage. Pyright has provisional support for PEP 724 (you need to set the `enableExperimentalFeatures` setting to true), but I don't recommend doing this for production code at this time because the PEP could change or be rejected.
