### ISSUE TITLE
[LSP]: retain function docstrings for decorators that return a class

### ISSUE THREAD

**Issue by RobertCraigie** [microsoft/pyright#6149]
**Is your feature request related to a problem? Please describe.**
Currently, defining a decorator that returns a callable class instead of another `Callable` results in the docstring for the function being lost. For example:

```py
from __future__ import annotations
from typing import Generic, TypeVar, Callable
from typing_extensions import ParamSpec

P = ParamSpec("P")
R = TypeVar("R")

class APIMethod(Generic[P, R]):
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> R:
        ...

def api_method() -> Callable[[Callable[P, R]], APIMethod[P, R]]:
    ...

@api_method()
def create(a: int) -> str:
    """Method description"""
    return f"Hello {a}"

create(1)
```

When hovering over the last line this is shown:
![Screenshot 2023-10-13 at 13 45 39](https://github.com/microsoft/pyright/assets/23125036/b07b5b94-df9f-45d8-bfca-f01b953ee805)

And if `api_method` is updated to return `Callable[[Callable[P, R]], Callable[P, R]]`, then the docstring is shown:

![Screenshot 2023-10-13 at 13 46 37](https://github.com/microsoft/pyright/assets/23125036/27df57f3-d258-4434-97d0-2cec71a8f7fc)

**Describe the solution you’d like**

Ideally Pyright would show the docstring in this case as well.

**Comment by erictraut** [comment]
Pyright already displays docstring information in the "signature help" when using a callable object in a call expression.

![image](https://github.com/microsoft/pyright/assets/7040122/afc47634-3769-4a9d-8984-d1b30f7e5c60)

Pyright does not display docstrings for a `__call__` method on a callable object when hovering over an identifier. This is true regardless of whether a `ParamSpec` is involved. I don't think it would be appropriate to display the `__call__` docstring unconditionally in the hover text, especially in cases where the identifier is not used in a call expression. One could make the argument that the `__call__` method docstring should be included in the hover text only in the case that the identifier appears as part of a call expression, but that's debatable. Currently, hover text doesn't depend on how the identifier is used, and there's value in this consistency.

In any case, the language server functionality in pyright is owned by the pylance team, so they would need to decide what principles they want to use for the "hover provider" (the component that provides the hover text). 

@debonte, I'm going to close this request as "won't fix" here in pyright, but you're welcome to transfer it to the pylance-release project if you want to consider it as an enhancement request or create a discussion forum post so you can collect additional user input.

**Comment by rattrayalex** [comment]
@erictraut you seem focused here on the fact that the cursor was over the identifier `create` rather than the parens, but the same behavior happens in the parens – is that also intended?

**Comment by erictraut** [comment]
I'm not sure what you mean by "the cursor was over the identifier...". Are you talking about the _cursor_ (the blinking insertion point) or the _mouse pointer_? The hover provider is invoked based on the location of the mouse pointer. The signature help provider (whose output is seen in the screen shot I posted above) is invoked based on the location of the cursor.

The OP uses the term "hover", so I presume he's talking about the "hover provider" behavior. Pyright's hover provider logic provides hover information only for identifiers, not for other tokens like parentheses. This is consistent with the behavior of other language servers in other languages.

If you hover over a token like a paren, pyright uses heuristics to find a nearby identifier, which is why you may see hover text when hovering over the open parenthesis. Such heuristics are especially important when the code is incomplete and not syntactically correct.

So yes, this behavior is expected.

**Comment by rattrayalex** [comment]
Ah, makes sense - I didn't understand that. 

> One could make the argument that the __call__ method docstring should be included in the hover text only in the case that the identifier appears as part of a call expression

Yes, I think we're here to make that argument. From a user's perspective, if they're calling something with `__call__`, why should it be a worse experience than calling something that directly inherits `Callable`?

It's my impression that `Callable` can't be subclassed, so this limits the ability for folks to provide decent DX for augmented functions/methods.

(For the record, this no longer blocks our use-case – we've moved away from this pattern for other reasons – but I do still think it'd be a good thing to do).

**Comment by wch** [comment]
I just ran into this exact same issue. It would be very helpful if pyright/pylance would preserve the docstring 
for decorators which return callable classes. As things currently stand, when we have decorators which return a callable class, it is difficult to use them in VS Code, because the docstring gets lost along the way.
