### ISSUE TITLE
OpenCV comparison MatLike vs float

### ISSUE THREAD

**Issue by brccabral** [microsoft/pyright#6187]
Pylance highlights MatLike comparison with float values, but the program runs fine.

```
import cv2

img = cv2.imread("larger_img.png", cv2.IMREAD_UNCHANGED)
find_me = cv2.imread("find_part.png", cv2.IMREAD_UNCHANGED)

result = cv2.matchTemplate(img, find_me, cv2.TM_CCOEFF_NORMED)

selected = result >= .7  # pylance highlights here
print(selected)
```

```
Operator ">=" not supported for types "MatLike" and "float"
  Operator ">=" not supported for types "ndarray[Any, dtype[generic]]" and "float"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

**Comment by erictraut** [comment]
`MatLike` is a type alias defined as `cv2.mat_wrapper.Mat | np.ndarray[Any, np.dtype[np.generic]]`. The `__ge__` method for the class `np.ndarray[Any, np.dtype[np.generic]]` does not support an argument of type `float`, so pyright is correct to emit a type error in this case. Mypy generates the same error.

I don't know enough about these libraries to say whether this is a bug in the type annotations — and if so, where that bug is. You may want to post a question in a discussion forum for the `cv2` library.

In any case, pyright is doing the right thing here, so I'm going to close the issue.
