### ISSUE TITLE
Huge resources consumption and time required when using `with` statements

### ISSUE THREAD

**Issue by alex-schulster** [microsoft/pyright#6200]
**Environment description**
I use Neovim 0.9.0 with Pyright LSP 1.1.32 on Ubuntu 22.04.1

**Describe the bug**
When using a `with` statement (see code snippet below for a concrete example), my CPU usage bumps to 100% on one core, node being the guilty process (the memory usage remains stable though) and it takes PyRight about a minute (!) to treat the line of code.

**Code or Screenshots**
Here is a code snippet in Python that triggers the bug. The code must be hand written and not copy pasted.

```python
with open('test', 'w') as file:
    file.write('test')
```
Here is a screenshot of the resources used when PyRight tries to crunch the line
![Screenshot from 2023-10-16 14-31-43](https://github.com/microsoft/pyright/assets/40316586/bdc702db-7581-4e1d-834b-54a632e257a3)

**VS Code extension or command-line**
PyRight is used as a LSP inside Neovim using Mason

**Comment by alex-schulster** [comment]
I am able to reproduce the bug with the same config but on a Mac, so it does not appear to be OS dependant.

From what I read on the internet, I wonder it it is not linked to the lack of file based cancelation in Neovim (see [this post](https://github.com/microsoft/pyright/issues/4878#issuecomment-1492085172))

Following your indication, the problem seems to come in fact from the `open` function. I think this is caused by the high number of overloads of the function. Commenting out most of the overloads and only keeping the first 2 ones solves the performance issue.
(`~/.local/share/nvim/mason/packages/pyright/node_modules/pyright/dist/typeshed-fallback/stdlib/builtins.pyi` file)


![SCR-20231020-d5f](https://github.com/microsoft/pyright/assets/40316586/d7a30478-71a5-4c85-8487-6ce4543056cb)
*Before overload reduction*

![SCR-20231020-dah](https://github.com/microsoft/pyright/assets/40316586/d6d7cbe3-f24f-45ce-b851-7fbca11b231a)
*After overload reduction*

**Comment by erictraut** [comment]
The lack of file-based cancelation will prevent additional commands from being processed by the language server until it completes the long-running command. In other words, it will exacerbate the problem if a command takes a long time time to process, but that doesn't explain why you're seeing such a long processing time.

There are only 7 overloads for `open` defined in `builtins.pyi`, so I wouldn't expect that to be a big performance bottleneck. If there were thousands of overloads, that could explain what you're seeing.

In VS Code, I see a small (perhaps 1s) delay when resolving the signature help for `open('w')`. That's a couple orders of magnitude different from what you're apparently seeing.

![OpenSignatureHelp](https://github.com/microsoft/pyright/assets/7040122/24392dd2-57f3-442f-9d0d-4e227a8ed2db)

I know very little about neovim or its LSP plugin. You may need to work with the maintainers of [coc-pyright](https://github.com/fannheyward/coc-pyright) or whatever LSP plugin you're using. They may be able to help further diagnose why you're seeing this behavior when using pyright with neovim.

If you're able to get additional clues, such as the specific language server request that is taking so much time to process, feel free to post here. In the meantime, I'm going to close this issue because I don't think there's much more I can do on my end.
