### ISSUE TITLE
Module not resolved with latest pip version

### ISSUE THREAD

**Issue by Timmmm** [microsoft/pyright#6209]
**Describe the bug**
I have a project that activates a `venv` environment and installs two local packages using `pip install --editable`. Then one package imports something from the other.

This works fine if i don't upgrade `pip` in the `venv` (so it uses version 20.2.4), however if I upgrade it to 23.3 then Pyright can't resolve the modules anymore. I guess this could be a `pip` issue but I don't know.

There's a second issue, in that resolving a module in the *same* package doesn't work. But in that case it is the other way around - it doesn't work with Pip 20.2.4 but it does with 23.3! So let's ignore that for now.

**Code or Screenshots**
Clone [this repo](https://github.com/Timmmm/python_issue).

Then run

```
cd project/tool
./setup.sh
```

Then open the repo in VSCode. Open `configure.py`. The import will not resolve, even if you select the venv interpreter.

If you start again but this time delete this line from `setup.sh` it works fine:

    python3 -m pip install --upgrade pip

**VS Code extension or command-line**
VSCode via Pylance v2023.10.30

**Comment by erictraut** [comment]
This is most likely related to editable installs and the unfortunate effects of PEP 660. See [this documentation](https://microsoft.github.io/pyright/#/import-resolution?id=editable-installs) for details. Please follow the suggested workarounds and see if that addresses your issue.

**Comment by Timmmm** [comment]
Aha, both `--config-settings editable_mode=compat` and `=strict` worked, thanks! Unfortunately neither seems to be idea. The docs for `compat` say it is transitional and will be removed in future, and although `strict` works, it means go-to-definition opens the symlinks rather than the original files, and VSCode doesn't work too well with symlinks. I guess most things don't work very well with symlinks because they're an ugly hack.

I'll stick with `compat` for now until they remove it or add a proper solution for tools. Thanks for the help!

**Comment by erictraut** [comment]
I agree that neither is ideal. The problem is not with symlinks but rather with dynamic "import hooks" that require execution of code to resolve imports. Dynamic import hooks work fine at runtime but do not work for tools that use static code analysis, since they don't execute any Python code by design. The packaging community was warned that if they went this route they would break all static analysis tools (including type checkers, language servers, linters, etc.), but they unfortunately went ahead with with the change anyway. If you have concerns about it, please reach out to the maintainer of your build backend (setuptools, etc.) and make your thoughts known.

**Comment by wookayin** [comment]
See #5473
