### ISSUE TITLE
Unsupported type "Unbound"

### ISSUE THREAD

**Issue by c3-willydouhard** [microsoft/pyright#622]
It looks like this problem already occurred and was fixed. Is this a regression ?

**To Reproduce**
Import variables from a module that is not installed and use. them.

**Expected behavior**
Pyright considers the imported variables as unknown / Any and does not highlight them in red

**Screenshots or Code**
<img width="718" alt="Screen Shot 2020-04-15 at 1 50 03 PM" src="https://user-images.githubusercontent.com/33715721/79334289-47e39680-7f20-11ea-8bca-57efd01b638c.png">

`nn` is of type unbound, accessing a property of an unbound type raises an error.

Using the VSCode extension.

**Comment by erictraut** [comment]
Thanks for the bug report. This problem is related to, but somewhat different from, the previous error. It occurs only when using an aliased import ("import x as y") and only when "y" is referenced from an execution context other than that in which the import statement is located (such as a function). You'll notice in your example that the error wasn't reported for the first use of "nn" because it's in the same execution context as the import.

In any case, this is a bug, and I've introduced a fix that will be in the next published version of Pyright. Thanks again for reporting it!

**Comment by erictraut** [comment]
This is now fixed in version 1.1.32, which I just published.
