### ISSUE TITLE
`python.analysis.*` settings don't always override Pyright settings for VSCode

### ISSUE THREAD

**Issue by max-muoto** [microsoft/pyright#6240]
**Describe the bug**
I'm looking to disable `useLibraryCodeForTypes` within our `pyproject.toml`, however this has the side-effect of disabling Pylance  functionality for unannotated 3rd-party libraries within VSCode.

I went to manually set `"python.analysis.useLibraryCodeForTypes": true` in our project's `.vscode/settings.json`, but the pyproject setting still takes precedence. However, I'm able to override the settings that fall under `python.analysis.diagnosticSeverityOverrides` (similar to this example: https://github.com/microsoft/pyright/issues/3039). 

Is there a reason why setting rules under `python.analysis.diagnosticSeverityOverrides` would take precedence over the `pyproject.toml` but the other `python.analysis` rules wouldn't?

It seems to me having VSCode settings take precedence over`pyproject.toml` settings for VSCode would be preferable, or at least giving users some way of overriding them in VSCode if they want differing settings for type-checking vs their language server.

**VS Code extension or command-line**
Have the Pylance VScode extension installed, but also have Pyright as a CLI tool installed.

Running on pyright 1.1.333.

**Comment by erictraut** [comment]
The rules for composing settings in pyright are complex. We need to merge settings from:
1. The command line
2. Config file (either pyrightconfig.json or pyproject.toml)
3. Language server project settings
4. Language server workspace settings
5. Language server user settings
6. File-specific overrides

To make things even more complex, some configuration settings affect each other. For example, if you set `typeCheckingMode` to `strict`, it overrides the diagnostic severities of many diagnostic rules.

The assumption is that if a setting is specified in a config file, it's authoritative for that project. When working on projects with many developers, it's important for everyone to use the same settings, so allowing individual team members to override project settings with their own values tends to lead to problems. 

The `python.analysis.diagnosticSeverityOverrides` language server setting is an exception to this general rule because of the complexities involved in the overlap between settings.

It's unlikely we'd make the change you're proposing. It would be very disruptive to pyright/pylance users and would lead to hard-to-diagnose problems for teams who are relying on consistent and deterministic behavior when a setting is specified in a project's config file.

If I understand you correctly, you want to see different behavior between your editor experience and your CI type checking. Most pyright/pylance users want those two to match as much as possible, so this is pretty atypical.

Here are some potential solutions for your use case:
1. Change your pyproject.toml so it doesn't specify a value for `useLibraryCodeForTypes`. This will allow you and your teammates to specify whatever value you want locally in your editor. Then create a separate `pyrightConfigForCI.json` file that specifies the settings you want to use for your CI scripts. When running the CLI version of pyright, you can specify a separate config file using the "-p" [command-line option](https://microsoft.github.io/pyright/#/command-line).
2. Leave `useLibraryCodeForTypes` enabled in pyproject.toml. If a particular untyped library is causing problems for type checking, create a dummy type stub that effectively causes all symbols imported from that library to be evaluated as `Any`. To do this, create a new directory in your code repo called "typings". Within this directory, create a subdirectory for the offending library. Within that subdirectory, create a file `__init__.pyi` and add the code `def __getattr__(name: str) -> int: ...`. This will tell pyright/pylance to not infer types for this library. You can check in this "typings" directory and its contents to your repo so everyone on the team gets the same behavior.

**Comment by max-muoto** [comment]
Thanks for the write-up Eric, this is super helpful!
