### ISSUE TITLE
Issues with __class_getitem__

### ISSUE THREAD

**Issue by monkeyman192** [microsoft/pyright#6255]
**Describe the bug**
I am trying to do some kind of generic typing with a decorator and found two issues relating to the `__class_getitem__` method.
One is related to the method itself where pylance doesn't like the type of the `cls` argument:
Line `def __class_getitem__(cls: "Decorator", key):` gives the error `Type of parameter "cls" must be a supertype of its class "type[Decorator]"` when hovering over the `"Decorator"` value.
The second is with the decorator when using it. This error is on the `int` in `@Decorator[int]`:
`Expected no type arguments for class "Decorator"`

**Code or Screenshots**
The following will reproduce both errors. This has a bit of extra code which isn't required, but it is just to make the entire example run-able and because this is mostly a minimal reconstruction of what I am doing.

```python
class Other:
    def __init__(self, func, generic):
        self.func = func
        self.generic = generic

    def __call__(self, *args, **kwargs):
        print(f'Calling func with generic params: {self.generic}')
        return self.func(*args, **kwargs)

class Decorator:
    _generic = None
    def __init__(self, func):
        self.func = func

    def __new__(cls, func):
        return Other(func, generic=cls._generic)

    def __class_getitem__(cls: "Decorator", key):
        cls._generic = key
        return cls

@Decorator[int]
def func(x):
    print(x)

func(3)
```

**VS Code extension or command-line**
using pylance v2023.10.50 in vscode with the python extension version v2023.19.13001012 (I decided to test with pre-release to see if it changed anything...)

**Comment by erictraut** [comment]
Pyright's behavior is correct here.

First, `__class_getitem__` is implicitly a `@classmethod`, so the first parameter must be a subtype of `type[Decorator]` rather than `Decorator`. As with all class methods, pyright will infer the type of `cls` to be `type[Self]` which is preferable to `type[Decorator]` because it accommodates subclasses.

Here's what the official [python documentation](https://docs.python.org/3/reference/datamodel.html#emulating-generic-types) says:

> When defined on a class, __class_getitem__() is automatically a class method. As such, there is no need for it to be decorated with [@classmethod](https://docs.python.org/3/library/functions.html#classmethod) when it is defined.

Second, it appears that you're attempting to implement your own generic types. This isn't supported by type checkers. If you want a type to be generic, it should use `Generic` as a base class.

Here's what the official [python documentation](https://docs.python.org/3/reference/datamodel.html#the-purpose-of-class-getitem) says:

> Custom implementations of [__class_getitem__()](https://docs.python.org/3/reference/datamodel.html#object.__class_getitem__) on classes defined outside of the standard library may not be understood by third-party type-checkers such as mypy. Using __class_getitem__() on any class for purposes other than type hinting is discouraged.
