### ISSUE TITLE
SQL Alchemy and pyright

### ISSUE THREAD

**Issue by dcsan** [microsoft/pyright#626]
I have a class which has a superclass, and uses sqlalchemy definitions of instance variables 
eg:

```python

class Model(Base):
    id = Column(BigInteger(), primary_key=True)
    uuid = uuid_column(nullable=False, index=True, unique=True)
    name = Column(String(255), nullable=False)
    external_id = Column(String(255), nullable=False)
    source_id = Column(BigInteger(), cascading_key('model_source.id'), nullable=False)
    version = Column(String(80), nullable=False)
    marked_for_production_time = Column(DateTime)

```

when I try to create an instance of `Model` passing in properties the syntax highlighting blows up

```python
        return Model(
            name=name,
            external_id=str(self.id), version='1.0',
            source_id=self.id,
            staging=True
        )
```

![image](https://user-images.githubusercontent.com/514002/79426804-8b69ef00-7f78-11ea-93c8-263a34a37075.png)

Is this because it's looking in the superclass for these properties? 
or the syntax above for SQLAlchemy columns confuses things?

**VS Code extension or command-line**
Using within VSCode

**Additional context**
Above works fine in PyCharm

**Comment by dcsan** [comment]
comparing code in PyCharm (vanilla config)
and using PyRight (after messing around with the config for a while)

![image](https://user-images.githubusercontent.com/514002/79429543-7abb7800-7f7c-11ea-9ce8-8e2328fcabc4.png)

**Comment by erictraut** [comment]
The problem here is that SQL Alchemy is making use of a metaclass (DeclarativeMeta) that implements non-standard behaviors. In particular, it dynamically auto-generates a constructor based on the class variables you've defined. PyCharm apparently has knowledge of this custom behavior. 

Pyright does not currently have knowledge of non-standard behaviors within any third-party libraries, and I don't currently plan to add such knowledge. I may eventually add a plug-in mechanism to pyright so non-standard behaviors for third-party libraries could be expressed in plug-in logic. This is how mypy solves this problem.

I'm not able to repro the exact errors that you're seeing. I might be able to offer some suggested workarounds, but I'll need some additional information from you first.
1. Have you created or installed type stubs for sqlalchemy?
2. Do you have the "pyright.useLibraryCodeForTypes" setting enabled in VS Code? (It's disabled by default.)
3. What version of sqlalchemy are you using?

**Comment by devenv** [comment]
Just to report that changing `useLibraryCodeForTypes` to false worked for me, e.g.:

```
useLibraryCodeForTypes = false,
typeCheckingMode = "basic",
```
