### ISSUE TITLE
Infer *args/**kwargs from base class

### ISSUE THREAD

**Issue by last-partizan** [microsoft/pyright#6344]
**Is your feature request related to a problem? Please describe.**
My use case is, when overriding some methods with lot of arguments, i use `args and kwargs`, and pass them without changes.

```python
class Book(models.Model)
    ...
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
```

I have considered using https://stackoverflow.com/questions/71968447/python-typing-copy-kwargs-from-one-function-to-another but probably this is better solved by inferring.

**Describe the solution you’d like**

If base class already has all arguments defined in superclass, pyright can infer args/kwargs.

MyPy has this issue, but they aren't added it yet: https://github.com/python/mypy/issues/10079

**Comment by erictraut** [comment]
I understand the concept you're proposing, but it won't work. Pyright already supports inferring the types of unannotated parameters when the signature of a child method matches the signature of a parent method of the same name. Inference is done on a per-parameter basis because each parameter in the child signature is a separate symbol. For example, if the signature is `foo(self, a, b, c)`, then `a`, `b`, and `c` are distinct symbols, and their types are inferred accordingly. 

With your proposal, there symbols that are present in the child method are `args` and `kwargs`. There are no types that can be inferred for these two symbols that would properly reflect the signature of the parent method.

If you want your child methods to be typed, you'll need to spell out the parameters individually.

**Comment by navignaw** [comment]
Is there a recommendation for a generic way to reuse kwargs types in child classes?

I just ran into a similar issue in the https://github.com/marshmallow-code/marshmallow/ library. It defines a [Field constructor](https://github.com/marshmallow-code/marshmallow/blob/c152af49ab5466104a34de5885cf52f4493f3c7d/src/marshmallow/fields.py#L155-L176) with dozens of kwargs. It feels unwieldy to force each of the 18 subclasses (e.g. [DateTime](https://github.com/marshmallow-code/marshmallow/blob/c152af49ab5466104a34de5885cf52f4493f3c7d/src/marshmallow/fields.py#L1263)) to copy out all of those kwargs just to inherit the typing.

However, as written, the kwargs ends up getting typed as "Unknown", leading to potentially unhandled errors at runtime that easily should have been caught by a typechecker.

Just as a reference, TypeScript has a generic utility called [ConstructorParameters](https://www.typescriptlang.org/docs/handbook/utility-types.html#constructorparameterstype) which achieves this.

**Comment by erictraut** [comment]
The closest thing in the Python type system is documented [here](https://typing.readthedocs.io/en/latest/spec/callables.html#unpack-for-keyword-arguments). It allows you to define a `TypedDict` and use it to define the keyword arguments in a `**kwargs` parameter.
