### ISSUE TITLE
New diagnostic rule defaults: "all"

### ISSUE THREAD

**Issue by sweemer** [microsoft/pyright#6376]
Currently there are three [diagnostic rule defaults](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#diagnostic-rule-defaults): `"off"`, `"basic"`, and `"strict"`.

I propose adding a fourth default `"all"`, which sets all the boolean rules to `true` and all the other rules to `"error"`.

The rules currently set to `"none"` in `"strict"` mode look useful to me, and I would prefer to add them by default rather than individually in my config (and potentially miss out on new ones that are added in the future).

**Comment by erictraut** [comment]
I don't think that would make sense. If a rule is not enabled by default in "strict" mode, that's because it is applicable for a minority of code bases. For example, `reportUninitializedInstanceVariable` `reportMissingSuperCall` and `reportImportCycles` would be problematic for most Python code bases.

If you think that a particular diagnostic rule looks useful, you're certainly welcome to enable it in your configuration file.

**Comment by ejfine** [comment]
> and potentially miss out on new ones that are added in the future

this is the larger concern for me.  is there a different way to "autosubscribe" to any new rules that are created?  I've found that capability very helpful in other tooling (e.g. ruff) so that when I upgrade versions I can see if there are any issues with my current codebase right away.  that gives me the option to make quick fixes now, disable the rule if I disagree with it, or ticket the fixes as future tech debt.  without autosubscribe, it is easy to run into the situation where your codebase keeps growing in violation of a new rule and you don't even realize it for a year and then all of a sudden you've got a large number of violations that are much more challenging to resolve
