### ISSUE TITLE
Generic class is not imported as a generic class

### ISSUE THREAD

**Issue by A5rocks** [microsoft/pyright#6377]
**Describe the bug**
I'm seeing inconsistent behavior between defining a generic class and importing it. (Or well, someone else did, I'm just pretty sure what's happening is a pyright bug. https://github.com/python-trio/trio/issues/2873)

**Code or Screenshots**

Unfortunately the first few attempts I did to try to spit out something that I *thought* was the cause (inheriting from `Tuple`, implied generics) didn't yield this same error. So, here's something that depends on `trio==0.23.1`:

```python
# pyright: strict
from trio._channel import MemorySendChannel, MemoryReceiveChannel, open_memory_channel
import typing

T = typing.TypeVar("T")

class omc(typing.Tuple[MemorySendChannel[T], MemoryReceiveChannel[T]]):
    def __new__(  # type: ignore[misc]  # "must return a subtype"
        cls, max_buffer_size: int | float
    ) -> tuple[MemorySendChannel[T], MemoryReceiveChannel[T]]:
        ...

    def __init__(self, max_buffer_size: int | float):
        ...

reveal_type(omc)
reveal_type(open_memory_channel)
```

Pyright, in response spits out:
```
C:\Users\A5rocks\Documents\trio\empty\pyright-repro.py
  C:\Users\A5rocks\Documents\trio\empty\pyright-repro.py:16:13 - information: Type of "omc" is "type[omc[Unknown]]"
  C:\Users\A5rocks\Documents\trio\empty\pyright-repro.py:17:13 - information: Type of "open_memory_channel" is "type[open_memory_channel]"
0 errors, 0 warnings, 2 informations
```

... Which seems wrong given `omc` is literally copy-pasted from `open_memory_channel`'s definition, with `Tuple` -> `typing.Tuple` and replacing the body of `__new__` with `...`.

**VS Code extension or command-line**
Installed via `pip` and `pip show pyright` reports version 1.1.334.

**Comment by erictraut** [comment]
Pyright is working correctly here, so I don't consider this a bug.

The problem is in the `trio/_channel.py` file. It declares a class called `open_memory_channel`. It derives from the type `Tuple[MemorySendChannel[T], MemoryReceiveChannel[T]]`. The problem is that `MemorySendChannel` and `MemoryReceiveChannel` are not defined at that point in the file, so they are evaluated as `Unknown`. The resulting class is therefore not considered generic. If you move the declaration of the `open_memory_channel` class later in the file (after `MemorySendChannel` and `MemoryReceiveChannel` have been defined, then it will work as you expect.
