### ISSUE TITLE
Variable of type `Self` does not cause `reportIncompatibleVariableOverride`

### ISSUE THREAD

**Issue by juk-r** [microsoft/pyright#6400]
Since in subclasses type will automatically change and its type is invariant, must report error. Except `Final[Self]` or similar.
```python
from typing import Self, reveal_type, Final

class A:
    x: Self
    # should be ok:
    y: Final[Self]

class B(A):
    ...

reveal_type(B.x) # B
```

with pyright 1.1.335

**Comment by erictraut** [comment]
The current behavior is intended, so I don't consider this a bug. The `reportIncompatibleVariableOverride` check is performed only when a subclass redefines a variable (that is defined in a parent class) in an incompatible way. In this example, `B` is not redeclaring the variable `x`, so there is no override to check.

I agree that there is a typing hole here. It may be desirable for type checkers to detect the condition where an instance variable is annotated with `Self` in a class that is not final. To my knowledge, no Python type checkers currently check for this condition.

I've changed this from a bug report to an enhancement request.

I'm going to reject the request for now because I'm not convinced this is a big enough problem to justify adding the feature and generating false positives for existing code bases that are exploiting this hole in a way that's safe. I'm willing to reconsider this decision in the future if there is sufficient demand from pyright users (e.g. in the form of upvotes) or the typing spec is updated to clarify that type checkers are expected to check for this condition.
