### ISSUE TITLE
Errors when returning a class instance from a classmethod in v1.1.335

### ISSUE THREAD

**Issue by neefrehman** [microsoft/pyright#6401]
**Describe the bug**

Since v1.1.335, we have been getting errors when we try to return an instance of a class, via its own classmethod. This is something we do frequently in our app, when converting an object in our domain model to its equivalent in our API (and vice-versa). 

The error messages are related to the literal string types in use, and look like:

```shell
Expression of type "Literal[StatusFromAPI.DRAFT]" cannot be assigned to return type "Self@StatusFromAPI".
  Type "Literal[StatusFromAPI.DRAFT]" cannot be assigned to type "Self@StatusFromAPI"
```

**Code or Screenshots**

also in a [Pyright playground link](https://pyright-play.net/?code=GYJw9gtgBApgdgV2gSwgBzCALlAooiAGigGUsR8kAoUSKLATzWTgHMpUNtSYAbYKlQDGvAIYBncaSyisCcQGEwccTLhYAYuAgARSKJYAKMhQIBKAFxUoNqDoBKAQQ0AVKAF4oAIgAmIUcBYXta2CgDyALIACgAyuC64Ht4AbqK8yD6yMD7BwmKS0rLyWpCOUQCShpQQliE2Ds5unr7%2BgcG2UOHRcQlJXkKQaLwwWDC5HQACIhLiECMAFmA%2BdVA%2BMMBQtBAA%2Bj76RiLixCyqonBCMBaFcorKp%2BoluvtwZlAAtAB8PPxWHR0QsiE8w4KjUF1%2Bf0hQgkMGu8iUoLOmm0egBLAAdA1XBDIbioCARggQHAoIdMU5XCs8dDxLCyEVboiHijnuiurF4rgcXi-gS5MTSbxxGzIhyEoJJtNJHMsItlh01hstttRMxDIdjkzwd9gK9PnDGfdkZBUQY4Nz-oDgScwZcqbiabCyViXBaeTY%2BUSSfSbgijY9TRiXfaoTDBcL2T0uSGeZ6BT74Xc1Manmi4CLupyqEA)

```python
from enum import Enum, StrEnum
from typing import Self

class StatusConstantFromDomain(StrEnum):
    DRAFT = "draft"
    COMPLETE = "validated"

class StatusFromAPI(Enum):
    DRAFT = "draft"
    COMPLETE = "complete"

    @classmethod
    def from_domain(cls, instance: StatusConstantFromDomain) -> Self:
        match instance:
            case StatusConstantFromDomain.DRAFT:
                return cls.DRAFT    # Expression of type "Literal[StatusFromAPI.DRAFT]" cannot be assigned to return type "Self@StatusFromAPI".  Type "Literal[StatusFromAPI.DRAFT]" cannot be assigned to type "Self@StatusFromAPI"
            case StatusConstantFromDomain.COMPLETE:
                return cls.COMPLETE # Expression of type "Literal[StatusFromAPI.COMPLETE]" cannot be assigned to return type "Self@StatusFromAPI".  Type "Literal[StatusFromAPI.COMPLETE]" cannot be assigned to type "Self@StatusFromAPI"

    @classmethod
    def to_domain(cls, instance: Self) -> StatusConstantFromDomain:
        match instance:
            case cls.DRAFT:
                return StatusConstantFromDomain.DRAFT
            case cls.COMPLETE:
                return StatusConstantFromDomain.COMPLETE
```

**VS Code extension or command-line**
We are running pyright via `npx pyright`, version `v1.1.335`

**Comment by neefrehman** [comment]
Thanks @juk-r. I think that a classmethod can't reference the class itself, at least from my testing. Referencing `StatusFromAPI` gives a `"StatusFromAPI" is not defined` error ([playground link](https://pyright-play.net/?code=GYJw9gtgBApgdgV2gSwgBzCALlAooiAGigGUsR8kAoUSKLATzWTgHMpUNtSYAbYKlQDGvAIYBncaSyisCcQGEwccTLhYAYuAgARSKJYAKMhQIBKAFxUoNqDoBKAQQ0AVKAF4oAIgAmIUcBYXta2CgDyALIACgAyuC64Ht4AbqK8yD6yMD7BwmKS0rLyWpCOUQCShpQQliE2Ds5unr7%2BgcG2UOHRcQlJXkKQaLwwWDC5HQACIhLiECMAFmA%2BdVA%2BMMBQtBAA%2Bj76RiLixCyqonBCMBaFcorKp%2BoluvtwZlAAtAB818XaZeVWHQ6EFkQnmHBUaguAMBMKEEhg31uELOmm0emBLAAdA1XNCYfioCARggQHAoIdsU5XCsCXDxAiyEUkfdUZB0QY4JiurF4rg8QTAUS5KTybxxFzIjyEoJJtNJHMsItlh01hstttRMxDIdjsjzpcePxXp9EUo9aynhi4PygSCwSdIZcafi6QiKTiXDaBTYhSSyYybmaWY92ViPc7YfDReLuT0%2BRGBb6RQH5EG1BbQ5zY7yqEA))

**Comment by erictraut** [comment]
@neefrehman, you need to enclose the annotation in quotes, since it's a forward reference ([playground link](https://pyright-play.net/?code=GYJw9gtgBApgdgV2gSwgBzCALlAooiAGigGUsR8kAoUSKLATzWTgHMpUNtSYAbYKlQDGvAIYBncaSyisCcQGEwccTLhYAYuAgARSKJYAKMhQIBKAFxUoNqDoBKAQQ0AVKAF4oAIgAmIUcBYXta2CgDyALIACgAyuC64Ht4AbqK8yD6yMD7BwmKS0rLyWpCOUQCShpQQliE2Ds5unr7%2BgcG2UOHRcQlJXkKQaLwwWDC5HQACIhLiECMAFmA%2BdVA%2BMMBQtBAA%2Bj76RiLixCyqonBCMBaFcorKp%2BoluvtwZlAAtAB83mRF4o9l5S8Vg6HQgsiE8w4KjUF2BIPhQgkMGu8iU0LOmm0ejBLAAdA1XHD4cSoCARggQHAoId8U5XCsSYjxMifjc0fdMZBsQY4LiurF4rgiSSQWS5JTqbxxHzIgKEoJJtNJHMsItlh01hstttRMxDIdjujzpcePxXp8UbcjZynji4MLQeDIScYZcGcSmciaQSXA6RTYxRSqazUXc1DbuXife6EUjJdL%2BT0hTGRYGJSGrRzHpHeYnBVQgA)). Alternatively, you can add a `from __future__ import annotations` at the top of the file to defer the annotation evaluation at runtime.

**Comment by erictraut** [comment]
I think pyright's (new) behavior is correct here. The type of `cls.DRAFT` is `Literal[StatusFromAPI.DRAFT]`, and this isn't type compatible with `Self`. The correct fix is to change the return annotation from `Self` to `StatusFromAPI` as suggested by @juk-r above.

Prior to 1.1.335, pyright's handling of `Self` was a bit too "loose", which is why you didn't see this with previous versions.

**Comment by neefrehman** [comment]
@erictraut thank you, we'll move forwards with using forward references.

As an aside, I also tried the `from __future__ import annotations` method you mentioned, but it had no impact on pyright. [Playground link here](https://pyright-play.net/?code=GYJw9gtgBA%2BjwFcAuCQFM5QJYQA5hCSgEMA7UsJYpLMUgZwChHRIo1SFod9CoBRThAA0UAMpIQgri3DQkAT1xZSAc2x4CRMWgA2wZgGNdxevXFUU9AMJ16VUkgBicgCKRiKgBQSpQgJQAXIxQoVCuAEoAgk4AKlAAvFAARAAmIMTASMkhYdYA8gCyAAoAMvyx-IkpAG7Eulip1GipOYzGpuYS1Aj0LpBRxQCSXtIQQbmhkTHxSWkZWTlhUAUl5ZXVyYaQuLpoSGhtywACHWYQ%2BwAWYKmTUKlowFCsEDCpHt7G9KIq9mSGaECFh6NjsDmcbg%2BpH8UAAtAA%2BcR6YDBZbLCDUQyXbAMBwA1FowmGUxoYFWWy4sgQyDuDEqAB00ziBMJrKg6BQIFIUC%2BjOicTubOJ9FJ3XJYKp-QgtM8pHpqzKFX4LLZaI5qG5vIV634zBOZ3oFyQ11uyweTxeMGIyi8Xx%2BlNI%2BKR%2BhhCLJvQpf0cUplKhV6Mx2N%2BeMBgtZwtJvKZsX9qtC6q57tBDup0qhfJmYaJJJ5uno8qKisqsbjCe5Yo9Eu9kLpcu1SsYQA).

**Comment by kkom** [comment]
@neefrehman – I think @erictraut's suggestion was to do something [like this](https://pyright-play.net/?code=GYJw9gtgBA%2BjwFcAuCQFM5QJYQA5hCSgEMA7UsJYpLMUgZwChHRIo1SFod9CoBRThAA0UAMpIQgri3DQkAT1xZSAc2x4CRMWgA2wZgGNdxevXFUU9AMJ16VUkgBicgCKRiKgBQSpQgJQAXIxQoVCuAEoAgk4AKlAAvFAARAAmIMTASMkhYdYA8gCyAAoAMvyx-IkpAG7Eulip1GipOYzGpuYS1Aj0LpBRxQCSXtIQQbmhkTHxSWkZWTlhUAUl5ZXVyYaQuLpoSGhtywACHWYQ%2BwAWYKmTUKlowFCsEDCpHt7G9KIq9mSGaECFh6NjsDmcbg%2BpH8UAAtAA%2BYFWfoQQZDYLLZYQaiGS7YBgOAEYzEkwymNBI3q2AlkCGQdzYlQAOmmcWJJI5UHQKBApCgXxZ0Tid05ZPoFO6Vmpf0cKIZnlITNWZQq-HZnMx3NQfIFyvW-GYJzO9AuSGut2WDyeLxgxGUXi%2BPxppCJlL6cjRMIRbul4LlUPVWJxeN%2BhMBIo5YopAtZsUDGtCWt5PrBtP9jMVsYjpPJ-N09CVRRVlXjCaTfMlVNTsshGcLa1VjCAA)

I.e. use `from __future__ import annotations` to write simply `StatusFromAPI` instead of `"StatusFromAPI"`

**Comment by neefrehman** [comment]
Ah I see! Thanks for the tip @kkom :)
