### ISSUE TITLE
Regression in support for cls of classmethod bound to Calalble in pyright 1.1.335

### ISSUE THREAD

**Issue by ringohoffman** [microsoft/pyright#6409]
**Describe the bug**
Previously supported via the fix for https://github.com/microsoft/pyright/issues/4447, `cls` in `classmethod`s were allowed to be bound as `Callable`s, but there was a regression in support for this in version 1.1.335.

**Code or Screenshots**

```python
from __future__ import annotations

from typing import Callable, Concatenate, ParamSpec

P = ParamSpec("P")


class A:
    def __init__(self, a_param_1: str) -> None:
        ...

    @classmethod
    def add_params(
        cls: Callable[P, A],
    ) -> Callable[Concatenate[float, P], A]:
        def new_constructor(i: float, *args: P.args, **kwargs: P.kwargs) -> A:
            return cls(*args, **kwargs)
        return new_constructor
    
    @classmethod
    def remove_params(
        cls: Callable[Concatenate[str, P], A],
    ) -> Callable[P, A]:
        def new_constructor(*args: P.args, **kwargs: P.kwargs) -> A:
            return cls("my_special_str", *args, **kwargs)
        return new_constructor


A.add_params()(1.0, "my_str")
A.remove_params()()
```

```console
$ pyright a.py
  a.py:12:6 - error: Argument of type "(cls: (**P@add_params) -> A) -> ((float, **P@add_params) -> A)" cannot be assigned to parameter "__f" of type "(type[_T@classmethod], **_P@classmethod) -> _R_co@classmethod" in function "__init__"
    Type "(cls: (**P@add_params) -> A) -> ((float, **P@add_params) -> A)" cannot be assigned to type "(type[_T@classmethod], **_P@classmethod) -> _R_co@classmethod"
      Parameter 1: type "type[_T@classmethod]" cannot be assigned to type "(**P@add_params) -> A"
        Type "type[_T@classmethod]" cannot be assigned to type "(**P@add_params) -> A"
          Function return type "object*" is incompatible with type "A"
            "object*" is incompatible with "A" (reportGeneralTypeIssues)
  a.py:20:6 - error: Argument of type "(cls: (str, **P@remove_params) -> A) -> ((**P@remove_params) -> A)" cannot be assigned to parameter "__f" of type "(type[_T@classmethod], **_P@classmethod) -> _R_co@classmethod" in function "__init__"
    Type "(cls: (str, **P@remove_params) -> A) -> ((**P@remove_params) -> A)" cannot be assigned to type "(type[_T@classmethod], **_P@classmethod) -> _R_co@classmethod"
      Parameter 1: type "type[_T@classmethod]" cannot be assigned to type "(str, **P@remove_params) -> A"
        Type "type[_T@classmethod]" cannot be assigned to type "(str, **P@remove_params) -> A"
          Function return type "object*" is incompatible with type "A"
            "object*" is incompatible with "A" (reportGeneralTypeIssues)
```

CLI version 1.1.335

**Comment by erictraut** [comment]
Previously, the reported error was `Type of parameter "cls" must be a supertype of its class "Type[A]"`. This is a different issue.

The type errors that you're seeing now are due to a bug fix that I introduced in pyright 1.1.335. I think pyright is doing the right thing here, whereas it previously was not.

The `classmethod` constructor requires you to pass it a value of type `Callable[Concatenate[type[_T], _P], _R_co]`. You're passing it a value of type `Callable[P, A]`, which is not compatible.

I'll note that mypy also generates errors for the code above, although it reports them in a different place.

Where are you using this approach? Is this in your own code, or is it in a library? Regardless, you should probably look for a different approach that doesn't run afoul of type checking rules.

**Comment by ringohoffman** [comment]
It is for an internal library at my job. The original example is a simplification of what we are actually doing. I will provide a more accurate example to illustrate why I want this behavior.

`Layer`s are created to be used by `Model`s. `Layer`s require a `shape`, which is determined based on the arguments to the `Model` constructor.

```python
from __future__ import annotations

from typing import Callable, Concatenate, Generic, TypeAlias, TypeVar, ParamSpec


class Layer:
    def __init__(self, shape: tuple[int, ...]) -> None:
        pass


ModelP = ParamSpec("ModelP")
LayerP = ParamSpec("LayerP")
LayerT = TypeVar("LayerT", bound=Layer)
LayerConstructor: TypeAlias = Callable[Concatenate[tuple[int, ...], LayerP], LayerT]


class Model(Generic[LayerP, LayerT]):
    def __init__(
        self,
        layer_class: LayerConstructor[LayerP, LayerT],
        model_param1: list[str],
        *args: LayerP.args,
        **kwargs: LayerP.kwargs,
    ) -> None:
        super().__init__()
        shape = (1, 2, 3)
        self.layer = layer_class(shape, *args, **kwargs)

    @classmethod
    def build(
        cls: Callable[Concatenate[LayerConstructor[LayerP, LayerT], ModelP], Model[LayerP, LayerT]],
        layer_class: LayerConstructor[LayerP, LayerT],
    ) -> Callable[ModelP, Model[LayerP, LayerT]]:
        def new_constructor(*args: ModelP.args, **kwargs: ModelP.kwargs) -> Model[LayerP, LayerT]:
            return cls(layer_class, *args, **kwargs)
        return new_constructor


class MySpecialLayer(Layer):
    def __init__(self, shape: tuple[int, ...], special_param1: int, special_param2: str) -> None:
        super().__init__(shape)


SpecialModel = Model.build(MySpecialLayer)  # a callable that expands out all the parameters of MySpecialLayer
special_model = SpecialModel(
    ["something", "something"],
    special_param1=1,
    special_param2="2",
)
```

The new constructors returned by `build` work really well with VS Code's Intellisense:

I like:
<img width="442" alt="Screenshot 2023-11-09 at 3 13 24 PM" src="https://github.com/microsoft/pyright/assets/27844407/800a9ffa-31ec-4d5f-8969-f1ceb52806d0">

<img width="523" alt="Screenshot 2023-11-09 at 3 13 10 PM" src="https://github.com/microsoft/pyright/assets/27844407/8fdc262d-35e6-4c52-9671-17716d9e325b">

And not so much when you don't use them:

<img width="920" alt="Screenshot 2023-11-09 at 3 23 15 PM" src="https://github.com/microsoft/pyright/assets/27844407/be668ea4-a849-4830-a2a7-5072c4929b42">

You can see the error persists with this updated example:

```console
$ pyright a.py
  /a.py:29:6 - error: Argument of type "(cls: (LayerConstructor[LayerP@Model, LayerT@Model], **ModelP@build) -> Model[LayerP@Model, LayerT@Model], layer_class: LayerConstructor[LayerP@Model, LayerT@Model]) -> ((**ModelP@build) -> Model[LayerP@Model, LayerT@Model])" cannot be assigned to parameter "__f" of type "(type[_T@classmethod], **_P@classmethod) -> _R_co@classmethod" in function "__init__"
    Type "(cls: (LayerConstructor[LayerP@Model, LayerT@Model], **ModelP@build) -> Model[LayerP@Model, LayerT@Model], layer_class: LayerConstructor[LayerP@Model, LayerT@Model]) -> ((**ModelP@build) -> Model[LayerP@Model, LayerT@Model])" cannot be assigned to type "(type[_T@classmethod], **_P@classmethod) -> _R_co@classmethod"
      Parameter 1: type "type[_T@classmethod]" cannot be assigned to type "(LayerConstructor[LayerP@Model, LayerT@Model], **ModelP@build) -> Model[LayerP@Model, LayerT@Model]"
        Type "type[_T@classmethod]" cannot be assigned to type "(LayerConstructor[LayerP@Model, LayerT@Model], **ModelP@build) -> Model[LayerP@Model, LayerT@Model]"
          Function return type "object*" is incompatible with type "Model[LayerP@Model, LayerT@Model]"
            "object*" is incompatible with "Model[LayerP@Model, LayerT@Model]" (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations 
```

**Comment by erictraut** [comment]
Thanks for the additional details. Unfortunately, I think you're going to need to find another approach. This isn't correct from a type perspective. Apologies that the previous bug in pyright led you to adopt this solution.

As I mentioned, mypy also generates errors for this code, but it reports them in a different location because of how it deals with the issue.

**Comment by ringohoffman** [comment]
@erictraut 

> Previously, the reported error was `Type of parameter "cls" must be a supertype of its class "Type[A]"`. This is a different issue.

Was the intention of https://github.com/microsoft/pyright/commit/bfcf41c227735f7a4b67591f8054e16066a5cad0 not to support the binding of `cls` in `classmethod`s to `Callable` using `Paramspec`? Even this simple case raises an error now, which was previously supported:

```python
from typing import Callable, ParamSpec, TypeVar

P = ParamSpec("P")
T = TypeVar("T", bound="A")


class A:
    @classmethod
    def build(cls: Callable[P, T]) -> Callable[P, T]:
        return cls
```

```console
$ pyright a.py
  a.py:8:6 - error: Argument of type "(cls: (**P@build) -> T@build) -> ((**P@build) -> T@build)" cannot be assigned to parameter "__f" of type "(type[_T@classmethod], **_P@classmethod) -> _R_co@classmethod" in function "__init__"
    Type "(cls: (**P@build) -> T@build) -> ((**P@build) -> T@build)" cannot be assigned to type "(type[_T@classmethod], **_P@classmethod) -> _R_co@classmethod"
      Parameter 1: type "type[_T@classmethod]" cannot be assigned to type "(**P@build) -> T@build"
        Type "type[_T@classmethod]" cannot be assigned to type "(**P@build) -> T@build"
          Function return type "object*" is incompatible with type "T@build"
            Type "object*" cannot be assigned to type "A" (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations 
```

**Comment by erictraut** [comment]
Apologies for the slow reply. I got sidetracked and forgot about this thread until now.

Here's how to think about this. The constructor for the `classmethod` class is defined as follows:

```python
class classmethod(Generic[_T, _P, _R_co]):
    def __init__(self, __f: Callable[Concatenate[type[_T], _P], _R_co]) -> None: ...
```

In your simplified example above, you're attempting to pass the method `build` to the `classmethod` constructor. The type of `build` is `(cls: Callable[P, T]) -> Callable[P, T]`. For the decorator call to succeed, `build` must be type compatible with (that is, assignable to) `Callable[Concatenate[type[_T], _P], _R_co]`. Callable parameters are contravariant, which effectively means the assignment direction is reversed. That means `type[_T]` must be assignable to `Callable[P, T]`. Since `_T` is not specialized, it is treated as its upper bound in this case, which is `object`. That means `type[object]` must be assignable to `Callable[P, T]`. This means `object` must be assignable to `T`, but `T` has an upper bound of `A`, so this assignment is not allowed.

If you remove the upper bound from `T`, your simplified example will type check without error:

```python
P = ParamSpec("P")
T = TypeVar("T")

class A:
    @classmethod
    def build(cls: Callable[P, T]) -> Callable[P, T]:
        return cls
```
