### ISSUE TITLE
int vs float inconsistent behavior  

### ISSUE THREAD

**Issue by danielpopescu** [microsoft/pyright#6431]
Code:

p = [1,2,3]
n = 1

def foo(lst: List[float]) -> List[float]:
    return lst

def foo1(num: float) -> float:
    return num

foo(p)
foo1(n)

call to foo reports this:

Pyright [reportGeneralTypeIssues]: Argument of type "list[int]" cannot be assigned to parameter "lst" of type "List[float]" in function "foo"

call foo1 has no issues....

I believe the latter should be the correct behavior (int be promoted to float where possible)

**Comment by erictraut** [comment]
When posting issues, please surround your code in triple backticks so it is formatted correctly.

Here's your code:

```python
p = [1, 2, 3]
n = 1

def foo(lst: list[float]) -> list[float]:
    return lst

def foo1(num: float) -> float:
    return num

foo(p)
foo1(n)
```

Pyright is working correctly here. This isn't a bug.

The variables `p` and `n` have no type annotation, so their types are inferred. The inferred type of `p` is `list[int]`. Since lists are mutable, the type parameter for a list is invariant. That means the type argument must match exactly. A `list[int]` is not type compatible with a `list[float]`.

For more details, refer to the [pyright documentation](https://microsoft.github.io/pyright/#/type-concepts).
