### ISSUE TITLE
Mark code unreachable after calling magic method hinted with NoReturn

### ISSUE THREAD

**Issue by ringohoffman** [microsoft/pyright#6432]
<img width="347" alt="Screenshot 2023-11-13 at 1 10 55 AM" src="https://github.com/microsoft/pylance-release/assets/27844407/1af76e3e-dcc6-4501-9248-0ee85c78fe9a">

It seems like Pylance doesn't mark code as unreachable for magic methods marked with `NoReturn`. I don't think that magic methods should different in this regard.

Can this be addressed?

```python
from typing import NoReturn

class A:
    def f(self) -> NoReturn:
        raise Exception('error')

    def __getitem__(self, index) -> NoReturn:
        raise Exception('error')

a = A()
a[1]
print("hello")  # nothing
a.f()
print("world")  # Pylance: code is unreachable

```

**Comment by erictraut** [comment]
Supporting this for magic methods is theoretically possible, but it would be prohibitively expensive. "NoReturn" calls affect reachability of the code flow graph, so they need to be evaluated during code flow traversal. This puts them on the hot path in the type evaluator. Supporting this feature for explicit calls is already very expensive, and I've incorporated a bunch of optimizations to make it feasible. These same optimizations cannot be applied for implicit (magic method) calls. Because of this, it's unlikely we'd ever implement the feature you're proposing here. It wouldn't be a good tradeoff for pyright or pylance users.
