### ISSUE TITLE
bound methods of a TypedDict don't retain type information

### ISSUE THREAD

**Issue by mikeshardmind** [microsoft/pyright#6490]
**Describe the bug**
A clear and concise description of the behavior you are seeing and the expected behavior along with steps to reproduce it.

**Code or Screenshots**
```py
from typing import TypedDict, reveal_type


class QuickExample(TypedDict):
    key1: int
    key2: str


ex = QuickExample(key1=1, key2="this")

reveal_type(ex)
reveal_type(ex.__getitem__("key1"))
reveal_type(ex["key1"])
reveal_type(ex.__getitem__)
```

and the corresponding informational messages:

```
Type of "ex" is "QuickExample"
Type of "ex.__getitem__("key1")" is "object"
Type of "ex["key1"]" is "int"
Type of "ex.__getitem__" is "(__key: str, /) -> object"
```

**VS Code extension or command-line**

Initially pylance, also confirmed on the [playground](https://pyright-play.net/?pythonVersion=3.12&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgCYAiSAxjADRQjEBuxAhgDYD68CxAUAKrtWAZxFQAigFdqAawCiAD1bZ2xABRFeFajACUALj5QTUWcTgBGA5hQxjp83ABMNkTBAC%2BxRVAC8kjJUCsqqGk6Wfpb0Ts5%2BAEQwABZIIvF6AowsHNwk6j4ZWWxcPBo%2BAHScnGjEMEgwxBBV6vER6YXMxbm8%2BYoA2q0WlvEAuh3ZJXkVVTV1DU2cGUA)

**Comment by erictraut** [comment]
This is the intended behavior, not a bug.

The `_TypedDict` type in `typing.pyi` defines the class as deriving from `Mapping[str, object]`, and the `__getitem__` method comes from the `Mapping` class. Neither pyright nor mypy synthesize overrides for the TypedDict `__getitem__` method. FWIW, mypy is the reference implementation for [PEP 589](https://peps.python.org/pep-0589/), which introduced TypedDicts.

Both pyright and mypy handle special-casing for TypedDict indexing at a higher level than `__getitem__`. In the case of pyright, this is especially important because pyright also supports narrowing of TypedDict keys based on existence checks.

```python
class QuickExample(TypedDict, total=False):
    key1: int
    key2: str

def func(x: QuickExample):
    print(x["key1"])  # Error: "key1" is not a required key

    if "key1" in x:
        print(x["key1"])  # No type error
```

This is done by internally tracking which keys in the TypedDict have been verified — and are therefore guaranteed to exist. This analysis wouldn't be possible if the type checker synthesized static `__getitem__` methods.

**Comment by mikeshardmind** [comment]
That's unfortunate, as it breaks reasonable assumptions about function composition. I'll just add this to the growing list of "things to bring up with the typing council" since you've placed this as due to the definition coming from Mapping
