### ISSUE TITLE
Type comments from PEP 484

### ISSUE THREAD

**Issue by dsuch** [microsoft/pyright#6526]
Hello,

reading PEP 484, I noticed a [section](https://peps.python.org/pep-0484/#type-comments) with an example reproduced here:

```python
with frobnicate() as foo:  # type: int
    # Here foo is an int
    ...

for x, y in points:  # type: float, float
    # Here x and y are floats
    ...
```

I am interested in providing type hints in this way, specifically in for loops and with statements.

However, I am not getting any type completion or warnings in my VS Code instance, whose Python plugin product from Microsoft, as I understand it, uses pyright.

Before I spend time on collecting all the details, or checking if this can be reproduced with other versions of your products, I have a quick question - is that syntax supported?

I am specifically not interested in declaring these types upfront, before loops or with blocks begin. Rather, I really prefer to provide hints as comments, exactly as in the PEP example.

Thank you.

**Comment by erictraut** [comment]
Type hints were originally added because the Python syntax didn't provide ways to annotate variables. The Python syntax (as of 3.6) was subsequently improved to support this. Since then, type comments have effectively been deprecated. They are supported in a limited manner by pyright only for libraries that were written prior to Python 3.6 and still need to support older versions of Python. We have no plans to expand the support for type comments. See [this documentation](https://microsoft.github.io/pyright/#/mypy-comparison?id=support-for-type-comments) for more details. 

It's likely that type comments will be officially deprecated in the near future. At that time, type checkers (including pyright) will formally make all type comments illegal by default. In other words, `reportTypeCommentUsage` will enabled by default.

The recommended way to declare types for the variables in your example above is the following:

```python
foo: int
with frobnicate() as foo:
    ...

x: float
y: float
for x, y in points:
    ...
```

**Comment by dsuch** [comment]
I see, thank you for the explanation.

However, I am not sure what you mean by "have been" or  "will be" deprecated. Are you saying that a part of the syntax of the language is going to be deprecated or has been already?

Is there any python-dev discussion behind it or a PEP that I can check? Or is it your decision as the architect of this product, hence "effectively"?

**Comment by hmc-cs-mdrissi** [comment]
https://mail.python.org/archives/list/typing-sig@python.org/thread/66JDHQ2I3U3CPUIYA43W7SPEJLLPUETG/#ZQL7HA3DKE3TRTLJSIQEIL4L5HD2DG3S is where the deprecation was discussed. There's no PEP associated to this and it's likely new typing council will instead cover this. There is relevant issue for it [here](https://github.com/JelleZijlstra/typing-spec/issues/1).

**Comment by dsuch** [comment]
Thank you @hmc-cs-mdrissi, I will follow up in the other ticket.

**Comment by erictraut** [comment]
> Are you saying that a part of the syntax of the language is going to be deprecated or has been already?

Type comments were never part of the Python syntax. They were introduced as a short-term workaround until the proper syntax was added. This was done many years ago in Python 3.6. If you want to use the type system, you should use the modern syntax. As I said, we have no plans to make further investments in this facility in pyright.
