### ISSUE TITLE
Creating a bokeh.figure the type is revealed as `Model` instead of `figure`.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pyright#6583]
Repro steps:

1. Install bokeh (I did it following the directions here: https://github.com/bokeh/tutorial)
2. Create a bokeh figure

```python
from bokeh.plotting import figure, show

d = figure()

reveal_type(d)
```

Expected result: 
Type of `d` is `figure`

Actual result:
Type of `d` is `Model`. `Model` is about 4 layers deep in the class hierarchy for `figure`.

This means calling functions on `figure` don't get completions and such.

**Comment by rchiodo** [comment]
This is probably a Pyright issue. Transferring.

**Comment by erictraut** [comment]
Pyright is working correctly here. This is a bug in the `bokeh` library.

The problem is in the `Model` class definition in the `bokeh.model.model` module. The `Model.__new__` method has an explicit return type parameter of `Model`. Pyright is honoring this type annotation. In all likelihood, this is not what the library author intended. The return type should be `Self`. Alternatively, the return type could be removed entirely, and pyright would correctly infer the return type.

This isn't an issue for mypy users because mypy notoriously ignores the return type of `__new__`. There are numerous bugs filed about this issue, and it will likely be fixed at some point. When it is, this will be an issue for mypy users as well.

Please report this to the `bokeh` library maintainers so they are aware of the problem.

**Comment by rchiodo** [comment]
I submitted a PR to bokeh:
https://github.com/bokeh/bokeh/pull/13564

**Comment by rchiodo** [comment]
Okay I'll try that instead :)
