### ISSUE TITLE
add an "all" option for `typeCheckingMode`

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pyright#6617]
If you have a question about a behavior that you’re seeing in pyright, consider posting to the [Pyright discussion forum](https://github.com/microsoft/pyright/discussions).

**Is your feature request related to a problem? Please describe.**
the "strict" `typeCheckingMode` option does not enable every rule. personally, i like to have all rules enabled in type checkers/linters. that way i can just disable rules i don't like as i encouner them.

**Describe the solution you’d like**
an "all" option for `typeCheckingMode`, or maybe it can be called "extra strict" or something

**Comment by erictraut** [comment]
This request has been discussed and rejected in the past.

The problem is that many of the diagnostic rules that are not included in the "strict" subset are not applicable to many code bases. They require specific coding styles, and they produce false positives if you don't adopt those coding styles. It's unlikely that your code base and coding style is compatible with all of these options.

If you value specific diagnostic rules, you're welcome to enable them in your project.
