### ISSUE TITLE
Support CPython extensions (e.g. Boost::Python) on linux

### ISSUE THREAD

**Issue by colinRawlings** [microsoft/pyright#667]
**Is your feature request related to a problem? Please describe.**
Our C++ code base has a relatively complete python interface constructed using `boost::python`.  On both windows and linux the in-built vs code intellisense works correctly (i.e. suggests symbols defined in the extension).  On windows pyright provides excellent static analysis while on linux it lists the modules as MissingImports.  

These go away upon renaming `libMyModule.so` to `MyModule.pyd` so I am fairly sure it is not a configuration issue on my side but rather a choice of pyright to not consider .so files (sorry in advance if this is in fact the case).

Pyright has become a central component of my workflow and as such I find myself struggling when developing on linux.

**Describe the solution you'd like**
Pyright is extended to handle CPython extensions on linux similarly to how it handles them on windows.

**Comment by erictraut** [comment]
Thanks for the suggestion.

Adding support for ".so" is a little more complex than ".pyd" because of [PEP 3149](https://www.python.org/dev/peps/pep-3149/). 

Good news though... I implemented support for ".so" (and ".dylib") native binaries. Of course, pyright won't be able to extract any type information from them, but it can confirm that there is a native library that satisfies the import.

This support will be in the next version of pyright.

**Comment by erictraut** [comment]
This is now addressed in Pyright 1.1.37, which I just published.
