### ISSUE TITLE
Throwaway variable `_` is not fully ignored and can trigger `reportUnknownVariableType`

### ISSUE THREAD

**Issue by aholmes** [microsoft/pyright#6756]
When using the "throwaway" variable (`_`) to store the return value of a function call, if the return type is partially `Unknown`, pyright fails with

> error: Type of "_" is unknown (reportUnknownVariableType)

An example of the affected code and repository is found [here](https://github.com/uclahs-cds/BL_Python/blob/5181ccdf587e5fd52d3c87efa4e150db7f169ad9/src/web/test/unit/middleware/test_middleware.py#L77). This project uses this [pyproject.toml file](https://github.com/uclahs-cds/BL_Python/blob/1770340a8cd144246556359304a904dd4e5b2822/pyproject.toml#L100-L147). The failure can be seen in this [GitHub Actions run](https://github.com/uclahs-cds/BL_Python/actions/runs/7228858876/job/19698932073?pr=33#step:5:174).

I would expect that `_` is effectively ignored when it's used. Indeed, using `_` and not referencing it does not trigger `reportUnusedVariable`, and it prevents `reportUnusedCallResult`.

**Comment by erictraut** [comment]
Pyright is working as intended here, so I don't consider this a bug.

As you point out, pyright does special-case `_` and exempt it from a number of checks. I'm willing to consider adding another exemption, but before doing this, I want to make sure we're being consistent and principled.

The current exemptions for `_` are intended to handle cases where an identifier _must_ be supplied somewhere but it is intended not to be used.

In your example, you're using `_` where an identifier is _not required_. You could simply delete the `_ =`, and your program would work fine, right? If so, then I'm not convinced that pyright should exempt `_` for this check.

**Comment by aholmes** [comment]
Good points. Thanks for the thoughts.

In my case, `_` is suggested per our development standards and pyright configuration. The absence triggers the `reportUnusedCallResult` that would otherwise require an ignore comment. For us, the `_` indicates that not storing or using the result is explicit and intentional. That said, you are correct that removing it makes no functional difference here, but it does introduce the pyright notice into our type checks.

Ultimately I would like not to have to use an ignore comment (I try to avoid them whenever possible), and I don't want to circumvent our policy/configuration to manage this particular case. Other than fixing the `Unknown` type, do you have some suggestions for how to handle this case if another `_` exception is not added?

**Comment by erictraut** [comment]
Thanks for the additional details. I think the only reason you're hitting this is because of your use of `reportUnusedCallResult`. This diagnostic check is a beyond-strict-mode diagnostic check (i.e. it's not even enabled in strict mode). It's rarely used because of its high false positive rate. I can kind of understand why some people might want to enable it in production code, but it sounds like you're using it in your test code as well.

The `reportUnknownVariableType` is a strict-mode diagnostic check, and I recommend using it only if your code base and the libraries it consumes are fully typed. It sounds like your code base is not?

So my suggestion is to try to fix the `Unknown`, perhaps by writing a custom type stub if the source of the `Unknown` is from an untyped dependency. Is that feasible in your case?

If that's not feasible, perhaps you'd find it acceptable to disable `reportUnusedCallResult` for test code modules — or at least for specific test code modules. You could use `# pyright: reportUnusedCallResult=false` at the top of the file. This would avoid a bunch of `# type: ignore` comments, which I agree are good to avoid.

**Comment by erictraut** [comment]
After thinking about this more, I'm going to reject the feature request for now. I don't think the justification for a special-case exemption is strong enough in this case. 

I'm willing to revisit this decision in the future based on feedback from other pyright users.

**Comment by aholmes** [comment]
Fair enough. Can I ask though, looking at it from the other side, what is the purpose of _not_ treating `_` specially? Is it purely the principle of not introducing more exceptions for edge cases?
