### ISSUE TITLE
pyright incompatible with constructing nested exceptiongroups with exceptiongroup backport

### ISSUE THREAD

**Issue by jakkdl** [microsoft/pyright#6795]
**Describe the bug**
I'm not 100% sure if this is an error in the signature for the backport, or in pyright. But strict mypy handles it without problem both on <3.11 and >=3.11. The code works without problem if pyright is targeting version==3.11.

I encountered the error in the following PR: https://github.com/python-trio/trio/pull/2898
https://github.com/python-trio/trio/actions/runs/7300704573/job/19895902558?pr=2898#step:5:1647

**Code or Screenshots**
`foo.py`
```python
import sys
if sys.version_info < (3, 11):
    from exceptiongroup import ExceptionGroup

exc: ExceptionGroup[ExceptionGroup[ValueError]] = ExceptionGroup(
    "", (ExceptionGroup("", (ValueError(),)),)
)
```
`pyproject.toml`
```
[tool.pyright]
pythonVersion = "3.10"
typeCheckingMode = "strict"
```

```
$ pyright foo.py                            
/tmp/pyright_exceptiongroup/foo.py
  /tmp/pyright_exceptiongroup/foo.py:6:9 - error: Argument type is partially unknown
    Argument corresponds to parameter "args" in function "__init__"
    Argument type is "tuple[ExceptionGroup[Unknown]]" (reportUnknownArgumentType)
1 error, 0 warnings, 0 informations 
```

```
$ pip list
Package           Version
----------------- -------
exceptiongroup    1.2.0
pyright           1.1.342
[...]
```

The signature in the backport can be seen at https://github.com/agronholm/exceptiongroup/blob/main/src/exceptiongroup/_exceptions.py and as far as I can tell it doesn't differ from the one in typeshed https://github.com/python/typeshed/blob/main/stdlib/builtins.pyi#L2130

**Comment by erictraut** [comment]
This is a due to a bug in the `exceptiongroups` library. The `exceptiongroup/_exceptions.py` module contains the following import statement:

```python
if TYPE_CHECKING:
    from typing import Self
```

But the `Self` symbol isn't exported from the `typing` module for Python versions older than 3.11. The symbol should be imported from `typing_extensions` instead.

This doesn't affect mypy because mypy does not honor the return type of `__new__`. If and when mypy maintainers implement support for `__new__` return type annotations, this same bug will affect mypy.
