### ISSUE TITLE
Error on `importlib.metadata.entry_points()` when passing `**` arguments.

### ISSUE THREAD

**Issue by mikenerone** [microsoft/pyright#6857]
I'm not sure where the problem is with this one (the annotations don't look like the cause to me, but I could be wrong):

**Describe the bug**
When calling the form `importlib.metadata.entry_points(**filters)`, Pyright outputs this error, even if the keyword arguments therein are correct:
```
Argument of type "str" cannot be assigned to parameter "extras" of type "list[str]" in function "entry_points"
```

**Code**

```python
# No pyright error for this one:
_ = importlib.metadata.entry_points(group="console_scripts")

# But this one produces the error even though it's seemingly equivalent:
filters: dict[str, str] = {"group": "console_scripts"}
_ = importlib.metadata.entry_points(**filters)
```

**VS Code extension or command-line**
Pyright 1.1.343 from the command line. Codebase is on Python 3.12.1.

**Comment by erictraut** [comment]
This behavior is intended, not a bug.

The `entry_points` method accepts multiple keyword arguments. Most of them are typed as `str`, but the `extra` parameter is annotated as `list[str]`. In your second example, you're attempting to call the function with `**filters` where `filters` is of type `dict[str, str]`. That means the `dict` potentially includes a key called `extras` with an incompatible type (a `str` rather than a `list[str]`.

For comparison, mypy produces the same error here.

**Comment by mikenerone** [comment]
Oh, I see, thanks much!

For anyone who may come across this question later, the solution is to annotate the `filters` dict as this type:
```python
class _EntryPointMatchParams(typing.TypedDict, total=False):
    group: str
    name: str
    value: str
    module: str
    attr: str
    extras: list[str]
```
