### ISSUE TITLE
Better document LSP server: no diagnostics because workspace is not initialized

### ISSUE THREAD

**Issue by not-my-profile** [microsoft/pyright#6874]
I am trying to create a Pyright plugin for Pycharm. `pyright/langserver.index.js` gets started succesfully, the client sends the `initialize` request, pyright responds, the client sends the `initialized` request and a `textDocument/didOpen` request but pyright doesn't send any `textDocument/publishDiagnostics` notifications. I debugged this by adding some `this.console.info` log calls to `packages/pyright-internal/src/languageServerBase.ts` (and rebuilding the server with `npm run build:cli:dev`). Apparently the following `await` in `onDidOpenTextDocument` never completes because the workspace isn't initialized yet?

https://github.com/microsoft/pyright/blob/8f02660e2d0b4943877497d5ac9724f8155eb6c4/packages/pyright-internal/src/languageServerBase.ts#L1182

What does an LSP client have to do for the pyright LSP server to initialize a workspace?

<details><summary>initialize request</summary>

```json
{
  "jsonrpc": "2.0",
  "id": "1",
  "method": "initialize",
  "params": {
    "processId": null,
    "rootPath": "/Users/mfischer/PycharmProjects/pyright-test1",
    "rootUri": "file:///Users/mfischer/PycharmProjects/pyright-test1",
    "capabilities": {
      "workspace": {
        "workspaceEdit": {
          "documentChanges": true,
          "failureHandling": "abort"
        },
        "workspaceFolders": true
      },
      "textDocument": {
        "completion": {
          "completionItem": {
            "documentationFormat": [
              "markdown",
              "plaintext"
            ],
            "deprecatedSupport": true,
            "tagSupport": {
              "valueSet": [
                1
              ]
            },
            "insertReplaceSupport": true,
            "labelDetailsSupport": true
          },
          "completionList": {
            "itemDefaults": [
              "commitCharacters",
              "editRange",
              "insertTextFormat",
              "insertTextMode",
              "data"
            ]
          }
        },
        "hover": {
          "contentFormat": [
            "markdown",
            "plaintext"
          ]
        },
        "definition": {
          "linkSupport": true
        },
        "codeAction": {
          "codeActionLiteralSupport": {
            "codeActionKind": {
              "valueSet": [
                "quickfix"
              ]
            }
          },
          "disabledSupport": true
        },
        "publishDiagnostics": {
          "tagSupport": {
            "valueSet": [
              1,
              2
            ]
          },
          "versionSupport": true
        }
      },
      "window": {
        "showMessage": {}
      }
    },
    "workspaceFolders": [
      {
        "uri": "file:///Users/mfischer/PycharmProjects/pyright-test1",
        "name": "pyright-test1"
      }
    ]
  }
}
```
</details>

**Comment by erictraut** [comment]
This is unlikely to be a bug in pyright. Pyright is used as a language server with many LSP plugins in many clients. You may want to look at those implementations (which are open-sourced) to see what you're doing differently. You may also find it useful to look at the sources for [pyright playground](https://github.com/erictraut/pyright-playground/blob/main/server/src/lspClient.ts) which uses the pyright LSP.

If you have questions, feel free to post to the discussion section of this project.

**Comment by not-my-profile** [comment]
Ah yeah thanks ... I was missing that the `workspace/didChangeConfiguration` notification has to be sent. It would be nice if the pyright LSP would report an error to clients via `window/logMessage` if `textDocument/didOpen` is received before `workspace/didChangeConfiguration` telling the client that the `didChangeConfiguration` is expected first.

**Comment by arvidfm** [comment]
I just came across this as well looking into the issues mentioned at https://github.com/InSyncWithFoo/pyright-experimental-plugin. So is it really the expected behaviour that Pyright will not process e.g. any `textDocument/codeAction` requests until a `workspace/didChangeConfiguration` notification has been sent?

Looking at the flow of the code in Pyright, if workspace folders are sent with the `initialize` request, [they will not be initialised](https://github.com/microsoft/pyright/blob/c64f9b3f1f2dbe89af8346dfab2e69a5af1460bb/packages/pyright-internal/src/languageServerBase.ts#L1338-L1340) because Pyright hasn't received an `initialized` notification yet, but then when the `initialized` notification is sent, [Pyright will not initialize the existing workspace folders](https://github.com/microsoft/pyright/blob/c64f9b3f1f2dbe89af8346dfab2e69a5af1460bb/packages/pyright-internal/src/languageServerBase.ts#L780-L784) if the client reports the `workspaceFolders` capability.

So the initially sent workspace folders never get initialised, and the only workaround seems to be to force Pyright to reinitialise all workspace folders with an empty `workspace/didChangeConfiguration` notification, or by removing and readding the workspace folders after initialisation using `workspace/didChangeWorkspaceFolders`.
