### ISSUE TITLE
Overriding functions with new parameters gives error of incompatible method override

### ISSUE THREAD

**Issue by Qazalbash** [microsoft/pyright#6952]
# Description
I have defined a general class for integration as `Integration`. `MonteCarloBoxIntegration` is its derived class. After running `pyright` I am having an error regarding incompatible method override.
## Code
```python
from abc import abstractmethod
from typing import Optional, Union
import numpy as np
from jaxtyping import Array

Numeric = Union[Array, np.ndarray, np.bool_, np.number, int, float]

class Integration:
    def __init__(self, name: Optional[str] = None) -> None:
        self._name = name

    @abstractmethod
    def compute_integral(self, *args, **kwargs) -> Numeric:
        raise NotImplementedError("Function should be implemented in the sub-class.")

class MonteCarloBoxIntegration(Integration):
    def __init__(self, name: Optional[str] = None) -> None:
        super().__init__(name)

    def compute_integral(
        self,
        h: Callable,
        low: Numeric,
        high: Numeric,
        N: int,
        *args,
        key: Optional[Array] = None,
        **kwargs,
    ) -> Numeric: ...
```
## Error
```bash
/media/gradf/Academic/project/jaxampler/jaxampler/_montecarlo/montecarlobox.py
  /media/gradf/Academic/project/jaxampler/jaxampler/_montecarlo/montecarlobox.py:42:9 - error: Method "compute_integral" overrides class "Integration" in an incompatible manner
    Positional parameter count mismatch; base method has 3, but override has 8 (reportIncompatibleMethodOverride)
```

**Comment by erictraut** [comment]
Pyright is working correctly here. The base class method `Integration.compute_integral` accepts any arguments whether they are passed positionally or by keyword. Your subclass defines `compute_integral` in a much more restrictive way. It allows only specific arguments to be passed. This is a violation of the Liskov Substitution Principle (LSP). It's fine for an override to be more permissive (e.g. accept additional optional arguments), but an override cannot be more restrictive.

To see why this is unsafe, consider the following extension to your code sample:

```python
def compute(f: Integration):
    f.compute_integral("bad", "parameter")

compute(MonteCarloBoxIntegration())
```

The `compute` function itself is type safe, but it will crash when calling the `compute_integral` method because the subclass of `Integral` is incorrectly overriding the base class. It's the job of a type checker to warn you about potential bugs like this, so pyright is doing the right thing here.

If you would like to ignore this error, you can disable the `reportIncompatibleMethodOverride` diagnostic check.

**Comment by Qazalbash** [comment]
@erictraut Thank you it is a nice explanation, I will think of a new design.
