### ISSUE TITLE
Since v1.1.346:  Cannot access member "NULL" for type "type[Any]"

### ISSUE THREAD

**Issue by stefanberger** [microsoft/pyright#7007]
**Describe the bug**

Since pyright v1.1.346 we are seeing the following error report in Keylime:

/home/stefanb/keylime/keylime/tpm/ec_crypto_helper.py
  /home/stefanb/keylime/keylime/tpm/ec_crypto_helper.py:56:35 - error: Cannot access member "NULL" for type "type[Any]"
    Member "NULL" is unknown (reportGeneralTypeIssues)

Reproducer:
```
git clone https://github.com/keylime/keylime.git
cd keylime
pyright keylime/tpm
```

I am not sure what the solution to this problem is other than ignoring the line. A reproducer is below.

**Code or Screenshots**

pip3 install cryptography

```python
from cryptography.hazmat.bindings.openssl import binding

b = binding.Binding()
print(b)
print(b.ffi)
print(b.ffi.NULL)  # this is the problematic line
```

**Comment by erictraut** [comment]
I think pyright's behavior is correct in this case. This appears to be a bug in the `cryptography` package. Older versions of pyright didn't correctly detect this bug.

The file `cryptography/hazmat/bindings/_rust/_openssl.pyi` contains the following statement, which is suspect:

```python
ffi = typing.Any
```

This defines a type alias called `ffi` that has a value of `typing.Any`. I'm guessing that the intent was to define a variable called `ffi` that has the type `Any`. The correct way to do that is `ffi: typing.Any`.

The file `cryptography/hazmat/bindings/openssl/binding.py` declares a class named `Binding` that defines a class-scoped variable named `ffi` that is declared as follows:

```python
class Binding:
    ...
    ffi = _openssl.ffi
```

This likewise defines a type alias named `ffi` with a type of `Any`. I'm guessing that the intent was to assign the value of the variable `_openssl.ffi`, but since that symbol was defined as a type alias, pyright doesn't interpret it as a variable assignment.

I'm going to close this issue because I don't think it's a bug in pyright. Please consider reporting the issue to the maintainers of the `cryptography` package.
