### ISSUE TITLE
Unexpected issue: Unable to access member "BluetoothSocket" of type "Bluetooth"

### ISSUE THREAD

**Issue by IVEN-CN** [microsoft/pyright#7079]
**Describe the bug**
in bluetooth model，but in vscode ,it tell me Unable to access member "BluetoothSocket" of type "Bluetooth"

**Code**
class Bluetooth:
    """蓝牙连接类"""
    def __init__(self,address='00:00:00:00:00:00'):
   
        while True:
            try:
                self.serverMACAddress = address                      
                self.port = 1                                          
                self.sock = bluetooth.BluetoothSocket(bluetooth.RFCOMM) 
                self.sock.connect((self.serverMACAddress, self.port))
                break
            except:
                continue
        if self.ifserial:
            while True:
                try:
                    self.ser = serial.Serial(port='/dev/rfcomm0', baudrate=9600)
                    break
                except:
                    continue

**Comment by erictraut** [comment]
Thanks for filing an issue, but I'm unable to help because you haven't provided enough information. The sample you've supplied is not a self-contained minimal code sample. It references symbols that are not defined, and I have no way of knowing where or how these symbols are defined.

Based on the description you've provided, I suspect that you are using a symbol that is defined in a library or a type stub. You should look at how it is defined to diagnose why you're seeing the typing error. It's unlikely that this is a bug in pyright.

If you have questions about pyright, please open a discussion thread.

If you think that you have found a bug in pyright, please open a bug report that follows the instructions in the bug template. We need full repro steps along with a minimal, self-contained code sample and a list of any required libraries and versions.
