### ISSUE TITLE
Feat: define/override constant value from command line

### ISSUE THREAD

**Issue by yanyongyu** [microsoft/pyright#7104]
**Is your feature request related to a problem? Please describe.**

I have a project that uses pyright-action to check the codes. i have defined a const in the pyproject.toml using `defineConstant`. I uses github action's matrix to switch the constant value and check the code in different env. but i cannot find a command line option to override the constant value.

Currently, i'm using `sed` as a workaround to modify the constant value in the pyproject.toml.

**Describe the solution you’d like**

Provide a way to change the constant value dynamicly.

**Comment by erictraut** [comment]
I think this feature is too specialized and esoteric to add, so I'm going to reject this enhancement request. I'm willing to revisit this decision in the future if there's sufficient signal from other pyright users (e.g. in the form of upvotes), but I'm going to close the issue now because I have no plans to implement it.

My recommendation is in line with your current solution — write a script that writes a value to pyproject.toml or to a custom pyrightconfig.json file.

**Comment by yanyongyu** [comment]
Thanks!
