### ISSUE TITLE
Flipped condition does not narrow

### ISSUE THREAD

**Issue by decorator-factory** [microsoft/pyright#7107]
**Describe the bug**
Inside of dunder methods, the `type(other) is not type(self)` guard successfully narrows `other`, but `type(self) is not type(other)` (which is exactly the same) does not. 

**Code**

[Playground link](https://pyright-play.net/?strict=true&code=MYGwhgzhAEBiD28BcAoa7oDcwgK4FNoBeaARhTQwBN8AzaAfQZABcmAKCfEWgGmngsAFvgBOSAQCMAVvmAsAlNAC0APmiTEIVBl3QAlvRYBPAA752gkaKX6YAO0HQT5zt1oKde76PwtcovbQAHKCAJIAtqYg%2BBH49iz4VJQ%2BfgFBXDwAdNh4hAA8AsJiOTgE6ADEAgDWFLo09EwA5mwMbjz8VmIS8DJyiirqmvDaKXqGzmYWmR4GDk4uFl02Xt66vv6BIeFRMXEJSWPraVszpXnQ6svnBEcYVWuPGAB6r2-vz3eVTz8AwmD2RwsaBgYDAfBQaBxCKSMTQABEuQI8OgtHgokm5gRvVk8nhQA)

```python
class Foo:
    value = 1

    def __lt__(self, other: object) -> bool:
        if type(other) is not type(self):
            return NotImplemented
        return self.value < other.value  # ok

    def __gt__(self, other: object) -> bool:
        if type(self) is not type(other):
            return NotImplemented
        return self.value > other.value
        #                   ^^^^^^^^^^^
        #                   Cannot access member "value" for type "object"
```

**Comment by erictraut** [comment]
This isn't a bug. These are different type guard patterns. The first is supported, and the second is not. For a full list of supported type guard patterns, see [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards). 

You will need to flip the condition if you want pyright to narrow the type in this case.

We occasionally add support for new type guard patterns, but each new one requires complex new logic and potentially slows down overall analysis because they tend to create false dependencies between expressions within the code flow analysis pass. So we add support for new patterns only when there's a strong signal from pyright users that it's a common use case. 

I'll note that mypy also does not support the second type guard pattern in your example.
