### ISSUE TITLE
`sympy` analysis unusably slow?

### ISSUE THREAD

**Issue by gekoke** [microsoft/pyright#7130]
I have observed the behavior described in the title in the following environments:

- In Emacs, on NixOS, using the [lsp-pyright](https://github.com/emacs-lsp/lsp-pyright) client.
- In VSCode, on NixOS, using the [Pyright extension](https://marketplace.visualstudio.com/items?itemName=ms-pyright.pyright)
- In VSCode, on NixOS, using the [Pylance extension](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance)
- In VSCode, on Windows 10,  using the [Pylance extension](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance)

This makes me suspect that this issue is not related to my environment. Still, I can't help but shake the feeling that I'm just doing something wrong if this issue hasn't gotten any attention, given the relative popularity of the software involved.

I suppose this is more of a help request. I understand that this may entirely be an upstream issue related to typing, and that there is nothing that Pyright can do. However, is there any workaround or mitigation in the meanwhile? Type analysis is not a necessity, but method and class name completion - which are essential - get deferred due to the long server response times.

I have tried setting `"python.analysis.useLibraryCodeForTypes": false` when using Pylance in VSCode, to no avail.

Thanks!

**Comment by erictraut** [comment]
Sympy is an untyped library that contains highly complex functions (many variables and complex flow graphs), so inferring function return types is costly. IIRC, sympy also relies on other complex typed libraries, so pyright needs to infer those types as well.

Setting `python.analysis.useLibraryCodeForTypes` to `false` should tell pyright not to attempt inferring return types, so I'm surprised that's not working for you.

The best solution is to find or create type stubs for the portions of sympy that you rely upon. This would involve a lot of work.

If you're able to find a specific repro case that's especially egregious in terms of analysis time, I'd be willing to look at it. Please file a separate issue if you'd like to do that. I'm going to close this bug report because there's no repro steps in it, so there's not much I can do with it.
