### ISSUE TITLE
`TypedDict` does not overload types for `.values()`

### ISSUE THREAD

**Issue by SebbyLaw** [microsoft/pyright#7210]
**Describe the bug**

Same as #3129 

**Code or Screenshots**

```python
from typing import TypedDict

class Counts(TypedDict):
    foo: int
    bar: int
    baz: int
    # many more integer fields...


c = Counts(foo=1, bar=2, baz=3)
x = sum(c.values())  # type error
```

I could do something like this:

```python
from typing import cast

...

x = sum(cast(dict[str, int], c).values())
```
But I'd rather not. Is there a reason we can't type `.values()` as a union of the types of the TypedDict?

**VS Code extension or command-line**
pyright 1.1.349
pyright 1.1.350

**Comment by erictraut** [comment]
This is by design, not a bug. A `TypedDict` is a structural form. It's not safe to assume that there are not additional key/value pairs within a value that conforms with a `TypedDict`.

```python
class CountsPlusOther(TypedDict):
    foo: int
    bar: int
    baz: int
    other: str

# There is no type violation here.
o: Counts = CountsPlusOther(foo=1, bar=2, baz=3, other="")
```

There is a draft [PEP 728](https://github.com/PIG208/peps/blob/pep-728/peps/pep-0728.rst) that introduces the ability to specify an `__extra__` field in a TypedDict definition. If this PEP is accepted, it would make it possible for a type checker to safely determine the return type of `values()`.
