### ISSUE TITLE
 Incorrect Type Hinting for dict.setdefault Method

### ISSUE THREAD

**Issue by vardareg** [microsoft/pyright#7235]
**Describe the bug**
Pylance doesn't hint correctly dict.setdefault method

**Code or Screenshots**
For this code:
```some_dict = {}
some_dict.setdefault('key',0)
```
it generates
```
(method) def setdefault(
    __key: Unknown,
    __default: Unknown,
    /
) -> Unknown
```
![image](https://github.com/microsoft/pyright/assets/101968327/e97f4ac5-6e8b-4d5b-8b23-5cd5d8b0ea57)

Vscode Pylance 2024.2.1

**Comment by erictraut** [comment]
Pyright is working correctly here. 

First, pyright doesn't "generate" the signature for the `setdefault` method. It evaluates the type of the method based on the type information provided to it. This information comes from the `builtins.pyi` type stub maintained by the typeshed project. 

The signature for `setdefault` looks correct to me. What do you think looks incorrect? Are you concerned about the `Unknown` types? Those appear because the specialized version of the `dict` is unknown in your particular usage. Its type cannot be inferred at the time of its construction because the expression `{}` doesn't provide information about the dictionary's keys and values. If you want this to have a more specific type, you would need to provide a type declaration for the `some_dict` variable, like this:

```python
some_dict: dict[str, str] = {}
```

To learn more about type declarations and type inference, check out pyright's documentation [here](https://microsoft.github.io/pyright/#/type-concepts).
