### ISSUE TITLE
TypeVar compatibility with Union

### ISSUE THREAD

**Issue by yellowjello** [microsoft/pyright#744]
**Describe the bug**
Not sure if it's intentional or not, but TypeVars don't seem to be compatible with Unions.

**To Reproduce**
Consider the following toy example:
```
from typing import TypeVar, Union

T = TypeVar("T", int, str) # T is either int or str
def func_a(p: T) -> T:
    # Imagine I do some processing that requires the
    # input to be int or str

    return p

def func_b(q: Union[int, str]) -> int:
    r = func_a(q) # Error on this line

    # Imagine I do some processing on r to come up
    # with the return value
    return 1
```
Pyright gives an error on the indicated line saying
```
Argument of type "int | str" cannot be assigned to parameter "p" in function "func_a" of type "TypeVar["T", int, str]"
  Type "int | str" is not compatible with constrained type "T"
```

**Expected behavior**
I would expect there to be no error since `Union[int, str]` should be compatible with `TypeVar("T", int, str)`, unless I misunderstood something about how TypeVars work.

Of course, if I use another TypeVar in the parameter of `func_b`, it works. But there are times in which I don't want to use another TypeVar (sometimes for readability reasons for example).

**VS Code extension or command-line**
VS Code extension 1.1.43

**Comment by erictraut** [comment]
This is correct behavior. The notation `TypeVar("T", int, str)` means that the type var must be constrained to either an `int` or a `str`. It can't be a union of the two types. If you want to constrain it to a union, you can specify `TypeVar("T", Union[int, str])`.

I confirmed that mypy also generates the same error in this case.

**Comment by nh2** [comment]
> you can specify `TypeVar("T", Union[int, str])`.

@erictraut That is invalid today:

```
error: TypeVar must have at least two constrained types
```

Does it need `bound=` here?

---

In any case, what is the correct way to call `func_a()` from `func_b()`? Is it

```python
    if isinstance(q, int):
      r = func_a(q)
    elif isinstance(q, str):
      r = func_a(q)
```

?

If yes, this is extremely verbose, especially if the invocation of `func_a()` is long, and many calls need to be made.

Would it not make sense to allow a direct call to `func_a()`, given that either value in the `Union` is accepted by `func_b()`?

My understanding is that `T = TypeVar("T", bound=Union[int, str])` is not a solution to this, because it is more permissive: It allows `func_b()` to accept argument `p: Union[int, str]`, even when the user wishes to express that it accept only `int` or `str`.

**Comment by erictraut** [comment]
Yes, I had a typo in my response above. It should say `T = TypeVar("T", bound=int | str)`. Here's an updated code sample that works without any type errors.

```python
from typing import TypeVar

T = TypeVar("T", bound=int | str)

def func_a(p: T) -> T:
    return p

def func_b(q: int | str) -> None:
    r = func_a(q)
```
