### ISSUE TITLE
Type inference on `@wraps` not working properly

### ISSUE THREAD

**Issue by adampauls** [microsoft/pyright#7461]
**Describe the bug**
A member function annotated with `@wraps` is not treated as closing over `self`. 

**Code or Screenshots**

```python
from collections.abc import Callable
from functools import wraps
from typing import Any, TypeVar


class Super:
    def foo(self, x: int) -> int:
        return x


class Foo:
    @wraps(Super.foo) # no error if this line removed
    def wraps_foo(self, x: int) -> int:
        print(f"here: {self} || {x}")
        return 5


Function = TypeVar("Function", bound=Callable[..., Any])


def takes_method(a: str) -> Callable[[Function], Function]:
    return lambda x: x


takes_method("unused")(Foo().wraps_foo)(5)  #  error: Argument missing for parameter "x" (reportCallIssue)
```

If I run this code (with and without `@wraps`), it does the same thing, so I believe pyright is in error that `x` is missing here. I don't think the typeshed stubs for `@wraps` do anything wrong but I'm not sure. 

Note that this is an attempt to minimize an issue that only appeared after 1.1.351. I do not know why my reproduction triggered an error on 1.1.351, but the real code we have internally does not. The real code we are using is calling [this function](https://github.com/huggingface/transformers/blob/b382a09e28c7e59129246ccdf4b00f2cac4547a4/src/transformers/modeling_utils.py#L2485) that uses `@wraps`. 

**VS Code extension or command-line**
Command line. Present on at least 1.1.351-3. Python 3.11.

**Comment by erictraut** [comment]
Pyright has no special knowledge of the `wraps` decorator. It's simply applying the type information provided in `functools.pyi`. It looks to me like it's applying the rules correctly. If you see something that I'm missing, let me know.

You mentioned that you're working around an issue that appeared in 1.1.351. Do you suspect that there was a regression in pyright, or did a bug fix or intended behavioral change uncover a problem in your code (e.g. a bad assumption about how the type system works)?

**Comment by adampauls** [comment]
I believe that pyright is in error here, in both the real-code case and in the case I mentioned here. If I had to guess what's going on in the real code, it's that pyright got better in some way revealed the error I am now seeing. 

Can you explain what you mean about pyright applying the rules correctly? Since the code executes correctly (with the value for `x` passed through as `5`), either pyright is incorrect, some function signature is incorrect, or Python's type system isn't powerful enough to express why the code is correct. 

Do you understand which is happening here? My understanding is that `Foo().wraps_foo` returns a function `int -> int`, so passing a single `5` should pass a value to `x`. The addition of `@wraps` should note change that (since `Super.foo` has the same signature as `Foo.foo`).

**Comment by erictraut** [comment]
> Can you explain what you mean about pyright applying the rules correctly?

As I said above, pyright has no special knowledge of the `wraps` function.  This function is defined as follows in `functools.pyi`:

```python
    def wraps(
        wrapped: Callable[_PWrapped, _RWrapped],
        assigned: Sequence[str] = ...,
        updated: Sequence[str] = ...,
    ) -> _Wrapper[_PWrapped, _RWrapped]: ...
```

For the `wrapped` parameter, you're passing `Super.foo ` which is type `foo(self: Super, x: int) -> int`. That means `_PWrapped` captures the signature `(self: Super, x: int)` and `RWrapped` captures the type `int`. The return type is therefore typed as `_Wrapper[(self: Super, x: int), int]`.

`_Wrapper` is defined as follows:

```python
class _Wrapper(Generic[_PWrapped, _RWrapped]):
    def __call__(self, f: Callable[_PWrapper, _RWrapper]) -> _Wrapped[_PWrapped, _RWrapped, _PWrapper, _RWrapper]: ...
```

And `_Wrapped` is defined as follows:

```python
class _Wrapped(Generic[_PWrapped, _RWrapped, _PWrapper, _RWrapper]):
    __wrapped__: Callable[_PWrapped, _RWrapped]
    def __call__(self, *args: _PWrapper.args, **kwargs: _PWrapper.kwargs) -> _RWrapper: ...
```

So the type of the expression `Foo().wraps_foo` is `_Wrapped[(self: Super, x: int), int, (self: Foo, x: int), int]`, and the `__call__` method on this object has the specialized and bound type `(self: Super, x: int) -> int`.

The problem here is that the ParamSpec is capturing an instance method, but the fact that it's an instance method (and therefore should be bound to an object, which provides the `self` argument) is lost in translation. Neither PEP 612 (which introduced ParamSpec) nor the type specification provides guidance for whether (or how) type checkers should preserve such information when callable signatures are transformed through a ParamSpec, especially when that ParamSpec is then used to specialize a class. Pyright incorporates some heuristics for when to do so, but it's not retaining the information in this case. In any case, I think pyright is conforming to the typing spec here.

This is one (of many) areas where we should improve the typing spec to reduce ambiguity and improve type checker consistency.

I'll investigate further whether I can retain this information without breaking other common ParamSpec use cases.

**Comment by adampauls** [comment]
Perhaps stating the obvious, but if I change the code so that it does typecheck:
```python
inst = Foo()
takes_method("unused")(inst.wraps_foo)(inst, 5)
```

it will crash.

I don't quite follow why `Foo().wraps_foo` (an instance method that already closes over `self) should have type `_Wrapped[(self: Super, x: int), int, (self: Foo, x: int), int]` -- that's they type of `Foo.wraps_foo` (the class method) right? I understand that the type checker might not be able to "see through" the type signature to know how to get the correct signature for the instance method, but in this case, I believe it's passing through a signature that is wrong in all cases (since `self` has already been closed over)? That is to say, if you cannot figure out how to special-case pyright to figure out how to remove the self parameter when going from class method to instance method, I wonder if would be better to fall back to `Any` or something so that the correct program is not ruled out.

**Comment by Azureblade3808** [comment]
> ..., I believe it's passing through a signature that is wrong in all cases (since `self` has already been closed over)?

It's not about type of `self` being wrong. In fact, type of `self` being `Super` instead of `Foo` is OK here. The main problem is that, the result of `wraps(...)(x)` is `x` itself and a _function_ in your case, but it can only be declared as a _callable_ object with current type system because of added attributes (i.e. `__wrapped__`) on the original object.

Note that a _callable_ object will not get bound on instances, unless it is a _function_. For example ---

```python
def f0(self, /) -> None: pass

class F1:
    def __call__(self, self_, /) -> None: pass

f1 = F1()

class C:
    f0 = f0
    f1 = f1

c = C()
C.f0(c)  # OK
C.f1(c)  # OK
c.f0()  # OK
c.f1()  # Boom
```

If you don't care about those added attributes, you may use a custom `wraps` with preferred signature. For example --

```python
import functools
from typing import Any, Callable, TypeVar

_Callable_t = TypeVar("_Callable_t")

def wraps(wrapped: Callable[..., Any]) -> Callable[[_Callable_t], _Callable_t]:
    return functools.wraps(wrapped)  # type: ignore
```

And then your snippet will become ---

```python
import functools
from typing import Any, Callable, TypeVar

_Callable_t = TypeVar("_Callable_t")

def wraps(wrapped: Callable[..., Any]) -> Callable[[_Callable_t], _Callable_t]:
    return functools.wraps(wrapped)  # type: ignore

class Super:
    def foo(self, x: int) -> int:
        return x

class Foo:
    @wraps(Super.foo)
    def wraps_foo(self, x: int) -> int:
        print(f"here: {self} || {x}")
        return 5

Function = TypeVar("Function", bound=Callable[..., Any])

def takes_method(a: str) -> Callable[[Function], Function]:
    return lambda x: x

takes_method("unused")(Foo().wraps_foo)(5)  #  No error.
```

**Comment by erictraut** [comment]
After investigating this further, I still think pyright is applying the ParamSpec rules correctly according to the typing spec, so I don't consider this a bug. 

A function consists of an input signature (the list of parameters, their names, declared types, etc.) plus a declared return type. A ParamSpec captures the input signature. In this case, the input signature of `Super.foo` is `(self: Super, x: int)`. The `wraps` decorator returns a `_Wrapped[(self: Super, x: int)]` object. It has a `__call__` method whose type is `__call__(self, *args: P.args, **kwargs.P.kwargs) -> _RWrapper`. When this is specialized, it becomes `__call__(_self, self: Super, x: int) -> int`.

@adampauls, if you feel strongly about this issue, I invite you to start a discussion in the Python [typing forum](https://discuss.python.org/c/typing/32). The typing spec will likely need to be clarified / amended if you want this use case to work.

**Comment by adampauls** [comment]
Does the type spec say what to do for the type signature of the instance method? As I argued above, typing it the same as the class method is always wrong (IIUC), so I assume the spec is simply silent on it? In that case, returning Callable[..., Any] or Callable[..., R] seems strictly better (so the correct program is not ruled out)?
