### ISSUE TITLE
Allowing omit optional fields of TypedDict

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#751]
**Is your feature request related to a problem? Please describe.**
We have some dict that allowing some fields to be "undefined". Since Python does not have an "undefined" type, we had to use Optional (Union with None) instead.

But in the current version of Pyright, there will be errors when assigning dict to a typed dict unless all the fields are provided, including those annotated as Optional.
![image](https://user-images.githubusercontent.com/3479453/85375881-883b4280-b569-11ea-9ef8-751bfc5fa231.png)

Similarly, when the TypedDict is called as a constructor, all fields must be provided ether, no matter.
![image](https://user-images.githubusercontent.com/3479453/85376478-58d90580-b56a-11ea-946e-4fe71dc705cd.png)

**Describe the solution you'd like**
The two examples described above are both valid in Python runtime, and it's more intuitive in my opinion because it's very normal to have some dict data lacking some fields, so I think Pyright should allow Optional fields to be omitted when typing-checking variable assignment and TypedDict class construction.

**Additional context**
In fact, I'm not sure if this is expected behavior or bug, or whether there's a more "Python-like" way to achieve what we want. Please tell me what you think :smiley:

**Comment by erictraut** [comment]
Pyright implements TypedDict as specified in the official specification (PEP 589). That spec doesn't provide any provisions for undefined entries.

Specifying an Optional type won't meet your needs because that requires initialization with None.

It sounds like what you want is the ability to specify default values for TypedDict fields. This was explicitly excluded from PEP 589, but the authors left the door open for adding it in future revs of the language.

```
These features were left out from this PEP, but they are potential extensions to be added in the future:

* TypedDict doesn't support providing a default value type for keys that are not explicitly defined. This would allow arbitrary keys to be used with a TypedDict object, and only explicitly enumerated keys would receive special treatment compared to a normal, uniform dictionary type.
```

One possible solution is to create a type hierarchy of TypedDict types. The base class would include all of the required fields, and subclasses would add additional fields.

```
class Data1(TypedDict):
   a: str

class Data2(Data1):
   b: str

c: Data1
c = Data1(a="1")
c = Data2(a="1", b="2")
```

**Comment by giyyapan** [comment]
Thanks for your reply, I think I'll have to deal with this by using some kind of wrapper class with default value assignment and generates a dict.

**Comment by tamuhey** [comment]
@giyyapan according to [the doc](https://docs.python.org/3/library/typing.html#typing.TypedDict), another solution might be to use `total=False` in the class definition:

```python
class Data(TypedDict, total=False):
   a: str
   b: str

c: Data
c = Data(a="1")
c = Data(a="1", b="2")
```
