### ISSUE TITLE
Stable Diffusion：AttributeError: 'LatentDiffusion' object has no attribute 'forge_objects_after_applying_lora'

### ISSUE THREAD

**Issue by chufanwsh** [microsoft/pyright#7570]
Stable Diffusion 运行环境：
Stable Diffusion environment：
version: [v1.8.0]  •  python: 3.10.11  •  torch: 2.2.0+cu118  •  xformers: 0.0.24+cu118  •  gradio: 3.41.2  •  checkpoint: [7c819b6d13]

引发错误的插件：sd-webui-lora-block-weight
Plugins that cause errors：sd-webui-lora-block-weight

错误相关信息（Error related information）
*** Error running postprocess: E:\sd-webui-aki-v4.7\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "E:\sd-webui-aki-v4.7\modules\scripts.py", line 816, in postprocess
        script.postprocess(p, processed, *script_args)
      File "E:\sd-webui-aki-v4.7\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 437, in postprocess
        shared.sd_model.forge_objects_after_applying_lora.unet.unpatch_model()
      File "E:\sd-webui-aki-v4.7\python\lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
    AttributeError: 'LatentDiffusion' object has no attribute 'forge_objects_after_applying_lora'

在SD 程序正常启动后，可以生成图片，在生成图片结束后会出现上面这个错误。我是个新手，还请大家帮忙解决。感谢帮助。
After the SD program starts normally, images can be generated, but the above error will appear after the image generation is completed. I am a beginner, please help me solve it. Thank you for your help.

**Comment by erictraut** [comment]
The issue you're reporting doesn't appear to be related to pyright. If you need help with a library, please reach out to the maintainers of that library.

If you need help with Python static type checking in general, feel free to post a question to the [pyright discussion forum](https://github.com/microsoft/pyright/discussions).

If you think you have found a bug in pyright, please provide a minimal, self-contained code sample that demonstrates the problem along with the expected behavior.
