### ISSUE TITLE
Subclass of Async Context Manager Ignored

### ISSUE THREAD

**Issue by Congee** [microsoft/pyright#760]
**Describe the bug**
Wrong type inferred for the instance of the subclass of an Async Context Manager

**Expected behavior**
The type of the instance of a subclass of an Async Context Manager should be the type of the subclass

**Code**
``` python
from __future__ import annotations

class BaseContextManager:
    def __enter__(self) -> ContextManager:
        ...

    def __exit__(self, *args, **kwargs):
        ...


class ContextManager(BaseContextManager): ...


with ContextManager() as ctxm: ...  # ctxm is inferred as ContextManager


class BaseAsyncContextManager:
    async def __aenter__(self, *args, **kwargs) -> BaseAsyncContextManager:
        ...

    async def __aexit__(self, *args, **kwargs):
        ...


class AsyncContextManager(BaseAsyncContextManager): ...


async def dummy_fn():
    async with AsyncContextManager() as actxm: ...  # actxm is inferred as BaseAsyncContextManager
```

**VS Code extension or command-line**
coc-pyright with pyright 1.1.45

Is this a bug or feature? Is it related to covariance? 🤔

**Comment by Congee** [comment]
Perhaps the return type of `__aenter__` should not be BaseAsyncContextManager? 🤔

**Comment by erictraut** [comment]
Yes, the behavior is correct. Pyright isn't inferring anything in this case because you have explicitly specified a type annotation. Pyright will always use a type if it's provided. Inference is used only in cases where a type annotation is omitted.

If you want the subclass to be returned, you have a few options.

If this is a type stub file (and since you're using "...", I presume it is), you should use a TypeVar to annotate the "self" parameter.

```
_T = TypeVar("_T")

class BaseAsyncContextManager:
    async def __aenter__(self: _T, *args, **kwargs) -> _T:
        ...

async def dummy_fn():
    async with AsyncContextManager() as actxm:
        ...  # actxm is as AsyncContextManager
```

If this is a source file (i.e. a ".py" file), if you omit the return type annotation and the method returns "self", Pyright will infer the subclass type correctly.

```
class BaseAsyncContextManager:
    async def __aenter__(self, *args, **kwargs):
        return self

async def dummy_fn():
    async with AsyncContextManager() as actxm:
        ...  # actxm is as AsyncContextManager
```

This bit of inference magic occurs because Pyright synthesizes a TypeVar type for an unannotated `self` parameter. It's as if you added the TypeVar annotation as in the first example above.

**Comment by Congee** [comment]
Ohhhh now I can understand it. How I wish python could have a type like rust's `Self`. Thank you for your explanation. I went with defining a TypeVar.

**Comment by Congee** [comment]
FWIW, mypy documented the protocol of AsyncContextManager https://mypy.readthedocs.io/en/stable/protocols.html#asynccontextmanager-t
