### ISSUE TITLE
TypeVarTuple is not moved to the end of TypeAlias type_params

### ISSUE THREAD

**Issue by Snarpix** [microsoft/pyright#7639]
**Describe the bug**
TypeVarTuple should be at the end of TypeAlias type_params, even if it appears earlier in TypeAlias signature, as specified by [PEP 646:](https://peps.python.org/pep-0646/):
> In order to substitute these type variables with supplied type arguments, any type variables at the beginning or end of the type parameter list first consume type arguments, and then any remaining type arguments are bound to the TypeVarTuple:
> 
> Shrubbery = Tuple[*Ts, T1, T2]
> 
> Shrubbery[str, bool]              # T2=bool,  T1=str,   Ts=Tuple[()]
> Shrubbery[str, bool, float]       # T2=float, T1=bool,  Ts=Tuple[str]
> Shrubbery[str, bool, float, int]  # T2=int,   T1=float, Ts=Tuple[str, bool]
> 

**Code or Screenshots**

```python
from typing import Callable, TypeVar, TypeVarTuple, Unpack

T = TypeVar("T")
Ts = TypeVarTuple("Ts")

Alias = Callable[[Unpack[Ts]], T]

A = Alias[int, float, list[int]]

def foo(a: float, b: list[int]) -> int: ...

a: A = foo
```

**VS Code extension or command-line**
```
pyright test.py
/mnt/extra/test.py
  /mnt/extra/test.py:13:8 - error: Expression of type "(a: float, b: list[int]) -> int" cannot be assigned to declared type "A"
    Type "(a: float, b: list[int]) -> int" cannot be assigned to type "A"
      Parameter 2: type "float" cannot be assigned to type "list[int]"
        "float" is incompatible with "list[int]"
      Function return type "int" is incompatible with type "list[int]"
        "int" is incompatible with "list[int]" (reportAssignmentType)
1 error, 0 warnings, 0 informations 


pyright --version
pyright 1.1.357
```

**Comment by erictraut** [comment]
Pyright is working correctly here and in conformance to the typing spec, so I don't consider this a bug.

You're misinterpreting the meaning of the spec. The TypeVarTuple is not "moved to the end". Rather, the non-TypeVarTuple type parameters at the beginning or end of the type parameter list are substituted first. In your example, the type parameter list for `Alias` is `[*Ts, T]`. Since `Ts` is a TypeVarTuple, the type parameter `T` is substituted first. It receives the type `list[int]`. The remaining types (`int` and `float`) are then received by `Ts`.

We've recently written extensive type spec conformance tests, and pyright passes all of these. You can find the tests [here](https://github.com/python/typing/blob/main/conformance/tests/generics_typevartuple_specialization.py).

Not surprisingly, the behavior of mypy and pyre match that of pyright in this regard.
