### ISSUE TITLE
Incorrect deepcopy Type Warning for Mapping in Pylance

### ISSUE THREAD

**Issue by laipz8200** [microsoft/pyright#7649]
I'm trying to deep copy a Mapping object, but Pylance tells me there's an error here, and I don't think it should be there.

```python
    @classmethod
    def from_mapping(cls, m: Mapping[str, Any]):
        v: Dict[str, Any] = deepcopy(m)  # <- Argument of type "Mapping[str, Any]" cannot be assigned to parameter "x" of type "_T@deepcopy" in function "deepcopy"
        return cls.from_dict(v)
```

**VS Code extension or command-line**
I'm using VS Code extension Pylance v2024.4.100 (pre-release)

**Comment by erictraut** [comment]
Pyright's behavior here is correct according to the typeshed stub [copy.pyi](https://github.com/python/typeshed/blob/dc4bfc02ef1082c4a9bb9b1e327b7684f30841d1/stdlib/copy.pyi#L11), which defines `deepcopy` in the following manner:
```python
def deepcopy(x: _T, memo: dict[int, Any] | None = None, _nil: Any = []) -> _T: ...
```

Note that it requires that you pass it a `dict` object, not a `Mapping` object.

If you think the type definition of `deepcopy` is incorrect, please file a bug in the [typeshed project](https://github.com/python/typeshed/issues).

**Comment by roganov** [comment]
I don't think it has anything to do with typeshed. The type of the first parameter of `deepcopy` is `_T`, not `dict` (it's the type of the second parameter `memo`).
Pyright correctly rejects this program because you shouldn't be able to assign a `Mapping` (the result of `deepcopy`) to a `dict`, but the error message is probably confusing.

@laipz8200 you will see the error more clearly if you refactor like this:

```python
    @classmethod
    def from_mapping(cls, m: Mapping[str, Any]):
        x = deepcopy(m) # no error
        v: Dict[str, Any] = x  # <- Expression of type "Mapping[str, Any]" cannot be assigned to declared type "Dict[str, Any]" "Mapping[str, Any]" is incompatible with "Dict[str, Any]"
        return cls.from_dict(v)
```

**Comment by erictraut** [comment]
Ah yes, you're right. I misdiagnosed the issue. 

However, it's still not a bug in pyright. Pyright is correct in generating an error here because `deepcopy` is annotated to return the same type `_T` that is passed to it. In your case, you're passing a `Mapping[str, Any]`, but you're expecting it to return a `dict[str, Any]`. As it's defined, `deepcopy` will return a `Mapping[str, Any]` in this case.

Not surprisingly, mypy generates the same error in this case.

I'm not familiar with the internal implementation of `deepcopy`. If it always returns a `dict` when it's presented with a `Mapping`, then its definition should probably be updated accordingly in the typeshed stubs.

In the meantime, you can avoid a type violation by doing the following:

```python
    v: dict[str, Any] = deepcopy(dict(m))
```

**Comment by laipz8200** [comment]
> I don't think it has anything to do with typeshed. The type of the first parameter of `deepcopy` is `_T`, not `dict` (it's the type of the second parameter `memo`). Pyright correctly rejects this program because you shouldn't be able to assign a `Mapping` (the result of `deepcopy`) to a `dict`, but the error message is probably confusing.
> 
> @laipz8200 you will see the error more clearly if you refactor like this:
> 
> ```python
>     @classmethod
>     def from_mapping(cls, m: Mapping[str, Any]):
>         x = deepcopy(m) # no error
>         v: Dict[str, Any] = x  # <- Expression of type "Mapping[str, Any]" cannot be assigned to declared type "Dict[str, Any]" "Mapping[str, Any]" is incompatible with "Dict[str, Any]"
>         return cls.from_dict(v)
> ```

You are right, after re-looking at the signature of `deepcopy` I found that this was my mistake.

I will consider @erictraut 's solution, thank you both.
