### ISSUE TITLE
Literal["\N{...}"] misunderstood?

### ISSUE THREAD

**Issue by gvanrossum** [microsoft/pyright#7653]
Inspired by the discussion about [exotic strings](https://discuss.python.org/t/exotic-kinds-of-string-annotations/50527) on Discourse I tried this simple example in the pyright playground:
```py
from typing import Literal

x: Literal["\N{QUOTATION MARK}"] = '"'
```

I believe this should work, and [it works in mypy](https://mypy-play.net/?mypy=latest&python=3.12&gist=159e24453a50d7ee6a7e173f20e930bd), but [pyright gives an error](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAySMApiAIYA2AsAFB0AeAXIcWVQNoBEAOgHIBvAIoBVAPIAVAIISAkmL5QAslIBKAaQC%2BXALpQAvFADkXI3SA).

Note that a plain escaped quote (`Literal["\""]`) works.

**Comment by erictraut** [comment]
Pyright currently has no understanding of translations between escaped unicode names and their corresponding unicode characters. I'll look into adding this, but if it meaningfully increases the download size or memory footprint of pyright, then I'm going to be reluctant to add this support. 

No pyright user has ever reported an issue related to unicode encodings within `Literal` type annotations, and I doubt if anyone in the wild is using this. Adding support for a feature that has zero usage among pyright users but harms all pyright users is not a good tradeoff.

Mypy gets this support for free because it's relying on the Python tokenizer and parser to interpret these strings.

**Comment by gvanrossum** [comment]
That's totally fair. Maybe the error message could be improved? It appears to think that the `\N` escape evaluates to `'-'`.

**Comment by erictraut** [comment]
Yeah, a better error message is a good idea. This will be included in this week's release.

**Comment by erictraut** [comment]
Some notes to my future self (or anyone else who is considering adding this support):

The CPython source base includes some large data tables that are generated from the official "Unicode Database", which is updated continually by the Unicode foundation. The source code for the tool that performs this translation can be found [here](https://github.com/python/cpython/blob/main/Tools/unicode/makeunicodedata.py).

The generated tables can be found in [this (very long) header file](https://github.com/python/cpython/blob/main/Modules/unicodename_db.h).

The runtime code that utilizes the data in this header file can be found [here](https://github.com/python/cpython/blob/73906d5c908c1e0b73c5436faeff7d93698fc074/Modules/unicodedata.c#L1276).
