### ISSUE TITLE
Multiple errors with subclass of a Generic class paramterized by ParamSpec

### ISSUE THREAD

**Issue by ringohoffman** [microsoft/pyright#7656]
**Describe the bug**
When you have a subclass of a generic class parameterized by ParamSpec, you get errors either calling it with no args or any args, even if either are acceptable.

**Code or Screenshots**
```python
from typing import Callable, Generic, TypeVar

from typing_extensions import ParamSpec

T = TypeVar("T")
P = ParamSpec("P")

class MyGeneric(Generic[P, T]):
    def __init__(self, cls: Callable[P, T], *args: P.args, **kwargs: P.kwargs) -> None:
        self.attr = cls(*args, **kwargs)

class MySubclass(MyGeneric[P, T]):
    ...

MyGeneric(int)  # OK
MySubclass(int)  # Arguments for ParamSpec "P@MyGeneric2" are missing

MyGeneric(int, 0)  # OK
MySubclass(int, 0)  # Expected 1 positional argument
```

**VS Code extension or command-line**
Pyright CLI v1.1.357

**Comment by erictraut** [comment]
You're in luck! This issue is addressed in pyright 1.1.358, which I just published a few minutes ago. :)

[Pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoDCAhgDYlEBGJApgDRQDi1K1ISAxvQCqLUBqREAFgAUKNCRYiVGgD61AB4xmAZyRgUKzNlz4ACoKIQAygmrtRorlAC8UHmYEgAFACIurgJSi9tqAZAjU3M3PS9LEXZyFS0AWTgmFjZ2Z0TWDgBtPW4AXU8ALlEoYqgAE2pgKFlZVCQYaucVahJgeiiVfMJScipqLNz6ACpBNA7-ADoRlSHBgGsAdynOvXGFqc8oAFoAPigAOQ1qQpES06gmlsmYGBA-dudhkFGZtaeVbzFI6Li4YwBXChRIgxZzxNLJfr2PLHU7jOERMHMdIpVAwDZQADEUAA8gBpUTxf6A77OVHorEAQSefwgzBgWmAuH8hhMZnYUFcegAAoikhwAEyuKCCahQCBIGIyBEJJHJUkoGD0AAM5Jx%2BJEhIBQJBqOVqoAogo2cpSlAAIxQHBqGDqFCkYXU2kK0RAA)

**Comment by ringohoffman** [comment]
How is that for turnaround!

**Comment by ringohoffman** [comment]
Did the publication fail? I don't see it on PyPI yet 👀

**Comment by erictraut** [comment]
Pyright is published to the npm package registry. There is also a [community-maintained python wrapper](https://github.com/RobertCraigie/pyright-python) for pyright that is published to pypi. If you use that mechanism to install pyright, you'll need to wait for it to be published. It's typically updated within 24 hours of me publishing a new version.
