### ISSUE TITLE
Enum and typing.Self seems incompatible types.

### ISSUE THREAD

**Issue by AlexanderPodorov** [microsoft/pyright#7712]
**Describe the bug**
See example code, the last line shows a warning, however it should not.

**Code or Screenshots**

```python
from collections.abc import Sequence
from enum import StrEnum
from typing import Self


class Test(StrEnum):
    A = "a"
    B = "b"

    @classmethod
    def test(cls) -> Sequence[Self]:
        return [cls.A, cls.B]  # shows warning, seems it should not
```

**VS Code extension or command-line**
Pylance v2024.4.101 (pre-release), pyright 1.1.358.

**Comment by erictraut** [comment]
I think pyright's behavior is correct here. The type of `cls.A` is `Literal[Test.A]`, and this is not type compatible with `Self`.

It's odd to use `Self` in an `enum` class the way you're doing here. Normally, `Self` is used to enable subclassing, but the runtime doesn't allow subclassing of enum classes, so this seems unnecessary.

Use `"Sequence[Test]"` rather than `Sequence[Self]`, and the type violation will disappear.

**Comment by sakosha** [comment]
with https://github.com/python/mypy/pull/19779 being merged, should this be reconsidered?
