### ISSUE TITLE
 Pyright unable to infer the type of Generic classmethod

### ISSUE THREAD

**Issue by sunfkny** [microsoft/pyright#7721]
**Describe the bug**
Since version 1.1.354, Pyright unable to infer the type of a generic class method in certain scenarios.

**Code or Screenshots**
```python
from typing import Generic, TypeVar, reveal_type

T = TypeVar("T")

class Option(Generic[T]):
    def __init__(self, value: T):
        self._val = value

    @classmethod
    def Some(cls, val: T) -> "Option[T]":
        return cls(val)

reveal_type(Option(1))           # Pyright correctly infers Option[int]
reveal_type(Option.Some(2))      # Pyright incorrectly infers Option[Unknown]

```

In this code, Pyright correctly infers the type of `Option(1)` as `Option[int]`, but since version 1.1.354, it incorrectly infers the type of `Option.Some(2)` as `Option[Unknown]` [Pyright Playground](https://pyright-play.net/?pyrightVersion=1.1.354&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoDiApikSEgMYA0UAKokQGoCGINIRAbkcwDYD68BEQCwAKHG0oAXjoMWIABQAiWsoCU4rWIq9mAZ31QA8ghhIwKRcVLkKAbVoBddQC5xUT1AAmRYFH5%2BVCQYQMV9Il5gGk4%2BAFciVzo3Dy80iKiAOn5Y3hkoXITtNIABXQN9CCIYAAswb1TPX38AZUgiRV19GL4k2nUoAFoAPihlU3NLRydldzE0tI4YOJAUKC7FXM0JHY5uPkEGRQmLKwBGdW29ngEhDpPLTLaqxQAmS-EgA). Prior to version 1.1.354, Pyright inferred the correct type for both cases [Pyright Playground](https://pyright-play.net/?pyrightVersion=1.1.353&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoDiApikSEgMYA0UAKokQGoCGINIRAbkcwDYD68BEQCwAKHG0oAXjoMWIABQAiWsoCU4rWIq9mAZ31QA8ghhIwKRcVLkKAbVoBddQC5xUT1AAmRYFH5%2BVCQYQMV9Il5gGk4%2BAFciVzo3Dy80iKiAOn5Y3hkoXITtNIABXQN9CCIYAAswb1TPX38AZUgiRV19GL4k2nUoAFoAPihlU3NLRydldzE0tI4YOJAUKC7FXM0JHY5uPkEGRQmLKwBGdW29ngEhDpPLTLaqxQAmS-EgA).

**VS Code extension or command-line**
ms-python.vscode-pylance `v2024.4.1`

**Comment by erictraut** [comment]
This is by design, not a bug. This behavior was previously somewhat ambiguous in the typing spec, but the recent addition of [PEP 696](https://peps.python.org/pep-0696/) (which introduces TypeVar default values) clarified how this must work.

When you call a constructor of a generic class, the specialized type of the class is not yet established and can be inferred from the arguments passed to the constructor.

By contrast, when you call a class method, the specialized type of the class is already established at the time that the method is bound to the class — prior to the call. If you don't explicitly provide type argument values, they take on their default values (as explained in PEP 696). If no default is specified, it implicitly becomes `Any` (i.e. `Unknown`). 

In your example above, if you want to invoke a class method `Some` on `Option[int]`, you'd need to write `Option[int].Some(2)`. Or if you use PEP 696 to specify a default type argument for `T`, you could do the following:

Code sample in [pyright playground](https://pyright-play.net/?pyrightVersion=1.1.354&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoDiApikSEgMYA0UIRAbkQIYA2A%2BvAkQLABQokWIlRo2RAB4wSAZyRgU0zNlz4AKoiIA1JiD59VUALxR1XbSAAUAIlVWaAEyLAmAVxYxDqGAEo9vCixM0ooA8ggwcigWxKTkFADaqgC63gBcfFCZUI7AUGxsqEgw%2BRbSRCzANPSsLkSpJmkZWc1lFQB0bNUsRlBdtX7NAAIBQdIQRDAAFmD2TZk5UADKkEQWAdJVrPWq3lAAtAB8UFZhEfKJSVbpvM3NdDAuIChQ6xZdvrx8dIysHBoWp0ibWW4wsACZvB8gA)

```python
from typing import Generic, reveal_type
from typing_extensions import TypeVar

T = TypeVar("T", default=int)

class Option(Generic[T]):
    def __init__(self, value: T):
        self._val = value

    @classmethod
    def Some(cls, val: T) -> "Option[T]":
        return cls(val)

reveal_type(Option.Some(2)) # Option[int]
```
