### ISSUE TITLE
Bug when using protocols with callable fields

### ISSUE THREAD

**Issue by jonathan-laurent** [microsoft/pyright#7735]
In the example below, Pyright fails to recognize that dataclass `A` implements protocol `HasF`. 
Note that the problems does not occur with protocol `HasX` so the problem seems to be related to field `f` being callable.

**Code:**

```python
from dataclasses import dataclass
from typing import Callable, Protocol

class HasX(Protocol):
    @property
    def x(self) -> int: ...

class HasF(Protocol):
    @property
    def f(self) -> Callable[[int], int]: ...

@dataclass
class A:
    x: int
    f: Callable[[int], int]

def test(a: A):
    has_x: HasX = a  # OK
    has_f: HasF = a  # ERROR with Pyright 1.1.356
```

**Detailed Error:**

```txt
Detailed Error:
Expression of type "A" cannot be assigned to declared type "HasF"
  "A" is incompatible with protocol "HasF"
    "A" is incompatible with "int"
    "f" is an incompatible type
      Type "() -> int" cannot be assigned to type "(int) -> int"
        Function accepts too many positional parameters; expected 0 but received 1PylancereportAssignmentType
```

**Pyright version:**
Bug found using Pyright 1.1.356, run from the VS-Code extension with Pylance.

**Comment by erictraut** [comment]
@n1yaz, that won't work because you're mixing up class variables and instance variables in your example. A callable that's stored as a class variable acts differently than a callable that's stored as an instance variable. If you declare a method using a `def` statement, it's a "pure" class variable and cannot be overwritten with an instance variable. In the case of a dataclass, it's a "pure" instance variable. If you define an attribute in a class (including a protocol), it is considered a "regular" class variable, which can be either a class variable or an instance variable. For details, refer to pyright's [documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=class-and-instance-variables).

If your intent is to define a method in a protocol, you should use a `def` statement rather than an attribute (variable) declaration.

```python
class Proto(Protocol):
    def method_a(self, arg_a: int, arg_b: bool) -> int: ...
    def method_b(self, arg_a: int, arg_b: bool) -> int: ...
```

If your intent is to define a variable that holds a callable type, then it's fine to use a variable declaration in the protocol, but you should not use a `def` statement in the protocol's implementation. Instead, you should assign the callable to an instance variable with an assignment statement.

```python
def a_impl(arg_a: int, arg_b: bool) -> int:
    return arg_a

class A(Proto):
    def __init__(self):
        self.method_a = a_impl
        self.method_b = lambda arg_a, arg_b: arg_a
```
