### ISSUE TITLE
 `random.choice` and list of enums produces inconsistent `None` type narrowing

### ISSUE THREAD

**Issue by qria** [microsoft/pyright#7785]
# Bug 
`random.choice` and list of enums produces inconsistent `None` type narrowing.
It looks like a bug because two seemingly equivalent codes are producing different behaviours.
I tried to distill it as much.

# Code

```python
from enum import StrEnum
import random

class MyEnum(StrEnum):
    A = 'A'
    B = 'B'


def foo(choice: MyEnum | None) -> MyEnum:
    if choice is None:
        choice = random.choice(list(MyEnum))
    return choice  # type error: MyEnum | None is incompatible with MyEnum


def bar(choice: MyEnum | None) -> MyEnum:
    if choice is None:
        enum_list = list(MyEnum)
        choice = random.choice(enum_list)
    return choice  # no type error

```

# Reproduction Environment

The pyright playground reproduces this behaviour, which runs version 1.1.360.

https://pyright-play.net/?code=GYJw9gtgBApgdgV2gSwgBzCALlAylkAUUQgChUNsoQBDOAE0lNIGMAbGgZ06gFkBPYkgAU%2BIiQCUALlJQ5UAIJQAvFADkCtbPkAhFep1bm9GMCjAwYYSwAWYZCxhS%2BgklAA%2BUAHJg4MCVAAtAB8LkIQMvJQyGa29o7RPD5%2BkVHycQ4w%2BrQMkAB0GY7CbMicWMIC4RIS2nIgMFgIIHBQhVlQAMRQWPxoWTAg4CDOlW6eyVml0XAskGg0WMgARmxZAO7IWDZhJMykJmZLNCDWdpkjrkge3r7%2BQaGjSKlyMa1nCVMTz2nwSAD6JTK%2BkB5UeEBqaXS7yyqhyjAgBWhwl%2BEABpSwEPk9UazTe8XaXTgYG6vX6g0wpCAA

**Comment by erictraut** [comment]
Pyright is working as intended here, although I can understand why it might appear otherwise.

Your example with function `foo` contains the statement `choice = random.choice(list(MyEnum))`. The LHS of the assignment is a variable with a declared type of `MyEnum | None`. This means pyright will use bidirectional type inference to determine the type of the RHS. Since the RHS is a call to a generic function, this means the "expected type" will be used to add constraints to the return type. The `random.choice` call is defined as `def choice(seq: SupportsLenAndGetItem[_T]) -> _T: ...`, which implies a constraint of `_T <: MyEnum | None` (where `<:` means "subtype of"). The subexpression `list(MyEnum)` is also evaluate with bidirectional type inference in this case. Given the constraint, the type of expression `list(MyEnum)` is inferred to be `list[MyEnum | None]`. That means that the type of the call to `random.choice` is evaluated as `MyEnum | None`. This type is assigned back to the LHS of the assignment expression, which explains why you're not seeing a narrower type in this case.

There are a couple of ways you can fix this in your code:
1. Evaluate `list(MyEnum)` separately, as you've done in the `bar` function within your code sample.
2. Assign the call to `random.choice` to a temporary variable that doesn't have a declared type. Then assign that temporary variable back to `choice`.
```python
        x = random.choice(list(MyEnum))
        choice = x
```

I'll note that mypy also generates errors for this code sample, which isn't surprising given that it also uses a similar technique for bidirectional type inference.
