### ISSUE TITLE
Dutch Localization for pyright

### ISSUE THREAD

**Issue by OseSem** [microsoft/pyright#7795]
I could add the dutch language to pyright's localization.

I will add this, and I will be fast but I just want to ask whether I should do this.

**Describe the solution you’d like**
A clear and concise description of the solution you would like to see.

The dutch language in pyright.

**Comment by erictraut** [comment]
Thanks for the offer. Localization support for pyright is provided through the pylance team at Microsoft. I'll let someone from the pylance team speak to whether they would like to see additional locales added by contributors. There is a maintenance cost associated with each new language because error strings are continually being improved and added, so that will need to be considered.

@rchiodo, @debonte, could you or someone else from the pylance team please add your thoughts to this thread? Thanks!

**Comment by debonte** [comment]
I appreciate your offer.

However, Dutch is not one of the supported languages in either [Visual Studio Code](https://code.visualstudio.com/docs/getstarted/locales#_available-locales) or [Visual Studio](https://learn.microsoft.com/en-us/visualstudio/releases/2022/system-requirements#supported-languages), and it's unlikely that we would ever add support in Pyright or Pylance for a language that isn't also supported by the core UI of the IDEs.

As Eric pointed out above, there's a long-term maintenance cost to each language we support, including having people on staff who are experts in that language. So the decision of which languages to support is made at a product-wide level (ex. all of VS Code).

If VS Code or Visual Studio add a Dutch language pack in the future, we would do the same. You could open an issue on the [vscode issue tracker](https://github.com/microsoft/vscode/issues) requesting Dutch localization and see how much support it gets.

cc: @luabud

**Comment by OseSem** [comment]
Thanks for responding, I will reach out to vscode to ask them about Dutch localization and if that would be accepted I will come back here later once that is finished. Greetings
