### ISSUE TITLE
`reportUnhashable` in `isinstance(x, set)` clause when using recursive `TypeAlias`.

### ISSUE THREAD

**Issue by randolf-scholz** [microsoft/pyright#7824]
Code sample in [pyright playground](https://pyright-play.net/?pyrightVersion=1.1.361&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgGoCGIANISQIIA2S5AzjXSnDSMQG7HkGAfXgJiAKFCQoAYzAMGxGTCRgULAHTkARjMzZc%2BAMLzFy1ShoBZcgmTpx4gkLlQAvLTEUQACgBEznJ%2BNHK8lMwoMG4EIACuxACU4gByxCwwxAAmAFyexIzMLO6ELmBQAD5QJgpKKmoA2n6p6Vn1gWAAun4dFVA2dqho9RxcUE1pGZltpV0djpnEwFDAYGA%2BYNoAVrntvdVmdSjTcj2V-fZDIzTtHQlQALQAfFAsxDDZ4lBfmEtILKjpcgoGTEdZbGivGAJD7fWFQHj8QQiEhgzZ3KAAYheb3qAFUUABrFBgADuKA6ACpepDjmAAAIrTqfOFfHgwWIgFBQADeAA9lrgoPzUFANpsAL6YqCAUHJmazyH9iHkAKIgcAgeaLKDaSio3LNSa024PZ6QmHfJC-f7qGBAkGoiFvaFyuEIgTCUSgsXorE0-FE0nkqmVGkG1rtOk6kAdOYs1lvDlcvkCkBCzBcsWSrGAGXJ4cQcHh8QALVgl7SKF0gBWvFVq3BAA)

```python
from typing import TypeVar, TypeAlias, Any, reveal_type
from collections.abc import Collection, Mapping

T_co = TypeVar("T_co", covariant=True)
Nested: TypeAlias = T_co | Collection["Nested[T_co]"] | Mapping[Any, "Nested[T_co]"]

def foo(obj: T_co | Collection[T_co] | Mapping[Any, T_co]) -> set:
    if isinstance(obj, set):
        reveal_type(obj)  # set[Unknown]* | set[T_co@foo]
        return {x for x in obj} # ✅
    raise TypeError

def bar(obj: Nested[T_co]) -> set:
    if isinstance(obj, set):
        reveal_type(obj)  # set[Unknown]* | set[Nested[T_co@bar]]
        return {x for x in obj} # ❌ reportUnhashable
    raise TypeError
```

[`mypy` reports no issues](https://mypy-play.net/?mypy=latest&python=3.12&gist=bc57d53bef4fd83792c7fbc2ee4ccb78), and reports types as `set[Any]` in each case.

**Comment by erictraut** [comment]
This behavior is intended, so I don't consider this a bug.

A `Mapping` object does not meet the requirements of hashability, so if you attempt to add a `Mapping` object to a set, you will see an error:

```python
def func1(obj: Mapping):
    x = {obj} # Type error: obj is not hashable
```

In your first example (`foo`), you are using a type guard to narrow the type of `obj` from `T_co | Collection[T_co] | Mapping[Any, T_co]` to `T_co | Collection[T_co]`, so when you iterate over the items in each of these, you do not receive any `Mapping` object.

In your second example (`bar`), when you iterate over the items in obj`, one of the subtypes is `Mapping`, which is not hashable.

Mypy doesn't emit an error here because it doesn't provide checks for hashability.

If you don't want pyright to check for hashability, you can disable the `reportUnhashable` check.

**Comment by randolf-scholz** [comment]
@erictraut We already know it's a set inside the `if isinstance` clause, so it is known that the elements are hashable! After your comment, I checked `typeshed` and was surprised that they do not bind the TypeVar of `set` to `Hashable`:

https://github.com/python/typeshed/blob/5883898b0ab08b7ad306e37ca70dd9e646b4ce2e/stdlib/builtins.pyi#L1111

https://github.com/python/typeshed/issues/9571

This seems to be the real underlying issue here.
