### ISSUE TITLE
Narrowing does not take shared variables into account

### ISSUE THREAD

**Issue by ktbarrett** [microsoft/pyright#7911]
**Describe the bug**
Assigning to a global variable narrows the deduced type (as it would for normal variables), not considering that any non-local code could change the value, re-widening the type.

This is also probably present with `nonlocal` variables and variables shared by upvalue (or whatever Python calls them).

**Code or Screenshots**

```python
foo: int | None

class Bar:
    def wew() -> None:
        global foo
        foo = None
        change_foo()
        if foo is not None:  # foo is 'None'
            print(foo)  # foo is 'Never'

def change_foo() -> None:
    global foo
    foo = 1
```

**VS Code extension or command-line**
Using the VSCode extension v2024.5.1.

**Comment by erictraut** [comment]
Yes, this is by design, so I don't consider it a bug.

Type narrowing is performed within an execution scope. Pyright (like most type checkers in most languages) assumes that you will not modify the value of the expression "behind the back" of the type checker in an alternate execution scope. For example, you can see that mypy makes this same assumption. Without this assumption, type narrowing would lose most of its utility because any function or method call (explicit or implicit) could invalidate previously-narrowed types.

If you're interested in leveraging static type checking in your code, you will need to avoid this design pattern. For example, you can use accessor functions rather than directly accessing a global variable.
