### ISSUE TITLE
Function defined in __init__.py is unknown

### ISSUE THREAD

**Issue by sylvainmouquet** [microsoft/pyright#7915]
Hi,

A function f in `__init__.py` is imported in the file `conftest.py`  by `from tests import f`

Pyright generates error : `error: "f" is unknown import symbol (reportAttributeAccessIssue)`

**Comment by erictraut** [comment]
You haven't provided enough information for me to help diagnose the issue. 

If you think this is a bug in pyright, please submit a bug report that includes a minimal, self-contained code sample and repro steps.

Based on the symptoms you've described, this is unlikely to be a bug in pyright, but I'm happy to help you diagnose the issue if you'd like to provide more details. I'm closing the issue in the meantime because there's nothing actionable here.
