### ISSUE TITLE
Pyright report typing problems even when using a typed lib

### ISSUE THREAD

**Issue by marlonpatrick** [microsoft/pyright#792]
**Describe the bug**

Pyright report typing problems even when using a typed lib like FastAPI.

**To Reproduce**

Run pyright with code and settings bellow. 

**Expected behavior**

Do not report this error: 3:1 - error: Type of "app" is unknown (reportUnknownVariableType)
app type is obviously FastAPI

Do not report this error: 5:2 - error: Type of "get" is unknown (reportUnknownMemberType)
get is a method which returns Callable

Do not report this error: 5:2 - error: Untyped function decorator obscures type of function; ignoring decorator (reportUntypedFunctionDecorator)
get is a method which returns Callable

**Screenshots or Code**

```
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
async def root():
    return {"message": "Hello World"}
```

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? command-line and vs code pylance, problem happens on both

Which version? pyright 1.1.49

**Additional context**

pyrightconfig.json
```
{
    "pythonPlatform": "Linux",
    "pythonVersion": "3.8",
    "venvPath": ".",
    "venv": ".venv",
    "typeCheckingMode": "strict"
}
```

pyright output

```
fastapi-example$ pyright
Loading configuration file at fastapi-example/pyrightconfig.json
No include entries specified; assuming fastapi-example/pyrightconfig.json
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding .git
stubPath fastapi-example/typings is not a valid directory.
Searching for source files
Auto-excluding fastapi-example/.venv
Found 1 source file
fastapi-example/main.py
  3:1 - error: Type of "app" is unknown (reportUnknownVariableType)
  5:2 - error: Type of "get" is unknown (reportUnknownMemberType)
  5:2 - error: Untyped function decorator obscures type of function; ignoring decorator (reportUntypedFunctionDecorator)
3 errors, 0 warnings 
Completed in 0.499sec
```

**Comment by erictraut** [comment]
This is the expected behavior when you use pyright in "strict" mode.

While the fastapi library contains some type information, it is incomplete. For example, the `get` method in the `FastAPI` class returns the type `Callable`, which doesn't specify the parameters or return type of the callable. Without this additional information, type analysis will be incomplete, leaving you vulnerable to type-related errors.

A correctly-annotated decorator should use a TypeVar that is bound to a Callable type -- something like this.
```
_TCallable = TypeVar("_TCallable", bound=Callable[..., Any])
def get(...) -> Callable[[_TCallable], _TCallable]: ...
```

If I add this annotation to the fastapi `get` method, pyright no longer reports these errors.

If you don't want to see these errors, pyright allows you to use less-strict modes. You can even disable specific errors on a file-by-file basis using comments at the top of the file:

```
# pyright: reportUnknownVariableType=false, reportUnknownMemberType=false, reportUntypedFunctionDecorator=false
```

**Comment by marlonpatrick** [comment]
Got it, thanks for the clarification.

Some questions:

- I still don't understand error reportUnknownVariableType "app = FastAPI()". What's the point?

- How can I know which rules are enabled or disabled when modifying the strict mode to a basic mode for example?

- Is there a way to disable a rule like reportUnknownMemberType only for code from libs, but still validate my own code? I know that my code will use external libs, but I refer to the methods, functions, parameters, variables that I declare myself.

**Comment by erictraut** [comment]
By default, Pyright looks only at type stubs for its type information. If you want it to use library code (".py" files) for type information (regardless of whether there are annotations in that code), you need to enable that feature. If you're using the VS Code extension, you can do this by setting "pyright.useLibraryImplementations" to true. If you're using the command-line version of Pyright, you can use the "--lib" switch. If you do this, the first error will go away because Pyright will be able to determine the type of `app` from the ".py" file.

In strict mode, every diagnostic rule is enabled. This mode is useful for production code bases where you want to leverage static type checking to find as many bugs as possible, and you don't mind investing the time to make the code "strictly typed". Enabling strict mode for an existing code base (one that wasn't written from scratch with strict enabled) typically requires quite a bit of work. Pyright is designed to allow you to enable strict mode on a file-by-file or directory-by-directory basis, leaving less-important code (e.g. test code or legacy code) alone. I've documented some tips [here](https://github.com/microsoft/pyright/blob/master/docs/getting-started.md). You can start also start with "basic" type checking mode and then enable individual diagnostic rules for your code base as you work your way toward "strictly typed".

All diagnostic rules apply only to your code, not the code in libs. The "reportUnknownMemberType" diagnostic, for example, is telling you that _your_ code is accessing a member whose type is unknown. Oftentimes, the preferred way to eliminate an "unknown type" diagnostic message is to augment or fix the type information in a type stub file or the library code.

**Comment by marlonpatrick** [comment]
Thanks for explanation @erictraut.
