### ISSUE TITLE
Attempting to type narrow on builtin classes with phantom subclasses adds those classes into the narrowed result

### ISSUE THREAD

**Issue by Pyprohly** [microsoft/pyright#7955]
This doesn’t look right to me:

```python
def f(data: complex | bytes) -> None:
    reveal_type(data)
    if isinstance(data, bytes):
        raise Exception
    reveal_type(data)
```

```python
/Users/danpro/Desktop/file.py
  /Users/danpro/Desktop/file.py:3:17 - information: Type of "data" is "complex | bytes"
  /Users/danpro/Desktop/file.py:6:17 - information: Type of "data" is "complex | float | int | bytearray | memoryview"
0 errors, 0 warnings, 2 informations 
```

Shouldn’t the type just be `complex` on the second info line?

---

In `type-concepts-advanced.md`, the first code example, it should say `reveal_type(val) # float | str | complex`, not `reveal_type(val) # int | str | complex`, on the first `reveal_type()` line.

**Comment by erictraut** [comment]
Pyright's behavior here is correct, so I don't consider this a bug.

`complex` and `float` are special "promotion types" in the type system. You can read about this in the [type spec](https://typing.readthedocs.io/en/latest/spec/special-types.html#special-cases-for-float-and-complex). This means, effectively, that when you use `complex` in a type annotation, it really means `complex | float | int`. This allows you to call `f(1)` or `f(1.0)` in your example without generating a type error even though `int` and `float` are not really subclasses of `complex`.

Historically, `bytes` was also treated as a promotion type by mypy even though this was never officially added to PEP 484 or the typing spec. When `bytes` is used in a type annotation, it was historically treated as though it was effectively `bytes | bytearray | memoryview`. This behavior has since been deprecated by [PEP 688](https://peps.python.org/pep-0688/), but it is still enabled in pyright (and in mypy) for backward compatibility. I plan to disable it by default in a year or so. If you would like to manually disable it, you can specify `"disableBytesTypePromotions": true` in your pyright config file.
