### ISSUE TITLE
"message": "Import \"numpy\" could not be resolved", 	

### ISSUE THREAD

**Issue by Rakesh-656** [microsoft/pyright#8038]
[{
	"resource": "/c:/Users/SOS/Downloads/5 EMA CALL BUYING-1.ipynb",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportMissingImports"
		}
	},
	"severity": 4,
	"message": "Import \"numpy\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 5,
	"startColumn": 8,
	"endLineNumber": 5,
	"endColumn": 13
}]

**Comment by Rakesh-656** [comment]
Import "NorenRestApiPy.NorenApi" could not be resolved

**Comment by Rakesh-656** [comment]
Import "pandas" could not be resolved from source

**Comment by erictraut** [comment]
You have not provided enough information to diagnose the issue. This is unlikely to be a problem in pyright but is instead a configuration issue or user misunderstanding, so I'm going to close the bug report. If you have questions about how to use pyright, please post questions in the discussion section of this project rather than filing bug reports.

**Comment by Rakesh-656** [comment]
import concurrent.futures
import time
import re
import numpy as np
from datetime import datetime,timedelta
from NorenRestApiPy.NorenApi import NorenApi
import pandas as pd
import pandas_ta as ta
class ShoonyaApiPy(NorenApi):
    def __init__(self):
        NorenApi.__init__(self, host='https://api.shoonya.com/NorenWClientTP/', websocket='wss://api.shoonya.com/NorenWSTP/')        
        global api
        api = self
