### ISSUE TITLE
Class cannot be used as an input type in itself

### ISSUE THREAD

**Issue by eedoc** [microsoft/pyright#806]
When I try to type hint an input to a function in a class with that same class, I get an unbound error. Using the class in another class works fine.

```
class A:    
    def foo(self, bar: A):
        self.bar = bar
```

Gives the error _"A" is unbound_, but

```
class B:
    def foo(self, bar: A):
        self.bar = bar
```

works fine.

Is this expected behavior or a bug?

**Comment by erictraut** [comment]
This is expected behavior. If you attempt to run your first example in the Python interpreter, it will generate an exception because class "A" is not yet bound when it interprets the value. PEP 484 provides a workaround for this case. You can use a forward reference for a type annotation by enclosing it in quotes. This way, the Python interpreter won't generate an exception, but a static type checker can still parse the type from the string.

```
class A:    
    def foo(self, bar: "A"):
        self.bar = bar
```

**Comment by eedoc** [comment]
Thanks!

**Comment by yellowjello** [comment]
As an FYI, if you're using Python 3.7+, you can add in a `from __future__ import annotations` and it will work without using a string annotation, since it will postpone the evaluation of the annotation.
