### ISSUE TITLE
Error when replacing a type alias by an equivalent Protocol

### ISSUE THREAD

**Issue by jonathan-laurent** [microsoft/pyright#8150]
I am encountering an error when replacing a type alias by a protocol that is supposed to be equivalent. Here is a minimal example.

```python
from collections.abc import Callable, Generator, Iterable
from typing import Any, Protocol

type Foo[T] = Generator[Any, Any, T]
type Bar[T] = Callable[[], Ret[T]]
type Ret[T] = Iterable[T | None]
type Pair[T] = tuple[Foo[T], Bar[T]]

def bar[T]() -> Ret[T]:
    yield None

type Decorator1[T] = Callable[[Callable[[], Foo[T]]], Pair[T]]

class Decorator2[T](Protocol):
    def __call__(self, f: Callable[[], Foo[T]], /) -> Pair[T]: ...

def decorator1[T](p: Bar[T]) -> Decorator1[T]:
    return lambda f: (f(), p)

def decorator2[T](p: Bar[T]) -> Decorator2[T]:
    return lambda f: (f(), p)

# OK
@decorator1(bar)
def test1() -> Foo[int]:
    yield
    return 0

# ERROR
@decorator2(bar)
def test2() -> Foo[int]:
    yield
    return 0
```

In the code above, `Decorator1` and `Decorator2` should be equivalent. However, `test1` typechecks while `test2` causes the following error, using pyright 1.1.367, in either basic or strict mode:

```txt
Argument of type "() -> Foo[int]" cannot be assigned to parameter "f" of type "() -> Foo[T@bar]" in function "__call__"
  Type "() -> Foo[int]" is incompatible with type "() -> Foo[T@bar]"
    Function return type "Foo[int]" is incompatible with type "Foo[T@bar]"
      "Generator[Any, Any, int]" is incompatible with "Generator[Any, Any, T@bar]"
        Type parameter "_ReturnT_co@Generator" is covariant, but "int" is not a subtype of "T@bar"
          Type "int" is incompatible with type "T@bar"
```

**Comment by billfelix** [comment]
收到，谢谢您的来信。我将及时回复您！ 
祝好！

**Comment by erictraut** [comment]
The behavior you're seeing is currently by design. The behavioral difference that you're seeing is between a `Callable` form and a callback protocol. See [this discussion](https://github.com/microsoft/pyright/issues/7782) for more details.

This is something that may change in the future as we clarify this and related parts of the [Python typing spec](https://typing.readthedocs.io/en/latest/spec/callables.html) that are currently ambiguous with regard to TypeVar scoping, constraint solving, and callback protocols. As I mentioned in the other issue linked above, I don't plan to make any changes in pyright until we reach consensus on the spec because it would be doubly disruptive to make a change now and then potentially need to change it again.

We've made great progress over the last year clarifying the typing spec, adding missing chapters, etc., but there is still work to be done. Thanks for your patience as we work through the issues. If you would like to participate in the effort, the [Python typing forum](https://discuss.python.org/c/typing/32) is where these issues are being discussed.
