### ISSUE TITLE
Pyright allows to inherit `Annotated[T, ...]`

### ISSUE THREAD

**Issue by LeeeeT** [microsoft/pyright#8180]
This should be disallowed

```python
from typing import Annotated

class C[T](Annotated[T, ...]): ...
```

**Comment by erictraut** [comment]
This isn't a type violation, and other type checkers don't bother checking for it. It appears to be a limitation in the runtime, so I don't know that this is something pyright should be concerned with. In any case, this bug is unlikely to go undetected; you'll crash the first time you run your code.

I'm going to reject the enhancement request for now, but I'm willing to reconsider it in the future if there is sufficient demand.
