### ISSUE TITLE
Incompatible types in assignment

### ISSUE THREAD

**Issue by tekumara** [microsoft/pyright#827]
Given:
```
from typing import Dict


def dictionaries(name: str, args: str) -> Dict:
    a = dict()
    a['Name'] = name
    b = dict()
    b['Args'] = args
    a['OtherDict'] = b

    return a
```

mypy detects
`test.py:9: error: Incompatible types in assignment (expression has type "Dict[str, str]", target has type "str")`

would be nice if pyright picked this up too

**Comment by erictraut** [comment]
Pyright is working correctly in this case. The code above provides no type annotations for any of the local variables, so Pyright attempts to infer types based on the value(s) assigned to these variables. For both `a` and `b`, the values assigned are provided by the constructor `dict()`. With no input arguments, this constructor returns the type `Dict[Any, Any]`, so that is the inferred type of `a` and `b`. 

It sounds like you would like `a` and `b` to have a type of `Dict[str, str]`? If so, here are a couple of ways to do this:

1. Provide an explicit type annotation for your variables:
```
a: Dict[str, str] = dict()
```

2. Use a dictionary expression:
```
a = {"Name": name}
```

3. Use a form of the `dict` constructor that allows inference of the key and value types of the resulting Dict:
```
a = dict([("Name", name)])
```

**Comment by tekumara** [comment]
Gotchya thanks for your help! Looks like mypy incorrectly infers `Dict[str, str]` where as pyright infers `Dict[any, any]` which makes more sense based on the evidence available.
