### ISSUE TITLE
incorrect variable type in for loop

### ISSUE THREAD

**Issue by mantognini** [Microsoft/pyright#83]
**Describe the bug**
Type annotations provided through VS Code is bogus in specific scenarios.

**To Reproduce**
(See reproducer code below.) Over your cursor on `dictA`, `dictB`, `dictC` and `dictD` to see that only `dictA` has not the expected type. Instead of having the same type as the other variables, `dictA` is said to be a `dict[Any, Any]` (mind the lower case 'd') instead of a `Dict[int, int]`, despite the type annotation.

The fact that `dictC` is not affected by the bug let me think it has something to do with the `for` loop. Also, using a typed wrapper around `dict()` works around the issue, apparently.

**Expected behavior**
`dictA` should have the same type annotation as the other `dict*` variables.

**Screenshots or Code**
Reproducer:
```
from typing import Dict

def foo() -> Dict[int, int]:
    return dict()

for x in range(1):
    dictA: Dict[int, int] = dict()
    dictB: Dict[int, int] = foo()

dictC: Dict[int, int] = dict()
dictD: Dict[int, int] = foo()
```
Screenshot:
![Screenshot](https://user-images.githubusercontent.com/693483/56654969-630f2380-6689-11e9-9083-13ad372966b8.png)

**VS Code extension or command-line**
I'm using VS Code extension, version 1.0.16.

**Additional context**
I haven't tried to reproduce this bug with other types than `Dict`, but maybe `List` and so on are also affected.

**Comment by erictraut** [comment]
Thanks for the bug report. 

It turns out that this behavior has nothing to do with loops. You will see this with any variable declared within a non-global (module-level) scope.

It took me a while to convince myself that this was actually a bug. It depends on the desired behavior.

When pyright encounters an assignment, it uses the type of the RHS (right hand side) to determine the LHS type. This is true even if the LHS has a declared type. Consider the following example:

```
foo: Union[int, str] = 3
foo = 'hello'
```

What type would you expect to see if you hover over the `foo` in the first line? How about the second line? The current version of pyright (1.0.16) will display `int` for the first one and `str` for the second one.

I've changed the type analyzer logic to use the annotated type rather than RHS type for assignments that include an annotation. So the next version of pyright will display `Union[int, str]` if you hover over the first `foo`. It will still display `str` for the type of the second one. Even though this behavior is arguably inconsistent, I think it will seen as more intuitive. If you disagree, let me know.

**Comment by erictraut** [comment]
The new behavior is implemented in 1.0.17, which I've just published. If you don't like the new behavior, feel free to re-open the bug.

**Comment by mantognini** [comment]
Thanks for the swift reply and patch!

I'm wondering if in your example with foo, the first assignment should tag foo as int as it used to, because int is more precise than the Union type. 

Another example probably worth considering: `bar : Any = 3`. Tagging bar with int could allow more precise analysis in the following code. So, maybe the annotation tag should be the most precise type of RHS and LHS. What do you think?

**Comment by erictraut** [comment]
An annotation of `Any` makes sense only when you want to tell the type analyzer to infer nothing about the type. So in that case, I think it would be incorrect to infer the type `int`.

As for union types, it may make sense to apply a type constraint to narrow the type as you suggest. I'll think about that more.

**Comment by Kein** [comment]
I'm having a similar issue, in Pylance which is backed by Pyright:
![image](https://user-images.githubusercontent.com/623756/101480469-cc2dd280-3964-11eb-8869-944ff81acf52.png)
![image](https://user-images.githubusercontent.com/623756/101480491-d223b380-3964-11eb-80e3-fc0df4d5286b.png)

I didn't feel like creating a separate issue yet before some clarification.
