### ISSUE TITLE
`__replace__` should be synthesized  for dataclasses in 3.13

### ISSUE THREAD

**Issue by max-muoto** [microsoft/pyright#8300]
Starting in Python 3.13, a dunder `__replace__` is added onto all dataclasses instances that effectively replicates the previous module level `dataclasses.replace`. See [here](https://github.com/python/cpython/pull/108752/) for the relevant cpython PR.

The same goes for named tuples, but I'm not sure how much of that's special-cased by type-checkers versus is just in type-checkers.

**Comment by erictraut** [comment]
Changing from bug report to enhancement request.

I'm struggling to find documentation for this feature. I'd prefer to wait until it's documented before adding support. I'd also like to see support for `copy.replace` added to typeshed first, since the type information for this function will have a bearing on whether it is important to model the `__replace__` method. Since this is a dunder method, it's presumably an implementation detail rather than something that would normally be called directly, but it may be important if it's exposed as a protocol in typeshed.

I'm going to decline the enhancement request for now because there are too many open questions, but I'm willing to reconsider this in the future.

**Comment by max-muoto** [comment]
> Changing from bug report to enhancement request.
> 
> I'm struggling to find documentation for this feature. I'd prefer to wait until it's documented before adding support. I'd also like to see support for `copy.replace` added to typeshed first, since the type information for this function will have a bearing on whether it is important to model the `__replace__` method. Since this is a dunder method, it's presumably an implementation detail rather than something that would normally be called directly, but it may be important if it's exposed as a protocol in typeshed.
> 
> I'm going to decline the enhancement request for now because there are too many open questions, but I'm willing to reconsider this in the future.

I currently have a PR open adding `copy.replace` to the TypeShed for [reference](https://github.com/python/typeshed/pull/12262), where I implement a protocol that requires it, which is mainly why I'm creating this issue.

**Comment by erictraut** [comment]
Reopening now that typeshed stubs have been updated to include `__replace__`.

**Comment by erictraut** [comment]
This will be included in the next release of pyright.

**Comment by max-muoto** [comment]
> This will be included in the next release of pyright.

Thanks Eric!

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.373.
