### ISSUE TITLE
SQLAlchemy + pylance issue: Argument of type "type[JSON]" cannot be assigned to parameter "sqltype"

### ISSUE THREAD

**Issue by some-crab** [microsoft/pyright#8311]
I am using pylance in vscode and I am receiving a problem with the following, though I am not sure what to do with it.

The code is using SQLAlchemy:

```python
from sqlalchemy.ext.mutable import MutableDict
from sqlalchemy import Column, Integer, JSON
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class MyModel(Base):
    __tablename__ = 'mymodel'
    id = Column(Integer, primary_key=True, index=True)
    data = Column(MutableDict.as_mutable(JSON))
```
The `JSON` argument to `MutableDict.as_mutable` is underlined, stating the following:
```
Argument of type "type[JSON]" cannot be assigned to parameter "sqltype" of type "TypeEngine[_T@as_mutable]" in function "as_mutable"
"type[type]" is incompatible with "type[TypeEngine[_T@as_mutable]]"
```

I am not entirely sure how to resolve this, or if I will need to ignore it in this case. I read the description in the link given in the popup but I am still unclear.

**Comment by rchiodo** [comment]
Thanks, will do.

**Comment by erictraut** [comment]
Looking at this closer, I don't think this is a type checking bug.

The `as_mutable` method accepts a value of type `TypeEngine[T]`. The symbol `JSON` is a class whose type is `type[TypeEngine[Any]]`. That's not compatible with `TypeEngine[T]`, so pyright is correct to generate an error here. Not surprisingly, mypy generates an error in the same place.

If `JSON` is a valid argument for this method, then the type information in `sqlalchemy` is incorrect, and a fix would need to be made in the sqlalchemy library itself. By my reading of the implementation, the signature for `as_mutable` should be:

```python
    @classmethod
    def as_mutable(cls, sqltype: type[TypeEngine[_T]]) -> TypeEngine[_T]: ...
```

If you'd like to see this issue fixed, you can report the bug to the maintainers of `sqlalchemy`.

I'm going to close this issue because there's nothing actionable for us to do in pyright or pylance.

**Comment by rchiodo** [comment]
My version of as_mutable is exactly that?

```python
    # File C:\Users\rchiodo\AppData\Local\anaconda3\envs\Python312\Lib\site-packages\sqlalchemy\ext\mutable.py
    @classmethod
    def as_mutable(cls, sqltype: TypeEngine[_T]) -> TypeEngine[_T]:
```

**Comment by erictraut** [comment]
Look closer. In my version above, there is an additional `type[...]` added to the `sqltype` parameter annotation.

**Comment by rchiodo** [comment]
Thanks, missed that.

**Comment by 0-th** [comment]
if anyone is facing similar typing errors, you can pass an instance of `JSON` or `JSONB` (for postgres) to `MutableDict.as_mutable()` and it should still work as expected.

```
    items: Mapped[dict[str, int]] = mapped_column(MutableDict.as_mutable(JSONB()))
```

**Comment by aidandj** [comment]
For anyone running into this issue, this was [fixed](https://github.com/sqlalchemy/sqlalchemy/commit/732698427e822b6ba81f1214864685903cdc13a4) in sqlalchemy
