### ISSUE TITLE
Add support for PEP 561 `py.typed` marker files

### ISSUE THREAD

**Issue by russelldavis** [microsoft/pyright#843]
If a library has a `py.typed` file, I would want/expect pyright to:

a) Extract type information from the library regardless of the `useLibraryCodeForTypes` setting
b) Not generate a "stub file not found" error when importing the library (when reportMissingTypeStubs is enabled)

For reference, mypy does the equivalent of both of those (and that's been working well for me).

**Comment by erictraut** [comment]
Pyright already honors inlined stub (pyi) files shipped as part of packages regardless of whether `py.typed` is present.

Packages that do not include stub files but instead choose to provide some type information in the source (py) files are also supported if you set `useLibraryCodeForTypes` to true. We've found that this approach is inferior to providing stub files, as the type information is almost always incomplete, generics are not fully supported, protocols are not defined, etc. As such, we strongly encourage package authors to provide inline stubs or separate stub packages. We do not want to encourage package authors to simply throw a few type annotations in and mark their package as "typed" by adding a `py.typed` file. That approach would not ultimately benefit the Python community.

**Comment by russelldavis** [comment]
Thanks for the reply. I see where you're coming from. The tricky part is dealing with newer libraries that are written to be fully typed from the start (where people generally don't use stubs).

Since mypy already works the way I described, and popular well-typed libraries are already using `py.typed`[1], I believe the current behavior will end up counterproductive to having quality types.

To illustrate: fastapi is a well-typed library with a `py.typed` file. It has no stubs, so the only way to use its types with pyright is to set `useLibraryCodeForTypes` to true. But that means the types from all the poorly typed libraries (without `py.typed`) are going to get pulled in as well, which is exactly what we're trying to avoid.

As you mentioned, there will be some authors that abuse this and use `py.typed` with poor/incomplete types. But I'm not sure there's any approach that can avoid that. Wouldn't those same authors be able to quickly autogenerate poorly typed stubs from their poorly typed code?


[1] A few that come to mind:
https://github.com/tiangolo/fastapi
https://github.com/aio-libs/aiohttp
https://github.com/samuelcolvin/pydantic
https://github.com/tiangolo/typer

**Comment by erictraut** [comment]
An implementation with types (even if those types are relatively complete) is no substitute for high-quality type stubs. 

If the code within the package is well-typed, it should be relatively easy for the author to generate a set of stubs from the source. They can use this as a starting point for creating high-quality, complete stubs.

We might revisit this decision in the future, but for now, we want to encourage package authors to provide high-quality type stubs separate from their source code. That is the direction we believe will best serve the Python community in the long run.

In the meantime, if you want to rely on libraries that include partial type information in their implementation, you can use `useLibraryCodeForTypes`. Pyright will do its best to fill in any missing type information through type inference. You are unlikely to be able to use the `strict` type checking mode with any such packages though, since the type information is almost always incomplete.

**Comment by russelldavis** [comment]
There might be a nice middleground here.

To rephrase what I was trying to get at before: if I'm using `useLibraryCodeForTypes` in order to get the types from a library like fastapi, wouldn't it be strictly better (in terms of weeding out bad types) if pyright could ignore all the libraries without `py.typed`?

To that end, what do you think of this revised proposal (ignoring everything from the original one):

useLibraryCodeForTypes becomes a tri-state option:

- `none`: equivalent to current setting of `false`
- `all`: equivalent to current setting of `true`
- `py.typed`: only uses types from libraries with a `py.typed` file

(could use a new option name if necessary for compatibility)

**Comment by erictraut** [comment]
Implementations (even those with annotated parameters and return types) are invariably incomplete — or at least lower-quality than what is possible with type stubs. The implementation typically needs to maintain backward compatibility with older versions of Python, so it cannot make use any of the newer type-related features like variable annotations, Literals, Prototypes, NamedTuples, dataclasses, TypedDicts, etc., and they rarely provide generics or overloads. Plus, Python is "leaky" in terms of exposing symbols that are not meant to be part of the interface contract. For example, all imported symbols are automatically re-exported from the module that imports them. Type stubs address all of these problems.

What value do you see in differentiating between stub-less packages that include a `py.typed` file versus those that don't? Both contain some type information (class declarations, class hierarchy information, function declarations, parameter counts and names, property names, instance variable names) plus any type information that can be inferred (e.g. function return types in many cases). Both may provide some parameter and return type annotations. Both are almost guaranteed to be incomplete in terms of accurately and completely describing the interface contract of the library. So why differentiate between them?

Perhaps I'm not fully appreciating what you mean by "weeding out bad types". Are you saying that you want to ignore all available type information from stub-less packages that omit a `py.typed` because you think that no type information is better than the type information that can be gleaned from these sources?

While I don't see any real upside of differentiating between these two classes of packages, I see a downside of doing so. It provides less incentive for package authors to deliver high-quality stubs that accurately describe their interface contracts. The sooner we can incentivize that to happen, the better off we'll all be.

**Comment by The-Compiler** [comment]
Note that PEP 561 also allows for *stub files* to be packaged with a `py.typed` marker and distributed separately from the main package - this is for example what [PyQt5-stubs](https://pypi.org/project/PyQt5-stubs/) does.

**Comment by erictraut** [comment]
Thanks for pointing that out, @The-Compiler. Yes, PEP 561 allows stub files to be distributed "inline" (shipped with the package) or as a separate stub package (named the same as the package but with "-stubs" appended to it). Pyright will find and use inline stubs and stub packages, and it does this regardless of whether the package contains a `py.typed` marker.

**Comment by russelldavis** [comment]
> Perhaps I'm not fully appreciating what you mean by "weeding out bad types"

I was thinking of the [docs](https://github.com/microsoft/pyright/blob/master/docs/settings.md) for `useLibraryCodeForTypes` that say it "may result in poor-quality type information". I had interpreted that to mean that poor quality types were a reason to avoid using the option (and hence there might be cases where they'd be worse than no types at all).

Having read your response, I see I misinterpreted it. I think it'd be clearer if instead it said something like "We recommend creating stubs rather than using the types in libraries, which are usually lower-quality and incomplete."

With that resolved, the case for my proposal is less compelling. But for completeness: there would still be value in avoiding the significant overhead (mentioned in the docs) for all the libraries that aren't `py.typed`.

You could argue that choosing `py.typed` libraries for this seems somewhat arbitrary (and indeed, it would also make sense to allow opting into or out of types for arbitrary libraries). But `py.typed` libraries should have better types, so their value to cost ratio should be higher (they may even have lower overhead if less inference is necessary?)

Anyway, with my new understanding, it's certainly less of an issue, so I'm happy to let it rest.
