### ISSUE TITLE
Question: how to use `pyre_extensions.ParameterSpecification` (PEP 612)

### ISSUE THREAD

**Issue by Congee** [microsoft/pyright#855]
`typing.ParameterSpecification` is not available until 3.9. I'm trying to get it work with the library pyre_extensions which you seem to have covered here.
https://github.com/microsoft/pyright/blob/150971c55ce67100b1b5ea89b653c9bc6e232717/client/typeshed-fallback/third_party/2and3/pyre_extensions.pyi#L1-L7

And it is tested here.
https://github.com/microsoft/pyright/blob/4ee7261b69987605ed33a1a66446f4d315c0cf77/server/src/tests/samples/paramSpec3.py#L5

I don't understand why I get an error since you have already [implementd](https://github.com/microsoft/pyright/issues/654) PEP 612.
![image](https://user-images.githubusercontent.com/2083950/87863502-6abf8580-c929-11ea-9628-bba469e56215.png)

Did I miss anything?

I'm using coc-pyright with pyright 1.1.53

**Comment by erictraut** [comment]
Pyright doesn't know anything about pyre_extensions, which is specific to the pyre type checker. That explains why you're not seeing the behavior you're expecting.

I did add support for ParameterSpecification in Pyright in anticipation of this functionality being included in Python 3.9. Unfortunately, it appears that PEP 612 has not yet been ratified, which means it's unlikely to make it into Python 3.9 and will need to wait until 3.10. That's why it hasn't yet appeared in the official typing.pyi in typeshed.

The version of typing.pyi that currently ships with Pyright deviates slightly from the version that's checked into typeshed. It includes the following addition:

```
if sys.version_info >= (3, 9):
    class ParameterSpecification:
        args: Any = ...
        kwargs: Any = ...

        def __init__(self, name: str): ...
```

The version of typing.pyi that currently ships with Pylance does not contain this addition, since we're trying to stick with stock typehshed stubs for Pylance.

I will likely remove the above code in an upcoming version of Pyright now that it has become clear that PEP 612 won't make it into Python 3.9.

If you want to play with the ParameterSpecification support that's in Pyright today, you can hand-edit your typing.pyi file to include the above block. Just note that your modifications will get overwritten the next time Pyright or Pylance are updated.

**Comment by Congee** [comment]
Thank you!

**Comment by layday** [comment]
Also note that the PEP was revised last month with the addition of `Concatenate` and with `ParameterSpecification`  shortened to `ParamSpec` (https://github.com/python/peps/pull/1424).

**Comment by charmoniumQ** [comment]
Unfortunately, stubbing out `ParamSpec` doesn't work with `Generic`. It yields this error at runtime: `TypeError: Parameters to generic types must be types.`. Unfortunately, I don't understand how metaclasses work in Python, so I can't figure out how to adapt your snippet to be a type.

Is there any backwards-compatible way to use `ParamSpec`?

Minimal (not) working example:
```
from typing import Generic, Any

class ParamSpec:
    def __init__(self, name: str): ...
    args: Any = ...
    kwargs: Any = ...

P = ParamSpec("P")
class CallP(Generic[P]):
    ...
```

**Comment by erictraut** [comment]
I can't tell what you're trying to do here. Perhaps you could post a more detailed question in the Discussions, and we'll try to help you out.

**Comment by charmoniumQ** [comment]
For posterity's sake, [here's ](https://github.com/microsoft/pyright/discussions/1763) the follow-up.
