### ISSUE TITLE
Addition of Literal[T] is assigned to LiteralString in loop

### ISSUE THREAD

**Issue by Etienne-Leveque** [microsoft/pyright#8551]
**Describe the bug**
Pyright can build a new Literal from the addition of literals, but in for loops, the addition of literals results in a LiteralString. I would expect the same behavior.

**Code or Screenshots**
```python
from typing import Literal

Foobar = Literal["foobar"]

foobar: Foobar = "foo" + "bar"
# ok

for _ in range(2):
    _foobar: Foobar = "foo" + "bar"
    # Expression of type "LiteralString" is incompatible with declared type "Foobar"
    # "LiteralString" is incompatible with type "Foobar"Pylance[reportAssignmentType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportAssignmentType)
```

**VS Code extension or command-line**
pyright 1.1.373 (cli)

**Comment by erictraut** [comment]
The current behavior is by design, so I don't consider this a bug. I'm going to change this from a bug report to an enhancement request and consider it in that light.

Pyright's "literal math" type evaluation behavior is currently not performed inside loops because it's impossible in the general case to determine (statically) whether it's safe to do so. Consider the following:

```python
x = "a"
y = ""

for _ in range(10):
    x = y + "b"
    y = x
```

For comparison, mypy doesn't support literal math except for `Final` variable assignments. It therefore flags `foobar: Foobar = "foo" + "bar"` as an error in your code.

It's possible that in certain constrained cases, such as in your example where the resulting value is being assigned back to a variable with a declared literal type, it could be made safe. I'll give this some thought. If it can be made safe, then the next question is whether this is a good investment. Perhaps you could provide more context for what you're trying to do here? I'm guessing that your real code is more complex than the minimal sample implies. In the example, it would be trivial to pull the `_foobar: Foobar = "foo" + "bar"` statement outside of the loop.

**Comment by erictraut** [comment]
I've investigated this further and convinced myself that pyright cannot safely do literal math inference within a loop, therefore the current behavior will remain.

I've added [documentation for this feature](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=literal-math-inference) that spells out its limitations.

**Comment by Etienne-Leveque** [comment]
Thank you for the explanation, indeed the real code is more complex but the workaround is simple, just a bit more verbose.
