### ISSUE TITLE
Duplicative import sometimes causes `reportInvalidTypeForm`

### ISSUE THREAD

**Issue by RobertCraigie** [microsoft/pyright#8616]
**Describe the bug**

Unfortunately I can't come up with a minimal reproduction as this setup doesn't reproduce the issue surprisingly:
<details>
<summary>Repro attempt</summary>

```py
# __init__.py
from .bar import BenefitFrequency as BenefitFrequency

# bar.py
from typing import Optional
from typing_extensions import Literal

BenefitFrequency = Optional[Literal["one_time", "every_paycheck", "monthly"]]

# foo.py
from . import BenefitFrequency
from .bar import BenefitFrequency

def method(frequency: BenefitFrequency) -> None:
    raise NotImplementedError()
```

</details>

In this [source code](https://github.com/Finch-API/finch-api-python/blob/main/src/finch/resources/hris/benefits/benefits.py) the [`BenefitFrequency`](https://github.com/Finch-API/finch-api-python/blob/main/src/finch/types/hris/benefit_frequency.py) type is imported twice - [1](https://github.com/Finch-API/finch-api-python/blob/f20594d6dbf12947d46f776b21a791dc285a9b3f/src/finch/resources/hris/benefits/benefits.py#L27) & [2](https://github.com/Finch-API/finch-api-python/blob/f20594d6dbf12947d46f776b21a791dc285a9b3f/src/finch/resources/hris/benefits/benefits.py#L31).

```py
BenefitFrequency = Optional[Literal["one_time", "every_paycheck", "monthly"]]

#

from ....types.hris import BenefitFrequency
from ....types.hris.benefit_frequency import BenefitFrequency
```

Which then causes errors like this
```
finch-python/src/finch/resources/hris/benefits/benefits.py
  finch-python/src/finch/resources/hris/benefits/benefits.py:56:9 - error: Type of parameter "frequency" is partially unknown
    Parameter type is "Unknown | NotGiven | None" (reportUnknownParameterType)
  finch-python/src/finch/resources/hris/benefits/benefits.py:56:29 - error: Variable not allowed in type expression (reportInvalidTypeForm)
```

Removing one of either of the two imports fixes the errors.

I totally appreciate how this code just shouldn't be importing the type twice & we'll fix that but I thought I'd report this behaviour here in case it's indicative of a bug in the pyright internals.

**VS Code extension or command-line**

The last CLI version that type checked this code successfully was `v1.1.366`, I can't determine the exact version when this started reporting errors as certain subsequent versions crash.

**Comment by erictraut** [comment]
This situation is dependent on two conditions:
1. The symbol is imported twice, effectively assigning a value to the local symbol `BenefitFrequency` twice.
2. The imported symbol is an old-style (PEP 484) type alias that doesn't use `typing.TypeAlias` (introduced in PEP 613) or the `type` keyword (introduced in PEP 695) to unambiguously indicate that the symbol is intended to be a type alias. These old-style type aliases are ambiguous because they use the same syntactic form as a variable assignment. Type checkers therefore need to fall back on some heuristics to determine whether to treat such a symbol as a variable or a type alias. These heuristics are currently unspecified, although I'm hoping that the final version of [PEP 747](https://peps.python.org/pep-0747/) may help here. One aspect of this heuristic is that the symbol can be assigned only once. In your example, it's effectively being assigned twice to the local `BenefitFrequency` symbol, which means that it's treated as a variable and not a type alias.

I think pyright's behavior is therefore correct, or at least defensible and internally consistent.

I recommend moving away from old-style type aliases and adopting `TypeAlias` or the `type` keyword if that's feasible.

You mentioned that you're seeing a crash in subsequent versions of pyright. If you're seeing this with the latest version, let me know and I'll investigate.
