### ISSUE TITLE
Hint on method of class is not aware of the class

### ISSUE THREAD

**Issue by tymokvo** [microsoft/pyright#8859]
**Describe the bug**
When annotating a method of a class with the type of that class, `pyright` returns [`reportUndefinedVariable`](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUndefinedVariable). However, the type hint within the constructor works as expected, and without a type hint, `pylance` infers the correct type.

**Code or Screenshots**
```python
class A:
    def __init__(self, a=None) -> None:
        self.a: A | None = a

    def get_a(self) -> A: # error
        if self.a:
            return self.a
        else:
            raise Exception()
```
With `pylance` in VSCode the behavior is a bit odd:

With the type hint, it becomes an error:
![image](https://github.com/user-attachments/assets/b9eafabb-f2cd-41c1-a881-87219af65e85)

Without the type hint, `pylance` infers the type as expected:
![image](https://github.com/user-attachments/assets/e2321247-60fc-47f6-a6b0-5e0d19270f8a)

**VS Code extension or command-line**
- VSCode via `pylance@2024.8.2` (see above)
- CLI `1.1.378`

**Comment by erictraut** [comment]
Pyright's behavior here is correct; this isn't a bug.

If you attempt to run the above code in the Python interpreter, you'll see that it crashes because `A` isn't defined.

You can fix this in your code by doing one of the following:
1. Enclose the return type annotation `A` in quotes, which tells static type checkers to treat it as a forward reference. For more details, refer to [this part](https://typing.readthedocs.io/en/latest/spec/annotations.html#string-annotations) Python typing spec.
2. Add a `from __future__ import annotations` to the top of your file. This tells the Python runtime to defer evaluation of type annotations avoiding this crash.

**Comment by tymokvo** [comment]
Got it, thank you1

**Comment by 9en9i** [comment]
@erictraut 
It seems that this is now relevant with the release of Python 3.14. I have some code that does not pass pyright validation:
```python
class Foo:
    def bar(self, foo: Foo) -> Foo:
        return foo


f = Foo()
f.bar(f)
```

I get two errors on the second line:
`error: "Foo" is not defined (reportUndefinedVariable)`
