### ISSUE TITLE
Incorrect `@overload` overlaps detection with `TypeVar(infer_variance=True)`

### ISSUE THREAD

**Issue by minmax** [microsoft/pyright#8860]
pyright 1.1.378

After upgrading from version 377, `pyright` found 1 error in my codebase, but I think it's a bug.

```python
from typing import Generic
from typing import Literal
from typing import Protocol
from typing import overload

from typing_extensions import TypeVar


T = TypeVar("T")

T_infer = TypeVar("T_infer", infer_variance=True)


class Field(Generic[T]):
    pass


class TypedEnumFieldProtocol(Protocol[T_infer]):
    # Overload 1 for "__new__" overlaps overload 2
    # and returns an incompatible type (reportOverlappingOverload)

    @overload
    def __new__(cls, null: Literal[False] = ...) -> Field[T_infer]: ...

    @overload
    def __new__(cls, null: Literal[True] = ...) -> Field[T_infer | None]: ...
```

If i add `infer_variance=True` to `T`, the error will go away.

**Comment by erictraut** [comment]
The new behavior that you're seeing is correct. The reason you didn't see it previously was because of a bug in older versions of pyright.

The problem here is that you have overlapping overloads that return incompatible types. If you were to call the `__new__` function with no arguments, you would match both overloads because they both have a default argument. But both overloads return incompatible types if the type parameter `T` is invariant. If `T` is covariant (which is what will be computed if you add `infer_variance=True`), then `Field[T_infer | None]` is a subtype of `Field[T_infer]`. This makes the overlapping overloads type safe.

You can fix the overlapping overload in your code by removing the `= ...` in the second overload.

**Comment by minmax** [comment]
The error also goes away if I swap the methods (I don't think I understand why, but I'm ok).
```python
    @overload
    def __new__(cls, null: Literal[True] = ...) -> Field[T_infer | None]: ...

    @overload
    def __new__(cls, null: Literal[False] = ...) -> Field[T_infer]: ...
```

Unfortunately I can't remove the default value because there are other preceding kreyword-only arguments in the real class.

```python
def __new__(cls, name: str | None = None, null: Literal[True] = ...) -> Field[T_infer | None]: ...
```

For context: `Field` from example it is a minimized version of `django.db.models.fields.Field` from `django_types`.

**Comment by minmax** [comment]
I found a solution, if you add `*` before arguments, then you don't have to specify the default value for any subsequent arguments.

```python
    def __new__(
        cls,
        *,
        verbose_name: str | None = ...,
        null: Literal[True],
    ):
```
