### ISSUE TITLE
Incorrect type narrowing of TypeVar with higher-order functions

### ISSUE THREAD

**Issue by minmax** [microsoft/pyright#8912]
pyright - 1.1.379 and main (d841fb9e9165c8cb088314d595a76ac98643ce43)

```python
from typing import Protocol
from typing import TypeVar
from typing_extensions import reveal_type


T = TypeVar("T", infer_variance=True)
R = TypeVar("R", infer_variance=True)


class IO(Protocol[T, R]):
    pass


def run(a: T, convert: IO[T, R]) -> R: ...


def convert(a: int | str) -> bool: ...


result = run(1, convert=convert)

reveal_type(result)  # Type of "result" is "R@IO"
```

**Comment by minmax** [comment]
Hm, a bit unexpectedly, but if you add `__call__`, the type will be correctly narrowed as `bool`.
```python
class IO(Protocol[T, R]):
    def __call__(self, obj: T, /) -> R:
        return cast(R, obj)
```

**Comment by erictraut** [comment]
I think pyright's behavior is correct here, so I don't consider this a bug. In your top example, you've defined an empty protocol `IO`. Any type will match against this protocol because it doesn't define any attributes or methods. There's also no way for class-scoped type parameters `T` or `R` to be solved when matching against it because they don't appear in the protocol definition. 

If your intent is for `IO` to define a callable, then you need to include a `__call__` method in it, as you've done in your second code sample.
