### ISSUE TITLE
pyright isn't finding python

### ISSUE THREAD

**Issue by daltairwalter** [microsoft/pyright#895]
I see the following error regardless of what command I run:
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640

I have tried:
pyright
and
pyright --createstub alt.hst.core.hstfitext

python is in the PATH and PYTHONHOME is properly set.

**Comment by erictraut** [comment]
I'm guessing that you're running on Windows, right?

Pyright can be configured to use a specific virtual environment. When it is not configured as such, it attempts to discover the import resolution paths of the default python interpreter by executing "python3". If it receives an error when executing "python3", then it executes "python". This order is important on Linux and MacOS because "python" typically points to a Python 2.x interpreter. On Windows, "python3" is typically not present or points to a script that displays the dialog box that you're seeing.

We haven't decided yet how to deal with this difference in behaviors across platforms. We should probably just avoid executing "python3" on Windows altogether.

In the meantime, you can avoid this by creating a config file that defines points to the venv that you want to use. For details about config files, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/settings.md).

**Comment by erictraut** [comment]
@jakebailey What are your thoughts on this? Should we just skip the "python3" step on Windows?

**Comment by jakebailey** [comment]
I think it'd be an improvement to not run `python3` on Windows. Any system which has a working `python3` binary will also have `python` set to that same install. Specifically, any global install direct from python.org won't include `python3`, but virtual environments will link it, the Windows Store adds it (rather, redirects the shim), `scoop`'s install adds it. It'd also be nice to detect when the `python` binary about to be run is one of the shims that doesn't do anything, but that's harder to do.

However, I'll also say that the message is probably not "harmful". I believe the code that is checking for the python version will fail and then it will try the other binary anyway, so a further improvement would be to swallow stderr.

The version checking code has been tweaked in Pylance to deal with the differences in Python 2's version output; it would good to sync things before these paths are updated to prevent conflicts.

**Comment by erictraut** [comment]
This is addressed in Pyright 1.1.59, which I just published.
