### ISSUE TITLE
Incorrect exhaustiveness checking when value under test is an attribute

### ISSUE THREAD

**Issue by mfisher87** [microsoft/pyright#8955]
**Describe the bug**

Pyright behaves differently depending on the context when exhaustively checking all possible values of a type. When checking a class attribute, Pyright complains that a value must be returned on all code paths. When checking a function argument, Pyright correctly understands the exhaustive check.

**Code or Screenshots**

Code sample in [pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAySMApiAIYA2AsAFB0DGl5Azi1AGJhgBcdUAqABMSwKAH1xqYpIAULEpWAAaKACNyIcQDcqASj61BxqAqUA6cRq27KUALzrNOqnX6CAAgnAIy8dwIiYtbyisB6UAC0AHyExGRUANoAROTJqslqyQC6hiaCICQwAK4gKKZhltYuNPRGgkGwJCwwoUoRMXGkFJSJAIyqAEy5ASaF2iRU4vC%2BbcDm1hGCAMRdCb2p6VCZOaPGSGJm89YOjpt5%2BWNFpeV9e4KKBxUWJ-ZnWReXBddlUIP3AlWAFEQOAQDwoOYoVAIMUWlBCiVfrZiiQoGBylQ7AwwCIoAhyDAABYsNy0RrAbiyDQALwhRG6SWSDC2ySEOQ6sQZ60SAGZVAAWEb1ATjSaUaaIEjU8g0parbk9FIsjLs7KjJ6007bFmfK5I8q80aPYKy7Vs5J64yIm5QAWjVYAOTA%2BPAakoJAg5iAA)

```python
from typing import Literal

class Foo:
    def __init__(self, bar_val):
        self._bar_val = bar_val

    @property
    def bar(self) -> Literal["a", "b"]:
        return self._bar_val

    def test(self) -> Literal[1, 2]:
        reveal_type(self.bar)    # Literal["a", "b"]
        if self.bar == "a":
            return 1
        elif self.bar == "b":
            return 2
        # Error: ... must return value on all code paths

def foo(baz: Literal["c", "d"]) -> Literal[3, 4]:
    reveal_type(baz)  # Literal["c", "d"]
    if baz == "c":
        return 3
    elif baz == "d":
        return 4
    # No problem.
```

**VS Code extension or command-line**

Reproduced in Pyright playground :point_up: and at CLI with version 1.1.379

**Comment by erictraut** [comment]
Pyright is working as intended here, so I don't consider this a bug.

Exhaustion works based on type narrowing. Checks like `self.bar == 'a'` don't allow for any type narrowing. The type of `self` remains `Self` after this check. There's no type in the Python type system that describes "an instance of `Foo` where the attribute `bar` is `'a'` rather than `'b'`". 

If you want this to work without a type error, you need to make two minor changes to your code. First, you need to assign the value of `self.bar` to a local variable. Let's call it `bar`. Second, you need to declare the type of `bar`. That's because we are taking advantage of an advanced narrowing feature called "[narrowing for implied else](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=narrowing-for-implied-else)". This technique is computationally expensive in the general case, so pyright applies it only when the narrowed expression is a local variable with a declared type.

```python
    def test(self) -> Literal[1, 2]:
        bar: Literal["a", "b"] = self.bar
        if bar == "a":
            return 1
        elif bar == "b":
            return 2
```

Alternatively, you can omit the type declaration for `bar` if you remove the `elif` test. Note that I've also added an `assert_never` call here for defensive purposes. This isn't required, but it can make your code more robust.

```python
    def test(self) -> Literal[1, 2]:
        bar = self.bar
        if bar == "a":
            return 1
        else:
            return 2
        assert_never(bar)
```
