### ISSUE TITLE
pyright flagging aws cdk types as incompatible when they aren't

### ISSUE THREAD

**Issue by fraghag** [microsoft/pyright#8984]
**Describe the bug**
pylance gives false incompatible type errors for many classes. My example below gives this error:

```
error: Argument of type "list[AccountPrincipal]" cannot be assigned to parameter "principals" of type "Sequence[IPrincipal] | None" in function "__init__"
    Type "list[AccountPrincipal]" is not assignable to type "Sequence[IPrincipal] | None"
      "list[AccountPrincipal]" is not assignable to "Sequence[IPrincipal]"
        Type parameter "_T_co@Sequence" is covariant, but "AccountPrincipal" is not a subtype of "IPrincipal"
          "AccountPrincipal" is incompatible with protocol "IPrincipal"
            "IPrincipal" is not assignable to "AccountPrincipal"
            "IPrincipal" is not assignable to "AccountPrincipal"
            "IPrincipal" is not assignable to "AccountPrincipal"
            "add_to_principal_policy" is an incompatible type (reportArgumentType)
```

I know the classes in aws_cdk are convoluted but I base my statement that pylance is wrong on the fact that the code runs without a problem and neither pycharm or mypy flags this as an error.

**Code**
```python
from aws_cdk import aws_iam as iam


iam.PolicyStatement(
    sid="some sid",
    effect=iam.Effect.ALLOW,
    actions=[],
    resources=[],
    principals=[iam.AccountPrincipal("123456789012")],
)
```

Packages:
aws-cdk-lib==2.158.0
pyright==1.1.380

**VS Code extension or command-line**
I get this error both in vscode and when running pyright from bash in wsl.

**Comment by erictraut** [comment]
Pyright's behavior is correct here.

The problem is that the class `AccountPrincipal` is not compatible with the protocol `IPrincipal`. Both classes define a method called `add_to_principal_policy`, but the signatures don't match. One contains a parameter named `statement` and the other `_statement`. This code will run fine if no one attempts to call this method with a keyword argument. It would crash if someone attempted to do this.

Pyright's behavior here is conformant with the [Python typing spec](https://typing.readthedocs.io/en/latest/spec/callables.html#assignment) whereas mypy's is not. Mypy's behavior in this case has been noted in the official [conformance tests](https://htmlpreview.github.io/?https://github.com/python/typing/blob/main/conformance/results/results.html). It has also been reported as a bug several times in the mypy issue tracker, but it hasn't been fixed yet.

I'm guessing that this difference in the `add_to_principal_policy` signature is unintended in the AWS library. I recommend reporting the issue to the maintainers of this library.

You might also want to report the issue to JetBrains for PyCharm.
