### ISSUE TITLE
`assignFromUnionType` gets fixated on type var constraints from first (after sorting) union subtype

### ISSUE THREAD

**Issue by ahmed-mahran** [microsoft/pyright#9010]
**Describe the bug**
`assignFromUnionType` gets fixated on type var constraints from first (after sorting) union subtype. 

**Code or Screenshots**

```python
def produce_union[T1, T2](t1: T1, t2: T2) -> Tuple[T1, T2] | Tuple[T1]: ...
def consume_union[*Ts](ts: Tuple[*Ts]): ...

_x = produce_union(1, 'a')
consume_union(_x) # Error
# Argument of type "Tuple[int, str] | Tuple[int]" cannot be assigned to parameter "ts" of type "Tuple[*Ts@consume_union]" in function "consume_union"
#   Type "Tuple[int, str] | Tuple[int]" is not assignable to type "Tuple[int, str]"
#     "Tuple[int]" is not assignable to "Tuple[int, str]"
#       Tuple size mismatch; expected 2 but received 1

# Both subtypes are accepted separately
def produce_union_subtype_1[T1, T2](t1: T1, t2: T2) -> Tuple[T1, T2]: ...
def produce_union_subtype_2[T1](t1: T1) -> Tuple[T1]: ...

consume_union(produce_union_subtype_1(1, 'a')) # OK
consume_union(produce_union_subtype_2(1)) # OK

if 1==1:
  a = (produce_union_subtype_1(1, 'a'))
else:
  a = (produce_union_subtype_2(1))
reveal_type(a) # Tuple[int, str] | Tuple[int]
consume_union(a) # Error
# Argument of type "Tuple[int, str] | Tuple[int]" cannot be assigned to parameter "ts" of type "Tuple[*Ts@consume_union]" in function "consume_union"
#   Type "Tuple[int, str] | Tuple[int]" is not assignable to type "Tuple[int, str]"
#     "Tuple[int]" is not assignable to "Tuple[int, str]"
#       Tuple size mismatch; expected 2 but received 1
```

**Comment by ahmed-mahran** [comment]
I'd like to contribute a fix that I've tried locally. It is based on combining bounds tracked by `ConstraintTracker` and `ConstraintSet`.

**Comment by ahmed-mahran** [comment]
Here is the patch https://github.com/ahmed-mahran/pyright/pull/1. If you agree with the approach, I can open a PR here if it is fine.

**Comment by erictraut** [comment]
Thanks for reporting the issue.

While your approach works for a narrow set of circumstances, it will not generalize well because the constraint logic you introduced doesn't take into account variance contexts, upper bounds, value constraints, TypeVarTuple rules for constraints, and various other factors. Your approach also breaks a number of other assumptions used in pyright's type evaluator. For those reasons, a different approach will be needed to address this issue.

**Comment by erictraut** [comment]
Looking at your code sample above more closely, I don't think this is a bug.

Consider the following:

```python
def consume_union1[*Ts](ts1: tuple[*Ts], ts2: tuple[*Ts]) -> tuple[*Ts]: ...

def func1(x1: tuple[int], x2: tuple[int, str]):
    reveal_type(consume_union1(x1, x2))

def consume_union2[*Ts](ts: tuple[*Ts]) -> tuple[*Ts]: ...

def func2(x: tuple[int] | tuple[int, str]):
    reveal_type(consume_union2(x))
```

The typing spec explicitly disallows the code in func1. See [this section](https://typing.readthedocs.io/en/latest/spec/generics.html#type-variable-tuple-equality) for details. I think that func2 is equivalent and is also disallowed by the same rule.

Note: I don't particularly like this rule for TypeVarTuples. It was added late in the PEP 646 drafting process, and it slipped by my review at the time. If I had noticed the edit, I would have spoken up at the time. Unfortunately, I learned about it only after the PEP had been accepted.

If you would like to champion a change to the spec, you're welcome to start a discussion in the [typing forum](https://discuss.python.org/c/typing/32).

BTW, mypy has a known bug where it does not comply with the spec here.

I'm going to close the issue since this behavior is mandated by the typing spec.
