### ISSUE TITLE
Regression in TypeAliasType where the type_param shares the name with a incompatible global variable

### ISSUE THREAD

**Issue by Daraan** [microsoft/pyright#9027]
While writing #9026 I realized a similar behavior when using TypeAliasType for Callables, which involed a type_param that has the same name as a global non ParamSpec:

Code sample in [pyright playground](https://pyright-play.net/?pyrightVersion=1.1.381&pythonVersion=3.11&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCCKcANFAMICGANtZQEbUCmZACpSJRAMoJMDGZACqImANQ5kQAVxQwsTAPr8AFgIDWDZm3Aww-MNQBQoSLESo0ipgA8YTFAGckYJ5my58IvgWpJKjt5MRkYAxFCOkEwqAO5MIExQTNSOweFo1GBaUKxQAIxGACZMwLBMjjCKCLr6ho5VSPzqzFpMABQAlABcRlB9UBlg9DQ5feHITcxQMZRyjrBgUAnA8Q78iTBqUPx0jvP0cFAoXMG9-UJQALxQQRIgbQBEQg8dIf1QAAIycgrKak2tM59HYBeasNqsGoGagAbSEAF1ulAAHSosZQAA8AFosZgUAZsJR5IxEjEkJsIicjicQuEAOKZYbUUYAJgA3FA1AkoMBcNtIAhmDAUOV9tJ8JxNvFMCAEswAG6zGBFEplCoNSbtVLUYDdIEDRkjVhsZRgE0GOScE3FYCUaTUZXvXLXdicHh8fhtADkrC9rzCUAAqiKbB77IUoAAybYqWZoJgR%2BjRSjylwgFWlezq%2BPyewQNra3U9d7hHFlnIcLhQXgCKBlnH650Vt01z0PVgvfUJeVMGiKeB8CEddGurit-X6qi0VpNoK%2BfyBUSPKd0Ekdsgr1ow42EYjwsgDpQISsQRyXCEkDqvEtQACSsBUqHUnNWoyQ81SDigAQfiUGTJyKFDByZEbjAQx5AQLpzD4bcYWDdQUDAGIUHheF9XCPJkSwgBmAAWHDoIAeQAaQw-JsORfC8IAamggBRWVcDefpgFkfh%2B1EPIrgoGhV2YVgYVQGB0JvIRwIdJAEC7Jgez7Q82jY-FOL4PJr36TDKPwwi%2BgeJSOMPPIHkweYHkPGE2mE4csQAPl3OB4QeZFyKw3C8Lw6CoD09iVKYIyTPwMzRAs6y7KIBynJcrSAA48mg8LeiitzaKgRjwBARxi36G0eXYvI2n4ehoM3NchLkRFoNRZz3n0-K6AgehCkoKAbGgtSWL6HL9JZAqit46dSrKkSKpRVF9W6tp6sa5rWvyf13i69icN64q%2BJnGE4TIKq0KRKrxqWyauGmlqyDgNrXiAA)

```python
from typing import Any, Callable, ParamSpec, TypeVar, runtime_checkable, Protocol
from typing_extensions import TypeAliasType

# somehwere else
# gloabl P 1
def test_protocols_pickleable():
    global P  # pickle wants to reference the class by name

    T = TypeVar("T")

    @runtime_checkable
    class P(Protocol[T]): ...  # <-- incompatible with same name

# Global P 2; here for completness but rather irrelevant
def test_pickle(self):
    global P, P_co, P_contra, P_default
    P = ParamSpec('P')

# Unexpected & changed behavior
def test_getitem(self):
    # ----- Param Spec -----
    P = ParamSpec("P")
    reveal_type(P)  # ParamSpec
    
    CallableP = TypeAliasType("CallableP", Callable[P, Any], type_params=(P,))
    # I think here P is seen as the global Protocol P. Tooltip: type[P[Unknown]]
    # 1.1.343: OK
    # 1.1.344+: Error

    func_type1 = CallableP[int]
    # Tooltip
    reveal_type(func_type1)
    # 1.1.343:  "func_type1" is "type[(int) -> Any]".
    # 1.1.344:  "func_type1" ist "type[() -> Any]".
    # 1.1.381: Any
 
    # 1.1.344+ Errors:
    def func1(cb: CallableP[int]): ...
    func1(lambda x: 1)

    def func2(cb: CallableP[[int]]): ...
    func2(lambda x: 1)

    def func3(cb: CallableP[[T, ...]]): ...
    func3(lambda x, y: 1)

```

**Comment by erictraut** [comment]
I don't think I understand what issue you're reporting here.

I needed to fix a bunch of issues in your code sample, but I assume those were all just typos:
* You implied that you're using Python 3.11. The `TypeAliasType` symbol isn't exported from the `typing` module in Python 3.11, so I presume you're importing it from `typing_extensions` instead.
* The expression `Callable[[P], Any]` appears in your code sample. This isn't a legal type expression. I presume you meant `Callable[P, Any]`.
* The type alias `Alt3` was defined twice. I renamed the second one `Alt4`.
* The type alias `Alt3` was defined with a mismatched name in both cases.
* The symbol `T` was not defined. I presume it is intended to be a normal TypeVar.

Using `reveal_type` on a `TypeAliasType` directly will reveal the type `TypeAliasType`, since that's the runtime type of the value.

If I make those fixes, pyright 1.1.381 doesn't report any errors, and it appears to work correctly in all cases.
Code sample in [pyright playground](https://pyright-play.net/?pythonVersion=3.11&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCCKcANFAMICGANtZQEbUCmZ5YKAxpTEyty1AAKlEJQgBlBEw5kAKoiYA1EQChQkWIlRoA%2BkwAePFAGck7Y5my588qQWpJKx20xUrZUALxQXykAAoAIllAgEoVQS8hETFJaSDBMLcqWgZmSO8Xe0dnBSCUukYmRNYaQuYAbUEyIjgAXTJ4KR0EGIhjT39q0PD7GABmKKyHJxcgvv7A0tSiqpriBs1m1tF2zu7e6hgAFiGFbNG8wL7tqYoytKYKtk5%2BPh4qxdrFpqYWto6ukh63ABMmYBQYAAV04AEZ-Bx6AAuc4zdIVVAwOqhWEAOgxalBHAhdAg9F%2BlCg%2BlhYPCKn%2BgJBnAATJCYXDysUKoiUMiUejMdSOHS8QSiSSoGS-gCgdj%2BvTYQVLoIWbIyBi0XUOVBFVjOBK%2BYTiWQ4KTwkA)

```python
from typing import Any, Callable, Concatenate, ParamSpec, TypeVar
from typing_extensions import TypeAliasType

T = TypeVar("T")
P = ParamSpec("P")

CallableP = TypeAliasType("CallableP", Callable[P, Any], type_params=(P,))
Alt3 = TypeAliasType("Alt3", Callable[P, Any], type_params=(P,))
Alt4 = TypeAliasType("Alt4", Callable[Concatenate[P], Any], type_params=(P,))

def func1(cb: CallableP[int]): ...
func1(lambda x: 1)

def func2(cb: CallableP[[int]]): ...
func2(lambda x: 1)

def func3(cb: CallableP[[T, ...]]): ...
func3(lambda x, y: 1)

```

Perhaps I'm misunderstanding what issue you're seeing. Could you provide another specific code sample that clearly demonstrates a behavior that you think is incorrect and specify what behavior you think it should exhibit instead?

**Comment by Daraan** [comment]
First, I am very sorry for opening an issue that was incomplete and not properly tested. Thank you very much for the reply and the time you've spent on this.

I did not properly sandbox the code sample to a minimal repro in another file to showcase the error. With your clean example I now see real cause of the issue I am facing.
There are two crucial differences, the definition happens inside a function (a parallel to https://github.com/microsoft/pyright/issues/9026) AND there exists a `global P` expression somehwere else where `P` is not a ParamSpec. In my case pyright use the global `P` for the `TypeAliasType` statement instead of the local `P = ParamSpec("P")`

I've updated the code sample and changed the title to express this now. Thank you once again.

**Comment by erictraut** [comment]
Thanks for the code corrections.

There are a couple of problems that I see in your code.

First, you are allocating a `ParamSpec` and a `TypeAliasType` as local variables. These objects are not designed to be used as local variables. The typing spec explicitly prohibits type aliases from being defined within a function body. If you try to use the Python 3.12 `type` statement to define the type alias rather than calling the underlying `TypeAliasType` constructor, pyright will emit an error indicating that type aliases must be allocated within a class or global scope only. While it's possible to call the `TypeAliasType` constructor within other contexts, a type checker will probably not treat it as a valid type alias in those contexts.

Second, the evaluation of a type expression in a `TypeAliasType` is deferred until it is used. This allows for forward declarations and recursive type alias definitions. When the expression is eventually evaluated, it will use the global scope to resolve any symbols referenced in this type expression. This makes sense because type aliases are intended to be defined in the global scope. Pyright is modeling this behavior and resolving `P` to the global scope.

I recommend moving your `TypeVar`, `ParamSpec`, and `TypeAliasType` allocations to the global scope. This is how these are meant to be used. If you do this, your code should work fine.

I'm going to close this issue because I think pyright is behaving correctly in this case.
