### ISSUE TITLE
Option to run type completeness check (`--verifytypes`) on packages that don't have a `py.typed` marker yet

### ISSUE THREAD

**Issue by smheidrich** [microsoft/pyright#9044]
**Is your feature request related to a problem? Please describe.**
When running Pyright with `--verifytypes some_package` and there is no `py.typed` marker present in `some_package`, Pyright fails with `error: No py.typed file found`. That makes sense for packages which are already fully- or mostly-typed and hence had a `py.typed` marker added already. But I imagine one use case for type completeness checking is to track progress or implement "ratcheting" for packages that have no, few, or broken type hints so far and therefore shouldn't have a `py.typed` marker quite yet.

Obviously, users can already trivially work around this by writing a script that adds `py.typed` for the duration of the check (for checks that run in CI, they don't even have to remove it again when done). But that seems kind of hacky, so I'm wondering if it wouldn't make more sense to address the root cause in Pyright itself.

**Describe the solution you’d like**
There are several ways this could be implemented. Some options:

1. If `py.typed` is missing, Pyright only prints a warning about this but otherwise proceeds with type completeness checking as normal.
2. Variant of that: Pyright does fail with an error if `py.typed` is missing, but only _after_ performing completeness checking.
3. Pyright gets a new config option `verifyTypesNoPyTyped` or CLI flag `--verifytypes-no-py-typed` or something like that to force it to proceed with completeness checking despite the absence of `py.typed`.

Thoughts?

**Comment by erictraut** [comment]
The reason pyright doesn't allow running `--verifytypes` on a non-py.typed package is that its rules for type evaluation are different for non-py.typed packages. In particular, py.typed packages are assumed to follow certain rules that allow a type checker to cleanly distinguish between "public" and "private" symbols, whereas non-py.typed packages do not. The `--verifytypes` command uses the py.typed rules to verify that all public symbols are typed. If it cannot accurately distinguish between public and private symbols, then its results will be misleading. For that reason, I'm reluctant to add the feature you're requesting. I think it's better to force a pyright user to explicitly add a "py.typed" marker so they are aware of what they're doing here rather than allowing them to run a command that is going to give them incorrect and misleading results.

**Comment by smheidrich** [comment]
I see, thank you for the explanation!
