### ISSUE TITLE
Pyright not using venvPath.

### ISSUE THREAD

**Issue by Frusadev** [microsoft/pyright#9091]
So everything was fine yesterday in the morning until i updated the plugins, venvPath, or other things similar like pythonPath, don't work as expected anymore.

For instance i could set `venvPath` to be `".venv"` and still get import errors. Even though the packages are installed. I can run the code, but in the editor, Pyright shows errors.
I'm encountering this issue in VSCode and in Neovim.

Here are some screenshots:

- sqlalchemy is installed but not detected by pyright
![In code](https://github.com/user-attachments/assets/4f0ea9df-9a06-4cc8-b2a4-2c43fbde345f)

- pyrightconfig.json
![Screenshot from 2024-09-26 14-20-38](https://github.com/user-attachments/assets/cd677cd4-f461-4721-bbe8-ee22f3a563cb)

With pylance, there are no errors:
![Pylance](https://github.com/user-attachments/assets/67b7fcb1-bcdf-421a-9c1e-9361b961ae8c)

**Comment by erictraut** [comment]
I don't recall any changes in the recent past to pyright's handling of `venv` and `venvPath`. Which version of pyright were you updating from, and which version are you running now?

The `venv` and `venvPath` configuration mechanism is not recommend, by the way. This mechanism is fragile because of the way it works. It needs to make assumptions about the layout of a virtual environment, and these assumptions are sometimes violated on some platforms and versions. It's possible that you're hitting one of those fragility issues. For this reason, I recommend moving away from this config mechanism to `pythonPath`. 

If you'd like me to investigate this issue further, I'll need more than just a few screen shots. I'll need a set of repro steps.

**Comment by Frusadev** [comment]
I'm currently using version 1.1.382 of Pyright. 
This is how things are after i remove the "venvPath" field from the config:

![Config](https://github.com/user-attachments/assets/17a64413-2876-4bb8-bb59-2f3d3e63ff1a)
![db.py](https://github.com/user-attachments/assets/35d8cc6f-00e4-4a69-84fb-edab39c5ccd2)
