### ISSUE TITLE
Wrong type deduction in union of tuples

### ISSUE THREAD

**Issue by Zaikaba** [microsoft/pyright#9113]
## Environment data

-   Language Server version: 2024.9.2
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.12.5 ( conda )
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

## Code Snippet

```python
def float_to_str( v: float ) -> str:
    return str( v )

def int_to_str( v: int ) -> str:
    return str( v )

def str_to_str( v: str ) -> str:
    return v

def stringify1( args: tuple[ float, float ] | tuple[ int, str ] ) -> str:

    if isinstance( args[ 0 ], float ):
        p = [ float_to_str( args[ 0 ] ), float_to_str( args[ 1 ] ) ] # Type "float | str" is not assignable to type "float"
    else:
        p = [ int_to_str( args[ 0 ] ), str_to_str( args[ 1 ] ) ] # Type "float | str" is not assignable to type "str"
    return str( p )

def stringify2( args: tuple[ float, float ] | tuple[ int, str ] ) -> str:

    if isinstance( args[ 0 ], float ) and isinstance( args[ 1 ], float ):
        p = [ float_to_str( args[ 0 ] ), float_to_str( args[ 1 ] ) ]
    else:
        # Type "int | float" is not assignable to type "int", Type "float | str | int" is not assignable to type "str"
        p = [ int_to_str( args[ 0 ] ), str_to_str( args[ 1 ] ) ]
    return str( p )

```
![error 2](https://github.com/user-attachments/assets/6ce6d390-6828-424a-b862-6add7a9abeab)

## Expected behavior

Type check should conclude that args: tuple[ float, float ] in if suite 1, and tuple[ int, str ] in if suite 2 of stringify1 and stringify2.

## Actual behavior

Type check fails as indicated in code.

## Logs

```

```

**Comment by erictraut** [comment]
Pyright is working as intended here, so I don't consider this a bug.

In your first example, you're using a type guard pattern that pyright doesn't support. For a full list of supported type guard patterns, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards). You're using a type guard pattern of `isinstance(x[I], T)` where `x` is a tuple, and you're expecting `x` to be narrowed based on the results of the `isinstance` call. This is a pretty complex type guard to evaluate, so it shouldn't be surprising that a static type checker might not support it. For comparison, mypy also doesn't support this. It would be theoretically possible to add such support, but it's unlikely that we'd do this unless there was strong signal from pyright users that this was a common usage pattern. As far as I can recall, this is the first time anyone has requested support for this pattern, so we haven't seen this signal.

In your second example, you are using a supported type guard pattern of `isinstance(x, T)` where `x` is the expression to be narrowed. In this case, the target expression is `args[0]`. 

I'm going to simplify your second case to attempt to explain the results you're seeing:

```python
def get_condition() -> bool: ...

def func(x: float):
    if isinstance(x, float) and get_condition():
        reveal_type(x) # float
    else:
        reveal_type(x) # float | int
```

Here I've replaced the expression `args[0]` with a simpler expression `x` which has an annotated type of `float`. I've also replaced the second part of the `and` statement with a `get_condition()` call to highlight the point that this expression does not include the subexpression `x`, just as the expression `isinstance(args[1], float)` in your code example does not include the subexpression `args[0]`.

In the Python type system, when `float` is used in a type annotation, it implies `float | int`. (See [this section of the typing spec](https://typing.readthedocs.io/en/latest/spec/special-types.html#special-cases-for-float-and-complex) for details.) This means the `isinstance(x, float)` check narrows the type of `x` to `float` in the positive ("if") branch. It cannot narrow `x` to just `int` in the negative ("else") branch here because of the presence of the `get_condition()` check, which could evaluate to either True or False.

Not surprisingly, mypy evaluates the same types for your second example as well.
