### ISSUE TITLE
Type narrowing for tuples

### ISSUE THREAD

**Issue by tkukushkin** [microsoft/pyright#9142]
Hello! Consider such code:

```python
import logging
from typing import assert_type

def foo(record: logging.LogRecord):
    if not record.exc_info:
        return
    if record.exc_info[0]:
        assert_type(record.exc_info[0], type[BaseException])  # ok
        assert_type(record.exc_info[1], BaseException)  # assert_type" mismatch: expected "BaseException" but received "BaseException | None"  (reportAssertTypeFailure)
    if record.exc_info[0] is not None:
        assert_type(record.exc_info[1], BaseException)  # ok
```

`exc_info` has type `tuple[type[BaseException], BaseException, TracebackType | None] | tuple[None, None, None] | None`

It's strange that it works with `is not None`, but doesn't work without it. And at the same time it works like expected with `record.exc_info[0]` in all cases but doesn't with record.exc_info[1].

Mypy works like expected in all cases.

**Comment by erictraut** [comment]
Pyright doesn't currently support this type guard pattern. (You probably knew this since you filed an enhancement request, but I mention this for others who might come across this issue.) The full list of type guard patterns supported by pyright can be found in [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards).

The statement `if record.exec_info[0]:` employs the `x` (truthy/falsey) type guard. This narrows the type of the `record.exec_info[0]` expression, but it doesn't narrow `record.exec_info`.

Pyright does support the type guard pattern `x[I] is None` where `x` is a union of tuples. In this case, it will narrow the type of `x`. You can leverage this type guard pattern by modifying your code to add `is not None` to the end of your check. I find that adding `is None` or `is not None` in cases like this is preferable anyway, since it avoids subtle bugs with truthy/falsey checks (such as empty lists or zero values).

The `x[I]` pattern could theoretically be extended to support this form of narrowing with a simple truthy/falsey test rather than requiring `is None` or `is not None`, but this would require additional custom logic and would likely have a performance impact on type analysis, especially in untyped code. We do occasionally add support for new type narrowing patterns but only if there's strong evidence that it's a commonly-used pattern. And even then, it's important that the performance tradeoff is worth it.

The fact that mypy supports this case provides some evidence that this is a commonly-used pattern, but I'd want to see additional signal in the form of upvotes from pyright users before adding such support.

In the meantime, there's a simple workaround — simply add `is None` or `is not None` to your condition expression.

I'm going to reject this enhancement request for now, but I'm willing to revisit it in the future if we get additional signal.
