### ISSUE TITLE
Python 3.9 from MS Store, Alternative syntax for unions requires Python 3.9 or newer

### ISSUE THREAD

**Issue by yedhrab** [microsoft/pyright#918]
I have downloaded Python 3.9 Beta from MS Store but VS Code Pyright gives these warning
![image](https://user-images.githubusercontent.com/49655146/89525283-9c23c680-d7ee-11ea-8969-015729da09f0.png)

![image](https://user-images.githubusercontent.com/49655146/89525443-e311bc00-d7ee-11ea-9a7b-03e49bfd0dc7.png)

**Comment by erictraut** [comment]
Thanks for reporting this. Unfortunately, [PEP 604](https://www.python.org/dev/peps/pep-0604/), which was slated to go into Python 3.9, wasn't ratified in time. So now this functionality has moved into Python 3.10. I recently changed the logic in Pyright to check for 3.10 instead of 3.9 for this feature, but I forgot to update the error message. It should say "3.10".

The corrected error message will be in the next version of Pyright and Pylance.

**Comment by erictraut** [comment]
This is now addressed in Pyright 1.1.61, which I just published. It will also be in the next release of Pylance.
