### ISSUE TITLE
Pyright ignores restriction on generic type constraint when using isinstance with a generic class conforming to a protocol

### ISSUE THREAD

**Issue by superlopuh** [microsoft/pyright#9202]
**Describe the bug**
When a checking whether a value conforming to a generic protocol with a type parameter is an instance of a generic class, it ignores whether the requirement of the type variable can be satisfied by the protocol type parameter.

**Code or Screenshots**
```python
from collections.abc import Iterable
from typing import Generic, TypeVar


class Base: ...


class IntWrapper(Base):
    def __init__(self, val: int) -> None:
        self.val = val


BaseT = TypeVar("BaseT", bound=Base)


class BaseIterable(Generic[BaseT], Iterable[BaseT]):
    def __init__(self, it: Iterable[int]) -> None: ...


def func(it: BaseIterable[BaseT] | Iterable[int]) -> BaseIterable[BaseT]:
    if isinstance(it, BaseIterable):
        return it # incorrectly typed as BaseIterable[BaseT@func] | BaseIterable[int], raises error
    else:
        return BaseIterable(it)
```

**VS Code extension or command-line**
Current VSCode and pyright 1.1.384

**Comment by erictraut** [comment]
Please confirm that you're seeing a narrowed type of `BaseIterable[BaseT@func] | BaseIterable[int]`. I'm not able to repro that behavior with the latest version (1.1.384). I'm seeing a narrowed type of `BaseIterable[BaseT@func] | BaseIterable[Unknown]` and no type error.

Code sample in [pyright playground](https://pyright-play.net/?enableExperimentalFeatures=true&code=GYJw9gtgBAxmA28CmMAuBLMA7AzgOgEMAjGKdCABzBFSgElUkRjkAoUSKVATwvSwDmZStVoBxJFiboYAGigAVXkgBqBEK00x4BHDigAhXUgBcUPBc2ttu-XSyoA6swoUmACiM4kAShOsoQKgAEyRgKAB9CP50VCj3b3hgeQA3AngzflQfKABaAD4oADlsUwCgisTgPDT4KABeKFqrLyQFBsVlNRB3ACJWhV75IjAAVyxg%2BtafKxs9Q2MGJhYkdwkpEBkAbQGAXXkl5iJkHeMFXb9ywNDwqJi4iISkJPlYs0OVrayLvMKSqTMFjwVhuUGA4xg7jeC28H2OSFO3nOUAAPvRGEcTt8cgUYUg4Sc9v4KuhwugcPwcKgCFgYKtYvJWgTfMSKkEQEgUkh0hEeG4odkrmyOahRiAsGRUELnt5WWyoCKxRKmRiVgKZkA)

I'm guessing that you're using an older version of pyright because I fixed a bug recently that affects this behavior.

Type narrowing behaviors are not dictated by the typing spec, so each type checker is free to implement its own algorithm. There are a variety of heuristics employed in pyright's algorithm that attempt to balance false positives and false negatives in typical use cases.

For what it's worth, mypy's type narrowing behavior matches pyright's in this particular case.

**Comment by superlopuh** [comment]
Ah yes, it's "BaseIterable[BaseT@func] | BaseIterable[Unknown]" indeed, I guess my VSCode's Pyright is outdated.

**Comment by erictraut** [comment]
Pylance (which is the default Python language server for VS Code) is based on pyright. It's typically a few versions behind. If you switch to the prerelease version of pylance, you will get a more up-to-date version.
