### ISSUE TITLE
TypeGuard not correctly narrowing types in 2024.10.1

### ISSUE THREAD

**Issue by tigerhawkvok** [microsoft/pyright#9219]
Consider:

```python
#!python3

from typing import Any, Final, TypeGuard, Union, cast
import pandas as pd
from pyspark.sql import DataFrame as DataFramePS
from pyspark.pandas.frame import DataFrame as DataFramePSPD

PANDAS_FRAME_TYPES_TUPLE:Final = (pd.DataFrame, DataFramePSPD)
PandasTypeFrame = Union[DataFramePSPD, pd.DataFrame]

def isPandasTypeFrame(frame: Any) -> TypeGuard[PandasTypeFrame]:
    return isinstance(frame, PANDAS_FRAME_TYPES_TUPLE)


randomDataFrame = cast(Union[pd.DataFrame, DataFramePSPD, DataFramePS], None)

if not isPandasTypeFrame(randomDataFrame):
    # Since this is _not_ a pandas frame, we can safely assume it is a PySpark DataFrame
    # This was working in v2024.04.01
    pandasFrame = randomDataFrame.pandas_api()
else:
    pandasFrame = randomDataFrame

```

However, note the [`TypeGuard` statement](https://docs.python.org/3.10/library/typing.html#typing.TypeGuard) is wholly ignored.

![Image](https://github.com/user-attachments/assets/b1f18e3e-6347-47e7-843a-43cd739493b6)

The first two types are impossible via the `TypeGuard`

vs-code extension, v2024.10.01

**Comment by erictraut** [comment]
Pyright is working correctly here. The `TypeGuard` mechanism does not narrow types in the negative (which is normally the "else") case. It applies only in the positive (normally the "if") case. In your code sample, you've included a `not` operator, which switches the polarity of the "if" and "else".

The behavior of `TypeGuard` has not changed in recent versions of pyright, so the fact that you are seeing different behavior between versions is probably due to something else like a configuration change or a code change.

If you switch from `TypeGuard` to `TypeIs`, you should get the behavior you're hoping to see. For more information about these special forms, refer to [this section of the typing spec](https://typing.readthedocs.io/en/latest/spec/narrowing.html).
