### ISSUE TITLE
Different result when inferring covariance of type variable

### ISSUE THREAD

**Issue by NeilGirdhar** [microsoft/pyright#9226]
Specifying covariance explicitly makes the type error disappear:
```python
from typing import Generic, TypeVar, override
from dataclasses import dataclass
T_co = TypeVar('T_co', covariant=True)


@dataclass(frozen=True)
# class CompoundDistributionInfo(Generic[T_co]): 
class CompoundDistributionInfo[T_co]:
    cls: type[T_co]

    def zeroed_instance(self) -> T_co:
        return self.cls()



class A:
    pass


class B(A):
    pass


class C:
    def f(self) -> CompoundDistributionInfo[A]:
        ...


class D(C):
    @override
    def f(self) -> CompoundDistributionInfo[B]:
        ...
```
Does Pyright take into account that the dataclass is frozen?

**Comment by erictraut** [comment]
Pyright is working as intended here, so I don't consider this a bug.

This is due to [this issue](https://github.com/python/mypy/issues/17623#issuecomment-2266312738) for which we don't yet have common agreement on a solution. If you'd like to pursue a resolution to this matter, I recommend posting to [the typing forum](https://discuss.python.org/c/typing/32). I'd like to see a clarification in the typing spec before I agree to change pyright's behavior here.

**Comment by NeilGirdhar** [comment]
Completely fair, thanks for taking the time to answer.
