### ISSUE TITLE
Function that combines two type bounds does not type-check although individual bounds do

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/pyright#9316]
**Describe the bug**
Although functions taking a generic type parameter type-check with two different type bounds, a third that combines the two type bounds does not.

**Code or Screenshots**
using `numpy==2.1.2`:

```python
from typing import Any

import numpy as np
import numpy.typing as npt

Int = np.integer[Any]
Float = np.floating[Any]

TYPE = np.float64


def f_int[N: Int](a: npt.NDArray[N]) -> npt.NDArray[TYPE]:
    return np.mean(a, 0, dtype=TYPE)


def f_float[N: Float](a: npt.NDArray[N]) -> npt.NDArray[TYPE]:
    return np.mean(a, 0, dtype=TYPE)


def f_both[N: (Int, Float)](a: npt.NDArray[N]) -> npt.NDArray[TYPE]:
    return np.mean(a, 0, dtype=TYPE)


int_array = np.array([1], dtype=np.uint8)
float_array = np.array([1.0], dtype=np.double)
print(f_int(int_array).dtype)
print(f_float(float_array).dtype)
print(f_both(int_array).dtype)
print(f_both(float_array).dtype)
```

`pyright bug.py`
```
c:\Git\bug.py
  c:\Git\bug.py:22:12 - error: No overloads for "mean" match the provided arguments (reportCallIssue)
  c:\Git\bug.py:22:20 - error: Argument of type "Array[N@f_both]" cannot be assigned to parameter "a" of type "_ArrayLikeComplex_co | _ArrayLikeObject_co" in function "mean"
    Type "Array[N@f_both]" is not assignable to type "_ArrayLikeComplex_co | _ArrayLikeObject_co"
      "ndarray[Any, dtype[N@f_both]]" is incompatible with protocol "_SupportsArray[dtype[bool] | dtype[integer[Any]] | dtype[floating[Any]] | dtype[complexfloating[Any, Any]]]"
        "__array__" is an incompatible type
          No overloaded function matches type "() -> ndarray[Any, _DType_co@_SupportsArray]"
      "ndarray[Any, dtype[N@f_both]]" is incompatible with protocol "_NestedSequence[_SupportsArray[dtype[bool] | dtype[integer[Any]] | dtype[floating[Any]] | dtype[complexfloating[Any, Any]]]]"       
        "__reversed__" is not present
        "count" is not present
        "index" is not present
    ... (reportArgumentType)
2 errors, 0 warnings, 0 informations
```

`python bug.py`
```
float64
float64
float64
float64
```

**VS Code extension or command-line**
command line

**Comment by erictraut** [comment]
Your code sample is demonstrating a difference between a type variable with an upper bound and a type variable with value constraints. Value constraints do not work the same as "multiple bounds", so you shouldn't think of them in that way.

The error you're seeing here is related to pyright's handling of overloaded calls, which is documented in detail [here](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=overloads). The `np.mean` call is overloaded, and it has different overload signatures that individually handle the `Int` and `Float` cases. However, pyright doesn't perform any sort of expansion to allow both overloads to be matched in a single call. The typing spec currently doesn't discuss type expansion or specify whether such expansion should or shouldn't be done for overloaded calls. Pyright does expand unions, but it doesn't currently expand value-constrained type vars. I've written a draft specification for this (discussed [here](https://discuss.python.org/t/draft-typing-spec-chapter-for-overloads/60788)), but it hasn't yet been agreed upon or incorporated into the typing spec. The draft proposal would *not* require (or allow) type checkers to perform expansion for value-constrained type variables, but this point is debatable.

Once there is an agreed-upon standard in this space, I'll update pyright to conform to it. Until then, I don't plan to make any changes to pyright's overload behavior because this will create churn if the final specification ends up differing from the current proposal.

In general, I recommend against using value constrained type variables. Their behaviors are not well defined by the typing spec (and therefore different [type checkers treat them differently](https://microsoft.github.io/pyright/#/mypy-comparison?id=value-constrained-type-variables)), they don't work like most people expect them to, and there are intrinsic limitations based on type checker designs and implementations. If you find yourself reaching for a value constrained type variable, I recommend looking for alternatives. There's almost always a better solution.

In this case, an overload is a more appropriate way to implement the `f_both` method.

```python
@overload
def f_both(a: npt.NDArray[Int]) -> npt.NDArray[Int]: ...
@overload
def f_both(a: npt.NDArray[Float]) -> npt.NDArray[Float]: ...
def f_both(a: npt.NDArray[Int] | npt.NDArray[Float]) -> npt.NDArray[Int] | npt.NDArray[Float]:
    return np.mean(a, 0, dtype=TYPE)
```

**Comment by bersbersbers** [comment]
Thank you for the excellent explanation.

I feel anything involving "combinations" (unions, bounds, value constraints, ...) of types is generally hard to get right "intuitively", which makes it so hard for users, type annotators and type checkers to do the same "right" thing unless it is explicitly standardized. Thank you for working towards that goal!

**Comment by bersbersbers** [comment]
By the way, I am not sure this is correct:

> The `np.mean` call is overloaded, and it has different overload signatures that individually handle the `Int` and `Float` cases.

`np.mean` has different overloads which handle complex and non-complex arguments differently; but all branches cover both `Int` and `Float`. Compare 

```python
_ArrayLikeComplex_co: TypeAlias = _DualArrayLike[
    (
        dtype[np.bool]
        | dtype[integer[Any]]
        | dtype[floating[Any]]
        | dtype[complexfloating[Any, Any]]
    ),
    bool | int | float | complex,
]

# ...

_ArrayLikeFloat_co: TypeAlias = _DualArrayLike[
    dtype[np.bool] | dtype[integer[Any]] | dtype[floating[Any]],
    bool | int | float,
]
```

This is what pylance shows as well:

![Image](https://github.com/user-attachments/assets/481f07f2-bdaf-4ce3-9434-c0810c649c96)

![Image](https://github.com/user-attachments/assets/dbee520f-b950-40a3-9309-9be49086abcf)

So IMHO, pyright should not be required to make any kind of expansion to

> allow both overloads to be matched in a single call

because it is the same overload after all.

Just pointing this out. I believe the remainder of your explanation still applies, in that pyright does not even try expanding anything so it cannot even see that the two overloads are the same.
