### ISSUE TITLE
`pyright` is not requesting workspace configuration from the client at startup; subsequently makes a bad decision

### ISSUE THREAD

**Issue by siegel** [microsoft/pyright#9329]
I am testing `pyright` for use with BBEdit as a supported LSP server for Python. During testing, `pyright` is not requesting workspace configuration from the client, even though the client explicitly specifies in its capabilities (provided during startup) that it supports workspace folders and configuration requests.

Here is an excerpt from the log (attached) of the specified capabilities:
```
    capabilities =     {
        // [irrelevant values omitted for brevity]
        workspace =         {
            applyEdit = 1;
            configuration = 1;
            workspaceEdit =             {
                documentChanges = 0;
                failureHandling = abort;
            };
            workspaceFolders = 1;
        };
    };
```

[pyright-lsp-log.txt](https://github.com/user-attachments/files/17528648/pyright-lsp-log.txt)

At no time during or after server startup does `pyright` send a `workspace/workspaceFolders` request, nor does it ever seem to send a `workspace/configuration` request.

I suspect that in the absence of any workspace configuration (which I think should be considered an error condition), the server subsequently decides to scan an inappropriate location (either `$HOME` or `/`), which leads `node` to eventually crash with an out-of-memory exception.

**Comment by erictraut** [comment]
@siegel, as we discussed by email, pyright works with dozens of other LSP clients, so it's not clear to me whether this is a pyright issue (where it's nonconformant with the protocol) or an issue in BBEdit.

You are welcome to debug the issue and submit a PR if you conclude that this is a pyright issue.

You are also welcome to file a bug in the [pylance-release](https://github.com/microsoft/pylance-release) issue tracker. The Microsoft Pylance team maintains the language server functionality in the pyright repo, and they are domain experts when it comes to the language server protocol.

I'm going to close the issue because I don't plan to take any further action at this time.
