### ISSUE TITLE
In nested negated narrowing, earlier ones are forgotten

### ISSUE THREAD

**Issue by hanwenguo** [microsoft/pyright#9395]
The following code uses two `if` statements to narrow the type of `x` from a union of 3 types to a single type, but Pyright does not follow on. It seems that it is only recognizing the most inner one `not (type(x) is bool)`, leading to the result in comment. 

```python
def f(x: str | int | bool) -> int:
    if not (type(x) is str):
        if not (type(x) is bool):
            reveal_type(x) # Pyright: Type of x is "str | int"
            return x + 1
        else:
            return 0
    else:
        return 0
```

On the other hand, in the following code without negation in conditions, Pyright knows that `x` is of empty type.

```python
def t(x: str | int | list) -> int:
    if type(x) is str:
        if type(x) is int:
            reveal_type(x) # Pyright: Type analysis indicates code is unreachable
            return x + 1
        else:
            return 0
    else:
        return 0
```

Output of `pyright --version`:
```text
pyright 1.1.387
```

**Comment by erictraut** [comment]
Pyright is working correctly here. The code in the top example is not type safe and will crash if you call it with an instance of a subclass of `str`:

```python
class MyStr(str):
    pass

f(MyStr("hi"))  # Crash
```

Pyright is able to narrow in the case of `not type(x) is bool` because `bool` cannot be subclassed. This is not true for `str` or `int`.

I recommend not using the `is` and instead using `isinstance`. It's generally more robust and type safe.

```python
def f(x: str | int | bool) -> int:
    if not isinstance(x, str):
        if not isinstance(x, bool):
            return x + 1
        else:
            return 0
    else:
        return 0
```
