### ISSUE TITLE
`assert <expression> == True` should narrow type

### ISSUE THREAD

**Issue by silverwind** [microsoft/pyright#9403]
**Describe the bug**
`assert isinstance(var, type) == True` does not narrow the type of `var` as expected. Removing the `== True` works, but I would expect both variants to narrow the type.

**Code or Screenshots**
```python
def a(var: dict | None):
  assert isinstance(var, dict) == True
  print(var.get("foo")) # error: "get" is not a known attribute of "None"

def b(var: dict | None):
  assert isinstance(var, dict)
  print(foo.get("foo")) # no error as expected
```

**VS Code extension or command-line**
pyright 1.1.388

**Comment by erictraut** [comment]
This (`isinstance(x, T) == True`) isn't a supported type guard form. For a full list of supported forms, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards).

We do occasionally add support for new forms, but each one requires specialized logic and potentially slows down type evaluation in the general case. I don't think this particular form would have a performance impact, but it would require additional custom logic. 

I personally would never append a redundant `== True`. Not only is it redundant, but it also harms code readability. I've also rarely seen this form used in practice.

I'm going to reject the enhancement request for now because I don't think this is a common form. I'm willing to revisit this decision in the future if there is signal from other pyright users that it's a feature they'd like to see supported (e.g. in the form of upvotes).

**Comment by silverwind** [comment]
> I personally would never append a redundant == True. Not only is it redundant, but it also harms code readability. I've also rarely seen this form used in practice.

I tend to use that form in unit test as it makes the code easier to read imho:

```py
assert foo("input1") == True
assert foo("input2") == False
```

Leaving out the `== True` there would make the code less easy to understand imho.
