### ISSUE TITLE
Fine-grained control over checks

### ISSUE THREAD

**Issue by tobiasdiez** [microsoft/pyright#953]
**Is your feature request related to a problem? Please describe.**
When adding typing to bigger projects, one part of the code will have some typing information while other parts have no typing information at all. Pyright already has some support of such a situation using the strict and ignore configuration paths. However, this is rather black and white: either you activate all rules for this code, or none at all. 

**Describe the solution you'd like**
Make it possible to scope the checks. So for code in `a/b` I want to apply rules A, B; and for code in `x/y` I want to apply rules X, Y.

**Comment by erictraut** [comment]
Configuration for Pyright is already very complicated. It already supports different type checking modes (basic vs strict) for specific directories, severity overrides for specific diagnostic rules within a config file, severity overrides for specific diagnostic rules within the VS Code settings, and severity overrides for specific diagnostic rules within individual files, and ignore/exclude paths for files or directories. I'm not inclined to further complicate it by adding per-directory severity overrides.

My recommendation (and this is what we do in my team's Python source base) is to define the baseline severity overrides that you want to use for your project as a whole. Then use file-level "# pyright" comments to override baseline severity levels as needed.

For example, here's a pyright comment in one of our unit test files, which is doing some gross monkey patching that violates type rules.

```
# pyright: strict, reportPrivateUsage=false, reportUnknownMemberType=false
```

If you use the VS Code extension (as opposed to the command-line version of Pyright), another option is to use a multi-root workspace and have a different pyrightconfig.json file within each root.

**Comment by tobiasdiez** [comment]
What about allowing multiple configuration blocks in the `pyrightconfig.json` file? Then the rules in that block apply only to the files matched by the corresponding `include` statement? This sounds a bit like the multi-root option.

**Comment by erictraut** [comment]
Yeah, that would be technically possible, but as I said, the configuration code in pyright is already ridiculously complex because it needs to merge configurations and settings from so many sources. It's already difficult to maintain the code, and it's confusing for users to understand where a setting is coming from and how it interacts with other settings. A diagnostic severity override can already be specified in the following ways, all at the same time:

The baseline diagnostic rule sets are defined by the "type checking mode", which is specified:
1. In a user settings file
2. In a project settings file
3. In a workspace settings file
4. In a pyrightconfig.json file using the typeCheckingMode
5. In a pyrightconfig.json file using the strict section (on a per-file or directory basis)
6. In individual files using #pyright comments

On top of these baseline rule sets, you can override individual rules:
7. In a user settings file
8. In a project settings file
9. In a workspace settings file
10. In a pyrightconfig.json file
11. In individual files using #pyright comments

And you can further suppress rules:
12. Using a file-level # type: ignore comment
13. Using a line-specific # type: ignore comment

All of these need to be considered when determining the severity level for a specific diagnostic rule today. You're proposing to add more layers of override.

**Comment by tobiasdiez** [comment]
I see, this is indeed quite complex. You could consider deprecating (or even removing) the strict section in favor of the multi-block mode. The aim of both features is the same: allow stricter type checking on a subset of the files.

It's of course your right to not implement this feature request. However, I think, it would be a good addition for larger projects where it is quite some work to go from zero type checking to strict mode.

**Comment by erictraut** [comment]
I'm going to close this for now, but other users should feel free to extend the thread if they feel like this functionality is needed. If there's sufficient support, I may reconsider in the future.

**Comment by Avasam** [comment]
I'd like to see something similar to how ESLint lets you override (per glob, but even just folder filter would be fine by me).
Or anything that makes pylance usable in monorepos with different config files. (Which could be resolved on pylance' side with multiple pyright ocnfig files)
See: https://github.com/microsoft/pylance-release/discussions/3426
