### ISSUE TITLE
Impossible to guard access to a non-total TypedDict via Literal union

### ISSUE THREAD

**Issue by sashkent3** [microsoft/pyright#9537]
**Describe the bug**
Consider the example below. At the point of `Test` object initialization, `axis` has a correct type of `Literal['x', 'y']` however the following type-guard is deemed not enough by Pyright. In the problems tab Pyright reports:
```
Could not access item in TypedDict
  "x" is not a required key in "Test", so access may result in runtime exception
  "y" is not a required key in "Test", so access may result in runtime exception
```
I believe it should be possible to use `TypedDict` in such a fashion.

**Code or Screenshots**
```python
import random
from enum import StrEnum
from typing import TypedDict


class Axis(StrEnum):
    X = "x"
    Y = "y"


class Test(TypedDict, total=False):
    title: str
    x: int
    y: int


if random.random() > 0.5:
    axis = Axis.X.value
else:
    axis = Axis.Y.value

t = Test()
if axis in t:
    print(t[axis])
```

**VS Code extension or command-line**
I'm running the VS Code extension v1.1.389

**Comment by erictraut** [comment]
Pyright's type narrowing logic for the `S in D` type guard pattern doesn't currently handle the case where `S` is a union of string literal types. It handles only a single string literal. Supporting unions of string literals for `S` strikes me as a reasonable enhancement request. I don't know if this is a common use case, but it looks like it would be straightforward to implement, and I don't anticipate that it would have a measurable impact on evaluation performance.

**Comment by erictraut** [comment]
Upon further investigation, this is not at all straightforward to implement. When `S` is a single string literal, the type guard guarantees that that key is present if the condition is true. Pyright internally tracks which keys it knows are present (either because they are required, because they have been explicitly set in the local scope, or because of a type guard condition). When `S` is a union of string literals, a static type checker cannot know statically which subset of keys are present that resulted in a true condition. 

For this reason, I'm going to reject this enhancement request.

**Comment by sashkent3** [comment]
Shouldn't
```
if axis in t:
    print(t[axis])
```
pass type checking regardless of the `axis` type?

**Comment by erictraut** [comment]
The type of `t` cannot be narrowed by this type guard. If you change the code to `if 'x' in t`, then the type of `t` can be narrowed (internally) to a variant of the `Test` type where the `x` key is recorded as "definitely present". However, `axis` is a union, so we can't say for sure whether `x` is present, `y` is present, or both are present. Therefore `t` cannot be narrowed in this case. Since it can't be narrowed, the expression `t[axis]` results in a type error.

I suppose it would be theoretically possible for a type checker to record some form of "dependent type narrowing" — i.e. remember that "if `axis` has the type `Literal['x']` then `Test` is narrowed to one type, but if `axis` has the type `Literal['y']`, then `Test` is narrowed to some other type, but dependencies like this would be infeasible to track in practice. I'm not aware of any type checker in any language that does such a thing.
