### ISSUE TITLE
Slicing a tuple can result in inconsistent type

### ISSUE THREAD

**Issue by alwaysmpe** [microsoft/pyright#9589]
Slicing a tuple of a minimum variable length from a position results in inconsistent type depending on position. If slicing from the start of a  position that may not exist the correct type is inferred, if slicing from after that position the result is a union of all values in the tuple, regardless of the type of the variable length section of the tuple (I had an off by one in my code...).

**Code or Screenshots**

```python
from typing import assert_type

def call_with(arg: tuple[str, str, int, *tuple[list[str], ...]]):
    assert_type(arg[3:], tuple[list[str], ...]) # no error
    assert_type(arg[4:], tuple[list[str], ...]) # "assert_type" mismatch: expected "tuple[list[str], ...]" but received "tuple[str | int | list[str], ...]"  (reportAssertTypeFailure)
```

**VS Code extension or command-line**
[playground latest](https://pyright-play.net/?pythonVersion=3.13&strict=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCGAzkQKZ4D68CpAULQCanBQDGBANhxQO5IwALABQEQaAFywArgg6kA2kRggANFCWrMKGGoBUMGXPkckSxcoC6agHS2LFgJTjaUV4RLkYVRKRFj5AMziVtKyCiZmGiG21o5QAMRQKGBQ5OAgLm7EZJTUvqJo8gAswWoGYcamMOYg0XYOCVAARNme3jRNUBCmEAQwrAKSpAAeNKwwpAzN5UYR1VE2dp0ARlL4IKSspEgAbpPThgoaUAA%2BWvhnczV1sZ1QQhs4eACCHngAKj4AYgRIHFIbBy0IA)

**Comment by erictraut** [comment]
Pyright is working as intended here, so I don't consider this a bug. The tuple slicing logic in pyright handles certain common cases. Notably, it handles cases where there the slice indices don't cut into the middle of an arbitrary-length element (either a `tuple[T, ...]` or an unpacked TypeVarTuple). In other cases, it falls back on a general solution that is a union of all element types in the tuple, which is what you're seeing here. 

It's possible to handle even more edge cases, but the existing logic is already very complex, and I would entertain adding support for additional cases only if I received strong signal from pyright users that it's an important case to handle. Since you're the first user to request this, I'm going to reject the enhancement request for now. I'm willing to revisit this decision in the future based on additional feedback.

**Comment by alwaysmpe** [comment]
Fair enough, if needed there's always the (slightly strange) workaround of `arg[3:][1:]`.
