### ISSUE TITLE
Visual Studio    CircuitPython v2  Import "circuitpython nrf24l01.rf24" could not be resolved by pylance

### ISSUE THREAD

**Issue by sas42** [microsoft/pyright#9604]
Tried to view code that works on rp2040 feather.  Visual Studio flags this error.
Import "circuitpython_nrf24l01.rf24" could not be resolvedPylancereportMissingImports

Import "circuitpython_nrf24l01.rf24" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)

![Image](https://github.com/user-attachments/assets/28d93ee3-69c9-4d93-8438-0b9ceecf1fb5)

**Comment by erictraut** [comment]
This is very unlikely to be a bug in pyright, but I can't say for sure because you haven't provided enough information in your bug report. This is most likely an issue with your pylance configuration, your python environment, or the library you're using. 

This error message indicates that pyright is not able to statically resolve the import statement. For help diagnosing such problems, please refer to [this documentation](https://microsoft.github.io/pyright/#/import-resolution).

If you're not able to diagnose the underlying condition on your own, please create a new topic in the discussion section and provide repro steps including the name and version of the package and the install instructions. I tried `pip install circuitpython_nrf24101`, but that doesn't work.
