### ISSUE TITLE
Expanding type aliases

### ISSUE THREAD

**Issue by layday** [microsoft/pyright#968]
Type aliases in the form of `SomeAlias = List[Tuple[SomeLongAndIntricateAnnotation, ...]]` are represented only by their name in tooltips and error messages.  It would be helpful if type aliases were expanded to avoid having to look them up manually, as in the example of a compound type, which a programmer might not have been able to memorise.

**Comment by erictraut** [comment]
They were previously expanded, and I invested a bunch of time and effort to use the type alias where possible. This was based on feedback we received from many users that the types in tooltips were too long and verbose, making them difficult to read.

I expand the type alias if you point to the type alias symbol, but if a type alias is used within another type, the symbolic name is used rather than the expansion.

**Comment by layday** [comment]
Thank you for explaining.  I can see how expanded types might get unwieldy and I had not noticed that the alias was expanded in isolation.
