### ISSUE TITLE
List[int] not handled the same in a operator expecting a List[float] as in the __<magic>__ method.

### ISSUE THREAD

**Issue by viblo** [microsoft/pyright#992]
**Describe the bug**
Operators where the argument is a typed as generic type with float as the type parameter, like List[float], generate error when the actual argument is a List[int]. However, calling the magic counterpart works fine.

**Expected behavior**
I expect using the operator directly to work in the same way as using the __<magic>__ method.

**Screenshots or Code**
```python
from typing import List

class A:
    def __add__(self, x: List[float]) -> None:
        pass

r1 = A() + [1] # Gives error:  Operator "+" not supported for types "A" and "list[int]"Pylance (reportGeneralTypeIssues)
r2 = A().__add__([1]) 
```

**VS Code extension or command-line**
Running VS Code with pyright included with Pylance.
Pyright version:  1.1.65

**Additional context**

**Comment by erictraut** [comment]
This is the correct behavior. For an explanation, please refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md#generic-types).

In your example, the correct fix is to use `Seuence[float]` rather than `List[float]`.

**Comment by viblo** [comment]
Thanks for the quick response! 
Ah, now I think I understand why the error comes. This is allowed according to mypy, so a bit confusing at first. If possible I think it would be great if the pyright docs could describe differences to mypy. 

But, I still wonder why `__add__` and `+` shouldn't be treated the same?

**Comment by erictraut** [comment]
The `__add__` and `+` cases are different in some important ways. The `+` operator must first evaluate the types of the LHS and the RHS operands. Then it determines whether the LHS class supports `__add__` and supports a parameter with the type of the RHS. If not, it then determines whether the RHS class support `__radd__` and supports a parameter with the type of the LHS. 

By contrast, `__add__` is just a simple function call. The type of the argument passed to `__add__` can be determined in the context of the function call using [bidirectional type inference](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md#bidirectional-type-inference-expected-types). This can't be applied in the case of `+` because both the LHS and RHS types need to be evaluated upfront.

**Comment by viblo** [comment]
Ah, so if I instead used a variable and then passed to both `__add__` and `+` it will also fail both, since then its type will be `List[int]`. I can see why trying to infer the types for `+` would be difficult.

Im havent worked with python type hints before, sorry for my limited understanding.
